### ISSUE TITLE
Bad IL format when loading assembly

### ISSUE THREAD

**Issue by mkSanalogic** [dotnet/core#2283] opened 2019-02-04 10:29 UTC
# Bad IL format error when loading assembly from memorystream

# General

About half a year ago, I created a project containing the following function:

```c#
        public static Assembly LoadAssemblyViaStream(string assemblyLocation)
        {
            byte[] file = null;
            int bufferSize = 1024;
            using (FileStream fileStream = File.Open(assemblyLocation, FileMode.Open))
            {
                using (MemoryStream memoryStream = new MemoryStream())
                {
                    byte[] buffer = new byte[bufferSize];
                    int readBytesCount = 0;
                    while ((readBytesCount = fileStream.Read(buffer, 0, bufferSize)) > 0)
                        memoryStream.Write(buffer, 0, readBytesCount);
                    file = memoryStream.ToArray();
                }
            }

            return Assembly.Load(file);
        }
```

Trying to reuse this code today, half a year later, I found it to no longer work.
When trying to load the assembly (the Assembly.Load in the return), the code throws a System.BadImageFormatException in System.Private.Corelib.dll.

I found a few issues when searching for the error message, but none of the suggested solutions, if there were any, resolved the error.

Since this exact code worked flawlessly six months ago and it no longer does, it should be a bug, right?

**Comment by karelz** [comment] 2019-02-17 09:15
> Since this exact code worked flawlessly six months ago and it no longer does, it should be a bug, right?

Not always. If you did something unsupported, it may have been actually broken on purpose as a bug fix.

Can you post a minimal repro (HelloWorld style) we can try on our end?

**Comment by mkSanalogic** [comment] 2019-02-22 06:32
Well, what unsupported operation did I conduct?
Also, what exactly do you want me to provide additional to what's already there?
Just paste the function into any program of your own and run it, providing the path to a .net assembly.
Might have to be a x64 assembly, I'm not 100% sure on that.

**Comment by karelz** [comment] 2019-02-27 04:14
Are you saying that the code above fails on EVERY assembly? (you seem to be unsure if it has to be x64 or not)
Did you try it on built-in assemblies? (e.g. System.dll)
Did you try it on more than 1 machine?
Which .NET Core version did you try? (try latest too just in case)

**Comment by mkSanalogic** [comment] 2019-03-05 11:29
*sigh*

For your entertainment:
I was using the latest 2.1 dotnet CORE version. 
Trying it on System assemblies yields the same result, it seems to be impossible to use this functionality (Assembly.Load from a byte[]) on ANY x64 dll in dotnet CORE.
x32 dlls seem to work just fine, though (!)
Updating to dotnet CORE 2.2 changed the error message text, but it's still the same error underlying error code (0x8007000B) and the root message also stays the same "BadImageFormatException"
Pasting the same code in a dotnet Framework console application utilizing the same code successfully loads any DLL, no matter whether it's x86 or x64. 
I also tried targeting x86 or x64 with both the dotnet CORE and the dotnet Framework applications, to no effect.

Any further questions?

**Comment by karelz** [comment] 2019-03-05 16:12
Are you running 32-bit or 64-bit app?
If 64-bit app fails to load x64 System assembly, that would be a concern.

**Comment by mkSanalogic** [comment] 2019-03-06 06:49
I said to in my previous comment, I tried both variants.
dotnet Framework loads x64 DLLs no matter whether you target x86 or x64.
dotnet CORE will load x32 DLLs no matter what, x64 DLLs fail with this error in both scenarios.

**Comment by karelz** [comment] 2019-03-30 17:37
@jeffschwMSFT can someone please check it out?

**Comment by jeffschwMSFT** [comment] 2019-04-01 16:24
@mkSanalogic can you give a exact set of steps that used to work?  For instance, when running <insert exact version> I can Assembly.Load(File.ReadAllBytes(<exact path of assembly>).    The reason the load of System.*.dll from the version direction fails is that those assemblies contain R2R images and are not valid to load in this way (the check is here: https://github.com/dotnet/coreclr/blob/master/src/vm/peimage.cpp#L1330).

cc @vitek-karas @sergiy-k

**Comment by vitek-karas** [comment] 2019-04-01 17:54
Based on your comments it worked on .NET Framework (4.2.* I assume).
Did it ever worked for you on .NET Core?

`Assembly.Load(byte[])` doesn't support loading native image assemblies (in .NET Framework these were called NGENed). In fact there's no way in the runtime (that I know of) to load native image assemblies from memory - the file format relies on the OS loader to perform relocations, which can't be triggered on a block of memory.

On .NET Framework the native image assembly is a separate file (`.ni.dll`) which typically lives in native assembly cache. The file in the framework folder (or GAC) is the pure-IL assembly. So I assume that on .NET Framework the code worked because you were giving it the pure-IL assemblies.

In .NET Core, most framework assemblies are native image assemblies which also contain the IL for the assembly. So it's a single file and it lives in the framework (there's no native assembly cache, or GAC for that matter). So it's likely that you're calling the method on native image assembly, which won't work as mentioned above.

I tried this on .NET Core 3.0 (preview) and it fails to load basically any interesting assembly from the framework, but it can load the application assembly just fine (since that is a pure-IL assembly).

Another consideration: Loading `System.Private.CoreLib` from a file or stream won't work, this assembly is special and it is always loaded first and only one version of it can be loaded ever.

**Comment by mkSanalogic** [comment] 2019-04-05 07:39
You can get all the answers to these questions from comments I already made before.

@jeffschwMSFT You say loading libraries this way is not valid, but why does it work in .NET Framework and why did it work in earlier versions of .NET CORE 2.1 as well? Doesn't quite add up for me.

@vitek-karas Yes, it works flawlessly in .NET Framework. You could try yourself easily within seconds - I provided a copy-paste ready function above.
I appreciate your extensive explanation why this cannot probably work ... but the fact remains that it DOES indeed work, both in .NET Framework and in .NET CORE as well - in the latter case just only for x86 DLLs. It ONLY fails on x64 DLLs.

Note that I didn't try to actually do much in terms of calling functions or otherwise actively working with the libraries loaded this way. What I did was hand the assembly to another function which returned the versioning information, iirc by reading AssemblyFileVersionAttribute.
I used this in a deployment tool to verify an update had indeed be correctly installed, I'd load the assembly from it's supposed destination and compare the file version found therein with the one determined in the deployment package.

**Comment by vitek-karas** [comment] 2019-04-05 08:19
I did try this myself (thanks a lot for the code snippet, that helps) before posting my questions. The thing is I never made it work on .NET Core, it simply doesn't accept native images (which is currently by design).

The reason it works on .NET Framework is that the assembly is pure IL, because the native assembly is a separate file. I'm only assuming this, since without knowing which exact file you're giving it, it's impossible to tell for sure.

Which version of .NET Core worked for you? And what file did you give it? I've tried with some random samples and it all failed (because they were all native images).
I also tried both x86 and x64, but no luck either.

What assemblies are you trying to load - maybe if possible, can you share the exact path?

Below is the program I'm trying locally. I tried it on .NET Core 3.0, 2.2 and 2.1. Same results.
I tried both x86 and x64, same results, it prints out something like this:
```
C:\Users\___\Source\Repos\ConsoleApp17\ConsoleApp17\bin\Debug\netcoreapp2.1\ConsoleApp17.dll
Worked: ConsoleApp17, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.9\System.Private.CoreLib.dll
Failed: Bad IL format.
c:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\2.2.3\System.Private.CoreLib.dll
Failed: Bad IL format.
```

It does work on .NET Framework:
```
C:\Users\___\Source\Repos\ConsoleApp17\ConsoleApp1\bin\Debug\ConsoleApp1.exe
Worked: ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
Worked: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\mscorlib\9e5fb54bb42672f30445fd7d36d2f815\mscorlib.ni.dll
Failed: Could not load file or assembly '20551080 bytes loaded from ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
```

But as mentioned above that is expected, the `mscorlib.dll` in the path above is the pure-IL assembly, the native image is in `C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\mscorlib\9e5fb54bb42672f30445fd7d36d2f815\mscorlib.ni.dll` and trying to load that fails (because that's a native image) (and the error message is really weird).

I must be doing something different than what you're trying... I just can't figure out what.

This is the code I'm using:
``` C#
using System;
using System.IO;
using System.Reflection;

namespace ConsoleApp17
{
    class Program
    {
        static void Main(string[] args)
        {
            Load(typeof(Program).Assembly.Location);
            Load(typeof(object).Assembly.Location);
            Load(@"c:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\2.2.3\System.Private.CoreLib.dll");
        }

        public static void Load(string path)
        {
            try
            {
                Console.WriteLine(path);
                var a = LoadAssemblyViaStream(path);
                Console.WriteLine("Worked: " + a.ToString());
            }
            catch (Exception ex)
            {
                Console.WriteLine("Failed: " + ex.Message);
            }
        }

        public static Assembly LoadAssemblyViaStream(string assemblyLocation)
        {
            byte[] file = null;
            int bufferSize = 1024;
            using (FileStream fileStream = File.Open(assemblyLocation, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
            {
                using (MemoryStream memoryStream = new MemoryStream())
                {
                    byte[] buffer = new byte[bufferSize];
                    int readBytesCount = 0;
                    while ((readBytesCount = fileStream.Read(buffer, 0, bufferSize)) > 0)
                        memoryStream.Write(buffer, 0, readBytesCount);
                    file = memoryStream.ToArray();
                }
            }

            return Assembly.Load(file);
        }
    }
}
```

**Comment by mkSanalogic** [comment] 2019-04-09 05:26
Hmm. I cannot get it to work with any windows dll either.

I do not remember which exact dlls I tried when I ran my tests, but I presume it must've been some of our own dlls, since (a) I could be sure they were indeed x86 or x64 and (b) that's what I intended to use the functionality for in the first place. I do not want to read versioning information from any random dll, I just wanted to read that of those written in .NET CORE by our own team and deployed by our tool.

What initially had happened was that I wrote the function I pasted to do the version verification and it failed to work after I had updated to a new version of .NET CORE. I only ran all the other tests because I was prompted to do so here.

I'll do another round of testing asap and report back.

Semi-related question: Is there a better .NET way to read versioning information from an assembly?

**Comment by vitek-karas** [comment] 2019-04-09 07:09
If all you need is to read metadata from the assembly, then the better choice is `MetadataLoadContext`. Some details can be found [here](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#type-metadataloadcontext). It's a netstandard2.0 package, so it should work even on 2.2, but I haven't tried myself. It actually might work with even native image assemblies since it's not loading them to run them, but only to read metadata from (but I haven't tried that either).

**Comment by farlock85** [comment] 2019-04-11 13:26
Since the last update I'm running into the same issue, except the odd thing is that our app runs fine for a few days doing the exact same operations and then suddenly this:

```
at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at FieldLink.Internal.Business.CodeExecutor.GetAssembly(String fileName, String sourceCode, IList`1& diagnostics) in C:\TeamCity\buildAgent\work\1057292a3d53e562\Internal\Business\CodeExecutor.cs:line 117
```

Which is just this code:
```
var filePath = $@"C:\Temp\Assemblies\{fileName}.dll";
var fileBytes = File.ReadAllBytes(filePath);
```

The `fileName.dll` comes from a dynamically compiled assembly.

When I restart the app pool, it works fine again, with the exact same assemblies.

**Comment by vitek-karas** [comment] 2019-04-11 13:32
@farlock85 By "the same issue" you mean that your code starts to fail with `Bad IL Format` exceptions?
Would it be possible to change the code to catch this exception and save the file someplace so that we can try to repro the problem?

The fact that it works fine for several days and then fails feels more like some kind of robustness issue, some kind of leak or something similar. But it's really hard to diagnose from the information provided.

**Comment by farlock85** [comment] 2019-04-11 13:40
@vitek-karas sorry that's correct yes, I only posted the first 2 lines of the stacktrace. 
` System.BadImageFormatException: Bad IL format.` is the exception.

I'm digging a bit more into it because I actually cache the loaded DLL's and try to use them afterwards, so now trying to pinpoint where the issue exactly occurs.

**Comment by karelz** [comment] 2019-04-27 18:52
Any update? If there is not actionable info, I recommend to close the issue until there is, then reopen again. Thanks!

**Comment by karelz** [comment] 2019-04-27 18:53
(oh, and I accidentally closed it now, sorry - anyway, we can reopen if there's something actionable, let us know)

**Closed by karelz** 2019-04-27 18:52 UTC
Labels: needs more info, question

**Comment by farlock85** [comment] 2019-04-27 18:55
@karelz unfortunately I haven't been able to reproduce or isolate the issue, it seems time bound (memory perhaps) so for now we had to write an exception handler around it which re-compiles the DLL's from scratch when the error occurs.

**Comment by karelz** [comment] 2019-04-27 19:05
OK, if you find out more in future, feel free to reopen / file new issue with more details. Thanks!

**Comment by farlock85** [comment] 2019-07-02 22:43
@karelz Took a while but eventually we found out why this error was happening. Turns out that the compiled would occasionally output an empty, 0 byte file, not sure why, but I have a process now that retries when it's 0 bytes.

But we I would read that file with `File.ReadAllBytes` it throws the Bad IL exception.
