### ISSUE TITLE
Please increase the time-out for downloads within the dotnet-install.ps1 script from 10 minutes to 30 minutes

### ISSUE THREAD

**Issue by Sathyaish** [dotnet/core#2079] opened 2018-11-27 12:30 UTC
# Increase in the download time-out limit from 10 to 30 minutes

A few days ago, I was trying to set up the source code for MS Build on my machine so I could play with it, but the build process for setting up the code on my machine kept failing. I finally figured that one of the problems why it was failing was that it was running a Powershell script named `dotnet-install.ps1` which was downloaded from the URL `https://dotnetcli.azureedge.net/dotnet/Sdk/2.1 .401/dotnet-sdk-2.1.401-win-x64.zip`, and in the script, a 10 minute time-out was declared for the download.

I have a 2 Mbps connection and that file takes only slightly more than 10 minutes on my computer. 

The specific line of code to change is in the script block that's passed as an argument to the `Invoke-With-Retry` method from within the `GetHTTPResponse` method in the Powershell script `dotnet-install.ps1`.

`$HttpClient.Timeout = New-TimeSpan -Minutes 30`

For details of the issue, please read [this comment](https://github.com/Microsoft/msbuild/issues/3937#issuecomment-442037965) of mine in this issue in the MS Build repo.

**Comment by Sathyaish** [comment] 2018-11-27 12:33
It appears that the right project to post this issue to is the CLI team, so please ignore this. I am re-posting this in the Issues section of the CLI repo.

**Comment by karelz** [comment] 2018-11-27 17:13
Duplicate of https://github.com/dotnet/cli/issues/10396

**Closed by karelz** 2018-11-27 17:13 UTC
