### ISSUE TITLE
debian11 can't install dotnet8

### ISSUE THREAD

**Issue by Cz2545481217** [dotnet/core#9331] opened 2024-05-26 08:40 UTC
### URL(s)

System Info：
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
Excuted Command：
source /etc/os-release
sudo apt-get install -y gpg wget
wget https://packages.microsoft.com/keys/microsoft.asc
cat microsoft.asc | gpg --dearmor -o microsoft.asc.gp
sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
wget https://packages.microsoft.com/config/$ID/$VERSION_ID/prod.list
sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
sudo apt-get update &&   sudo apt-get install -y dotnet-runtime-8.0
Error Info:
E: Unable to locate package dotnet-runtime-8.0
E: Couldn't find any package by glob 'dotnet-runtime-8.0'
E: Couldn't find any package by regex 'dotnet-runtime-8.0'
I've tried all the .net8 packages and can't find it。

### Description

System Info：
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
Excuted Command：
source /etc/os-release
sudo apt-get install -y gpg wget
wget https://packages.microsoft.com/keys/microsoft.asc
cat microsoft.asc | gpg --dearmor -o microsoft.asc.gp
sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
wget https://packages.microsoft.com/config/$ID/$VERSION_ID/prod.list
sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
sudo apt-get update &&   sudo apt-get install -y dotnet-runtime-8.0
Error Info:
E: Unable to locate package dotnet-runtime-8.0
E: Couldn't find any package by glob 'dotnet-runtime-8.0'
E: Couldn't find any package by regex 'dotnet-runtime-8.0'
I've tried all the .net8 packages and can't find it。

**Comment by bigtallcampbell** [comment] 2024-05-29 14:32
Also can't install dotnet-sdk-6.0.  Following the instructions at [https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian#debian-11](https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian#debian-11)

```bash
wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb


sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-6.0
```

Result:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package dotnet-sdk-6.0
E: Couldn't find any package by glob 'dotnet-sdk-6.0'
E: Couldn't find any package by regex 'dotnet-sdk-6.0'

**Comment by leecow** [comment] 2024-05-30 21:19
The latest 6.0 and 8.0 SDKs appear to be available and working now. 

@Cz2545481217 make sure that where you have `https://packages.microsoft.com/config/$ID/$VERSION_ID/prod.list` that the actual executing line is `https://packages.microsoft.com/config/debian/11/`

**Comment by antonfirsov** [comment] 2024-06-02 21:11
Closing, since it seems to be resolved. Feel free to reopen if the issue is still present.

**Closed by antonfirsov** 2024-06-02 21:11 UTC
Labels: area-release-notes

**Comment by Cz2545481217** [comment] 2024-09-04 04:56
> Also can't install dotnet-sdk-6.0. Following the instructions at https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian#debian-11
> 
> ```shell
> wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
> sudo dpkg -i packages-microsoft-prod.deb
> rm packages-microsoft-prod.deb
> 
> 
> sudo apt-get update && \
>   sudo apt-get install -y dotnet-sdk-6.0
> ```
> 
> Result: Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package dotnet-sdk-6.0 E: Couldn't find any package by glob 'dotnet-sdk-6.0' E: Couldn't find any package by regex 'dotnet-sdk-6.0'



> The latest 6.0 and 8.0 SDKs appear to be available and working now.
> 
> @Cz2545481217 make sure that where you have `https://packages.microsoft.com/config/$ID/$VERSION_ID/prod.list` that the actual executing line is `https://packages.microsoft.com/config/debian/11/prod.list`

Thank you bro, I'm using docker now。

**Comment by pedroveiga99** [comment] 2024-09-05 13:42
Is this really solved? I'm getting the same error. I have tried with both debian 11 and debian 12. I think this should be reopened.

**Comment by leecow** [comment] 2024-09-05 16:09
@pedroveiga99 and @Cz2545481217 - things look to be OK on Debian 11. 

```
root@73fa5f261fe2:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@73fa5f261fe2:/# apt search dotnet-sdk-8.0
Sorting... Done
Full Text Search... Done
dotnet-sdk-8.0/bullseye 8.0.401-1 amd64
  Microsoft .NET SDK 8.0.401

root@73fa5f261fe2:/# apt search dotnet-sdk-6.0
Sorting... Done
Full Text Search... Done
dotnet-sdk-6.0/bullseye 6.0.425-1 amd64
  Microsoft .NET SDK 6.0.425
```

Note that we only publish x86_64 installers. If you want to install on ARM64, you'll need to use either the [.tar.gz packages](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual) available on the [download pages](https://dotnet.microsoft.com/en-us/download/dotnet/8.0) or the [dotnet-install script](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script). 

![Screenshot 2024-09-05 at 9 06 31 AM](https://github.com/user-attachments/assets/429e5a90-6319-406f-a861-be4fe7c22df5)

**Comment by pedroveiga99** [comment] 2024-09-05 16:46
@leecow  Yeah you are right. I'm trying to install in arm64. Is there any previsions on when will that be available? This seems to be an issue since 2018 
https://github.com/dotnet/runtime/issues/3263

**Comment by leecow** [comment] 2024-09-05 17:40
@pedroveiga99 - there are conversations going on in the community to get .NET natively into Debian, much like it's in Red Hat, Ubuntu, Fedora, and others. Hopefully that moves forward.
