### ISSUE TITLE
Package ref version issue

### ISSUE THREAD

**Issue by rdzidziguri** [dotnet/core#831] opened 2017-08-14 22:03 UTC
Just update to the latest net core and runtime and SDK and VS version to 2017.3 as well and created NET Standard class library. but as soon as i Expand dependencies node i was surprised to see it still references NET Core 1.1.0 package. Is there something i am missing and is this normal as i was expecting to see 2.0 version there for NET Core.

```
{
  "runtimeTarget": {
    "name": ".NETStandard,Version=v2.0/",
    "signature": "d5ef1509ab9594c5ee7350d5e7860d93d6b54c43"
  },
  "compilationOptions": {},
  "targets": {
    ".NETStandard,Version=v2.0": {},
    ".NETStandard,Version=v2.0/": {
      "ClassLibrary1/1.0.0": {
        "dependencies": {
          "NETStandard.Library": "2.0.0"
        },
        "runtime": {
          "ClassLibrary1.dll": {}
        }
      },
      "Microsoft.NETCore.Platforms/1.1.0": {},
      "NETStandard.Library/2.0.0": {
        "dependencies": {
          "Microsoft.NETCore.Platforms": "1.1.0"
        }
      }
    }
  },
  "libraries": {
    "ClassLibrary1/1.0.0": {
      "type": "project",
      "serviceable": false,
      "sha512": ""
    },
    "Microsoft.NETCore.Platforms/1.1.0": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-kz0PEW2lhqygehI/d6XsPCQzD7ff7gUJaVGPVETX611eadGsA3A877GdSlU0LRVMCTH/+P3o2iDTak+S08V2+A==",
      "path": "**microsoft.netcore.platforms/1.1.0**",
      "hashPath": "microsoft.netcore.platforms.1.1.0.nupkg.sha512"
    },
    "NETStandard.Library/2.0.0": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-7jnbRU+L08FXKMxqUflxEXtVymWvNOrS8yHgu9s6EM8Anr6T/wIX4nZ08j/u3Asz+tCufp3YVwFSEvFTPYmBPA==",
      "path": "netstandard.library/2.0.0",
      "hashPath": "netstandard.library.2.0.0.nupkg.sha512"
    }
  }
}
```

This brings to another issue like if I update that package i can not longer reference that net standard librry in net core 2.0 web app.

**Comment by JRBonnema** [comment] 2017-08-21 18:05
Strange that nobody has apparently looked at this yet. I get the same mistake when creating a Net standard class library. It must be a problem that doesn't affect most people.  When I compile I see lots of warnings like the one below. Apparently something has gone wrong downloading the .NET Core 2.0 SDK. The Dll's are apparently kept at different locations and not are all the same, some ones contains .NET Core 2.0 Dlls, others .Net Core 1.1 Dlls. A part of the problem is solved by emptying the NuGet cache. A repair load of 2.0 SDK goes ok, but doesn't solve the problem. Maybe its has something to do with roaming users?

	Encountered conflict between 'Reference:C:\Program Files\dotnet\sdk\NuGetFallbackFolder\netstandard.library\2.0.0\build\netstandard2.0\\ref\System.Reflection.dll' and 
		'Reference:C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection\4.3.0\ref\netstandard1.5\System.Reflection.dll'.  
	Choosing 'Reference:C:\Program Files\dotnet\sdk\NuGetFallbackFolder\netstandard.library\2.0.0\build\netstandard2.0\\ref\System.Reflection.dll' 
		because AssemblyVersion '4.1.2.0' is greater than '4.1.0.0'.

**Comment by ratidzidziguri** [comment] 2017-08-21 21:06
@JRBonnema  Do u mean i need to clean some cache on my local machine? could you please provide more info on how to test what u suggest?

**Comment by JRBonnema** [comment] 2017-08-24 12:10
I managed to solve the problems I had. Part of my installlation of VS 2017 had become corrupt, especially the .Net4.7 part. I solved this by using the Repair option in Visual Studio. I experimented with using project template Class Library (.Net Standard). When just created such a project references Microsoft.NETCore.platforms ( 1.1.0), which is confusing, but I think it's not wrong. It's easy to forget that .Netstandard is a specification, not a framework and .Netstandard supports .Net.Core 1.1. After you add the propertygroup below to the project directory, the project will however create both a .Net Core 2.0 and .Net 4.6.1 dll. Try it out yourself. 
         
         <PropertyGroup>
               <TargetFrameworks>netcoreapp2.0;net4.6.1</TargetFrameworks>
         </PropertyGroup>

**Comment by ratidzidziguri** [comment] 2017-08-24 17:15
@JRBonnema  Did not get your point. do you mean that this issue will be fixed if i do VS installation rep or u say that this behavior is normal and there is nothing to worry about?

**Comment by JRBonnema** [comment] 2017-08-24 17:17
It's confusing, but not wrong

**Comment by Petermarcu** [comment] 2017-10-06 18:28
How are you creating the .NET Standard 2.0 library? Are you using the .NET Standard Class library template or the Portable Class Library dialog? A clean .NET Standard 2.0 class library should not reference 1.1 to my knowledge.

@dsplaisted

**Comment by rdzidziguri** [comment] 2017-10-06 19:06
NET Standard Class library template no portable and I am doing this from VS 2017 update 3

**Comment by livarcocc** [comment] 2017-10-06 20:26
Can you share the contents of the created csproj?

**Comment by rdzidziguri** [comment] 2017-10-06 20:31
sure

`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

</Project>
`

**Comment by Petermarcu** [comment] 2017-10-12 06:20
Shot in the dark but perhaps your NuGet cache is corrupt. Can you try:

`dotnet nuget locals all –clear`

**Comment by Petermarcu** [comment] 2017-10-12 06:28
I get similar output as you in my project.assets.json with that simple project. I don't think the problem. It builds just fine for me. It's got to have something to do with the state of your machine. @emgarten in case he has ideas.

**Comment by rdzidziguri** [comment] 2017-10-12 17:45
https://github.com/dotnet/standard/issues/497
Here is the issue created over standard Repo. I think those are very similar and but that issue does not bring much light on this. so this is very annoying.

**Comment by alexeyzimarev** [comment] 2017-10-15 11:48
This is even worse. I converted RestSharp to be on netstandard2.0. It builds fine on my machine. But on my other machine and on anyone else's it is throwing errors on everything - `CultureInfo`, `List`, etc.

So I looked how it shows and compared it with a completely new .NET Standard class library. Here is how they look:

![image](https://user-images.githubusercontent.com/2821205/31584452-365ae620-b1af-11e7-8340-a92e0a5fc552.png)

The csproj files are completely identical:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

</Project>
```

I tried using `<NetStandardImplicitPackageVersion>2.0.0</NetStandardImplicitPackageVersion>` and it has no effect. But hence that the RestSharp project does not even have a reference to `netstandard.dll`. How this is even possible???

**Comment by Petermarcu** [comment] 2017-10-15 16:50
Yes, the netstandard.dll reference is supposed to be implicitly inserted through the netstandard2.0 tfm reference. I'm not sure what's going on there. We should track this as a new issue because not having the reference at all seems to be a different problem. I've opened this issue for you in the dotnet/standard repo to track it. https://github.com/dotnet/standard/issues/538

**Comment by Petermarcu** [comment] 2017-10-19 04:34
@ericstj any thoughts on the original issue here?

**Comment by ericstj** [comment] 2017-10-19 15:19
When you say original issue, you mean that NETStandard.Library references Platfroms 1.1.0?  That's already discussed here: https://github.com/dotnet/standard/issues/497.  Let me know if you had a different question.

**Comment by Petermarcu** [comment] 2017-10-19 15:57
You are right. Looks like this issue can be closed now.

**Closed by Petermarcu** 2017-10-19 15:57 UTC
