### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by aroushtechbd** [dotnet/core#5786] opened 2020-12-24 07:47 UTC
I get an error when opening Office 2013 documents after upgrading from Windows 7 to Windows 10, such as Word encountered an error trying to open the file or The file is corrupted and cannot be opened.

**Comment by mairaw** [comment] 2021-01-08 02:47
Closing since the issue is unrelated to .NET.

**Closed by mairaw** 2021-01-08 02:47 UTC
