### ISSUE TITLE
.NET core .exe doesn't show an error message when the runtime isn't installed

### ISSUE THREAD

**Issue by pieterphilippaerts** [dotnet/core#3581] opened 2019-10-09 15:15 UTC
I'm building a .NET Core 3 desktop application and I'm publishing it as "Framework dependent" (i.e. the .NET core 3 framework must be installed on the computer).

When I run the application on a computer without the .NET core runtime installed, nothing happens. I obviously didn't expect the application to work, but I did expect some kind of error. But the application simply quits without any user feedback whatsoever.

Is it possible to add some kind of check to the native executable and show an error message to the user that the .NET core runtime is missing? Preferably a message that includes a download link (like the full .NET Framework does).

For completeness, it's a WPF application that I'm testing on a 32-bit Windows 8.1. I don't think this is relevant, but in any case...

**Comment by pieterphilippaerts** [comment] 2019-10-09 15:20
As an additional note, when you install the .NET core runtime but you don't install the Windows Desktop pack, the executable also quits without any user feedback. When I use "dotnet run" from the console, I do get an error message...

**Comment by dagood** [comment] 2019-10-09 17:43
There's discussion happening about this over at https://github.com/dotnet/core-setup/issues/8222, we're looking at fixing it in 3.1. Yeah, this is particularly painful for WPF/WinForms apps since there's nowhere for stderr to show up.

**Comment by dagood** [comment] 2019-10-09 17:43
Duplicate of https://github.com/dotnet/core-setup/issues/8222

**Closed by dagood** 2019-10-09 17:43 UTC
