### ISSUE TITLE
.NET Core August Update - 2.1.3

### ISSUE THREAD

**Issue by vivmishra** [dotnet/core#1875] opened 2018-08-21 16:44 UTC
[Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.3/2.1.3.md)
[Download 2.1.3](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.3/2.1.3-download.md)

Please report any issues you find with 2.1.3, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/aspnet/Home) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/corefx](https://github.com/dotnet/corefx/issues) - for API issues and questions
* [dotnet/coreclr](https://github.com/dotnet/coreclr/issues) - for runtime issues
* [dotnet/core-setup](https://github.com/dotnet/core-setup/issues) - for installer issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

**Comment by stephenpope** [comment] 2018-08-22 12:54
I like the list of commits that you are putting out with the release notes now.
It would be *extremely* useful when you do a release if there was a list of the nuget packages that were updated / pushed to nuget for that release.
I have to run new / modified packages by our legal dept so getting a list of what changes happen release to release is a little painful currenly :)

**Comment by leecow** [comment] 2018-08-22 17:34
Thanks for the feedback @StephenBonikowsky, this is something that we _really_ want to do. My dream is an aggregated, per package change list but that will require some build tooling changes so we'll see how far we can get :-)

**Comment by StephenBonikowsky** [comment] 2018-08-22 17:36
The real @stephenpope :)

**Comment by leecow** [comment] 2018-08-22 17:52
Sigh ... I love autocomplete in all it's forms.

**Comment by stephenpope** [comment] 2018-08-22 20:47
Thanks Lee .. looking forward to it.

**Comment by vbenedichuk** [comment] 2018-08-24 04:28
Guys, why .net core 2.1.2 for linux is not available anymore?

**Comment by Petermarcu** [comment] 2018-08-24 04:40
It should be. Where are you looking?

**Comment by vbenedichuk** [comment] 2018-08-24 04:55
https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/runtime-2.1.2 - here

**Comment by Petermarcu** [comment] 2018-08-24 05:05
Yes, that's intentional because you should get the latest patches version whenever possible.  Is there a reason you want 2.1.2 and not .3? You should be able to add a .2 on the end of the package name but we don't recommend specifying explicit patch versions because you should pick up security updates by default.

**Comment by vbenedichuk** [comment] 2018-08-24 05:18
Thank you I'll try. 
We have a bouncing issue which appears on 2.1.3 but not appears on 2.1.2. Looks like it's somehow related to concurrency or to something inside dbcontext.
As it bouncing it's really hard to trace it so we need to have 2.1.2 at least until we will catch and fix it.

**Comment by Petermarcu** [comment] 2018-08-24 05:28
If you are hitting a behavior change in 2.1.3 that is preventing upgrade, we'd love to get an issue filed with details so we can investigate. Patches shouldn't break or regress any behavior.

**Comment by vbenedichuk** [comment] 2018-08-24 05:38
I can't fill it yet. We facing it in 1 module. During the xunit test run, execution freezes at random point. On CI docker image it happens 4 of 5 times on my test docker it happens once in about 8 times. 
On 2.1.2 all goes smoothly everywhere. We haven't got it on prod yet but I believe it's because we don't have intensive load there.
I'll fill the bug it as soon as I'll find out how to reproduce it with 100% guarantee.

**Comment by Petermarcu** [comment] 2018-08-24 05:51
Let us know. You say a random point but is there anything common on the stack in the different cases? Can you share a stack trace from any of the cases?

**Comment by Praveen-Rai** [comment] 2018-08-27 18:13
@vivmishra Visual Studio keeps referring to Microsoft.AspNetCore.App v2.1.1. https://github.com/dotnet/core/issues/1895

**Comment by Petermarcu** [comment] 2018-09-11 20:18
Closing in favor of https://github.com/dotnet/core/issues/1932

**Closed by Petermarcu** 2018-09-11 20:18 UTC
Labels: Announcement
