### ISSUE TITLE
releases.json not current for Azure DevOps Server installer

### ISSUE THREAD

**Issue by PatGet** [dotnet/core#3656] opened 2019-10-18 09:59 UTC
We are using the .net core build tasks from within the Azure DevOps Server. The ".NET Core SDK Installer" Task uses the "releases.json" file from this Repo to get Version information but it seems to be not current.

**Comment by wenz** [comment] 2019-10-18 14:08
I've added entries for the latest stable versions, pulling data from the individual releases.json files. HTH

**Comment by dagood** [comment] 2019-10-18 15:34
Duplicate of https://github.com/dotnet/core/issues/3475

**Closed by dagood** 2019-10-18 15:34 UTC

**Comment by dagood** [comment] 2019-10-18 15:36
> This will be handled by the Azure Pipelines folks. See [microsoft/azure-pipelines-tasks#11100](https://github.com/microsoft/azure-pipelines-tasks/issues/11100)

The root of it is that this file is deprecated, and we're removing it as soon as possible.
