### ISSUE TITLE
i got an issue in running the application after editing the code

### ISSUE THREAD

**Issue by vignesh123007** [dotnet/core#6698] opened 2021-09-15 06:01 UTC
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by tannergooding** [comment] 2021-09-15 15:01
Closing as duplicate of #6697, #6696, and #6695

**Closed by tannergooding** 2021-09-15 15:01 UTC
