### ISSUE TITLE
Debian 10 listing missing from installation page

### ISSUE THREAD

**Issue by sharkwouter** [dotnet/core#3201] opened 2019-08-15 20:51 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current
Operating System: Linux Debian 9 - x64

This page doesn't list instructions for Debian 10 yet, even though a Debian 10 repo is already available. For Debian 10 the only line which has to be changed is this one:
```bash
wget -q https://packages.microsoft.com/config/debian/9/prod.list
```
Into:
```bash
wget -q https://packages.microsoft.com/config/debian/10/prod.list
```

**Comment by dagood** [comment] 2019-08-19 16:42
This is part of a larger discussion at https://github.com/dotnet/core/issues/2576 about how to keep the list up to date.

A few confounding issues:
* The packages on the Debian 9 repository are the same as the ones on the Debian 10 repository. There's no pressing need to update.
* These aren't our repositories. Other Microsoft teams use it too, and they might *not* have packages on the Debian 10 feed, even though they would work just fine. You can only install one Microsoft repo at a time, so by instructing users to use the Debian 10 feed we could break the other team's install/update scenario. (This is the case with PowerShell.)

/cc @leecow

**Comment by dagood** [comment] 2019-08-19 16:42
Duplicate of https://github.com/dotnet/core/issues/2576

**Closed by dagood** 2019-08-19 16:42 UTC
