### ISSUE TITLE
System.ArgumentException: Cannot remove this column, because it is a part of the constraint Constraint1 on the table .    at System.Data.DataColumnCollection.CanRemove

### ISSUE THREAD

**Issue by pyliakm** [dotnet/core#3023] opened 2019-07-11 20:33 UTC
# Issue Title

System.ArgumentException: Cannot remove this column, because it is a part of the constraint Constraint1 on the table .    at System.Data.DataColumnCollection.CanRemove

# General
**.Net core 2.2**
**Windows 10 Version 1803**
Stack trace:
   at System.Data.DataColumnCollection.CanRemove(DataColumn column, Boolean fThrowException)
   at System.Data.DataColumnCollection.BaseRemove(DataColumn column)
   at System.Data.DataColumnCollection.Remove(DataColumn column)
   at System.Data.ProviderBase.SchemaMapping.RollbackAddedItems(List`1 items)
   at System.Data.ProviderBase.SchemaMapping.SetupSchemaWithKeyInfo(MissingMappingAction mappingAction, MissingSchemaAction schemaAction, Boolean gettingData, DataColumn parentChapterColumn, Object chapterValue)
   at System.Data.ProviderBase.SchemaMapping..ctor(DataAdapter adapter, DataSet dataset, DataTable datatable, DataReaderContainer dataReader, Boolean keyInfo, SchemaType schemaType, String sourceTableName, Boolean gettingData, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.FillMappingInternal(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 schemaCount, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.FillMapping(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 schemaCount, DataColumn parentChapterColumn, Object parentChapterValue)

Snippet of code:
` DataTable cards = new DataTable();
  cards.Load(reader);`
where reader is SqlDataReader

The problem is related with geography sql data type, if I remove the column with this data type, it works fine.

**Comment by carlossanlop** [comment] 2019-07-22 20:29
@divega is this something your team could help with? If not, do you know who could take a look?

**Comment by divega** [comment] 2019-07-22 23:18
Although I don't have enough data to identify this as the direct root cause of the exception, SQL Server spatial types are known not to support .NET Core. So it is possible that this is a duplicate of https://github.com/dotnet/SqlClient/issues/30.

**Comment by carlossanlop** [comment] 2019-09-27 18:37
Moving to dotnet/SqlClient for better visibility and to help determine if it is indeed a dupe or not.

**Comment by carlossanlop** [comment] 2019-09-27 18:38
This issue was moved to dotnet/SqlClient#230

**Closed by carlossanlop** 2019-09-27 18:38 UTC
