### ISSUE TITLE
Checksum comparison fail

### ISSUE THREAD

**Issue by qfilip** [dotnet/core#3887] opened 2019-11-21 19:34 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/sdk-3.0.101
Operating System: Gecko Linux x64 (openSuse 15 spin)

console output:
>Warning: Digest verification failed for file 'netstandard-targeting-pack-2.1.0-x64.rpm'
>[/var/cache/zypp/packages/packages-microsoft-com-prod/netstandard-targeting-pack-2.1.0->x64.rpm]

  >expected fa194a8c12913dcec85c8d24bfc91686a7b93128b4c05346df16e2c641e2ba41
  >but got  45e199caf1151a750d11d9c5c7669d6e23d8dbb33da54d1d90bde55745996480

EDIT:
Also, if possible, please provide libicu package in your repository.

**Comment by dagood** [comment] 2019-11-21 19:43
Duplicate of https://github.com/dotnet/core/issues/3853

libicu is specific to your distro, so you need to find what package in your distro will install it on your machine and ignore the dependency `dotnet-runtime-deps` takes on it.

**Closed by dagood** 2019-11-21 19:43 UTC
