### ISSUE TITLE
unable to install dotnet-sdk-2.1   / 2.2

### ISSUE THREAD

**Issue by ip75** [dotnet/core#2827] opened 2019-06-04 07:00 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/opensuse/sdk-2.1.302
Operating System: Linux openSUSE Leap - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

> ip@linux-2mvj:~> sudo zypper install dotnet-sdk-2.1
> Loading repository data...
> Reading installed packages...
> Resolving package dependencies...
> 
> Problem: nothing provides libicu52_1 needed by dotnet-runtime-deps-2.1-2.1.11-1.x86_64
>  Solution 1: do not install dotnet-sdk-2.1-2.1.700-1.x86_64
>  Solution 2: break dotnet-runtime-deps-2.1-2.1.11-1.x86_64 by ignoring some of its dependencies
> 
> Choose from above solutions by number or cancel [1/2/c] (c):
> ip@linux-2mvj:~> sudo zypper install libicu52_1
> Loading repository data...
> Reading installed packages...
> 'libicu52_1' not found in package names. Trying capabilities.
> No provider of 'libicu52_1' found.
> Resolving package dependencies...
> 
> Nothing to do.
> ip@linux-2mvj:~> sudo zypper install libicu
> Loading repository data...
> Reading installed packages...
> 'libicu' not found in package names. Trying capabilities.
> **'libicu60_2' providing 'libicu' is already installed.**
> Resolving package dependencies...
> 
> Nothing to do.

fail.......  infinite loop

dotnet-sdk-2.2 is the same one....

> ip@linux-2mvj:~> uname -a
> Linux linux-2mvj 4.12.14-lp150.11-default #1 SMP Fri May 11 08:28:30 UTC 2018 (a9fee09) x86_64 x86_64 x86_64 GNU/Linux
>

**Comment by dagood** [comment] 2019-06-04 19:18
There was some discussion about this issue in https://github.com/dotnet/core-setup/issues/5628, and a fix was merged into the 2.1/2.2 branches for the next servicing release: https://github.com/dotnet/core-setup/pull/6246.

Basically, we're changing our RPM package to depend on `libicu` rather than a specific `libicu52_1` or `libicu60_2`. This way, the same RPM will work across releases of Leap. This will be released in the next servicing release, around July (unless something changes).

**Comment by dagood** [comment] 2019-06-04 19:18
Duplicate of https://github.com/dotnet/core-setup/issues/5628

**Closed by dagood** 2019-06-04 19:18 UTC
