### ISSUE TITLE
Error installing .net core 3.0 in Raspbian

### ISSUE THREAD

**Issue by kerumirembora** [dotnet/core#3666] opened 2019-10-20 22:52 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian10/sdk-current
Operating System: Linux Debian 10 - x64

Hello. I'm trying to install .net core 3.0 on a Rasberry PI 3 running Raspbian buster. 

After following the instructions in https://dotnet.microsoft.com/download/linux-package-manager/debian10/sdk-current, when I try to `sudo apt-get install dotnet-sdk-3.0`, the following error message is shown:

`Reading package lists... Done`
`Building dependency tree`  
`Reading state information... Done`  
`E: Unable to locate package dotnet-sdk-3.0`  
`E: Couldn't find any package by glob 'dotnet-sdk-3.0'`  
`E: Couldn't find any package by regex 'dotnet-sdk-3.0'`

**Comment by dagood** [comment] 2019-10-21 16:52
RPi runs on arm, not x64, you'll want to follow these instructions on that page:

> Not running x64? You'll need to [download the .NET Core binaries](https://dotnet.microsoft.com/download/dotnet-core/3.0#sdk-3.0.100) instead.

**Comment by dagood** [comment] 2019-10-21 16:52
Duplicate of https://github.com/dotnet/core/issues/2422

**Closed by dagood** 2019-10-21 16:52 UTC
