### ISSUE TITLE
Command 'dotnet' not found,already installed dotnet-sdk snap

### ISSUE THREAD

**Issue by ReportDataCode** [dotnet/core#5012] opened 2020-08-03 12:58 UTC
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by ReportDataCode** [comment] 2020-08-03 12:59
OS:Ubuntu 20(focal fossa)
installed from: ubuntu software center
issue:installed but command not found

**Comment by dagood** [comment] 2020-08-04 05:50
When you install via Snap, by default you have to type `dotnet-sdk.dotnet` to run it, not just `dotnet`. But, you can run this command once to set up the `dotnet` command to work normally:

```
sudo snap alias dotnet-sdk.dotnet dotnet
```

This is documented in the release notes: https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.6/3.1.6-install-instructions.md#install-using-snap

https://github.com/dotnet/core/issues/4746 is an open issue asking for some improvement here.

Let us know if this doesn't work for you, or you hit some other issue. Thanks.

**Comment by dagood** [comment] 2020-08-04 05:50
Duplicate of https://github.com/dotnet/core/issues/4746

**Closed by dagood** 2020-08-04 05:50 UTC
