### ISSUE TITLE
I cannot establish SSL connection when USING CentOS

### ISSUE THREAD

**Issue by wujunchengman** [dotnet/core#7626] opened 2022-07-22 03:32 UTC
### Description

At first, I deployed an Asp.Net Core application on AlamLinux9, but when it was connected to the SQL Server database, there was a message indicating that the platform did not support it. Then I tried to write HelloWorld to access the database, but I failed to install dotnet ef tool. It tells me that I can't set up an SSL connection, and I wonder if this is the same problem

### Configuration

dotnet-sdk-6.0

CentOS Stream 9 / AlmaLinux8 / AlmaLinux9

### Other information

```shell
 dotnet tool install --global dotnet-ef


/usr/lib64/dotnet/sdk/6.0.106/NuGet.targets(130,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/tmp/hm4qicuc.hgs/restore.csproj]
/usr/lib64/dotnet/sdk/6.0.106/NuGet.targets(130,5): error :   The SSL connection could not be established, see inner exception. [/tmp/hm4qicuc.hgs/restore.csproj]
/usr/lib64/dotnet/sdk/6.0.106/NuGet.targets(130,5): error :   The remote certificate is invalid because of errors in the certificate chain: NotSignatureValid [/tmp/hm4qicuc.hgs/restore.csproj]
无法还原工具包。
工具“dotnet-ef”安装失败。此故障可能由以下原因导致:

* 你尝试安装预览版，但未使用 --version 选项来指定该版本。
* 已找到具有此名称的包，但是它不是 .NET 工具。
* 无法访问所需的 NuGet 源，这可能是由于 Internet 连接问题导致。
* 工具名称输入错误。
```

**Comment by bartonjs** [comment] 2022-07-22 15:23
This sounds like a known issue on CentOS 9 where some root certificate authorities are being reported as NotSignatureValid.  We've fixed that in runtime 6.0.7, which released on July 12th.  https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by wujunchengman** [comment] 2022-07-25 07:45
Thank you.  Can you provide a temporary solution? For example, where should certificates be copied to and where is the system repository source slow to update to the corresponding version

**Comment by bartonjs** [comment] 2022-07-25 16:11
The issue isn't with the certificates, but with the CentOS 9 SHA-1 deprecation feature.

The workaround would be to disable the SHA-1 deprecation feature, or upgrade your version of .NET.

**Comment by buyaa-n** [comment] 2022-08-08 18:40
@wujunchengman if your problem is solved please close the issue

**Closed** 2022-08-09 01:14 UTC
Labels: needs-more-info, area-runtime
