### ISSUE TITLE
Unable to install aspnet core 2.2 on CentOS 7

### ISSUE THREAD

**Issue by Yanal-Yves** [dotnet/core#2558] opened 2019-04-09 20:46 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/centos/runtime-current
Operating System: Linux CentOS / Oracle - x64

I just started a new official CentOS 7 VM on AWS EC2  and run the following command

```
sudo rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
sudo yum -y update
sudo yum -y install aspnetcore-runtime-2.2 
```

The last command generates the following error, any idea what should I do to install aspnet core 2.2 on CentOS7?

```
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: rep-centos-fr.upress.io
 * extras: rep-centos-fr.upress.io
 * updates: ftp.pasteur.fr
Resolving Dependencies
--> Running transaction check
---> Package aspnetcore-runtime-2.2.x86_64 0:2.2.4-1 will be installed
--> Processing Dependency: dotnet-runtime-2.2 >= 2.2.4 for package: aspnetcore-runtime-2.2-2.2.4-1.x86_64
--> Running transaction check
---> Package dotnet-runtime-2.2.x86_64 0:2.2.4-1 will be installed
--> Processing Dependency: dotnet-runtime-deps-2.2 >= 2.2.4 for package: dotnet-runtime-2.2-2.2.4-1.x86_64
--> Processing Dependency: dotnet-hostfxr-2.2 >= 2.2.4 for package: dotnet-runtime-2.2-2.2.4-1.x86_64
--> Running transaction check
---> Package dotnet-hostfxr-2.2.x86_64 0:2.2.4-1 will be installed
--> Processing Dependency: dotnet-host >= 2.2.4 for package: dotnet-hostfxr-2.2-2.2.4-1.x86_64
---> Package dotnet-runtime-deps-2.2.x86_64 0:2.2.4-1 will be installed
--> Processing Dependency: libicu for package: dotnet-runtime-deps-2.2-2.2.4-1.x86_64
--> Running transaction check
---> Package dotnet-host.x86_64 0:2.2.4-1 will be installed
---> Package libicu.x86_64 0:50.1.2-17.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=============================================================================================================================================================================================================================================
 Package                                                        Arch                                          Version                                               Repository                                                          Size
=============================================================================================================================================================================================================================================
Installing:
 aspnetcore-runtime-2.2                                         x86_64                                        2.2.4-1                                               packages-microsoft-com-prod                                         30 M
Installing for dependencies:
 dotnet-host                                                    x86_64                                        2.2.4-1                                               packages-microsoft-com-prod                                         44 k
 dotnet-hostfxr-2.2                                             x86_64                                        2.2.4-1                                               packages-microsoft-com-prod                                        196 k
 dotnet-runtime-2.2                                             x86_64                                        2.2.4-1                                               packages-microsoft-com-prod                                         27 M
 dotnet-runtime-deps-2.2                                        x86_64                                        2.2.4-1                                               packages-microsoft-com-prod                                        2.2 k
 libicu                                                         x86_64                                        50.1.2-17.el7                                         base                                                               6.9 M

Transaction Summary
=============================================================================================================================================================================================================================================
Install  1 Package (+5 Dependent packages)

Total size: 64 M
Total download size: 30 M
Installed size: 81 M
Downloading packages:
dotnet-host-2.2.4-x64.rpm      FAILED                                                                    0% [                                                                                              ]  0.0 B/s |    0 B  --:--:-- ETA
https://packages.microsoft.com/rhel/7/prod/dotnet-host-2.2.4-x64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=packages-microsoft-com-prod clean metadata     ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
dotnet-hostfxr-2.2.4-x64.rpm   FAILED
https://packages.microsoft.com/rhel/7/prod/dotnet-hostfxr-2.2.4-x64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=packages-microsoft-com-prod clean metadata  ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
aspnetcore-runtime-2.2.4-rh.rh FAILED                                                                   85% [================================================================================              ] 9.6 MB/s |  26 MB  00:00:00 ETA
https://packages.microsoft.com/rhel/7/prod/aspnetcore-runtime-2.2.4-rh.rhel.7-x64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=packages-microsoft-com-prod clean metadata  26 MB  00:00:00 ETA
Trying other mirror.


Error downloading packages:
  dotnet-hostfxr-2.2-2.2.4-1.x86_64: [Errno 256] No more mirrors to try.
  aspnetcore-runtime-2.2-2.2.4-1.x86_64: [Errno 256] No more mirrors to try.
  dotnet-host-2.2.4-1.x86_64: [Errno 256] No more mirrors to try.

```

**Comment by chenli118** [comment] 2019-04-10 04:37
Package                  Arch    Version    Repository                    Size
================================================================================
Installing:
 dotnet-sdk-2.2           x86_64  2.2.203-1  packages-microsoft-com-prod  114 M
Installing for dependencies:
 aspnetcore-runtime-2.2   x86_64  2.2.4-1    packages-microsoft-com-prod   30 M
 dotnet-host              x86_64  2.2.4-1    packages-microsoft-com-prod   44 k
 dotnet-hostfxr-2.2       x86_64  2.2.4-1    packages-microsoft-com-prod  196 k
 dotnet-runtime-2.2       x86_64  2.2.4-1    packages-microsoft-com-prod   27 M
 dotnet-runtime-deps-2.2  x86_64  2.2.4-1    packages-microsoft-com-prod  2.8 k

Transaction Summary
================================================================================
Install  1 Package (+5 Dependent packages)

Total size: 172 M
Installed size: 172 M
Is this ok [y/d/N]: y
Downloading packages:


Package dotnet-runtime-2.2.4-x64.rpm is not signed

**Comment by Yanal-Yves** [comment] 2019-04-10 07:12
I am now having the same error as @chenli118 now.

Any idea?

**Comment by jsrgjcy** [comment] 2019-04-10 10:02
+1

**Comment by roikra** [comment] 2019-04-10 10:21
Also facing the same issue. 

Transaction Summary
========================================================================
Install  1 Package (+6 Dependent packages)

Total size: 179 M
Installed size: 196 M
Is this ok [y/d/N]: y
Downloading packages:

Package dotnet-runtime-2.2.4-x64.rpm is not signed

**Comment by Rwing** [comment] 2019-04-10 10:45
+1

**Comment by lcals** [comment] 2019-04-10 11:13
+1

**Comment by Ruberoid** [comment] 2019-04-10 12:32
`sudo yum -y install aspnetcore-runtime-2.2 --nogpgcheck`

**Comment by luto** [comment] 2019-04-10 12:51
Installing software without signatures is a bad idea, because you cannot trust that the packages actually came from the dotnet team. Signatures are enforced in the default `microsoft-prod.repo` for a reason. Please do not skip them.

**Comment by karelz** [comment] 2019-04-10 15:31
Is it similar to #2559? @dagood 
cc @omajid @tmds

**Comment by dagood** [comment] 2019-04-10 15:37
Looks like it to me. 😞 Copying from there to keep people in the loop:

> I asked @leecow about this (https://github.com/dotnet/core-setup/issues/5759) and the RPMs weren't signed correctly for this release. @vivmishra is working on fixing it.

**Comment by karelz** [comment] 2019-04-10 15:39
Duplicate of https://github.com/dotnet/core-setup/issues/5759

**Closed by karelz** 2019-04-10 15:39 UTC

**Comment by chenli118** [comment] 2019-04-11 02:44
Fixed .change /etc/yum.repos.d/microsoftxxx.repos  gpgcheck=0
