### ISSUE TITLE
Unable to install Dot.Net Core 2.2 on Ubuntu 19.04

### ISSUE THREAD

**Issue by usayme** [dotnet/core#2615] opened 2019-04-20 13:09 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 18.10 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by belst** [comment] 2019-04-20 19:06
Probably because Ubuntu 19.04 does not provide `libssl-1.0` anymore.

**Comment by raaraya** [comment] 2019-04-22 02:09
Same here, still looking at what can I do about it.
```
sudo apt-get install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.4) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by karelz** [comment] 2019-04-22 15:59
Duplicate of https://github.com/dotnet/core/issues/2526

**Closed by karelz** 2019-04-22 15:59 UTC

**Comment by gotsalyuk** [comment] 2019-04-23 11:38
> Same here, still looking at what can I do about it.
> 
> ```
> sudo apt-get install dotnet-sdk-2.2
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.4) but it is not going to be installed
>                   Depends: dotnet-runtime-2.2 (>= 2.2.4) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.
> ```

I have the same problem

**Comment by karelz** [comment] 2019-04-23 16:38
@gotsalyuk did you check the dupe?

**Comment by gotsalyuk** [comment] 2019-04-24 13:56
@karelz No, I installed through a snap-in to call `$>dotnet-sdk.dotnet`

**Comment by karelz** [comment] 2019-04-24 14:09
No idea what that is (sorry, not a Linux expert). Your symptom is same as in the dupe - check that out.
