### ISSUE TITLE
I install dotnet-sdk-3.1.405 but my setup required the .NET Framework version 3.5 is it ok for my set up or I should Install it also ?

### ISSUE THREAD

**Issue by Wadkarmanoj** [dotnet/core#5885] opened 2021-01-27 14:34 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Wadkarmanoj** [comment] 2021-01-27 14:36
I install dotnet-sdk-3.1.405 but my setup required the .NET Framework version 3.5 is it ok for my set up or I should Install it also ?
![1234](https://user-images.githubusercontent.com/78091581/106006311-f1d47f80-6069-11eb-91d7-2462e3b69377.JPG)

**Comment by mairaw** [comment] 2021-01-27 18:35
Duplicate of #5886

**Closed by mairaw** 2021-01-27 18:35 UTC
