### ISSUE TITLE
Error downloading packages

### ISSUE THREAD

**Issue by renruliang** [dotnet/core#3856] opened 2019-11-20 08:38 UTC
Error downloading packages:
  netstandard-targeting-pack-2.1-2.1.0-1.x86_64: [Errno 256] No more mirrors to try.

**Comment by kocmana** [comment] 2019-11-20 10:13
I am expiriencing a similar issue with this package when installing under fedora 31. It seems to be related with a checksum mismatch:
[MIRROR] netstandard-targeting-pack-2.1.0-x64.rpm: Downloading successful, but checksum doesn't match. Calculated: 45e199caf1151a750d11d9c5c7669d6e23d8dbb33da54d1d90bde55745996480(sha256)  Expected: fa194a8c12913dcec85c8d24bfc91686a7b93128b4c05346df16e2c641e2ba41(sha256) 
[FAILED] netstandard-targeting-pack-2.1.0-x64.rpm: No more mirrors to try - All
mirrors were already tried without success

**Comment by otmanel31** [comment] 2019-11-20 11:07
+1 same issue as @kocmana  with following issue:
Downloading packages:
netstandard-targeting-pack-2.1 FAILED
https://packages.microsoft.com/centos/7/prod/netstandard-targeting-pack-2.1.0-x64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=packages-microsoft-com-prod clean metadata
Trying other mirror.


Error downloading packages:
  netstandard-targeting-pack-2.1-2.1.0-1.x86_64: [Errno 256] No more mirrors to try.

**Comment by craigjbass** [comment] 2019-11-20 16:27
Dupe of #3853

**Closed** 2019-11-20 16:28 UTC
