### ISSUE TITLE
C++/CLI migration to .Net core on Linux

### ISSUE THREAD

**Issue by saxenark** [dotnet/core#2508] opened 2019-03-26 11:18 UTC
Hi,

I have a managed C++ component that references a C# assembly based on .net 4.7.2. We are considering our software on Linux and hence are evaluating .Net core as an option. 

What is not clear to me from all the docs is how to proceed with migration of the managed C++ component (/clr) over to .Net core.  How do I reference my C# based .net core classes from the C++ code migrated to Linux (g++) which will no longer be aware of C# assemblies?

**Comment by karelz** [comment] 2019-03-26 15:23
C++/CLI support is coming in .NET Core 3.0 - @richlander can you please provide details?
cc @leecow

**Comment by saxenark** [comment] 2019-03-27 13:43
Hi, please also do suggest what would be the equivalent of the C++/CLI (/clr) on the Linux world! from .NET core porting perspective from Windows to Linux.

**Comment by saxenark** [comment] 2019-03-29 10:07
@richlander, @karelz 
I am waiting for some direction on how to port my .net framework code which uses C++/CLI to .net core on Linux. Let me know if I can provide any additional inputs

**Comment by saxenark** [comment] 2019-04-03 02:04
what do I need to do get a quick response?

**Comment by karelz** [comment] 2019-04-03 03:51
Not sure if you're going to get quick response from @richlander 
I have no idea what are our plans in the space sadly.

**Comment by karelz** [comment] 2019-06-05 04:04
@richlander 2 months old question ... can you please reply?

**Comment by hez2010** [comment] 2019-06-07 04:02
Any progress on C++/CLI for .NET Core?

**Comment by anto0ine** [comment] 2019-06-11 07:34
I am interested to. Any update on whether/when C++/CLI will be supported in .NET Core?

**Comment by carlossanlop** [comment] 2019-09-27 18:06
Here's a recent announcement about this: https://devblogs.microsoft.com/cppblog/the-future-of-cpp-cli-and-dotnet-core-3/

**Comment by szilvaa** [comment] 2020-01-01 17:39
This is also discussed here: https://github.com/dotnet/coreclr/issues/659

**Comment by vmharisankar** [comment] 2020-01-13 05:13
I am also in this same situation. Currently .Net Cor C++/CLI only support windows. But I am looking for a Linux Application. 

C# side I have a .NetCore application, 
C++ side I can Manage Platform Independency. 
But C++/CLI I have no idea how to make it platform independent. 

Can someone please suggest a method?

**Comment by jmaine** [comment] 2020-08-06 07:03
Currently, the only workaround to get to this goal is to remove all the C++/CLI code and replace the code in question with DllImportAttribute calls. You may even need to create a C compatible bindings for the C++ code that your attempting to integrate with.

**Comment by LifeIsStrange** [comment] 2021-03-14 15:17
This library might help https://github.com/Const-me/ComLightInterop
But yeah official Linux support should be prioritarized

**Comment by mairaw** [comment] 2021-08-11 23:10
Any updates here @richlander?

**Comment by richlander** [comment] 2021-08-11 23:31
We don't plan to enable C++/CLI on Linux (or any other OS other than Windows). It would require us to do one of two things:

- Enable the MSVC compiler on Linux. That would be a very large project since MSVC has only ever targeted and run on Windows.
- Enable the C++/CLI feature in Clang/LLVM or GCC. That, too, would be a very large project.

We haven't identified any reasonable cost version of this project. It's a very large and complicated feature set that is sensitive to the C++ compiler, OS, and architecture. I cannot think of another feature like that or that is even in the same ballpark.

**Comment by richlander** [comment] 2021-08-11 23:32
We have worked with folks that have adopted P/Invoke or COM instead. This project could also help. https://github.com/AaronRobinsonMSFT/DNNE. Those kinds of approaches are our best guidance.

**Comment by mairaw** [comment] 2021-08-11 23:42
Thanks @richlander for the pointers. I think we can close the issue then since we don't plan on doing this.

**Closed by mairaw** 2021-08-11 23:42 UTC
Labels: question

**Comment by hylas-deng** [comment] 2022-05-07 00:03
Do not close this, please! This issue is important. .Net would be uncompleted without solving it.

**Comment by AraHaan** [comment] 2022-05-07 00:19
lol it's not a big deal tbh, honestly just make an wrapper for the native code (and static link what you are wrapping inside) and have the wrapper expose the apis in an C way which stub into the real c++ apis.

Then use the new .NET 7 Preview 5 LibraryImport source generator.

**Comment by hylas-deng** [comment] 2022-05-07 02:11
With C, nothing else is big deal. Actually, I want to do a lot of things without C. I need OOP, or OOP with less manual wrapper.

**Comment by hez2010** [comment] 2022-05-08 11:39
> can you describe how to implement this, and the community would help

It's not possible without gcc and clang support to be able to compile C++/CLI code to managed assembly. Gcc has the C++/CLI implementation decade years ago, but it had been removed.

**Comment by AraHaan** [comment] 2022-05-08 11:58
I mean it *is* possible to separate it into it's own separate compiler and ship it with the .NET SDK, however it would be more or so done in the future (or never) as there are more important things for the .NET Team to do.

**Comment by hez2010** [comment] 2022-05-11 15:38
> I mean it is possible to separate it into it's own separate compiler and ship it with the .NET SDK

It's not feasible to do this, otherwise the .NET SDK will need to ship with the whole Windows SDK/libc+linux headers and libs.

**Comment by MiheevN** [comment] 2022-05-11 15:47
I'm ready to optionally download at least 50GB,
as long as it works.
It should be fundamentally possible.

**Comment by hez2010** [comment] 2022-05-11 15:55
Also I don't think the effort is worthy. This basically means that the .NET team would need to create a cross-platform C++ compiler, and also need to follow the latest C++ standard, which needs at least years of work to achieve this. 
IMO only if existing C++ compilers such as gcc and clang come with C++/CLI support can this be done with reasonable efforts. I don't think this can be done without support from existing C++ compilers on Linux.

**Comment by hez2010** [comment] 2022-05-11 16:51
LLVMSharp is only a binding for .NET, it doesn't add support for C++/CLI to LLVM.

**Comment by hu-xd** [comment] 2022-10-28 00:48
welp, didn't I say "cross-platform" ? 😏
yes, xlang was designed to work with any operating system / compiler toolchain, and no need to modify the compilers etc.

**Comment by bstordrup** [comment] 2022-12-18 21:27
A lot of comments here are talking about changing compilers for this.

But what about a C++/CLI project compiled for .netcore on a Windows machine - will that be able to run on Linux?

Another thing is the choice to support C++/CLI for .netcore. Great idea - but why was `netstandard2.0` not chosen as the new target instead of (or together with) .netcore? Since `netstandard2.0` is a common denominator between `net462` and `netcoreapp3.1`, a C++/CLI library would be a great tool for migrating existing very large code bases with Native C++ and .NET Framework projects to a code base with Native C++ and .NET Core projects without having to do the conversion of **all** projects at the same time.

**Comment by AraHaan** [comment] 2022-12-19 04:04
> A lot of comments here are talking about changing compilers for this.
> 
> But what about a C++/CLI project compiled for .netcore on a Windows machine - will that be able to run on Linux?
> 
> Another thing is the choice to support C++/CLI for .netcore. Great idea - but why was `netstandard2.0` not chosen as the new target instead of (or together with) .netcore? Since `netstandard2.0` is a common denominator between `net462` and `netcoreapp3.1`, a C++/CLI library would be a great tool for migrating existing very large code bases with Native C++ and .NET Framework projects to a code base with Native C++ and .NET Core projects without having to do the conversion of **all** projects at the same time.

most likely no, your best bet is to instead use pure C++ (without /CLR) and p/invoke the code in C# to use it cross platform.

You can even publish the native libraries in nuget packages per OS for the architectures that .NET supports on them as well and then have the C# wrapper package reference all of those (so then the correct one would be used on each OS).

**Comment by bstordrup** [comment] 2023-01-26 11:31
> most likely no, your best bet is to instead use pure C++ (without /CLR) and p/invoke the code in C# to use it cross platform.
> 
> You can even publish the native libraries in nuget packages per OS for the architectures that .NET supports on them as well and then have the C# wrapper package reference all of those (so then the correct one would be used on each OS).

What part is not supported? Is that the platform specific methods calling into Windows libraries? Then what about pure code that is implemented in native C++ and does not call platform specific methods? Will they be able to run provided the C++ runtime is available? Or is it the C++ runtime that has the issues?

**Comment by ankofl** [comment] 2024-07-22 10:23
I guess today, even if we install net core.runtime on Linux, we still won't be able to use libraries using C++\CLI inside it?

I will be very annoyed if this is still the case...

**Comment by robindegen** [comment] 2024-07-23 13:26
The fact that there is still no proper full crossplatform C++/CLI  (including with AOT) support is baffling to me. You have this great powerful language and framework that is now finally crossplatform; but taking in any external library that isn't just pure C without code generation is an absolute pain. C++/CLI would help so much; especially if it can be combined with AOT and you can just link statically to other C++ libraries.

**Comment by MiheevN** [comment] 2024-07-23 13:37
I support you once again.
This functionality is even more important than VS on Linux.

Combining languages ​​would move the industry far forward and make C# clearly the best language to use.
Since all the weak points could be connected.

I don't understand why they don't do this.
This is already half implemented and works on Windows. There is not much left, at least tell me where to pay if necessary.

This functionality will no longer be needed until some C## appears, which will once again natively support the connection of all languages. And be written by some kind of AI.
