### ISSUE TITLE
.NET Core 3.0 and plugin scenario - Assembly.LoadFrom fails when an older version of dependency assembly has already been loaded

### ISSUE THREAD

**Issue by sdg002** [dotnet/core#3426] opened 2019-09-23 13:20 UTC
# Issue Title

This is a scenario where I have a 
1.`.NET Core Console 3.0 EXE` , 
2.`.NET Framework Console EXE` 
3. Two ` .NET Standard 20` class libraries, both of which implement a contractual interface from a common `Contracts` library. 

The EXE has a reference to the Contracts library only.  The class libraries behave like plugins. The sample code has been simplified to highlight  technical problem.  Both the plugin class library projects have the attribute **CopyLocalLockFileAssemblies** to ensure that all dependent assemblies get copied over to their respective folders.  The EXE wakes up and attempts to load either of the plugin class libraries using `Assembly.LoadFrom` method. The EXE built with .NET Framework has no issues in loading both of the plugins simultaneously. The EXE built with .NET Core fails.

# Solution structure

- *ConsoleAppNETFrameWorkAssemblyLoadFrom* (EXE, fwk 461)
- *ConsoleAppNetCoreAssemblyLoadFrom* (EXE, Core 3.0)
- *PluginsDeliveryFolder* (Dummy class library with subfolders where all plugins are copied over)
- *PluginNewtonsoftv12* (.NET Standard 20, references NewtonSoft v12)
- *PluginNewtonsoftv9* (.NET Standard 20, references NewtonSoft v9)
- *Contracts* (.NET Standard 20)

# Steps to reproduce - Framework

1. Set project **ConsoleAppNETFrameWorkAssemblyLoadFrom**  as the active project
2. Place break point in the first line of main
3. Change the variables `folderNewtonsoftV9` and `folderNewtonsoftV12`  as per your environment
4. Do a build all.
5. Ensure that the plugins DLLs are copied over to **PluginsDeliveryFolder**
6. The code will load the plugin assembly **PluginNewtonsoftv9.dll** , followed by **PluginNewtonsoftv12.dll**
7. Both plugins should work without any exceptions. 

# Steps to reproduce - .NET Core 3.0

1. Set project **ConsoleAppNetCoreAssemblyLoadFrom** as the active project
2. Place break point in the first line of main
3. Change the variables `folderNewtonsoftV9` and `folderNewtonsoftV12`  as per your environment
4. Do a build all.
5. Ensure that the plugins DLLs are copied over to PluginsDeliveryFolder
6. The code will load the plugin **PluginNewtonsoftv9.dll** without any problems
6. The  exception **System.IO.FileLoadExceptio**n will be thrown when plugin **PluginNewtonsoftv12.dll** is attempted

# Code snippet

```
        static void Main(string[] args)
        {
            try
            {
                string folderNewtonsoftV9 = @"C:\Users\saurabhd\MEFFwkCoreComparison\PluginsDeliveryFolder\out\PluginNewtonsoftv9\PluginNewtonsoftv9.dll";
                string folderNewtonsoftV12 = @"C:\Users\saurabhd\MEFFwkCoreComparison\PluginsDeliveryFolder\out\PluginNewtonsoftV12\PluginNewtonsoftv12.dll";
                string[] pathsAssemblies = new string[] { folderNewtonsoftV9, folderNewtonsoftV12 };
                foreach (string pathAssembly in pathsAssemblies)
                {
                    var assembly = System.Reflection.Assembly.LoadFrom(pathAssembly);
                    Type tTarget = assembly.GetTypes().FirstOrDefault(t => t.Name.ToLower() == "class1");
                    var plugin = Activator.CreateInstance(tTarget) as Contracts.ISomePlugin;
                    plugin.DoWork();

                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
        }

```

# System.IO.FileLoadException details

> {"Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)":"Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"}
>     Data: {System.Collections.ListDictionaryInternal}
>     FileName: "Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"
>     FusionLog: ""
>     HResult: -2146232799
>     HelpLink: null
>     InnerException: {"Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.":null}
>     Message: "Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)"
>     Source: "PluginNewtonsoftV12"
>     StackTrace: "   at PluginNewtonsoftV12.Class1.DoWork() in C:\\Users\\saurabhd\\MyTrials\\OtherStuff\\MEFFwkCoreComparison\\PluginNewtonsoftV12\\Class1.cs:line 18\r\n   at ConsoleAppNetCoreAssemblyLoadFrom.Program.Main(String[] args) in C:\\Users\\saurabhd\\MyTrials\\OtherStuff\\MEFFwkCoreComparison\\ConsoleAppNetCoreAssemblyLoadFrom\\Program.cs:line 22"
>     TargetSite: {Void DoWork()}
> 

# Sample code
https://github.com/sdg002/MEFFwkCoreComparison
You will need Visual Studio 2019
I am on Windows 10

# Summary
- .NET Framework has no problems in loading 2 plugin assemblies which reference different versions of NewtonSoft. 
- .NET Core 30 fails to load the higher version of Newtonsoft (12) if the older version of Newtonsoft(9) has already been loaded by a previous plugin.
- This is a serious problem because .NET Core is prohibiting us from developing a large application which has been broken down into "plugins". Such a scenario was very much possible and widely documented with .NET Framework.

# Linked issue
I had initially logged a similar issue where the plugins were being loaded by **Managed Extensibility Framework**.  
https://github.com/dotnet/core/issues/3376

**Comment by sdg002** [comment] 2019-09-23 15:29
I tried using `AssemblyLoadContext.Default.LoadFromAssemblyPath` instead of `Assembly.LoadFrom` but this failed to event load the first plugin, i.e. the class library which references Newtonsoft(9)

`                    var assembly = AssemblyLoadContext.Default.LoadFromAssemblyPath(pathAssembly);`


Reading through various articles I get a hint that handling the  `Resolving` event of `AssemblyLoadContext` might work. But, this introduces new challenges and questions. 
- How would lazy loading in Managed Extensibility Framework work? 
- The referenced assembly Newtonsoft.dll is located along side the class library. If .NET Core has a different logic for referenced assemblies, then this needs documentation.

**Comment by scalablecory** [comment] 2019-09-30 17:14
Closing as duplicate of https://github.com/dotnet/coreclr/issues/26861

**Closed by scalablecory** 2019-09-30 17:14 UTC
