### ISSUE TITLE
NET教程-10分钟之内的Hello World

### ISSUE THREAD

**Issue by loooljp** [dotnet/core#5612] opened 2020-11-17 06:30 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Creating this template will make changes to existing files:
  Overwrite   myApp.csproj
  Overwrite   Program.cs

Rerun the command and pass --force to accept and create.

**Comment by mairaw** [comment] 2020-11-17 22:40
Duplicate of #5613

**Closed by mairaw** 2020-11-17 22:40 UTC
