### ISSUE TITLE
Can't install .Net 5 SDK preview on Ubuntu after previously installing .Net Core 3.1 SDK

### ISSUE THREAD

**Issue by svick** [dotnet/core#4811] opened 2020-06-10 13:19 UTC
I set up a brand new instance of WSL1 Ubuntu 20.04, followed [the guide](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004-) to install .Net Core SDK 3.1.301 using `apt-get` and then tried to install .Net 5 SDK preview by following [this guide](https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.0-preview.4-install-instructions.md#install-using-debrpm-packages) using `install-dotnet-preview.sh` (snap doesn't seem to work on WSL1). When I did that, the installation failed with an error, the full output is:

```
~$ sudo bash install-dotnet-preview.sh
1

*** Checking required system dependencies for detected OS: Ubuntu 20.04 LTS ...
***     tar is already installed.
***     gzip is already installed.
***     curl is already installed.

*** Setting package type to deb.
*** Download source: dotnet-5.0.0-preview.4-deb.tar.gz

*** Downloading https://dotnetcli.blob.core.windows.net/dotnet/release/install-preview/5.0.0-preview.4/dotnet-5.0.0-preview.4-deb.tar.gz to /home/svick ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 84.1M  100 84.1M    0     0   385k      0  0:03:43  0:03:43 --:--:--  398k

*** Unpacking dotnet-5.0.0-preview.4-deb.tar.gz ...

dotnet_packages/
dotnet_packages/aspnetcore-runtime-5.0.0-preview.4.20257.10-x64.deb
dotnet_packages/aspnetcore-targeting-pack-5.0.0-preview.4.20257.10.deb
dotnet_packages/dotnet-apphost-pack-5.0.0-preview.4.20251.6-x64.deb
dotnet_packages/dotnet-host-5.0.0-preview.4.20251.6-x64.deb
dotnet_packages/dotnet-hostfxr-5.0.0-preview.4.20251.6-x64.deb
dotnet_packages/dotnet-runtime-5.0.0-preview.4.20251.6-x64.deb
dotnet_packages/dotnet-runtime-deps-5.0.0-preview.4.20251.6-x64.deb
dotnet_packages/dotnet-sdk-5.0.100-preview.4.20258.7-x64.deb
dotnet_packages/dotnet-targeting-pack-5.0.0-preview.4.20251.6-x64.deb
dotnet_packages/netstandard-targeting-pack-2.1_2.1.0-1_amd64.deb


Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'aspnetcore-runtime-5.0' instead of '/home/svick/dotnet_packages/aspnetcore-runtime-5.0.0-preview.4.20257.10-x64.deb'
Note, selecting 'aspnetcore-targeting-pack-5.0' instead of '/home/svick/dotnet_packages/aspnetcore-targeting-pack-5.0.0-preview.4.20257.10.deb'
Note, selecting 'dotnet-apphost-pack-5.0' instead of '/home/svick/dotnet_packages/dotnet-apphost-pack-5.0.0-preview.4.20251.6-x64.deb'
Note, selecting 'dotnet-host' instead of '/home/svick/dotnet_packages/dotnet-host-5.0.0-preview.4.20251.6-x64.deb'
Note, selecting 'dotnet-hostfxr-5.0' instead of '/home/svick/dotnet_packages/dotnet-hostfxr-5.0.0-preview.4.20251.6-x64.deb'
Note, selecting 'dotnet-runtime-5.0' instead of '/home/svick/dotnet_packages/dotnet-runtime-5.0.0-preview.4.20251.6-x64.deb'
Note, selecting 'dotnet-runtime-deps-5.0' instead of '/home/svick/dotnet_packages/dotnet-runtime-deps-5.0.0-preview.4.20251.6-x64.deb'
Note, selecting 'dotnet-sdk-5.0' instead of '/home/svick/dotnet_packages/dotnet-sdk-5.0.100-preview.4.20258.7-x64.deb'
Note, selecting 'dotnet-targeting-pack-5.0' instead of '/home/svick/dotnet_packages/dotnet-targeting-pack-5.0.0-preview.4.20251.6-x64.deb'
Note, selecting 'netstandard-targeting-pack-2.1' instead of '/home/svick/dotnet_packages/netstandard-targeting-pack-2.1_2.1.0-1_amd64.deb'
The following NEW packages will be installed:
  aspnetcore-runtime-5.0 aspnetcore-targeting-pack-5.0 dotnet-apphost-pack-5.0 dotnet-hostfxr-5.0 dotnet-runtime-5.0
  dotnet-runtime-deps-5.0 dotnet-sdk-5.0 dotnet-targeting-pack-5.0
The following packages will be upgraded:
  dotnet-host
The following packages will be DOWNGRADED:
  netstandard-targeting-pack-2.1
1 upgraded, 8 newly installed, 1 downgraded, 0 to remove and 53 not upgraded.
E: Packages were downgraded and -y was used without --allow-downgrades.
```

After I uninstalled .Net Core 3.1 SDK, and tried again, the installation succeeded.

**Comment by dagood** [comment] 2020-08-27 22:09
> (My initial guess would be that `dotnet-5.0.0-preview.4-deb.tar.gz` has a bad (older) version of `netstandard-targeting-pack-2.1`.)

I ran a command that repros this issue at https://github.com/dotnet/core/issues/4542#issuecomment-664475585, and some extra details I got from it invalidated this idea. I'm going to close this issue as a duplicate to keep tracking this over there.

**Comment by dagood** [comment] 2020-08-27 22:09
Duplicate of https://github.com/dotnet/core/issues/4542

**Closed by dagood** 2020-08-27 22:09 UTC
Labels: area-setup
