### ISSUE TITLE
Down load of .NET 5.0

### ISSUE THREAD

**Issue by BBuno** [dotnet/core#7009] opened 2021-12-07 08:14 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by maryamariyan** [comment] 2021-12-07 21:53
Closing as dupe of https://github.com/dotnet/core/issues/7010

**Closed by maryamariyan** 2021-12-07 21:53 UTC
