### ISSUE TITLE
packages.microsoft.com issue

### ISSUE THREAD

**Issue by aukesj** [dotnet/core#6371] opened 2021-06-14 20:00 UTC
I know this is the .NET team, but since there seems to be no public contact for the packages.microsoft.com repo I don't know where to address this. Please forward this issue for me.

### Description

I'm using CentOS with Foreman / Katello to offer patches to our servers. The Ubuntu patches are served as well. Now for Ubuntu Focal (20.04) the repo seems fine, but for Bionic (18.04), I get checksum errors:

`DEBSYNC002: Unable to sync 42044737-20ba-4567-89b1-ab531887e734 from https://packages.microsoft.com/ubuntu/18.04/prod: mismatching checksums for adutil-preview_0.7.022_amd64.deb: expected f657b73dd8d6c1486a0862f53010a4562e287cb5, actual 89283b83f411664e29b3dffc649d63b4c9f0596c`

### Configuration

Foreman 2.3.5, but since this seems to be a problem with the package checksums, I guess the issue is on the packages.microsoft.com site.

Thank you in advance for looking in to this!

**Comment by michaelgsharp** [comment] 2021-06-14 20:55
So this happened last week to a different linux distro. Turns out that after some packages were updated on our end, took about 4 - 6 hours or so for this error to go away. Has to do with mirror syncing, or something like that.

I just checked and we updated the packages for Bionic about 2.5 hours ago, so this should be the same issue as last week and should clear up on its own in another couple of hours. I'll keep the issue open for now, but in a couple of hours can you check again and then close if it working?

**Comment by dagood** [comment] 2021-06-14 21:48
It looks like you've hit the same issue as https://github.com/dotnet/core/issues/5860. (January!) The https://packages.microsoft.com maintainers weren't able to reproduce the problem at the time. 😕

> Turns out that after some packages were updated on our end, took about 4 - 6 hours or so for this error to go away. Has to do with mirror syncing, or something like that.

The time limit for .NET packages before escalation is only 30 minutes: https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#failed-to-fetch. IIRC it's actually not expected to happen at all after some improvements the packages.microsoft.com team made to their publishing process.

**Comment by michaelgsharp** [comment] 2021-06-14 21:54
And here is the similar one that just happened last week. https://github.com/dotnet/core/issues/6356 on Debian.

**Comment by dagood** [comment] 2021-06-14 22:00
That's unfortunate. It's definitely possible that things regressed. I don't actively work in this area anymore (the issue just caught my eye) so I'm not necessarily up to date.

**Comment by mairaw** [comment] 2021-06-15 00:37
Do you know who does @dagood?

**Comment by dagood** [comment] 2021-06-15 00:52
@rbhanda may be able to help with this.

**Comment by aukesj** [comment] 2021-06-15 06:32
I checked again just now, but unfortunately the mismatching checksum still exists.

**Comment by dagood** [comment] 2021-06-15 14:34
@aukesj for some diag info, could you try the commands in https://github.com/dotnet/core/issues/5860#issuecomment-763087279 to get the IP of the mirror you're using?

**Comment by rbhanda** [comment] 2021-06-15 15:05
I am following up on this with the packages.microsoft.com team.  I will keep the thread updated once I hear back from them.

**Comment by aukesj** [comment] 2021-06-15 15:15
$ ping packages.microsoft.com
PING csd-apt-weu-d-4.westeurope.cloudapp.azure.com (13.81.215.193): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
^C
--- csd-apt-weu-d-4.westeurope.cloudapp.azure.com ping statistics ---
3 packets transmitted, 0 packets received, 100.0% packet loss
$ wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
--2021-06-15 17:13:04--  https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
Resolving packages.microsoft.com (packages.microsoft.com)... 13.81.215.193
Connecting to packages.microsoft.com (packages.microsoft.com)|13.81.215.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3132 (3.1K) [application/octet-stream]
Saving to: ‘packages-microsoft-prod.deb’

packages-microsoft-prod.deb         100%[=================================================================>]   3.06K  --.-KB/s    in 0s

2021-06-15 17:13:04 (597 MB/s) - ‘packages-microsoft-prod.deb’ saved [3132/3132]

$ sum packages-microsoft-prod.deb
35135 4 packages-microsoft-prod.deb
$ md5 packages-microsoft-prod.deb
MD5 (packages-microsoft-prod.deb) = a743911ec6ef33668b61c51947d87ecb

**Comment by aukesj** [comment] 2021-06-15 15:49
Furthermore, my Foreman (repo) server which tries to mirror the Microsoft packages for Ubuntu says:

DEBSYNC002: Unable to sync 42044737-20ba-4567-89b1-ab531887e734 from https://packages.microsoft.com/ubuntu/18.04/prod: mismatching checksums for adutil-preview_0.7.022_amd64.deb: expected f657b73dd8d6c1486a0862f53010a4562e287cb5, actual 89283b83f411664e29b3dffc649d63b4c9f0596c

When I browse to https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/a/adutil-preview/ I see a different version of the adutil-preview package; adutil-preview_0.7.029_amd64.deb

Maybe this is just my lack of knowledge regarding Debian/Ubuntu packages.

**Comment by aukesj** [comment] 2021-06-15 15:57
Because I thought the version difference was quite suspicious, I decided to remove the Ubuntu Bionic repo from the Foreman product "Microsoft Packages", recreated it and synced it succesfully! So, this was a Foreman issue and is now solved.

**Comment by michaelgsharp** [comment] 2021-06-15 16:52
Awesome. Thanks everyone for your help. I'll go ahead and close the issue since its been resolved.

**Closed by michaelgsharp** 2021-06-15 16:52 UTC
