### ISSUE TITLE
new socket based on socketInformation not supported

### ISSUE THREAD

**Issue by soyang2828** [dotnet/core#4130] opened 2020-01-15 08:14 UTC
new socket based on socketInformation not supported. And together CloneAndClose() is not supported either. This is used for scenario like one process handing over request to another process for load-balancing or for request dispatching.

**Comment by scalablecory** [comment] 2020-01-15 15:42
Closing as duplicate of https://github.com/dotnet/runtime/issues/1760.

If you can, please note specific scenarios in that issue as it will help us in prioritizing.

**Closed by scalablecory** 2020-01-15 15:42 UTC
