### ISSUE TITLE
program not run

### ISSUE THREAD

**Issue by shrirang10** [dotnet/core#7240] opened 2022-03-01 09:59 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

C:\Users\Shrirang\MyApp>dotnet run
C:\Users\Shrirang\MyApp\Program.cs(2,1): error CS8802: Only one compilation unit can have top-level statements. [C:\Users\Shrirang\MyApp\MyApp.csproj]

The build failed. Fix the build errors and run again.

Provide details about the problem you're experie
![net](https://user-images.githubusercontent.com/88581901/156147575-2b89a573-2bd5-4366-b24b-4835a4446194.JPG)
ncing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment] 2022-03-01 18:32
Hi @shrirang10 - If you search for the error message you get a very detailed explanation of the root cause of the error: https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements

Closing since it's answered in the linked documentation.

**Closed by carlossanlop** 2022-03-01 18:32 UTC

**Comment by mairaw** [comment] 2022-03-01 23:35
The problem here is that you created a new project inside the MyApp folder. You should only run the dotnet new command once. You can either delete the internal MyApp folder or delete everything and start over.
