### ISSUE TITLE
Not showing version even dotnet is installed

### ISSUE THREAD

**Issue by barshalamixaane** [dotnet/core#3135] opened 2019-08-01 10:22 UTC
Hi, I am having following issue though i have installed dotnet. please help me.
![Screenshot from 2019-08-01 16-04-33](https://user-images.githubusercontent.com/33709071/62285819-2320bf00-b476-11e9-9515-5feb651d98fd.png)

**Comment by dasMulli** [comment] 2019-08-01 10:45
Did you try opening an new terminal?

**Comment by barshalamixaane** [comment] 2019-08-06 04:58
> Did you try opening an new terminal?

yes I tried but its not solving the problem. Do you have any new idea? If so please help me.

**Comment by dagood** [comment] 2019-08-07 06:38
When installing via snap, the command has a namespace and is called `dotnet-sdk.dotnet` by default. You can alias it to `dotnet` using `sudo snap alias dotnet-sdk.dotnet dotnet`. More info here (and on other versions' download markdown files): https://github.com/dotnet/core/blob/a71496fbae20d49d3d79b14fb029d0323a26d793/release-notes/2.2/2.2.6/2.2.401-sdk-download.md#install-using-snap

**Comment by dagood** [comment] 2019-08-07 06:39
Duplicate of https://github.com/dotnet/core/issues/2692

**Closed by dagood** 2019-08-07 06:39 UTC
