### ISSUE TITLE
Problems installing dotnet on Mac OS 10.14.4

### ISSUE THREAD

**Issue by rthacker02** [dotnet/core#2693] opened 2019-05-08 13:28 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I am running OSX Mojave 10.14.4. The dotnet core files install but when I attempt to run dotnet in terminal - message: command not found. I can navigate to /usr/local/share/dotnet/dotnet and see that it actually did install. I can run ./dotnet at that location and get information back regarding dotnet. I have ran export PATH="/usr/local/share/dotnet/" but it does not seem to have an effect.

My goal is to be able to use VS Code but regardless of what I do it does not recognize that .net core is installed.

**Comment by dagood** [comment] 2019-05-08 22:43
> The dotnet core files install but when I attempt to run dotnet in terminal - message: command not found.

Is that the exact error messsage? This seems strange, usually the command name is in there. Like this:

```
$ foo
-bash: foo: command not found
```

Admittedly I'm on macOS 10.13.6, I'm not sure if this might have changed.

> I have ran `export PATH="/usr/local/share/dotnet/"` but it does not seem to have an effect.

Also strange, that should definitely work. (Even without `export`.) To be specific, does running these commands in the same terminal results in `command not found`?

```
$ export PATH="/usr/local/share/dotnet/"
$ dotnet
Usage: dotnet [options]
...
```

(I'm pointing out "in the same terminal" on the off chance you weren't aware that `export PATH=...` only takes effect in the same session. 🙂)

I wonder if you have some configuration like `~/.bash_profile` that's interfering. Can you try this series of commands to see if it works without your normal config?

```
env -i bash --norc --noprofile
export PATH="/usr/local/share/dotnet/"
dotnet
```

**Comment by rthacker02** [comment] 2019-05-09 13:52
I was trying to do this in the same session. I tried running the statements recommended and dotnet worked after clearing the bash profile. However, once I shutdown the terminal window/session no more joy. Possibly I am trying to add this to the PATH statement incorrectly. I would like for this to be permanent.

On May 8, 2019 at 4:44 PM, Davis Goodin <notifications@github.com> wrote:



The dotnet core files install but when I attempt to run dotnet in terminal - message: command not found.

Is that the exact error messsage? This seems strange, usually the command name is in there. Like this:

$ foo

-bash: foo: command not found



Admittedly I'm on macOS 10.13.6, I'm not sure if this might have changed.

I have ran export PATH="/usr/local/share/dotnet/" but it does not seem to have an effect.

Also strange, that should definitely work. (Even without export.) To be specific, does running these commands in the same terminal results in command not found?

$ export PATH="/usr/local/share/dotnet/"

$ dotnet

Usage: dotnet [options]

...



(I'm pointing out "in the same terminal" on the off chance you weren't aware that export PATH=... only takes effect in the same session. 🙂)

I wonder if you have some configuration like ~/.bash_profile that's interfering. Can you try this series of commands to see if it works without your normal config?

env -i bash --norc --noprofile

export PATH="/usr/local/share/dotnet/"

dotnet

**Comment by dagood** [comment] 2019-05-09 15:18
> However, once I shutdown the terminal window/session no more joy.

That was only a diagnosis step, not a solution. Now we know something in your shell configuration is preventing the normal configuration from working right.

If you're ok with posting your `~/.bash_profile`, `~/.bashrc`, `~/.profile`, etc. on Gist or something, maybe some line will stand out. Otherwise you're going to need to go through your shell's configuration to narrow down the cause.

**Comment by karelz** [comment] 2019-05-17 21:56
No info - should we close it @dagood? Or is there any next step?

**Comment by dagood** [comment] 2019-05-17 22:19
Let's close it for now, I would love to help get to the bottom of this if you have some time to send more info though, @rthacker02.

**Closed by dagood** 2019-05-17 22:19 UTC
Labels: needs more info
