### ISSUE TITLE
Having trouble in Ubuntu 18.04 installing dotnet (156011 != 155826)

### ISSUE THREAD

**Issue by BRAND-H** [dotnet/core#5373] opened 2020-10-16 03:48 UTC
I've built my container multiple times this evening, all built fine, and this **just** now started failing, nothing's changed.

-----------------------

Get:1 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease [4003 B]
Get:2 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages [156 kB]
Err:2 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
  File has unexpected size (156011 != 155826). Mirror sync in progress? [IP: 40.118.250.56 443]
  Hashes of expected file:
   - Filesize:155826 [weak]
   - SHA512:89de923d7c9395f6fd289afc05795fc29318b668727653ab024e33ce85a5bf909f59ce52efc9ca0cdfe1cc5ce7451796f1b38964d046913658ba86f9ffd97662
   - SHA256:18e2eff37d95013f29f7c68baf8f71954346a7118bc79de8246023cd78f8d853
   - SHA1:aab0617c5532798ffa6caf014f2e6b51035625b9 [weak]
   - MD5Sum:a3c30ff695b02ebe310c0852563b288a [weak]

**Comment by dagood** [comment] 2020-10-16 05:19
Thanks for reporting this--I've moved the issue to dotnet/core for slightly more visibility while we work on getting it fixed.

Note to others: I've confirmed this error shows up for me too on a fresh Docker container. After setting up the Ubuntu 18.04 feed based on https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#1804- and running `apt update`, it shows up. This is affecting the entire feed, not just .NET packages.

/cc @rbhanda @NikolaMilosavljevic

**Comment by rbhanda** [comment] 2020-10-16 05:31
As per our team there is a service updating repos. It should be resolved once that is done. Meanwhile I am following up on this issue and keep everyone updated with changes.

**Comment by halvorhm** [comment] 2020-10-16 05:47
I have to ask @dagood, I've seen this problem several times, and you always fix it or bring it to the right people 🙏. But could the team maybe review its tests or something so we see less of this size mismatch problem in the future? Again, thanks for the great communication!

**Comment by dagood** [comment] 2020-10-16 06:03
Thanks for the kind words. 😄 There's some more info about our communication with the team that hosts packages.microsoft.com to help them improve the reliability of the service at https://github.com/dotnet/core/issues/4167, which is slow but still ongoing. They deployed some improvements earlier this year which has seemed to make release-day outages happen less often (we used to have one basically every time we published a servicing release), so we'll be interested to hear what happened this time.

**Comment by rbhanda** [comment] 2020-10-16 06:14
The services are now restored, the issue should be resolved now.

**Comment by halvorhm** [comment] 2020-10-16 06:18
Works here as well, thanks!

**Comment by rbhanda** [comment] 2020-10-16 21:30
Closing this since the issue is resolved.

**Closed by rbhanda** 2020-10-16 21:30 UTC
Labels: area-setup
