### ISSUE TITLE
The 3.1.0 dotnet-runtime-3.1 Linux packages say "3.1.0 Preview 3" in their descriptions (Debian + RPM)

### ISSUE THREAD

**Issue by dagood** [dotnet/core#3975] opened 2019-12-08 01:25 UTC
Note that like the other issues with 3.1.0 (https://github.com/dotnet/core/issues/3950), the package's description says 3.1.0 Preview 3, but it actually installs a build that is essentially 3.1.0 stable, and it should work fine.

I saw this comment on the blog post calling out the problem: https://devblogs.microsoft.com/dotnet/announcing-net-core-3-1/#comment-4170.

---

I've tried installing 3.1.0 on Ubuntu 19.04 and CentOS 7, and "3.1.0" is installed on the machine:

```
$ dotnet --info
...
  Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

However the package description says "3.1.0 Preview 3"

```
$ yum info dotnet-runtime-3.1
...
Summary     : Microsoft .NET Core Runtime - 3.1.0 Preview 3 Microsoft.NETCore.App
```

This seems to be the same underlying problem that's caused the other 3.1.0 "Preview 3" issues. When I looked into it earlier, I found there weren't any differences that should matter to Linux users: https://github.com/dotnet/runtime/issues/492#issuecomment-561408378.

This may not be worth fixing until 3.1.1, due to the risk and cost in replacing the bad packages with the correct ones without advancing the patch version.

@leecow

**Comment by leecow** [comment] 2019-12-09 15:54
Thanks for the tracking issue. Since this has the same root cause as the comments in https://github.com/dotnet/core/issues/3950 and https://github.com/dotnet/core/issues/3962,  closing as a duplicate.

**Closed by leecow** 2019-12-09 15:54 UTC

**Comment by dagood** [comment] 2019-12-09 15:59
@leecow to make sure the info's reachable here, do we plan to fix the Linux packages for 3.1.0 or not?

**Comment by leecow** [comment] 2019-12-09 16:00
This will be fixed for all packages and installers exhibiting the behavior in 3.1.1 in January.

**Comment by SimonCropp** [comment] 2020-01-14 23:45
@leecow we installed 3.1.1 today and it still shows as preview
