### ISSUE TITLE
Add debian 10 support , update the document please

### ISSUE THREAD

**Issue by netroby** [dotnet/core#3288] opened 2019-09-01 04:18 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current
Operating System: Linux Debian 9 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by dagood** [comment] 2019-09-03 14:30
Duplicate of https://github.com/dotnet/core/issues/2576

Some extra info from https://github.com/dotnet/core/issues/3201#issuecomment-522658160:

> This is part of a larger discussion at #2576 about how to keep the list up to date.
> 
> A few confounding issues:
> 
> * The packages on the Debian 9 repository are the same as the ones on the Debian 10 repository. There's no pressing need to update.
> * These aren't our (.NET Core's) repositories. Other Microsoft teams use it too, and they might _not_ have packages on the Debian 10 feed, even though they would work just fine. You can only install one Microsoft repo at a time, so by instructing users to use the Debian 10 feed we could break the other team's install/update scenario. (This is the case with PowerShell.)

**Closed by dagood** 2019-09-03 14:30 UTC
