### ISSUE TITLE
ContentWithTargetPath not working in asp.net core 3

### ISSUE THREAD

**Issue by muh00mad** [dotnet/core#3560] opened 2019-10-06 20:53 UTC
I'm using Visual studio 2019 v16.3.2 in windows and I've a asp.net core 3.0.0 project with folders contain JSON files and I've modified the project file so it will copy the json files from the directory structure to the root bin directory using the following xml

```xml
  <ItemGroup>
    <ContentWithTargetPath Include="Configuration\api.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>api.json</TargetPath>
    </ContentWithTargetPath>

    <ContentWithTargetPath Include="Configuration\api.dev.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>api.dev.json</TargetPath>
    </ContentWithTargetPath>
  </ItemGroup>
```
Yet the files copied twice, once in the root directory and another in their folder structure.

**Comment by scalablecory** [comment] 2019-10-07 17:16
CC @safern @ViktorHofer

**Comment by ViktorHofer** [comment] 2019-10-07 17:24
cc @rainersigwald

**Comment by dasMulli** [comment] 2019-10-07 19:06
Adding `ContentWithTargetPath` definitions will not remove the default configuration for the existing files so you'll need to update the existing content items to not cause additional copy operations:

```xml
  <ItemGroup>
    <Content Update="Configuration\*.json" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
  </ItemGroup>
```

**Comment by muh00mad** [comment] 2019-10-09 05:51
@dasMulli this wasn't the with visual studio 2017 with .net core projects

**Comment by dasMulli** [comment] 2019-10-09 06:13
Yes the 3.0 web sdk (actually the razor sdk) more aggressively copies json files.

I've previously opened https://github.com/aspnet/AspNetCore/issues/14799 because I don't think that Properties\launchSettings.json should be copied (it is not published though).

A change between 2.* and 3.* is also that content files are now copied to the output directory as well as published. But I believe you would have had the same experience when calling `dotnet publish` in 2.* that you now already have during build. 

cc @javiercn

**Comment by javiercn** [comment] 2019-10-09 08:17
@muh00mad Thanks for reporting the issue.

We think this is duplicate of https://github.com/aspnet/AspNetCore/issues/14799 so we will be closing this issue and tracking the problem in the mentioned issue.

Thanks!

**Closed by javiercn** 2019-10-09 08:17 UTC
