### ISSUE TITLE
blazor.server.js fails to negotiate with server 500 error

### ISSUE THREAD

**Issue by phantomkingx** [dotnet/core#2610] opened 2019-04-19 21:17 UTC
Using vanilla blazor template

3.0.100-preview5-011475 (issue does not exist in preview4)

```
System.TypeLoadException: Could not load type 'System.Text.Json.Utf8JsonWriter' from assembly 'Microsoft.AspNetCore.Http.Connections.Common, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' due to value type mismatch.
   at Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.WriteResponse(NegotiationResponse response, IBufferWriter`1 output)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.WriteNegotiatePayload(IBufferWriter`1 writer, String connectionId, HttpContext context, HttpConnectionDispatcherOptions options)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.ProcessNegotiate(HttpContext context, HttpConnectionDispatcherOptions options, ConnectionLogScope logScope)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher.ExecuteNegotiateAsync(HttpContext context, HttpConnectionDispatcherOptions options)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by karelz** [comment] 2019-04-19 22:22
cc @ahsonkhan @GrabYourPitchforks @joshfree

**Comment by ahsonkhan** [comment] 2019-04-19 22:45
@BrennanConroy, @natemcmaster - can you please help do the initial triage here if this is an issue at the SignalR layer?

https://github.com/aspnet/AspNetCore/blob/9212f4a3df81ed28707d56e1b339f334fa48eb36/src/SignalR/common/Http.Connections.Common/src/NegotiateProtocol.cs#L37

**Comment by BrennanConroy** [comment] 2019-04-19 22:49
Looks like a dupe of https://github.com/aspnet/AspNetCore/issues/9574

**Comment by karelz** [comment] 2019-04-19 23:07
Duplicate of https://github.com/aspnet/AspNetCore/issues/9574

**Closed by karelz** 2019-04-19 23:07 UTC
Labels: area-aspnet
