### ISSUE TITLE
Error while installing the aspnetcore-runtime-2.1 package

### ISSUE THREAD

**Issue by dotanga** [dotnet/core#3791] opened 2019-11-12 06:57 UTC
Hi,
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/centos7/runtime-2.1.13
Operating System: Linux CentOS 7 - x64

After retrieving the RPM "`sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm`"
and running the yum "`sudo yum install aspnetcore-runtime-2.1`"
I get an error in installing the package "dotnet-host.x86_64 0:3.0.0-1":
`Error: Rpmdb changed underneath us`

Environment:
VM: GCE n1-standard-1
OS: CentOS 7 - x64

**Comment by dagood** [comment] 2019-11-12 18:31
I'm not able to reproduce the issue on a CentOS 7 Docker container. I looked at search results for `Rpmdb changed underneath us` and I wasn't able to find anything very enlightening about it... there was one yum bug that looks like it happened when running some commands in parallel, but nothing about the authoring of RPMs being able to cause this.

**Comment by dotanga** [comment] 2019-11-13 13:52
Thank you for the comment @dagood 
I will look at the parallel issue that you mentioned, because it might be the case - I run the install command through Packer and it might parallel things up.

**Comment by scalablecory** [comment] 2020-09-02 22:42
Looks like no progress for some time, closing this out.

**Closed by scalablecory** 2020-09-02 22:42 UTC
