### ISSUE TITLE
RHEL7 yum install broken aspnetcore-runtime-2.2

### ISSUE THREAD

**Issue by bobbyvacco** [dotnet/core#3889] opened 2019-11-21 20:39 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/runtime-aspnetcore-2.2.8
Operating System: Linux - CentOS 7 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

when running yum install aspnetcore-runtime-2.2, I'm getting an error for file not found (this worked yesterday) it looks like the repo isn't updated with the proper reference to the 2.2.8 version name after the 3.0.1 release yesterday/this morning.

Downloading packages:
STDERR: https://packages.microsoft.com/rhel/7/prod/aspnetcore-runtime-2.2.8-rh.rhel.7-x64.rpm: [Errno 14] HTTPS Error 404 - Not Found

**Comment by bobbyvacco** [comment] 2019-11-21 20:41
aspnetcore-runtime-2.2.8-rh.rhel.7-x64.rpm doesn't exist in this repo, however, aspnetcore-runtime-2.2.8-x64.rpm does (which is the version i actually want)

**Comment by dagood** [comment] 2019-11-21 20:55
Duplicate of https://github.com/dotnet/core/issues/3875

I believe you can install the non-`rh.rhel.7` version manually (you're right, that's what you need) using yum, as a workaround:

```
sudo yum install https://packages.microsoft.com/rhel/7/prod/aspnetcore-runtime-2.2.8-x64.rpm
sudo yum install dotnet-sdk-3.0
```

**Closed by dagood** 2019-11-21 20:55 UTC

**Comment by bobbyvacco** [comment] 2019-11-22 16:46
'yum install aspnetcore-runtime-2.2` works again. thanks!
