### ISSUE TITLE
Fail to install dotnet core 3.0.1 on SLES 12 SP4

### ISSUE THREAD

**Issue by rtssrl** [dotnet/core#3930] opened 2019-11-28 15:25 UTC
Following instructions at https://dotnet.microsoft.com/download/linux-package-manager/sles/runtime-current:

`zypper in aspnetcore-runtime-3.0`

got:

```
Retrieving: aspnetcore-runtime-3.0.1-rh.rhel.7-x64.rpm ..............[not found]
File './aspnetcore-runtime-3.0.1-rh.rhel.7-x64.rpm' not found on medium 'https://packages.microsoft.com/sles/12/prod'
```

Looks like it's trying to install RHEL 7 package on a SLES

**Comment by dagood** [comment] 2019-12-02 16:11
Duplicate of https://github.com/dotnet/core/issues/3875

**Comment by dagood** [comment] 2019-12-02 16:11
I've added `SLES` to the other issue's title to maybe make it more findable. There's a workaround there: https://github.com/dotnet/core/issues/3875#issuecomment-557268395

**Closed by dagood** 2019-12-02 16:11 UTC
