### ISSUE TITLE
2022-03 6.0.3 update only patches AspNetCore.App of the hosting bundle..? 

### ISSUE THREAD

**Issue by vaguepromise** [dotnet/core#7282] opened 2022-03-15 14:17 UTC
We have a system where both .NET Core 5.0 and .NET Core 6.0 co-exist and were installed from the downloadable hosting bundle. We're approving the security updates, via WSUS, each month for both 5.x and 6.x on this system, however seem to find the patching behaviour is different, and I'm unsure if this is by design.

The .NET 5.x security update appears to patch both AspNetCore.App and NETCore.App runtimes - so successfully uplifted both Microsoft.AspNetCore.App and Microsoft.NETCore.App versions from 5.0.14 to 5.0.15 as expected. However on the same system, the .NET 6.x security update has only uplifted the Microsoft.AspNetCore.App version from 6.0.2 to 6.0.3, however the Microsoft.NETCore.App runtime remains at 6.0.2. The developer I'm working with tells me this is problematic. He found that by downloading and re-running the hosting bundle version 6.0.3 uplifted the NETCore.App version to 6.0.3 as one would expect, and his issues are resolved. 

It's worth mentioning that having trawled the WindowsUpdate.log on this particular system, no error seems to be encountered so the security update is installing correctly. I've been able to reproduce this same behaviour on both a Windows Server 2012R2 and Windows Server 2019 system so it's not an OS specific issue. 

So is this behaviour with this months (and forthcoming) security updates by design? If so, why does it differ from .NET 5? 

Thanks.

**Comment by rzikm** [comment] 2022-03-17 13:46
Seems to be duplicate of #7290.

**Closed by rzikm** 2022-03-17 13:46 UTC
