### ISSUE TITLE
C#: `checked` keyword misbehaviour with switch-expression-bodied function 

### ISSUE THREAD

**Issue by Dreamoochy** [dotnet/core#7529] opened 2022-06-13 09:47 UTC
### Description

There is a code:
```csharp
Int32 x = Int32.MaxValue;
Int32 y = Int32.MaxValue;

try
{
  WriteLine($"{x} * {y} = {SomeFuncSwitch(x, y, 2)}");
  WriteLine($"{x} + {y} = {SomeFunc(x, y)}");
}
catch ( OverflowException ex )
{
  WriteLine( $"Overflow in {ex.TargetSite}!" );
}

static Int32 SomeFunc(Int32 x, Int32 y) => checked (x + y);

static Int32 SomeFuncSwitch(Int32 x, Int32 y, UInt16 condition) =>
checked (
  condition switch
  {
    1 => x + y,
    _ => x * y
  }
);
```
`SomeFunc()` throws exception, whereas `SomeFuncSwitch()` does not. It will if switch cases are `checked`.

### Expected

`SomeFuncSwitch()` should throw an exception or some warning/error* shoud be shown.

### Reality

Neither exception is thrown nor warning/messages* are shown.

### Configuration

* .NET v6.0.300
* C# v10.0
* Compiler v4.3.0-2.22267.5 (89370447)
* Windows 11 Pro 22000.708
* Arch: x64
* VSCodium v1.67.2

*P.S. I mean something like compiler warning if such construction is not supported.

**Comment by svick** [comment] 2022-06-13 11:56
This is a duplicate of https://github.com/dotnet/roslyn/issues/61843.

**Closed** 2022-06-13 12:55 UTC

**Comment by Dreamoochy** [comment] 2022-06-13 12:59
Closed as a duplicate.
