### ISSUE TITLE
.NET Core 3.0 Preview 9

### ISSUE THREAD

**Issue by leecow** [dotnet/core#3304] opened 2019-09-04 19:06 UTC
[Release Notes](https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview9.md)
[Download](https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview9-download.md)

**Blog posts**

[.NET Core](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-9/)
[ASP.NET Core](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/)

Please report any issues you find with 3.0.0 Preview 9, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [aspnet/AspNetCore](https://github.com/aspnet/AspNetCore) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/corefx](https://github.com/dotnet/corefx/issues) - for API issues and questions
* [dotnet/coreclr](https://github.com/dotnet/coreclr/issues) - for runtime issues
* [dotnet/core-setup](https://github.com/dotnet/core-setup/issues) - for installer issues
* [dotnet/winforms](https://github.com/dotnet/winforms/issues) - for Winforms issues
* [dotnet/wpf](https://github.com/dotnet/wpf/issues) - for WPF issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

**Comment by sujayvsarma** [comment] 2019-09-05 10:20
Build with restore is broken. Which would be the right repo to file this?

Here is what happens. 

```
dotnet build --runtime win-x64 --configuration Debug --verbosity detailed
```

Here is the tail of the build output:
![Screenshot](https://user-images.githubusercontent.com/7371750/64333041-603b1c80-cff3-11e9-9e37-9caa1c13478d.png)

It just hangs there until `CTRL+C` cancelled. I attempted to get the Nuget URLs displayed using Edge browser. It downloaded successfully. So I am not sure why it is failing on the build restore.

By doing the "VS will install .NET Core", you have effectively screwed up my development AND build systems. Because ".NET Core 3.0 SDK" cannot be uninstalled without uninstalling all the modules of VS that I require. 

Notes:

1. Normal build & run from within Visual Studio works fine (using 2019 Community Edition, Preview 3.0, updated just earlier today).

2. I noticed the above when I was trying to publish it to Azure. The project was an ASP.NET Core 3.0 MVC application. 

3. The version released online is `3.0.100-preview9-014004` (from [here](https://dotnet.microsoft.com/download/dotnet-core/3.0)). But the one that BUILD tries to restore is `3.0.0-preview9-19423-09`.

Quick Solutions appreciated.

**Comment by ares128** [comment] 2019-09-05 13:08
snap package still not upgrading!
Pls find some time to do it.

**Comment by FabianMaurerRedheads** [comment] 2019-09-05 15:05
Preview9 breaks the build for me.
I get a lot of errors like
```
Error MSB3041: Unable to create a manifest resource name for "Converter\ConvertForm.resx". Could not find a part of the path 'C:\Users\USERNAME\Documents\Programming\JiraWorkbench\JiraWorkbench\JiraWorkbench.GUI\Converter\Converter\ConvertForm.cs'. (1, 1)
Error MSB3041: Unable to create a manifest resource name for "Repository\JiraForm.resx". Could not find a part of the path 'C:\Users\USERNAME\Documents\Programming\JiraWorkbench\JiraWorkbench\JiraWorkbench.GUI\Repository\Repository\JiraForm.cs'. (1, 1)

```
The Problem here seems to be that "\Converter\Converter\" is wrong, it needs to be just "\Converter\"
Using "Win10 Pro 1903" and "VS2019 16.3.0 Preview  3.0"

Should I create a separate issue for this? If so, where would be the place?

**Comment by sujayvsarma** [comment] 2019-09-06 03:37
@FabianMaurerRedheads: 

- From what directory are you running the build? 
In a multi-project solution scenario, it needs to be from the same directory as your SLN file.

**Comment by FabianMaurerRedheads** [comment] 2019-09-06 07:09
@sujayvsarma 
The error occurs when doing "dotnet publish" in the same directory as the SLN, and when building in VisualStudio as well.

**Comment by Archomeda** [comment] 2019-09-06 07:14
I still have [this issue](https://github.com/dotnet/core/issues/3184#issuecomment-521829202) from preview 8. Test logs: [Linux](https://github.com/Archomeda/Gw2Sharp/runs/213960019), [Windows](https://github.com/Archomeda/Gw2Sharp/runs/213960025)

Also, I never got a follow up from:
> As you're saying that there's breaking changes between previews, do you  know what has been changed between P7 and P8 that might cause this  behavior? P7 worked just fine.

Now it's P9 of course. I would very much like this issue to be solved before the final version goes live.

**Comment by sujayvsarma** [comment] 2019-09-06 10:07
Interesting. Actually shortly after the announcement when I tried to build, I faced a ton of issues with the build restoring packages from NuGet. I had filed an issue as well. But after about an hour, it went away on its own as NuGet's servers picked up the new packages.

@FabianMaurerRedheads: Could you turn the logging to verbose and look at the logs for the actual problem? It may be something ELSE is broken earlier in the build/publish task-pipeline. The .NET system is notorious for providing crazy and unrelated top-level error messages during a build.

**Comment by FabianMaurerRedheads** [comment] 2019-09-06 11:11
@sujayvsarma I opened an issue for better tracking here: https://github.com/dotnet/core/issues/3319

I included a code sample, which is probably the best.

**Comment by leecow** [comment] 2019-09-06 18:47
> snap package still not upgrading!
> Pls find some time to do it.

@ares128 - I have promoted Preview 9 from the Edge channel to Beta. You should get the auto-refresh now.

**Comment by FeodorFitsner** [comment] 2019-09-08 18:56
Having the same issue with preview 9: `error MSB3041: Unable to create a manifest resource name for "Email/Templates.resx". Could not find a part of the path '/app/Appveyor/Email/Email/Templates.cs'.`. Double `/Email/Email`.

**Comment by mikeHag** [comment] 2019-09-15 15:56
Have a WPF application running with .Net and Entity Framework 6 as well as Entity Framework Core 2.26.  I used the Database First approach.  Entities have "buddy" classes that add Data Annotations.

Validation works.  Here is the method.
        private void ValidateDataAnnotations(string propertyName, object currentValue)
        {
            var results = new List<ValidationResult>();
            var context = new ValidationContext(Model) { MemberName = propertyName };
            Validator.TryValidateProperty(currentValue, context, results);

            foreach (var result in results)
            {
                AddError(propertyName, result.ErrorMessage);
            }
        }

I moved the project to .Net Core 3.0 Preview 9.  Using EF Core 3.0 Preview 9 the same method fails to catch validation errors included in buddy classes using MetadataType.  It appears that the prior behavior merged the CustomAttributes of the MetadataType with the Entity and that now they are treated separately.  

Here is code that will work with the upgraded project.  It needs to get the CustomAttributes from the MetadataType and validate each.  TryValidateProperty only works against DataAnnotations within the scaffolded entity partial classes.

        private void ValidateDataAnnotations(string propertyName, object currentValue)
        {
            /*
             * https://visualstudiomagazine.com/Articles/2012/04/01/Integrating-Validation-with-the-Entity-Framework.aspx
             */
           
           object mdtObj = this.Model.GetType().GetCustomAttributes(
               typeof(MetadataTypeAttribute), true).FirstOrDefault();
           if (mdtObj != null)
           {

               MetadataTypeAttribute mdt = (MetadataTypeAttribute)mdtObj;
               PropertyInfo prop = mdt.MetadataClassType.GetProperty(propertyName);
               var atts = prop.GetCustomAttributes(typeof(ValidationAttribute), true);
               foreach (ValidationAttribute att in atts)
               {
                   if (!att.IsValid(currentValue))
                   {
                       AddError(propertyName, att.ErrorMessage);
                   }

               }
           }
           
           /* 
            * Original implementation.  Works with .Net and EF 6.  Also works with .Net and EF Core 2.2.6
            */
            
           var results = new List<ValidationResult>();
           var context = new ValidationContext(Model, null, null) { MemberName = propertyName };
           Validator.TryValidateProperty(currentValue, context, results);

           foreach (var result in results)
           {
               AddError(propertyName, result.ErrorMessage);
           }
... 

Do I have that right?  Is it by design?  Am I missing something basic?

Thanks

**Comment by leecow** [comment] 2019-09-16 12:13
@ajcvickers - can you have a look at https://github.com/dotnet/core/issues/3304#issuecomment-531577158 above?

**Comment by jwooley** [comment] 2019-09-20 14:39
I can confirm that I'm seeing the same resx error MSB3041 in a winform app where the form controls and resx are in subfolders. If I move the resx file to the root of the project, the error goes away.

**Comment by sujayvsarma** [comment] 2019-09-22 05:32
@jwooley Please see https://github.com/microsoft/msbuild/issues/4695 for your issue. The issue has been fixed, and should soon be in a .NET Core update.

**Comment by ajcvickers** [comment] 2019-10-07 20:03
@mikeHag: I believe this is due to https://github.com/dotnet/corefx/issues/32876

**Comment by mairaw** [comment] 2020-05-13 01:07
Closing older announcement issues.

**Closed by mairaw** 2020-05-13 01:07 UTC
Labels: announcement
