### ISSUE TITLE
No PKG installer for osx for ASP.NET core runtime  

### ISSUE THREAD

**Issue by JiahongJin1** [dotnet/core#4081] opened 2020-01-06 08:30 UTC
**--Description**
There is no PKG installer for osx for ASP.NET core runtime , only binaries installer.
![image](https://user-images.githubusercontent.com/46206739/71804654-1ba5b780-309f-11ea-9c3b-00d51d644481.png)

![image](https://user-images.githubusercontent.com/46206739/71804669-27917980-309f-11ea-9ddb-f5a6c37032c3.png)

**--Note:** 
There is no PKG installer for ASP.NET Core Runtime either on public download page. Take .net core 3.1 for example 
![image](https://user-images.githubusercontent.com/46206739/71803934-0891e800-309d-11ea-8e65-8a9dc96e858d.png)

**Comment by dagood** [comment] 2020-01-06 16:09
(Transferred from core-setup, this is an ASP.NET or release process issue, not a Runtime issue. dotnet/runtime is the new place for Runtime issues anyway, not core-setup.)

Is this a bug report (these files have existed in a previous release and don't in this one (which one?)) or a feature request?

**Comment by livarcocc** [comment] 2020-01-06 16:32
I believe these files never existed before.

**Comment by dagood** [comment] 2020-01-06 20:23
Closing: this seems to be expected behavior. To request these pkgs be created I think the way to go is filing a feature request issue at https://github.com/aspnet/AspNetCore/issues. (I can't move this issue from the dotnet => aspnet org using the GitHub transfer feature.)

**Closed by dagood** 2020-01-06 20:23 UTC
