### ISSUE TITLE
Error MSB4044 - CheckEmbeddedRootDescriptor

### ISSUE THREAD

**Issue by Symbai** [dotnet/core#2208] opened 2019-01-08 01:51 UTC
# Issue 
I got this error in console when trying to publish:
`ILLink.Tasks.targets(451,5): error MSB4044: The CheckEmbeddedRootDescriptor task did not receive a value for the required AssemblyPath parameter.`

# General

Created a new .NET Core 3.0 WPF project
Added ILLink.Tasks nuget package
Ran this command:
`dotnet publish -c release -r win-x64 -o out`

**Comment by Symbai** [comment] 2019-01-08 01:56
Is already reported in mono linker repo: https://github.com/mono/linker/issues/428

**Comment by karelz** [comment] 2019-01-08 03:59
Duplicate of https://github.com/mono/linker/issues/428

**Closed by karelz** 2019-01-08 03:59 UTC

**Comment by cup** [comment] 2019-05-05 19:52
https://github.com/dotnet/core/issues/2208
https://github.com/dotnet/coreclr/issues/24397
https://github.com/dotnet/winforms/issues/210
https://github.com/mono/linker/issues/428
