### ISSUE TITLE
InvalidDataException on Debian 6.0 but not on Windows 10

### ISSUE THREAD

**Issue by Erlite** [dotnet/core#762] opened 2017-07-20 09:46 UTC
Heya,

I use a package, CoreRCON, which allows me to connect to Source Game Servers to remotely send console commands. On start, my app creates the connections to the servers, and stores them for later. The problem is, one of the rcon server connection throws a `System.IO.InvalidDataException` on my Debian server, but testing on my Windows PC, no error is thrown. Trying to catch the exception in a try-catch statement doesn't work.

Exception: https://hastebin.com/eyibotehup.css
Server: Linux botsrv 4.5.7-std-3 #1 SMP Tue Jul 12 09:56:30 UTC 2016 x86_64 GNU/Linux

Result on Server: 
![image](https://user-images.githubusercontent.com/25248023/28411481-bdfde610-6d38-11e7-823e-bd5510520856.png)

Result on PC: 
![image](https://user-images.githubusercontent.com/25248023/28411447-ab457646-6d38-11e7-8881-2355a9fd801b.png)

**Comment by svick** [comment] 2017-07-21 15:36
I think this is a bug in CoreRCON. It assumes that [its `TCPPacketReceived` method](https://github.com/ScottKaye/CoreRCON/blob/0686557/src/CoreRCON/RCON.cs#L131) will be called for every "packet". But TCP is a stream-based protocol, it does not really have packets (or rather, it uses packets only as an implementation detail), you can't assume that the buffer you receive contains exactly the information you want, not more or less, as is explained in [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.receiveasync?view=netcore-1.1#remarks):

> For byte stream-style sockets, incoming data is placed into the buffer until the buffer is filled, the connection is closed, or the internally buffered data is exhausted.

If it seems to work reliably on Windows, then that's probably just luck.

And CoreRCON is also the reason why the exception is uncatchable: it's thrown from `TCPPacketReceived`, which is the event handler for `SocketAsyncEventArgs.Completed`. As far as I know, if the handler throws an exception (and doesn't handle it itself), you can't catch it.

**Comment by Petermarcu** [comment] 2017-10-07 05:56
Sounds like @svick has helped conclude there is nothing here to fix in .NET Core. If it gets root caused as an issue in the platform, let us know. I'm going to close this for now.

**Closed by Petermarcu** 2017-10-07 05:56 UTC
