### ISSUE TITLE
Update .NET Core Support Policy for .NET 3.1

### ISSUE THREAD

**Issue by jawn** [dotnet/core#3972] opened 2019-12-06 15:19 UTC
# .NET Core Support Policy

Go to https://dotnet.microsoft.com/platform/support/policy/dotnet-core

The document needs to be updated for the release of 3.1

![image](https://user-images.githubusercontent.com/1705112/70333642-2c66d180-1844-11ea-833d-c32c61faffc5.png)

**Comment by scalablecory** [comment] 2019-12-06 23:42
Duplicate of #3971

**Closed by scalablecory** 2019-12-06 23:42 UTC
