### ISSUE TITLE
SSL error when updating to .NET core 3.1

### ISSUE THREAD

**Issue by jfalameda** [dotnet/core#5181] opened 2020-09-10 13:45 UTC
Hi,

We are using .NET core on an API gateway in combination with service fabric. As a result of upgrading .NET core from 2.0 to 3.1 https has stopped working. 

This is an extra of a CURL call displaying the error:

```
*   Trying xxxxxxx...
* Connected to xxxxxx.se (xxxxx) port 8081 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl@1.1/cert.pem
  CApath: /usr/local/etc/openssl@1.1/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

It is an issue hard to reproduce. Could this be caused by an incompatibility with the service fabric listeners? I see that TSL1.3 has being enforced.

Any ideas?

Thanks,
José.

**Comment by GrabYourPitchforks** [comment] 2020-09-11 01:33
Dupe of https://github.com/dotnet/core/issues/5182.

**Closed by GrabYourPitchforks** 2020-09-11 01:33 UTC
