### ISSUE TITLE
Dot NET EXE

### ISSUE THREAD

**Issue by HamdaouiJ** [dotnet/core#2430] opened 2019-03-12 16:52 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Error Message
The program cant start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.

**Comment by leecow** [comment] 2019-03-12 20:56
Need a bit more information to know how to help. What version of Windows? What steps did you perform leading up to the error message?

**Comment by karelz** [comment] 2019-03-19 01:22
Duplicate of https://github.com/dotnet/core-setup/issues/4388

**Closed by karelz** 2019-03-19 01:22 UTC
Labels: area-tutorials, needs more info

**Comment by HamdaouiJ** [comment] 2019-03-27 13:55
Thanks for your email:
Windows 7 HomePremiumIntel i3 CPU M380 @ 2.53 GHz 2.53 GHz64 Bit Operating System

Sincerely yours,Chokri Jack Belgacem Hamdaoui
c.hamdaoui@aol.com


-----Original Message-----
