### ISSUE TITLE
.NET Core application name does not change in taskbar?

### ISSUE THREAD

**Issue by mudasir111** [dotnet/core#1351] opened 2018-03-15 06:30 UTC
.NET Core application name does not change in taskbar?

Even after the self contained publishing the process name doesn't change, the assembly name property seems to work only on changing the .dll file name.

I have four applications running, but for each process it shows dotnet as shown in the picture

![attachment](https://user-images.githubusercontent.com/25227248/37447441-223afbf2-2848-11e8-99af-5f4ae191a37a.PNG)

**Comment by svick** [comment] 2018-03-15 11:31
I think this is a duplicate of https://github.com/dotnet/core-setup/issues/2007.

**Comment by Petermarcu** [comment] 2018-03-15 18:59
@steveharter @nguerrera is this something for the host or something that needs to be fixed in publish. Host doesn't know the name of the app until publish.

**Comment by Petermarcu** [comment] 2018-03-15 19:09
I think the different here is that for a self-contained application or any application where the host is renamed to match the program name, we should be able to give something better in task manager.

**Comment by Petermarcu** [comment] 2018-03-17 17:35
@nguerrera @livarcocc I'm going to move this to the CLI repo because I think this is about what happens when the apphost exe is renamed and updated to "look like the app".

**Comment by Petermarcu** [comment] 2018-03-17 17:35
Issue moved to [dotnet/cli #8832](https://github.com/dotnet/cli/issues/8832) via [**ZenHub**](https://www.zenhub.com/)

**Closed by Petermarcu** 2018-03-17 17:35 UTC
