### ISSUE TITLE
.net mac error

### ISSUE THREAD

**Issue by rremove** [dotnet/core#6933] opened 2021-11-17 19:52 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

I tried to install dotnet 6.0 over 3 times and each time after i finished the insalling when i open the terminal and i type "dotnet" it said "zsh: command not found: dotnet" .I tried to install dotnet 5.0 too but it gave me the same error.The installing location was Macintosh HD.

**Comment by greenozon** [comment] 2021-11-19 21:20
Refer for steps for Macos over here  https://docs.microsoft.com/en-us/dotnet/core/install/macos

**Comment by eiriktsarpalis** [comment] 2021-11-22 16:05
Duplicate of #6953.

**Closed by eiriktsarpalis** 2021-11-22 16:05 UTC
