### ISSUE TITLE
Path not automatically update when I install .NetSDK 

### ISSUE THREAD

**Issue by Adrianjewell91** [dotnet/core#3831] opened 2019-11-18 15:23 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos Mojave: 10.14.6

The tutorial expects the .NET SDK to be installed and then be automatically runnable from the command prompt (see tutorial) if you follow the instructions and use the wizard. In actuality, you need to update path after installtion, according to the path that is given at the end of the installation wizard (which for me was: "/usr/local/share/dotnet")

**Comment by dagood** [comment] 2019-11-18 18:43
This is probably https://github.com/dotnet/core-setup/issues/6521. The macOS installer uses the Apple `path_helper` utility, which is very easy to break if you have your own shell profile (`.bashrc`, `.bash_profile`, etc.). More info in that issue.

Closing because it's very likely the same problem, but let me know if it's not and we'll reopen. (Or you can always open a new issue with additional info.)

**Comment by dagood** [comment] 2019-11-18 18:43
Duplicate of https://github.com/dotnet/core-setup/issues/6521

**Closed by dagood** 2019-11-18 18:43 UTC
