### ISSUE TITLE
wpf compiles but wont run

### ISSUE THREAD

**Issue by yilmazdurmaz** [dotnet/core#2363] opened 2019-03-02 23:56 UTC
# Issue Title

wpf compiles but wont run

# General

actually, the problem is solvable IF you are connected to the internet, after spending some time, searching and trying things.

solution: install "Microsoft_Visual_C_Redistributable_2015"

# Remaining problem

I work mostly offline with local packages with other core versions, required nugets downloaded on a separate machine. only console by the way. to try out wpf with core 3, I downloaded the zip file, and this happened. cost me some time to find out about redis and download it and move it etc..

so, for offline developers like me, there needs to be a warning in readme files that for WPF project they need this redistributable installed.

**Comment by karelz** [comment] 2019-03-03 02:57
Duplicate of https://github.com/dotnet/wpf/issues/37

**Closed by karelz** 2019-03-03 02:57 UTC
