### ISSUE TITLE
No support for System.Web.DataVisualization in .NET Core

### ISSUE THREAD

**Issue by justintoth** [dotnet/core#2513] opened 2019-03-27 15:39 UTC
# Issue Title

Our application relies on the System.Web.DataVisualization assembly to generate our charts (System.Web.UI.DataVisualization.Charting namespace.) However, this only exists in .NET Framework and not .NET Core.

# General

We're moving all of our applications over to .NET Core and our class libraries to .NET Standard, and the charting is the last bit of .NET Framework code that we're having trouble porting over. I'd be interested if there are any plans to port over System.Web.DataVisualization to .NET Core? If not (or if not for a while), can you at least provide me with the source code so that I can attempt the conversion myself?

**Comment by karelz** [comment] 2019-03-30 18:45
That is by design at the moment - https://apisof.net/catalog/System.Web.UI.DataVisualization.Charting
@Eilon any thoughts on future addition of the namespace into .NET Core? Is there ASP.NET issue tracking its addition?

**Comment by karelz** [comment] 2019-03-30 18:46
cc @terrajobst

**Comment by Eilon** [comment] 2019-04-01 04:08
Most of what's in that namespace are ASP.NET Web Forms control, so even if they were available in .NET Core, you couldn't use them in ASP.NET Core because there's no Web Forms. But someone could try building some new components based on the existing charting rendering logic. Not a trivial task.

**Comment by justintoth** [comment] 2019-04-01 13:55
Right, the charts could just spit out html strings instead of rendering as ASP.NET Web Forms controls.

**Comment by karelz** [comment] 2019-04-01 15:56
That sounds like a good idea for separate project. Likely outside of the scope of ASP.NET.
Either way, closing here as this is not the right place to track it.

**Closed by karelz** 2019-04-01 15:56 UTC
Labels: area-aspnet

**Comment by wjkhappy14** [comment] 2020-06-18 02:33
why ？

**Comment by Eilon** [comment] 2020-06-18 03:14
@wjkhappy14 sorry it's not clear to me what you are asking. If you're looking for charting solutions for ASP.NET Core, I just did a quick web search and there are many free and many paid solutions for this. Many libraries are JavaScript-based libraries that generate nice looking canvas/SVG-based graphs. There are other solutions that generate charts as images.
