### ISSUE TITLE
Can't find dotnet-sdk-3.0 for Linux Debian 10 - x64

### ISSUE THREAD

**Issue by tallman5** [dotnet/core#3454] opened 2019-09-24 17:46 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian10/sdk-3.0.100
Operating System: Linux Debian 10 - x64

Following instructions on the page, all steps worked up to last one which fails:

$ sudo apt-get install dotnet-sdk-3.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-sdk-3.0
E: Couldn't find any package by glob 'dotnet-sdk-3.0'
E: Couldn't find any package by regex 'dotnet-sdk-3.0'

**Comment by molekm** [comment] 2019-09-24 19:45
Same issue here

**Comment by dagood** [comment] 2019-09-24 20:48
I'm not able to repro this in a Docker container (`debian:10`). However, I do need to install `gpg` or else the command doesn't work (`bash: gpg: command not found`), and that's easy to miss when pasting a whole block of commands. That does cause `sudo apt-get update` to fail, too, though.

Can you post the output of every command you ran during the install, to make sure everything's as expected?

Also, the output of this command would be useful to see if the feed has been installed correctly:

```
# Shows the repositories you have configured. Source: https://askubuntu.com/a/741948
grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
```

**Comment by petertriho** [comment] 2019-09-25 01:22
I'm also having this issue on a rpi 3 running raspbian buster lite

'''
pi@raspberrypi:/etc/apt/sources.list.d $ grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
/etc/apt/sources.list:deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
/etc/apt/sources.list.d/microsoft-prod.list:deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/debian/10/prod buster main
/etc/apt/sources.list.d/raspi.list:deb http://archive.raspberrypi.org/debian/ buster main
/etc/apt/sources.list.d/influxdb.list:deb https://repos.influxdata.com/debian buster stable
'''

**Comment by dagood** [comment] 2019-09-25 03:25
@petertriho, RPi doesn't run on x64, you'll want to follow these instructions on that page:

> Not running x64? You'll need to [download the .NET Core binaries](https://dotnet.microsoft.com/download/dotnet-core/3.0#sdk-3.0.100) instead.

**Comment by dagood** [comment] 2019-09-30 14:34
It's quite possible the original issue was caused by a failed `apt update` due to https://github.com/dotnet/core/issues/3513. Closing as a probable duplicate and due to lack of information.

**Closed by dagood** 2019-09-30 14:34 UTC
Labels: needs more info
