### ISSUE TITLE
SOS_README.md

### ISSUE THREAD

**Issue by GitStorageOne** [dotnet/core#4258] opened 2020-02-14 13:39 UTC
# How to get rid of file `SOS_README.md`? 

Can't find any info on how to achieve that.

# General

Every time we compile project based on core 3.1, this file appears.  
If i delete file, application don't work.  
Maybe it tells that we are missing something important?

**Comment by evan-choi** [comment] 2020-05-06 09:41
![image](https://user-images.githubusercontent.com/9690415/81163096-2cbcf180-8fc9-11ea-9b66-c54e278cbaed.png)

**Comment by hdvoice123** [comment] 2020-05-13 14:10
I'd also like to know this. It seems really weird and I just spent way too much time on this.

**Comment by dave-sampson13** [comment] 2020-06-22 06:41
Anyone...?

**Comment by mairaw** [comment] 2023-01-31 00:28
This seems like a duplicate of https://github.com/dotnet/runtime/issues/33648, which was fixed a long time ago.

**Closed by mairaw** 2023-01-31 00:28 UTC
