### ISSUE TITLE
Ploblem .net

### ISSUE THREAD

**Issue by Aldopiardi** [dotnet/core#8735] opened 2023-09-02 18:25 UTC
Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
[Error - 2:58:48 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: Cannot find module 'c:\Users\aldop\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64\dist\extension.js'
Require stack:
- c:\Users\aldop\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\aldop\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\aldop\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
- 
	at Module._resolveFilename (node:internal/modules/cjs/loader:1010:15)
	at s._resolveFilename (node:electron/js2c/utility_init:2:2740)
	at Module._load (node:internal/modules/cjs/loader:858:27)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (c:\Users\aldop\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28084)
	at f._load (c:\Users\aldop\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:25418)
	at C._load (c:\Users\aldop\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.i [as __$__nodeRequire] (c:\Users\aldop\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)
	at r.rb (c:\Users\aldop\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:26597)
	at async Promise.all (index 0)

Windows 10 Pro
Sistema operacional de 64 bits, processador baseado em x64
8,00 GB (utilizável: 7,81 GB
Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz   3.40 GHz

**Comment by buyaa-n** [comment] 2023-09-08 00:17
> [Error - 2:58:48 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
> Error: Cannot find module 'c:\Users\aldop.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64\dist\extension.js'

Looks like your internet connection is interrupted, please check your connection and try again, closing as the issue is not related to .NET

**Closed by buyaa-n** 2023-09-08 00:17 UTC
