### ISSUE TITLE
Azure Devops Pipeline, Blazor build error on SDK 7.0.302, target UseDotNet@2

### ISSUE THREAD

**Issue by danielheddelin** [dotnet/core#8490] opened 2023-05-25 07:16 UTC
When building a Blazor server project on 7.0.302 in Azure devops it fails.
Building locally using 7.0.302 works fine in visual studio, no errors.

The error is CS0115 and occurs on pretty much every Blazor lifecycle method, such as:
"_Error CS0115: 'ActionPlan.OnInitializedAsync()': no suitable method found to override_"
or OnParametersSetAsync() etcetera.

I managed to isolate our pipeline build problem to SDK 7.0.302 specifically. When changing to 7.0.203 it works again.

The build target that fails contains an SDK target looking like this:
```
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.x'
```

which picks 7.0.302, and when changing the version to 7.0.203 (which was the version used when the build lastly worked) specifically - it runs fine.

**Comment by mairaw** [comment] 2023-05-25 16:10
Duplicate of #8489

**Closed by mairaw** 2023-05-25 16:10 UTC
