### ISSUE TITLE
Apply to add Priority Queue to .Net Core

### ISSUE THREAD

**Issue by memoryfraction** [dotnet/core#2048] opened 2018-11-11 02:42 UTC
Apply to add Priority Queue to .Net Core

# General
Priority Queue is a useful data structure. Some one may explain that SortedSet can handle similar scenarios. Problem is, sometimes, users  need to add duplicate items.

So, I apply to add Priority Queue to .NET CORE.

Thanks

**Comment by karelz** [comment] 2018-11-12 19:12
Duplicate of https://github.com/dotnet/corefx/issues/574

**Closed by karelz** 2018-11-12 19:12 UTC
