### ISSUE TITLE
Extra parenthesis in dotnet.microsoft.com code

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/core#5197] opened 2020-09-14 16:38 UTC
The footer in dotnet.microsoft.com has the following HTML:

```html
        <nav aria-label="Microsoft corporate links">
            <ul class="c-list f-bare" data-m='{"cN":"Corp links_cont","cT":"Container","id":"c1c1m1r1a2","sN":1,"aN":"c1m1r1a2"}'>
                                <li  id="c-uhff-powered by asp.net core")>
                    <a class="c-uhff-link" href="https://dotnet.microsoft.com/learn/web/what-is-aspnet-core" data-mscc-ic="false" data-m='{"cN":"Powered by ASP.NET Core_nav","id":"n1c1c1m1r1a2","sN":1,"aN":"c1c1m1r1a2"}'>Powered by .NET 5.0.0-preview.8.20407.11</a>
                </li>
                <li  id="c-uhff-contact microsoft")>
                    <a class="c-uhff-link" href="https://support.microsoft.com/contactus/" data-mscc-ic="false" data-m='{"cN":"Contact Microsoft_nav","id":"n2c1c1m1r1a2","sN":2,"aN":"c1c1m1r1a2"}'>Contact Microsoft</a>
                </li>
                <li  id="c-uhff-support")>
                    <a class="c-uhff-link" href="https://dotnet.microsoft.com/platform/support" data-mscc-ic="false" data-m='{"cN":"Support_nav","id":"n3c1c1m1r1a2","sN":3,"aN":"c1c1m1r1a2"}'>Support</a>
                </li>
                <li  id="c-uhff-privacy &amp; cookies")>
                    <a class="c-uhff-link" href="https://go.microsoft.com/fwlink/?LinkId=521839" data-mscc-ic="false" data-m='{"cN":"Privacy \u0026 Cookies_nav","id":"n4c1c1m1r1a2","sN":4,"aN":"c1c1m1r1a2"}'>Privacy &amp; Cookies</a>
                </li>
                <li  id="c-uhff-terms of use")>
                    <a class="c-uhff-link" href="https://go.microsoft.com/fwlink/?LinkID=206977" data-mscc-ic="false" data-m='{"cN":"Terms of Use_nav","id":"n5c1c1m1r1a2","sN":5,"aN":"c1c1m1r1a2"}'>Terms of Use</a>
                </li>
                <li  id="c-uhff-trademarks")>
                    <a class="c-uhff-link" href="https://www.microsoft.com/trademarks" data-mscc-ic="false" data-m='{"cN":"Trademarks_nav","id":"n6c1c1m1r1a2","sN":6,"aN":"c1c1m1r1a2"}'>Trademarks</a>
                </li>

                <li>&#169; Microsoft 2020</li>
                
            </ul>
        </nav>
```

There are extra parentheses after `id="someId"` and before the `>`

**Comment by mairaw** [comment] 2020-09-14 18:02
Thanks @Youssef1313. I'll have to investigate this problem since that part of the code is generated by an internal tool.

**Comment by mairaw** [comment] 2020-09-14 23:28
The team is aware of the issue and should deploy a fix tomorrow.

**Comment by mairaw** [comment] 2020-09-17 00:16
Closing since the issue is gone now

![image](https://user-images.githubusercontent.com/12971179/93404899-56700a00-f840-11ea-8f21-82949937d81f.png)

**Closed by mairaw** 2020-09-17 00:16 UTC
