### ISSUE TITLE
Installing .NET on my Mac

### ISSUE THREAD

**Issue by Shraddha0426Swaroop** [dotnet/core#6957] opened 2021-11-22 19:52 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Task: I am trying to determine that Net Core is installed so I can used Visual Studio to code in C#. I am getting an error saying Visual Studio cannot find .NET on my machine. I need help with this task:

I ran the command suggested and received the following message in my terminal:
zsh: command not found: ~$

Although the following commands produced the following responses
shraddhaswaroop@Shraddhas-MacBook-Pro-2 ~ % where dotnet
/usr/local/share/dotnet/dotnet
shraddhaswaroop@Shraddhas-MacBook-Pro-2 ~ % dotnet --version
6.0.100

**Comment by mairaw** [comment] 2021-11-22 20:10
It seems your installation is fine given that `dotnet --version` worked.

You don't need to type ~$, just `dotnet`. Would it be more helpful if we removed those characters?

Also, are you getting any errors on VS Code too?

**Comment by scalablecory** [comment] 2021-11-22 20:16
Are you using VS Code, or VS for Mac?

**Comment by Shraddha0426Swaroop** [comment] 2021-11-22 20:56
> 

I am using VS Code. 
<img width="432" alt="Screen Shot 2021-11-22 at 12 54 41 PM" src="https://user-images.githubusercontent.com/94868080/142934114-81500b3b-c361-4b71-92d4-917c02a67945.png">

**Comment by Shraddha0426Swaroop** [comment] 2021-11-22 21:00
> It seems your installation is fine given that `dotnet --version` worked.
> 
> You don't need to type ~$, just `dotnet`. Would it be more helpful if we removed those characters?
> 
> Also, are you getting any errors on VS Code too?

I am getting errors in VS Code. Can you help me resolve this? This is what I am getting:
<img width="496" alt="Screen Shot 2021-11-22 at 12 59 57 PM" src="https://user-images.githubusercontent.com/94868080/142934567-21839406-ab47-4727-9899-a28fcfa1c75b.png">

**Comment by BeauNouvelle** [comment] 2021-12-05 08:21
There seems to be a few other similar issues here on Github and has popped up recently...

https://github.com/dotnet/core/issues/6953

**Comment by eiriktsarpalis** [comment] 2021-12-06 20:09
Duplicate of https://github.com/dotnet/sdk/issues/22910

**Closed by eiriktsarpalis** 2021-12-06 20:09 UTC
Labels: area-tutorials
