### ISSUE TITLE
[Error] DotNet Core 2.1 The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by HenryDeveloper** [dotnet/core#1692] opened 2018-06-13 20:54 UTC
KeyNotFoundException: The given key was not present in the dictionary.

Hi everyone,

I have a problem when upgrade from netcore 2.0 to 2.1.

I have a webproject (not NetCore) but it use libraries of AspNet Core, so when i try to start the project all good but when the iServiceCollection call the function AddMvc() i am getting the keynotfoundexception and this just happen when i installed of new version of netcore.

More information about the project:
![image](https://user-images.githubusercontent.com/11890226/41377330-fd26ed36-6f18-11e8-912c-ef190a204c08.png)

![image](https://user-images.githubusercontent.com/11890226/41377502-703b32a0-6f19-11e8-8f65-b118f36fd474.png)

Thanks for advance.

**Comment by Petermarcu** [comment] 2018-06-14 16:01
@muratg can you move this to the ASP.NET repo?

**Comment by muratg** [comment] 2018-06-14 16:38
@mkartakmsft can you take a look please?

**Comment by thucnguyen77** [comment] 2018-06-25 06:59
Hi,

I got the same error in my existing API. 

What I did was just to install .NET Core SDK version 2.1.300. 

I have neither upgraded my existing code to .NET, nor made any reference to .NET Core 2.1 libraries.

I am trying to make it work "side-by-side" as advertised, using the global.json file, not still not succeed yet.

Has anyone been able to get over it?

**Comment by muratg** [comment] 2018-06-25 16:28
@thucnguyen77 @HenryDeveloper Could you guys share some code that reproduces this issue please?  A simple app with the problem on a GitHub repo would be ideal!  Thanks.

**Comment by atpyatt** [comment] 2018-07-27 08:57
The solution here: https://github.com/aspnet/Home/issues/3132#issuecomment-388082725 fixed this problem for me.

**Comment by karelz** [comment] 2018-10-02 23:27
Seems to be resolved, closing. Please let me know if you are still facing the problem.

**Closed by karelz** 2018-10-02 23:27 UTC
