### ISSUE TITLE
Can't Install Dot Net Core on Ubuntu 19.04

### ISSUE THREAD

**Issue by antfusa** [dotnet/core#2612] opened 2019-04-19 22:35 UTC
![Screenshot from 2019-04-19 18-34-06](https://user-images.githubusercontent.com/38739462/56446645-d43d8800-62d1-11e9-9500-3b8a165f9632.png)
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-10/sdk-current
Operating System: Linux Ubuntu 18.10 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by antfusa** [comment] 2019-04-19 22:35
I know this says 18.04 in the terminal but its the closet thing listed

**Comment by karelz** [comment] 2019-04-19 22:41
Duplicate of #2526

**Closed by karelz** 2019-04-19 22:41 UTC
