### ISSUE TITLE
S390x Support

### ISSUE THREAD

**Issue by AdrianKoshka** [dotnet/core#4866] opened 2020-06-24 19:11 UTC
# S390x Architecture support 

# General

I believe this would be the first step in order to eventually have PowerShell available for Linux systems on mainframes (otherwise known as S390x). While I realize there may not be demand for .NET Core on the mainframe, I personally would appreciate having my shell of choice on Linux on mainframes.

**Comment by omajid** [comment] 2020-06-24 19:13
Here's a related issue: https://github.com/dotnet/runtime/issues/34195

**Comment by scalablecory** [comment] 2020-06-24 19:43
Duplicate of https://github.com/dotnet/runtime/issues/34195

**Closed by scalablecory** 2020-06-24 19:43 UTC
