### ISSUE TITLE
Ubuntu 19.04?

### ISSUE THREAD

**Issue by AnharMiah** [dotnet/core#2689] opened 2019-05-07 11:58 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-current
Operating System: Ubuntu 19.04 - x64

It doesn't appear that `Ubuntu 19.04` is listed yet, I don't want to use any wonky workarounds, what is the estimated date when 19.04 will be available?

**Comment by dagood** [comment] 2019-05-07 14:51
I don't have an estimate for you, but #2526 has alternatives and will be up to date as we get more info. (If installing from a tarball isn't too wonky, that's an option. It's a valid/supported way to install at least.)

**Comment by dagood** [comment] 2019-05-07 14:51
Duplicate of #2526

**Closed by dagood** 2019-05-07 14:51 UTC
