### ISSUE TITLE
Linux-CentOS7  NETCORE3.0

### ISSUE THREAD

**Issue by AFunnyKitty** [dotnet/core#3858] opened 2019-11-20 11:12 UTC
https://packages.microsoft.com/rhel/7/prod/netstandard-targeting-pack-2.1.0-x64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=packages-microsoft-com-prod clean metadata=- ]  45 kB/s | 2.1 MB  00:00:00 ETA 
Trying other mirror.

Error downloading packages:
  netstandard-targeting-pack-2.1-2.1.0-1.x86_64: [Errno 256] No more mirrors to try.

**Comment by craigjbass** [comment] 2019-11-20 16:27
Dupe of #3853

**Closed** 2019-11-20 16:28 UTC
