### ISSUE TITLE
Trouble installing .NET SDK 2.2 App Building for Raspberry PI 3+

### ISSUE THREAD

**Issue by jorgenfhlarsen** [dotnet/core#2690] opened 2019-05-07 13:57 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current
Operating System: Linux Debian 9 - x64

The production list here:
https://packages.microsoft.com/config/debian/9/prod.list
point to an invalid directory.

Adjusting to the - assumed new - directory here: /debian/9/prod/dists/stretch/main/
Still gives trouble.

As a missing Issuing licence is missing the instalation says

**Comment by jorgenfhlarsen** [comment] 2019-05-07 13:59
Above shall be ARM 64 processor

**Comment by dagood** [comment] 2019-05-07 14:57
The exact errors you're getting are a bit unusual, but in general, you can't use the x64 instructions to install on an ARM/ARM64 architecture like Raspberry Pi. For now, you need to install from the tarball.

Just to make sure, I tried the install instructions on a fresh (x64) `debian:9` Docker container and they seem to be working fine right now.

**Comment by dagood** [comment] 2019-05-07 14:58
Duplicate of #2422

**Closed by dagood** 2019-05-07 14:58 UTC
