### ISSUE TITLE
Unable to dotnet build when %20 in folder name

### ISSUE THREAD

**Issue by jschwellnus92** [dotnet/core#4468] opened 2020-03-27 02:01 UTC
Spent about 2 hours trying to figure out why I couldn't build a repo after I cloned it, it turned out dotnet core doesn't like it when there's "%20" in a folder name.

With "%20" in folder name:
![ConEmu64_w4WkKYSCZF](https://user-images.githubusercontent.com/39755231/77713580-ae585180-7011-11ea-90e5-fc2cf93c989d.jpg)

Without "%20" in folder name:
![ConEmu64_bfAww2GH2X](https://user-images.githubusercontent.com/39755231/77713577-ac8e8e00-7011-11ea-9b64-bfc19e889fe0.jpg)

**Comment by scalablecory** [comment] 2020-03-27 15:04
@wli3 @dsplaisted it looks like we're url-decoding paths? Can you help route this?

**Comment by dsplaisted** [comment] 2020-03-30 03:53
@rainersigwald Is this an MSBuild issue (can't build with `%20` in the path to a project?

**Comment by rainersigwald** [comment] 2020-03-30 14:08
Yes: microsoft/msbuild#2178. Unlikely to be fixable, unfortunately.

**Comment by scalablecory** [comment] 2021-11-23 20:37
Closing as duplicate of https://github.com/dotnet/msbuild/issues/2178

**Closed by scalablecory** 2021-11-23 20:37 UTC
