### ISSUE TITLE
how to install .net in ubuntu 19.04

### ISSUE THREAD

**Issue by vijayakrishnans** [dotnet/core#2699] opened 2019-05-09 15:29 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 18.10 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by dagood** [comment] 2019-05-09 17:26
Duplicate of #2526

**Closed by dagood** 2019-05-09 17:26 UTC
