### ISSUE TITLE
Creating duplicate files on selecting opting "Add MVC Dependencies"?

### ISSUE THREAD

**Issue by nithinbandaru1** [dotnet/core#514] opened 2017-02-22 08:23 UTC
Hi,

When I am trying to create new controller for first time it gives me option to add mvc dependencies with two options as shown in image below.

![full dependencies](https://cloud.githubusercontent.com/assets/25755972/23202805/ce27add4-f905-11e6-8394-4e64745c37e0.PNG)

**_Now when I select full dependencies option it is adding duplicate files like:_**
1. ViewImport.cshtml though there is ViewImports.cshtml
2. Layout.cshtml though there is _Layout.cshtml

**_I think It should add those files only if the files are not present._**

**NOTE:** This option doesn't popup when I create using Add -->New item-->Controller. It only happens when I do Add-->Controller(shortcut) .

Looks like a bug for me. Is it?

**Comment by Petermarcu** [comment] 2017-03-05 04:01
@DamianEdwards

**Comment by richlander** [comment] 2017-03-10 06:45
@glennc @danroth27

**Comment by danroth27** [comment] 2017-03-10 16:56
Yeah, this dialog is super confusing when you already have MVC included in a project. 

@barrytang @sayedihashimi Please take a look

**Comment by barrytang** [comment] 2017-03-10 20:43
@prafullbhosale?

cc @mlorbetske @balachir

**Comment by sayedihashimi** [comment] 2017-03-14 15:58
@prafullbhosale let's discuss later today when you get in the office.

**Comment by olivier-voutat** [comment] 2017-03-16 09:26
And why entity framework is in the dependencies? I have a very special scenario where I just cannot use EntityFramework...

**Comment by olivier-voutat** [comment] 2017-03-16 09:31
And in the scaffolding file it is written:

1. Add Scaffolding CLI tool to the project:
    <ItemGroup>
        <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />
    </ItemGroup>

But when I try to do it, it says that is not supported.

**Comment by olivier-voutat** [comment] 2017-03-16 10:10
My bad. Now I understood. Add manually to project file... :-P 

But when I try to add manually "Microsoft.VisualStudio.Web.CodeGeneration.Design" I get this error.

Restoring packages for C:\Development\CustomerCenter\Assura.CustomerCenter.WebApp\Assura.CustomerCenter.WebApp.csproj...
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETCoreApp,Version=v1.1.
Package restore failed. Rolling back package changes for 'Assura.CustomerCenter.WebApp'.
Time Elapsed: 00:00:00.8155988
========== Finished ==========

But the "Add MVC Dependencies" is able to install it.

**Comment by prafullbhosale** [comment] 2017-03-16 16:51
Moving this to scaffolding repo: https://github.com/aspnet/scaffolding/issues/243

**Closed by prafullbhosale** 2017-03-16 16:51 UTC

**Comment by rocknet** [comment] 2017-04-21 16:08
> Moving this to scaffolding repo: aspnet/Scaffolding#243

This was moved to a previously closed issue?

**Comment by prafullbhosale** [comment] 2017-04-24 16:18
Ah, it was a typo. It was moved to aspnet/scaffolding#423 and not 243.
aspnet/scaffolding#423 was closed as dupe of aspnet/scaffolding#411
