### ISSUE TITLE
.Net core ubuntu service stopped when any exception come

### ISSUE THREAD

**Issue by salahrzzaz** [dotnet/core#2502] opened 2019-03-24 13:11 UTC
.Net core ubuntu service stopped when any exception come

I have website .net core 2.0  the service is crash when any exception come hot to disable this scenario when error come the service didn't crash

**Comment by leecow** [comment] 2019-03-27 21:34
I'm sure we'll need quite a bit more info to be able to help. Also, 2.0 is out of support so you should strongly consider moving to 2.1 (LTS) or 2.2.

@dougbu @Eilon

**Comment by Eilon** [comment] 2019-03-27 21:49
@salahrzzaz if you can share an app on GitHub that reproduces this issue, plus tell us the exact error(s) and logs, we can take a look.

**Comment by salahrzzaz** [comment] 2019-03-29 10:00
ok I will share app code and logs but last error come before service crash timeout exception with mongo database

**Comment by karelz** [comment] 2019-03-30 18:43
@salahrzzaz try to create repro with least external dependencies - if the problem is Mongo database itself (or some library for interop with it), this may not be the right place to report the problem ...

**Comment by Eilon** [comment] 2019-04-08 17:40
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by Eilon** 2019-04-08 17:40 UTC
Labels: area-aspnet, needs more info
