### ISSUE TITLE
Não consigo continuar a instalação após digitar  Program.cs.

### ISSUE THREAD

**Issue by jessicazaparolli** [dotnet/core#6081] opened 2021-03-22 19:59 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment] 2021-03-22 22:28
Duplicate of #6082

**Closed by mairaw** 2021-03-22 22:28 UTC
Labels: duplicate
