### ISSUE TITLE
.net download issue

### ISSUE THREAD

**Issue by michaelbuj** [dotnet/core#6496] opened 2021-07-23 15:10 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I click to download x64 .net and it gives me a 404 page

**Comment by mairaw** [comment] 2021-07-23 17:33
Thanks for reporting the issue @michaelbuj. Is that still happening?

@rbhanda

**Comment by mairaw** [comment] 2021-07-23 18:07
Also, can you let us know where are you located? We're trying to pin down if this is specific to certain regions.

**Comment by michaelbuj** [comment] 2021-07-23 19:52
i live in north carolina usa.
i got it to work an hour ago but i just checked and it does the same thing, clicking download button takes me to a "404-not found" page.

https://download.visualstudio.microsoft.com/download/pr/474a078c-f415-4bae-8571-2fe8ea37ed51/a8ac1fe825f63411c375633bd98205c4/dotnet-sdk-5.0.302-win-x64.exe

that's the url of the 404

**Comment by mairaw** [comment] 2021-07-23 19:54
Thank you. And I apologize for the inconvenience.

**Comment by Nisden** [comment] 2021-07-26 07:34
We are seeing the same issue while downloading the latest .NET Core SDK on Azure DevOps using [Use .NET Core](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops)

```
2021-07-26T07:28:31.4366405Z ##[section]Starting: Use .NET Core sdk 5.0.x
2021-07-26T07:28:31.4373051Z ==============================================================================
2021-07-26T07:28:31.4373347Z Task         : Use .NET Core
2021-07-26T07:28:31.4373823Z Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
2021-07-26T07:28:31.4374289Z Version      : 2.184.0
2021-07-26T07:28:31.4374492Z Author       : Microsoft Corporation
2021-07-26T07:28:31.4374712Z Help         : https://aka.ms/AA4xgy0
2021-07-26T07:28:31.4374981Z ==============================================================================
2021-07-26T07:28:31.7633479Z Tool to install: .NET Core sdk version 5.0.x.
2021-07-26T07:28:33.9283059Z Found version 5.0.302 in channel 5.0 for user specified version spec: 5.0.x
2021-07-26T07:28:33.9789270Z get-os-distro: Error: Distribution specific OS name and version could not be detected: UName = Linux
2021-07-26T07:28:33.9792379Z Version 5.0.302 was not found in cache.
2021-07-26T07:28:33.9792985Z Getting URL to download .NET Core sdk version: 5.0.302.
2021-07-26T07:28:33.9793587Z Detecting OS platform to find correct download package for the OS.
2021-07-26T07:28:33.9798571Z [command]/home/vsts/work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.184.0/externals/get-os-distro.sh
2021-07-26T07:28:33.9799319Z Primary:linux-x64
2021-07-26T07:28:33.9799831Z Legacy:-x64
2021-07-26T07:28:33.9800384Z Detected platform (Primary): linux-x64
2021-07-26T07:28:33.9800952Z Detected platform (Legacy): -x64
2021-07-26T07:28:33.9815942Z Downloading: https://download.visualstudio.microsoft.com/download/pr/8468e541-a99a-4191-8470-654fa0747a9a/cb32548d2fd3d60ef3fe8fc80cd735ef/dotnet-sdk-5.0.302-linux-x64.tar.gz
2021-07-26T07:28:34.0097543Z ##[error]Failed while installing version: 5.0.302 at path: /opt/hostedtoolcache/dotnet with error: Could not download installation package from this URL: https://download.visualstudio.microsoft.com/download/pr/8468e541-a99a-4191-8470-654fa0747a9a/cb32548d2fd3d60ef3fe8fc80cd735ef/dotnet-sdk-5.0.302-linux-x64.tar.gz Error: Error: Unexpected HTTP response: 404
2021-07-26T07:28:34.0178694Z ##[section]Finishing: Use .NET Core sdk 5.0.x
```

We started observing this issue Friday at 11:53 CEST

**Comment by revanmj** [comment] 2021-07-26 07:52
Interesting thing, downloads works fine in Firefox for me, but fail with 404 in Chrome and Edge.

**Comment by Nisden** [comment] 2021-07-26 08:00
Its an intermittent issue. About a third of our build's fail with this issue.

**Comment by maftieu** [comment] 2021-07-26 10:05
Same here on Azure DevOps pipelines, with 3.1.411 for Linux => https://download.visualstudio.microsoft.com/download/pr/c7afc344-acf0-4a6c-8e53-4455f2bcfc85/321418f6300e475f6c5d52849efa2e2e/dotnet-sdk-3.1.411-linux-x64.tar.gz
Sometimes download succeed; sometimes it fail.

This morning, from my laptop, I was having 404 on 2 browsers ; download OK on 1 other. I think one of the download server behind download.visualstudio.microsoft.com does not have all the files, so no luck if you get to that one,

**Comment by aressler38** [comment] 2021-07-26 18:51
I am having the same problem on Azure DevOps pipelines.

```get-os-distro: Error: Distribution specific OS name and version could not be detected: UName = Linux
Primary:linux-x64
Legacy:-x64
Detected platform (Primary): linux-x64
Detected platform (Legacy): -x64
##[debug]Got download URL for platform with rid: linux-x64
##[debug]
##[debug]Agent.Version=2.189.0
##[debug]Agent.TempDirectory=/agent/_work/_temp
##[debug]testing directory '/agent/_work/_temp'
Downloading: https://download.visualstudio.microsoft.com/download/pr/c7afc344-acf0-4a6c-8e53-4455f2bcfc85/321418f6300e475f6c5d52849efa2e2e/dotnet-sdk-3.1.411-linux-x64.tar.gz
##[debug]destination /agent/_work/_temp/1ab51582-c136-4015-884d-79e2cb1e43eb
##[debug]downloading
##[debug]Failed to download "1ab51582-c136-4015-884d-79e2cb1e43eb" from "https://download.visualstudio.microsoft.com/download/pr/c7afc344-acf0-4a6c-8e53-4455f2bcfc85/321418f6300e475f6c5d52849efa2e2e/dotnet-sdk-3.1.411-linux-x64.tar.gz". Code(404) Message(Not Found)
##[debug]task result: Failed
##[error]Failed while installing version: 3.1.411 at path: /opt/hostedtoolcache/dotnet with error: Could not download installation package from this URL: https://download.visualstudio.microsoft.com/download/pr/c7afc344-acf0-4a6c-8e53-4455f2bcfc85/321418f6300e475f6c5d52849efa2e2e/dotnet-sdk-3.1.411-linux-x64.tar.gz Error: Error: Unexpected HTTP response: 404
##[debug]Processed: ##vso[task.issue type=error;]Failed while installing version: 3.1.411 at path: /opt/hostedtoolcache/dotnet with error: Could not download installation package from this URL: https://download.visualstudio.microsoft.com/download/pr/c7afc344-acf0-4a6c-8e53-4455f2bcfc85/321418f6300e475f6c5d52849efa2e2e/dotnet-sdk-3.1.411-linux-x64.tar.gz Error: Error: Unexpected HTTP response: 404
##[debug]Processed: ##vso[task.complete result=Failed;]Failed while installing version: 3.1.411 at path: /opt/hostedtoolcache/dotnet with error: Could not download installation package from this URL: https://download.visualstudio.microsoft.com/download/pr/c7afc344-acf0-4a6c-8e53-4455f2bcfc85/321418f6300e475f6c5d52849efa2e2e/dotnet-sdk-3.1.411-linux-x64.tar.gz Error: Error: Unexpected HTTP response: 404
get-os-distro: Error: Distribution specific OS name and version could not be detected: UName = Linux
Primary:linux-x64
Legacy:-x64
Detected platform (Primary): linux-x64
Detected platform (Legacy): -x64
##[debug]Got download URL for platform with rid: linux-x64
##[debug]
##[debug]Agent.Version=2.189.0
##[debug]Agent.TempDirectory=/agent/_work/_temp
##[debug]testing directory '/agent/_work/_temp'
Downloading: https://download.visualstudio.microsoft.com/download/pr/c7afc344-acf0-4a6c-8e53-4455f2bcfc85/321418f6300e475f6c5d52849efa2e2e/dotnet-sdk-3.1.411-linux-x64.tar.gz
##[debug]destination /agent/_work/_temp/1ab51582-c136-4015-884d-79e2cb1e43eb
##[debug]downloading
##[debug]Failed to download "1ab51582-c136-4015-884d-79e2cb1e43eb" from "https://download.visualstudio.microsoft.com/download/pr/c7afc344-acf0-4a6c-8e53-4455f2bcfc85/321418f6300e475f6c5d52849efa2e2e/dotnet-sdk-3.1.411-linux-x64.tar.gz". Code(404) Message(Not Found)
##[debug]task result: Failed
##[error]Failed while installing version: 3.1.411 at path: /opt/hostedtoolcache/dotnet with error: Could not download installation package from this URL: https://download.visualstudio.microsoft.com/download/pr/c7afc344-acf0-4a6c-8e53-4455f2bcfc85/321418f6300e475f6c5d52849efa2e2e/dotnet-sdk-3.1.411-linux-x64.tar.gz Error: Error: Unexpected HTTP response: 404
##[debug]Processed: ##vso[task.issue type=error;]Failed while installing version: 3.1.411 at path: /opt/hostedtoolcache/dotnet with error: Could not download installation package from this URL: https://download.visualstudio.microsoft.com/download/pr/c7afc344-acf0-4a6c-8e53-4455f2bcfc85/321418f6300e475f6c5d52849efa2e2e/dotnet-sdk-3.1.411-linux-x64.tar.gz Error: Error: Unexpected HTTP response: 404
##[debug]Processed: ##vso[task.complete result=Failed;]Failed while installing version: 3.1.411 at path: /opt/hostedtoolcache/dotnet with error: Could not download installation package from this URL: https://download.visualstudio.microsoft.com/download/pr/c7afc344-acf0-4a6c-8e53-4455f2bcfc85/321418f6300e475f6c5d52849efa2e2e/dotnet-sdk-3.1.411-linux-x64.tar.gz Error: Error: Unexpected HTTP response: 404
```

If I try to go to the link in my browser, it downloads fine. https://download.visualstudio.microsoft.com/download/pr/c7afc344-acf0-4a6c-8e53-4455f2bcfc85/321418f6300e475f6c5d52849efa2e2e/dotnet-sdk-3.1.411-linux-x64.tar.gz

**Comment by adrianwyatt** [comment] 2021-07-26 20:40
Dupe issue: https://github.com/microsoft/azure-pipelines-tasks/issues/15086

**Comment by kyeondiscord** [comment] 2021-07-26 22:58
Trying to download anything from https://dotnet.microsoft.com/download/dotnet/5.0 gives a 404 error

**Comment by mairaw** [comment] 2021-07-26 23:19
Announcement link: https://github.com/dotnet/announcements/issues/192

**Comment by mairaw** [comment] 2021-07-26 23:53
Folks, let me know if you're still seeing the issue. The team has pushed a fix and I'd like to confirm things are working again for everyone.

**Comment by BamboozeledFox** [comment] 2021-07-27 00:30
@mairaw when manually clicking on a link it works but my DevOps pipeline is still failing with a 404.

```
Starting: Install .Net 5 SDK
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.184.0
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
Tool to install: .NET Core sdk version 5.x.
Found version 5.0.302 in channel 5.0 for user specified version spec: 5.x
Version 5.0.302 was not found in cache.
Getting URL to download .NET Core sdk version: 5.0.302.
Detecting OS platform to find correct download package for the OS.
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.184.0\externals\get-os-platform.ps1'"
Primary:win-x64
Detected platform (Primary): win-x64
Downloading: https://download.visualstudio.microsoft.com/download/pr/2881a25e-f265-43ee-a095-3a05b0466771/45959c837217c768a3b8171edc6607b3/dotnet-sdk-5.0.302-win-x64.zip
##[error]Failed while installing version: 5.0.302 at path: C:\hostedtoolcache\windows/dotnet with error: Could not download installation package from this URL: https://download.visualstudio.microsoft.com/download/pr/2881a25e-f265-43ee-a095-3a05b0466771/45959c837217c768a3b8171edc6607b3/dotnet-sdk-5.0.302-win-x64.zip Error: Error: Unexpected HTTP response: 404
Finishing: Install .Net 5 SDK
```

**Comment by maftieu** [comment] 2021-07-27 06:54
> Folks, let me know if you're still seeing the issue. The team has pushed a fix and I'd like to confirm things are working again for everyone.

I've tested to download multiple times the same file as yesterday, and all downloads were fine.

**Comment by safern** [comment] 2021-07-27 18:18
@mairaw this seems to have been mitigated, should we close this issue?

**Comment by mairaw** [comment] 2021-07-27 19:42
Yes, we can close this now.

**Closed by mairaw** 2021-07-27 19:42 UTC
Labels: area-tutorials

**Comment by m-dastagir** [comment] 2022-12-12 13:04
The issue is back on, the download link is not working.
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.11-windows-hosting-bundle-installer

**Comment by mairaw** [comment] 2022-12-12 22:31
@m-dastagir please open a new issue since the team won't triage old bugs. We'll need more information for us to be able to follow up on that.
