### ISSUE TITLE
Trying to downoad .NET on my computer

### ISSUE THREAD

**Issue by luisa2011** [dotnet/core#2624] opened 2019-04-22 23:32 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by dagood** [comment] 2019-04-24 15:02
I'm guessing this is a duplicate of https://github.com/dotnet/core/issues/2623 filed accidentally. We're looking into the problem there, thanks for reporting it.

**Closed by dagood** 2019-04-24 15:02 UTC

**Comment by karelz** [comment] 2019-04-24 15:25
Duplicate of #2623

**Comment by karelz** [comment] 2019-04-24 15:26
@dagood FYI: See how the text above recognized the duplicate via GH functionality ;) ... it just has to be its own reply ...

**Comment by dagood** [comment] 2019-04-24 15:31
Based on the docs I thought it would detect it from my comment (and I assumed that it wasn't detected because I wasn't a repo admin or something like that). Thanks for the info. 👍
