### ISSUE TITLE
openSUSE 15 Linux package repository is broken - "Signature verification failed on file 'repomd/xml'

### ISSUE THREAD

**Issue by paulcociuba** [dotnet/core#4133] opened 2020-01-15 14:37 UTC
# openSUSE 12 Linux package repository is broken

Signature verification failed for file 'repomd.xml' from repository 'packages-microsoft-com-prod'.

    Note: Signing data enables the recipient to verify that no modifications
    occurred after the data were signed. Accepting data with no, wrong or
    unknown signature can lead to a corrupted system and in extreme cases even
    to a system compromise.

    Note: File 'repomd.xml' is the repositories master index file. It ensures
    the integrity of the whole repo.

    Warning: This file was modified after it has been signed. This may have been
    a malicious change, so it might not be trustworthy anymore! You should not
    continue unless you know it's safe.

Signature verification failed for file 'repomd.xml' from repository 'packages-microsoft-com-prod'.

It would seem that the packages for ASP.net Core Runtime and .Net Core Runtime and SDK were updated on January the 14th, yet the signature of the repository is still dated to January 9th:

https://packages.microsoft.com/sles/12/prod/repodata/
- repomd.xml.asc is still dated to January 9th

The same holds true for SUSE 15 repos as well.
![SUSE-key](https://user-images.githubusercontent.com/32518162/72442419-bf344d80-37ac-11ea-9a1b-2a51e18deba1.png)

**Comment by dagood** [comment] 2020-01-15 16:46
I'm not able to reproduce the issue from a fresh `opensuse/leap:15.1` Docker container, can you please post full logs to make sure all earlier steps went ok, and the time the install was attempted?

---

Renaming 12 => 15 in title because .NET Core doesn't support openSUSE 12. (The 12 feed doesn't look like it actually has any .NET Core packages anyway, seeing https://packages.microsoft.com/opensuse/15/prod/ vs https://packages.microsoft.com/opensuse/12/prod/.)

**Comment by dagood** [comment] 2020-01-15 17:42
Closing: this issue was actually with SUSE 12 and SUSE 15. I opened https://github.com/dotnet/core/issues/4136 for that issue after confirming.

**Closed by dagood** 2020-01-15 17:42 UTC
Labels: area-setup, needs more info
