### ISSUE TITLE
Fedora 30: netstandard-targeting-pack-2.1.0-x64.rpm: Downloading successful, but checksum doesn't match.  No more mirrors to try.

### ISSUE THREAD

**Issue by ShaihutdinovRZ** [dotnet/core#3878] opened 2019-11-21 06:53 UTC
In Fedora 30 (5.3.11-200.fc30.x86_64) I'm try to install latest NET Core 3 (there is updates 19 and 20 Nov 2019 - see https://packages.microsoft.com/fedora/30/prod/) by following commands:
1. sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
2. sudo wget -q -O /etc/yum.repos.d/microsoft-prod.repo https://packages.microsoft.com/config/fedora/30
3. sudo dnf -y install dotnet-sdk-3.0
And I get following errors:
sudo dnf -y install dotnet-sdk-3.0
packages-microsoft-com-prod                     2.1 MB/s | 3.9 MB     00:01
Last metadata expiration check: 0:00:09 ago on Thu Nov 21 06:39:47 2019.
Dependencies resolved.
================================================================================
 Package                   Arch   Version     Repository                   Size
================================================================================
Installing:
 dotnet-sdk-3.0            x86_64 3.0.101-1   packages-microsoft-com-prod  64 M
Installing dependencies:
 compat-openssl10          x86_64 1:1.0.2o-7.fc30
                                              updates                     1.1 M
 libicu                    x86_64 63.2-2.fc30 updates                     9.0 M
 aspnetcore-runtime-3.0    x86_64 3.0.1-1     packages-microsoft-com-prod 7.5 M
 aspnetcore-targeting-pack-3.0
                           x86_64 3.0.1-1     packages-microsoft-com-prod 1.4 M
 dotnet-apphost-pack-3.0   x86_64 3.0.1-1     packages-microsoft-com-prod  66 k
 dotnet-host               x86_64 3.0.1-1     packages-microsoft-com-prod  39 k
 dotnet-hostfxr-3.0        x86_64 3.0.1-1     packages-microsoft-com-prod 147 k
 dotnet-runtime-3.0        x86_64 3.0.1-1     packages-microsoft-com-prod  29 M
 dotnet-runtime-deps-3.0   x86_64 3.0.1-1     packages-microsoft-com-prod 2.8 k
 dotnet-targeting-pack-3.0 x86_64 3.0.1-1     packages-microsoft-com-prod 3.4 M
 netstandard-targeting-pack-2.1
                           x86_64 2.1.0-1     packages-microsoft-com-prod 2.1 M

Transaction Summary
================================================================================
Install  12 Packages

Total download size: 118 M
Installed size: 148 M
Downloading Packages:
(1/12): compat-openssl10-1.0.2o-7.fc30.x86_64.r 1.2 MB/s | 1.1 MB     00:00
(2/12): aspnetcore-targeting-pack-3.0.1.rpm     1.6 MB/s | 1.4 MB     00:00
(3/12): dotnet-apphost-pack-3.0.1-x64.rpm       901 kB/s |  66 kB     00:00
(4/12): dotnet-host-3.0.1-x64.rpm               548 kB/s |  39 kB     00:00
(5/12): dotnet-hostfxr-3.0.1-x64.rpm            1.8 MB/s | 147 kB     00:00
(6/12): aspnetcore-runtime-3.0.1-rh.rhel.7-x64. 3.0 MB/s | 7.5 MB     00:02
(7/12): dotnet-runtime-deps-3.0.1-fedora.27-x64  43 kB/s | 2.8 kB     00:00
(8/12): libicu-63.2-2.fc30.x86_64.rpm           2.9 MB/s | 9.0 MB     00:03
(9/12): dotnet-targeting-pack-3.0.1-x64.rpm     2.4 MB/s | 3.4 MB     00:01
[MIRROR] netstandard-targeting-pack-2.1.0-x64.rpm: Downloading successful, but checksum doesn't match. Calculated: 45e199caf1151a750d11d9c5c7669d6e23d8dbb33da54d1d90bde55745996480(sha256)  Expected: fa194a8c12913dcec85c8d24bfc91686a7b93128b4c05346df16e2c641e2ba41(sha256)
[MIRROR] netstandard-targeting-pack-2.1.0-x64.rpm: Downloading successful, but checksum doesn't match. Calculated: 45e199caf1151a750d11d9c5c7669d6e23d8dbb33da54d1d90bde55745996480(sha256)  Expected: fa194a8c12913dcec85c8d24bfc91686a7b93128b4c05346df16e2c641e2ba41(sha256)
[MIRROR] netstandard-targeting-pack-2.1.0-x64.rpm: Downloading successful, but checksum doesn't match. Calculated: 45e199caf1151a750d11d9c5c7669d6e23d8dbb33da54d1d90bde55745996480(sha256)  Expected: fa194a8c12913dcec85c8d24bfc91686a7b93128b4c05346df16e2c641e2ba41(sha256)
(10/12): dotnet-runtime-3.0.1-x64.rpm           1.9 MB/s |  29 MB     00:14
[MIRROR] netstandard-targeting-pack-2.1.0-x64.rpm: Downloading successful, but checksum doesn't match. Calculated: 45e199caf1151a750d11d9c5c7669d6e23d8dbb33da54d1d90bde55745996480(sha256)  Expected: fa194a8c12913dcec85c8d24bfc91686a7b93128b4c05346df16e2c641e2ba41(sha256)
[FAILED] netstandard-targeting-pack-2.1.0-x64.rpm: No more mirrors to try - All mirrors were already tried without success

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Cannot download netstandard-targeting-pack-2.1.0-x64.rpm: All mirrors were tried

**Comment by dagood** [comment] 2019-11-21 07:07
Duplicate of https://github.com/dotnet/core/issues/3853

**Closed by dagood** 2019-11-21 07:07 UTC
