### ISSUE TITLE
.NET Core 2.1 - Breaking Change

### ISSUE THREAD

**Issue by jshunia** [dotnet/core#1623] opened 2018-05-31 05:20 UTC
# .NET Core 2.1 - Breaking Change

After upgrading one of my projects from .NET Core 2.0 to .NET Core 2.1, it would no longer compile.  The issue seems to be related to the CancellationTokenRegistration type or perhaps some change/bug fix related to uninitialized local variables.

# General
I am running Visual Studio 2017 Community v15.5.2 on Windows 10.  The error code reported to me by VS was: "(Code: CS0165) Use of unassigned local variable 'tokenRegistration'"

Here is the code which triggered the error:

```
Task<TResult> task = new Task<TResult>(() =>
{
	CancellationTokenRegistration tokenRegistration;

	try
	{
		// Boring task logic.
		... 
	}
	finally
	{
		if (tokenRegistration != default(CancellationTokenRegistration)) // Error here!
		{
			tokenRegistration.Dispose();
		}
	}
},
cancellationToken.Value,
TaskCreationOptions.LongRunning);
```
The fix was to change to initialize the 'tokenRegistration' variable to 'default(CancellationTokenRegistration)'.  Looking at the code now, I'm wondering how it ever compiled.

**Comment by VladislavAntonyuk** [comment] 2018-05-31 08:37
Update your vs to version 15.7 at least

**Comment by svick** [comment] 2018-05-31 12:02
I believe this is caused by https://github.com/dotnet/corefx/issues/6185.

In short, previously, reference assemblies didn't contain private fields for `struct`s such as `CancellationTokenRegistration`. This meant that C# didn't check definite assignment for those types, which allowed code like your example. This bug was fixed in .Net Core 2.1, which means that code that compiled and worked fine before, but was in some sense incorrect, because it didn't initialize types that should be initialized, does not compile anymore.

**Comment by jshunia** [comment] 2018-05-31 14:00
@VladislavAntonyuk I will try upgrading to the latest version of VS 2017 and get back to you.

@svick  Very interesting, thanks for the info!  That seems to line up with what I suspected.

**Closed** 2018-05-31 23:38 UTC

**Comment by erwan-joly** [comment] 2018-06-06 03:51
![screen shot 2018-06-06 at 3 21 59 pm](https://user-images.githubusercontent.com/35202750/41016077-5ff90bce-69a1-11e8-8612-c4e1f55464bb.png)
interesting thing was that different struct had a different behavior before i got a breaking change too on this but really easy to fix just add a default value

**Comment by VladislavAntonyuk** [comment] 2018-06-06 07:51
It had made to avoid possible null reference exception

**Comment by martinsuchan** [comment] 2018-11-20 09:17
Same breaking change is happening in UWP apps after updating to Microsoft.NETCore.UniversalWindowsPlatform NuGet 6.2.0+ 
![48697530-1eb4be80-ebe5-11e8-8e3a-d1bca379fc4d](https://user-images.githubusercontent.com/3041397/48763384-7a4a7f00-ecad-11e8-8af4-8b3427b57047.png)

**Comment by karelz** [comment] 2018-11-26 05:04
@martinsuchan that should be separate bug. Is it a compiler error or "just a warning"?
@HollyAM @MattWhilden where do you track UWP bugs?

**Comment by martinsuchan** [comment] 2018-11-26 09:10
It's a change of struct signature. Added private fields now prohibit usage of just `Size size;` for initialization.  
It's discussed in more detail here: https://github.com/Microsoft/dotnet/issues/927

**Comment by karelz** [comment] 2018-11-26 18:01
Ah ok, so that one is primary and we do not need another UWP tracking bug, is that correct?
