### ISSUE TITLE
dont net issue

### ISSUE THREAD

**Issue by farazraj** [dotnet/core#2711] opened 2019-05-12 10:26 UTC
Problem encountered on https://dotnet.microsoft.com/learn/web/aspnet-hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![image](https://user-images.githubusercontent.com/49255964/57580974-b246b800-74c1-11e9-9ec7-ea69c4829f52.png)

**Comment by AdvancedPowerArmor** [comment] 2019-05-12 11:52
I think you might not have installed required Windows' updates. You can also try to download Visual C++ Redistributable for Visual Studio 2015 update from here: https://www.microsoft.com/en-us/download/details.aspx?id=48145

I think it is easy to fix. Maybe try this tutorial: https://www.drivereasy.com/knowledge/api-ms-win-crt-runtime-l1-1-0-dll-missing-error-solved/

**Comment by dagood** [comment] 2019-05-12 14:24
Yep, here's the Microsoft page listing the required updates: https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x#net-core-dependencies.

**Comment by dagood** [comment] 2019-05-12 14:24
Duplicate of #2541

**Closed by dagood** 2019-05-12 14:24 UTC
