### ISSUE TITLE
Windows desktop application in .net core 3.0 preview version is not running with .net core 3.0 runtime version

### ISSUE THREAD

**Issue by jigarBiskitwala** [dotnet/core#2780] opened 2019-05-23 13:46 UTC
I have a windows desktop application in .net core 3.0 preview, when I publish it and run on different machine, it is not working with .net core 3.0 preview run time version.
As per my knowledge, sdk is for development. And to run on other machine it only need .net core run time version.

In my case on other machine, it is working only with  .net core 3.0 preview sdk but not with .net core 3.0 preview run time.

The same issue with descriptive at https://stackoverflow.com/questions/56235099/windows-formdesktop-application-in-net-core-3-0-preview-for-version-is-not-ru

Can you please help/suggest me with this?

Thank you

**Comment by karelz** [comment] 2019-05-23 16:00
Are you able to reproduce it with HelloWold app? Is it UI app? WinForms or WPF?

**Comment by dagood** [comment] 2019-05-25 05:25
> As per my knowledge, sdk is for development. And to run on other machine it only need .net core run time version.

Overall, this is true, and it's called "[framework-dependent deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/#framework-dependent-deployments-fdd)" (FDD). The problem is there is no official standalone installer for the WindowsDesktop runtime available yet--it's only included as part of the SDK. Getting proper installers for WindowsDesktop runtimes is tracked by https://github.com/dotnet/core-setup/issues/6384.

(Note that the _.NET Core_ runtime is different from the _WindowsDesktop_ runtime. Only the latter is able to run WinForms and WPF apps. This is similar to how you need the _ASP.NET_ runtime to run ASP.NET FDD apps.)

There's some more info about this issue at https://github.com/dotnet/core-setup/issues/6381.

A few ways forward until this is fixed:

1. Install the full SDK on your target machine for now. Rest assured that in the future there will be a standalone WindowsDesktop runtime installer for this scenario you can use instead.
1. Publish your app as self-contained, so the user doesn't need to install any runtime. (https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli#self-contained-deployment)
1. Use an MSI I linked in https://github.com/dotnet/core-setup/issues/6381#issuecomment-491325222 to install the WindowsDesktop runtime. (This is not a great experience, and points to the very latest daily build which may not work.)

Closing because this is a known issue, but let me know if those options don't make sense.

**Closed by dagood** 2019-05-25 05:25 UTC
