### ISSUE TITLE
.NET Core Release Data (releases.json) Redesign and Deprecation 

### ISSUE THREAD

**Issue by leecow** [dotnet/core#1986] opened 2018-10-05 22:54 UTC
# .NET Core Release Data (releases.json) Redesign and Deprecation

The releases.json and releases.csv files began life as helper tools for some of our internal release work, some experimentation and to possibly be useful to the community. It has been great to learn the files are indeed in use and many folks depend on them as a trigger for a number of activities.

* [release-notes/releases.json](https://github.com/dotnet/core/blob/master/release-notes/releases.json)
* [release-notes/releases.csv](https://github.com/dotnet/core/blob/master/release-notes/releases.csv)

Between the usages which we have become aware and in considering further activities that could be enabled to reason about things such as checking .NET Core version availability and support status, it became clear the current format is inadequate.

An updated format has been designed and tested which will replace the current files. The timeline below describes the path to obsoleting the current files.

## The Plan

| Date | Action |
| :--- | :----- |
| Oct 2018 | Notify the community of the coming change |
| Oct 2018 | Release the new json format into dotnet/core |
| Oct 2018 - Feb 2019 | Maintain the old json and csv files |
| Feb 2019 | Reminder announcement that old format file is coming soon |
| Mar 2019 | Old json and csv files are obsoleted and removed from dotnet/core |

## Breaking change

If you are currently utilizing the old version json or csv, you will need to update the relevant code to work with the new format. If you are just getting started with consuming this data, use the new version.

## The Format

Below are fragments of the files from our most recent .NET Core release.

### release-index.json

This file consists of a top level array with data on the latest release versions and a property for locating the more detailed channel-specific releases.json. This file is found in [dotnet/core/release-notes](https://github.com/dotnet/core/tree/new-json/release-notes/)

[releases-index.json](https://github.com/dotnet/core/blob/new-json/release-notes/releases-index.json)

```
{
    "releases-index": [
        {
            "channel-version": "2.1",
            "latest-release": "2.1.5",
            "latest-release-date":"2018-10-02",
            "product": ".NET Core",
            "support-phase": "lts",
            "eol-date": "",
            "releases.json": "https://github.com/dotnet/core/blob/master/release-notes/2.1/releases.json",
        },
        ...
}
```

### releases.json

This file provides detailed data for each release. A copy of this file will be found in each versioned directories under [dotnet/core/release-notes](https://github.com/dotnet/core/release-notes). For example [dotnet/core/release-notes/2.1](https://github.com/dotnet/core/tree/new-json/release-notes/2.1)

[releases.json](https://github.com/dotnet/core/tree/new-json/release-notes/2.1/releases.json)

```
{
    "channel-version": "2.1",
    "latest-release": "2.1.5",
    "latest-release-date":"2018-10-12",
    "support-phase": "lts",
    "eol-date": "",
    "lifecycle-policy": "https://www.microsoft.com/net/support/policy",
    "releases":
    [
        {
            "release-date":  "2018-10-02",
            "release-version":  "2.1.5",
            "security":  false,
            "release-notes":  "https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.5/2.1.5.md",
            "runtime":  
            {
                "version":  "2.1.5",
                "version-display":  "2.1.5",
                "vs-version":  "15.8.6",
                "files":  
                [
                    {
                        "name": "dotnet-runtime-linux-arm.tar.gz",
                        "url": "https://download.visualstudio.microsoft.com/download/pr/4d555219-1f04-47c6-90e5-8b3ff8989b9c/0798763e6e4b98a62846116f997d046e/dotnet-runtime-2.1.5-linux-arm.tar.gz",
                        "hash": "89a77a07065ea24e7198c77a233b9ce5c6cf51b1deb2ef55c88f0adbb2ecd9db1ba4e7d55eec2ef7139c47f91346fed360161a5bb6e3a7ccfc4559bcde286364"
                    },
                    ...
                ]
            }
            "sdk":  
            {
                "version":  "2.1.403",
                "version-display":  "2.1.403",
                "vs-version":  "15.8.6",
                "csharp-language":  "7.3",
                "fsharp-language":  "4.5",
                "files":  
                [...]
            }
        }
    ]
}
```

**Comment by dasMulli** [comment] 2018-10-05 23:02
How does the new format account for SDK releases independent of runtime releases?
e.g. I cannot find the 2.1.400 SDK in the new format which is present in the old format, but tools may need to find these version - independent of the runtime version.

Scenario: VSTS (or other CI tool) download tasks that only has the desired SDK version as input.
How do I resolve "2.1.4", "2.1.400", "2.2.100-preview-foo" from the new format json files? (index + release specific json files)

**Comment by arthurrump** [comment] 2018-10-17 15:20
> How does the new format account for SDK releases independent of runtime releases?

It looks like the `runtime` field can just be left out, for example 2.1.201 in the 2.0 channel only has an `sdk` field. Still weird that 2.1.400 is not in there...

Some other weird things that I noticed:
- In the releases.json for 1.1 the version of the SDK is sometimes (but not always) referred to with `version-sdk` instead of the `version` field that is used in all other files.
- There are two releases without a `release-version` field, namely 2.1.0-preview2+sdk2.1.300-preview2 and 1.0.1+sdk1.0.0-preview2-003131. Is that on purpose? If so, why?
- Release 1.1.6 is listed to be released on 2017-11-14, which is the same day as 1.1.5. According to the [release notes](https://github.com/dotnet/core/blob/master/release-notes/1.1/1.1.6.md) it was released on 2018-01-09.

**Comment by arthurrump** [comment] 2018-10-18 09:08
Also, shouldn't 2.2 be listed in the index as preview? And previews 1 and 2 are missing in the 2.2 releases.json.

**Comment by matkoch** [comment] 2018-11-07 22:51
@leecow ping ^^^^

**Comment by leecow** [comment] 2018-11-07 23:09
Sorry @matkoch was on a bit of vacation and missed this. Yes, this is 2 trips 1) the latest channel-version from releases-index.json which would point you to the correct releases.json for picking up the latest release.

**Comment by dasMulli** [comment] 2018-11-08 07:04
@leecow could you also have a look at my comment earlier? esp the question: given an SDK version number (e.g. 2.1.400), how do I get to the download URLs?

**Comment by leecow** [comment] 2018-11-08 16:33
@dasMulli - got it. Put that on my mental todo list yesterday while doing something completely different :-) 

A possible solution is to include the latest SDK version in release-index.json. Since 'latest-release' == latest runtime version, an sdk field would communicate the latest SDK which carries that runtime.

How does that strike you? 

On a slightly different topic, I think a security release note needs to be included in the index. A goal is to provide the ability to determine whether an update is both available and interesting on the first trip to the data.

**Comment by dasMulli** [comment] 2018-11-08 18:58
@leecow the problem is that any mapping between an SDK version and download URLs needs history of the SDKs which is being deprecated as part of this issue.

Having only the "latest for runtime" doesn't help.

The current azure pipeline tasks for the .NET Core tools installer tasks rely on releases.json to give download URLs for **any valid SDK version number** that has been released in the past. Tasks for other CI/CD systems need this as well.

The user story would be:
In order to create reproducible build definitions, as a build Author, I want to specify the exact SDK version number used during build which is to be downloaded and used during the build process.

**Comment by leecow** [comment] 2018-11-08 21:30
Yep, I understand. The index is just a lightweight entry for discovery. The channel releases.json files would have all of the history and details (including download url) to cover what you describe.

**Comment by dasMulli** [comment] 2018-11-08 23:44
@leecow I don't see 2.1.400 in there.

2.1.2 runtime was released with 2.1.302
Then a 2.1.400 was released, again for the 2.1.2 runtime
Then a 2.1.3 runtime was released along a 2.1.401 SDK

We'd need download URLs for all 3 of these SDKs.
Currently, only 2 (2.1.302, 2.1.401) are provided.

**Comment by leecow** [comment] 2018-11-12 03:08
I'm thinking through the case where we have an updated toolset which contains an existing runtime. 

2.1.500 will be shipping with an updated runtime (2.1.6) so that will be a 'normal' case.

**Comment by karelz** [comment] 2019-03-30 18:38
Closing as it seems to be in place by now.

**Closed by karelz** 2019-03-30 18:38 UTC
Labels: Announcement
