### ISSUE TITLE
.NET Core 2.2.0 Preview 3

### ISSUE THREAD

**Issue by vivmishra** [dotnet/core#2004] opened 2018-10-17 17:06 UTC
# .NET Core 2.2.0 Preview 3

[Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.2/preview/2.2.0-preview3.md)
[Download](https://github.com/dotnet/core/blob/master/release-notes/2.2/preview/2.2.0-preview3-download.md)
                 

Please report any issues you find with 2.2.0 Preview 3, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/aspnet/Home) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/corefx](https://github.com/dotnet/corefx/issues) - for API issues and questions
* [dotnet/coreclr](https://github.com/dotnet/coreclr/issues) - for runtime issues
* [dotnet/core-setup](https://github.com/dotnet/core-setup/issues) - for installer issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

**Comment by peppy** [comment] 2018-10-18 11:53
Agree that it is very hard to locate the changes in preview releases. At very least, links to commit logs (or closed PR/issue logs) for the range of included changes would be very helpful!

**Comment by ltouro** [comment] 2018-10-18 12:49
@keithn @peppy maybe this helps: https://github.com/search?q=org%3Aaspnet+is%3Aissue+is%3Aclosed+milestone%3A2.2.0-preview3. _all issues closed in the 2.2.0 Preview 3 milestone_

Saw here: https://github.com/aspnet/Announcements/issues/323

**Comment by tommcdon** [comment] 2018-10-18 18:08
> what is the release strategy for OOB packages such as System.Diagnostics.DiagnosticSource? When can we expect to have them on nuget.org?

Adding @brianrob and @adamsitnik to comment on System.Diagnostics.DiagnosticSource

**Comment by brianrob** [comment] 2018-10-18 18:15
To my knowledge, all of the NuGet packages that are produced by the CoreFx build are published to nuget.org when we release.  It doesn't look like any of the NuGet packages have been updated on nuget.org yet for any 2.2 preview releases.

@vancem, does DiagnosticSource follow this plan, or is it published to nuget.org on-demand?

**Comment by memark** [comment] 2018-10-26 08:55
I've run into an issue. Have the CORS values returned by preflight requests been changed?

>curl 'https://server/api' -X OPTIONS -H 'Access-Control-Request-Headers: content-type' -H 'Access-Control-Request-Method: PUT' -H 'Origin: xxx'

Preview 2 gives
>Access-Control-Allow-Headers: content-type
>Access-Control-Allow-Methods: PUT

Preview 3 gives
>Access-Control-Allow-Headers: *
>Access-Control-Allow-Methods: *

Given that * is not very well supported, parts of my application is now broken.

**Comment by muratg** [comment] 2018-10-26 15:49
@javiercn could you take a look at the CORS behavior change above?

**Comment by javiercn** [comment] 2018-10-26 16:08
@muratg Yes. We fixed this to make it spec compliant a few days ago, but seems that clients don’t support * very well. 

@pranavkm we should just reflect the request headers here when all are allowed.

**Comment by pranavkm** [comment] 2018-10-26 16:48
@memark what browser \ OS are you using?

**Comment by memark** [comment] 2018-10-29 13:29
@pranavkm We have seen the problem described above on

Microsoft Edge
Version 42.17134.1.0
OS: Windows 10 Pro, version 1803, build 17134.345

Internet Explorer 11
Version 11.345.17.134.0
OS: Windows 10 Pro, version 1803, build 17134.345

Google Chrome
Version 69.0.3497.100 (Official Build) (64-bit)
OS: MacOS Mojave (10.14)

Safari
Version 12.0 (14606.1.36.1.9)
OS: MacOS Mojave (10.14)

Firefox
Version 62.0.3 (64-bit)
OS: MacOS Mojave (10.14)

**Comment by foureighteen** [comment] 2018-11-07 07:39
I ran into an issue caused by misconfiguration. According to this documentation https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?tabs=aspnetcore2x&view=aspnetcore-2.2, _Cookie.Expiration_ is obsolete. Yet I got no warnings or errors when I used _Cookie.Expiration_ instead of _ExpireTimeSpan_ in ASP.NET Core 2.2 Preview 3.

**Comment by muratg** [comment] 2018-11-07 16:47
@javiercn @pranavkm could one of you guy create a bug under aspnet/cors for this issue?

**Comment by javiercn** [comment] 2018-11-07 17:02
@muratg I believe we already fixed this

**Comment by ionepaul** [comment] 2018-11-27 15:06
hi, i know that [#1144 ](https://github.com/aspnet/KestrelHttpServer/issues/1144) issue regarding the kestrel server not allowing invalid characters in headers was fixed in .NET Core 2.2.0-preview2 and it was working fine, but it seems that in .NET Core 2.2.0-preview3 the invalid characters are not accepted anymore and kestrel throws 400 like before. 

Does anyone encountered this issue or know anything about it? Do I need to adjust some options or anything ?

Thank you.

**Comment by karelz** [comment] 2018-11-27 18:09
@ionepaul it would be best to take the discussion on the bug you linked - @muratg @Eilon @Tratcher can you please take a look?

**Comment by ionepaul** [comment] 2018-11-29 16:35
hi @Tratcher, just opened [#4318](https://github.com/aspnet/AspNetCore/issues/4318) with all the details, it seems that is happening both for preview2 and preview3 only when running behind IIS.

**Comment by karelz** [comment] 2018-12-05 01:52
Closing in favor of #2098 (RTW release)

**Closed by karelz** 2018-12-05 01:52 UTC
Labels: Announcement
