### ISSUE TITLE
Blazor チュートリアル - 最初の Blazor アプリをビルドする de

### ISSUE THREAD

**Issue by yukkuri55** [dotnet/core#8745] opened 2023-09-07 11:21 UTC
Problem encountered on https://dotnet.microsoft.com/ja-jp/learn/aspnet/blazor-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by buyaa-n** [comment] 2023-09-08 02:05
@yukkuri55 the issue is not actionable, closing, if you still have an issue please provide details about the problem you're experiencing

**Closed by buyaa-n** 2023-09-08 02:05 UTC
