### ISSUE TITLE
TypeLoadException when storing struct with ArraySegment of own type

### ISSUE THREAD

**Issue by SaculRennorb** [dotnet/core#6026] opened 2021-03-07 23:21 UTC
### Description

Not necessarily instantiating, but **storing** a struct `A` with an `ArraySegment<A>` inside causes a TypeLoadException.

This seems to happen when placing a struct with a generic array of type `A` inside a struct of type `A`. This shouldn't be a problem tho, since the array is a 'pointer' and therefore takes up constant space inside the struct regardless of type.

Here is a mostly minimal Sample:
```csharp
using System;

namespace CompilerBug2Tests {
  class Program {
    struct A {
      public ArraySegment<A> Array;
    }
    
    struct B {
      public B[] Array;
    }

    struct Segment<T> {
      public T[] Arr;
    }
    struct C {
      public Segment<A> Array;
    }

    struct DSegment {
      public D[] Arr;
    }
    struct D {
      public DSegment Array;
    }

    static void Main(string[] args) {
      // this does not crash
      var b = new B();

      // neither does this
      new A();

      // this however does
      //var a = new A();

      // as well as this 
      //var c = new C();

      // this works again
      var d = new D();
    }
  }
}
```

### Configuration

* the project targets core 3.1
* `dotnet --version` : 5.0.100
* Win10 x64
* I Don't know if the bug also occurs on different platforms, I don't have the time to test atm.

**Comment by antonfirsov** [comment] 2021-03-08 16:10
@SaculRennorb the simplest repro of your issue looks like as following:

```C#
struct P<T> { 
}

struct Q {
    public P<Q> Value;
}

class Program
{
    static void Main(string[] args)
    {
        var q = new Q();
    }
}
```

This is basically a duplicate of dotnet/runtime#6924, and unlikely to be fixed according to https://github.com/dotnet/runtime/issues/6924#issuecomment-547078135. If you think you have a good justification (real life use case) feel free to comment under that discussion.

**Closed by antonfirsov** 2021-03-08 16:10 UTC
