### ISSUE TITLE
Fedora wrong rpm package getting installed for aspnetcore-runtime-3.0 (3.0.101)

### ISSUE THREAD

**Issue by mdx0111** [dotnet/core#3879] opened 2019-11-21 11:18 UTC
Updating .Net Core 3.0.100 to 3.0.101 is installing wrong package on Fedora (31). The package being installed is aspnetcore-runtime-3.0.1-rh.rhel.7-x64.rpm rather than aspnetcore-runtime-3.0.1-x64.rpm.

This is causing the dotnet run to return the following message:

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '3.0.0' was not found.
  - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
```
The temporary workaround is manually installing the aspnetcore-runtime-3.0.1 from https://packages.microsoft.com/rhel/7/prod/aspnetcore-runtime-3.0.1-x64.rpm

Please do not hesitate to let me know if you need any further details.

Many thanks.

**Comment by Spaniol** [comment] 2019-11-21 13:43
Same issue is reproducible on CentOS Linux release 7.7.1908 (Core)

**Comment by craigjbass** [comment] 2019-11-21 16:01
A few things here @dagood - 

1) I removed dotnet packages entirely to be able to perform a system upgrade.
2) Went to reinstall dotnet 3.0.0 - so I followed the advice here: https://github.com/dotnet/core/issues/3853#issuecomment-556101411

I think there is something not quite right with the published dependency graph from the `dotnet-sdk-3.0` package:

```
> $ sudo dnf install dotnet-sdk-3.0                                                                                                                                                                                                 ⬡ 10.7.0 
Last metadata expiration check: 0:09:35 ago on Thu 21 Nov 2019 15:38:13 GMT.
Dependencies resolved.
==============================================================================================================================================================================================================================================
 Package                                                              Architecture                                  Version                                          Repository                                                          Size
==============================================================================================================================================================================================================================================
Installing:
 dotnet-sdk-3.0                                                       x86_64                                        3.0.101-1                                        packages-microsoft-com-prod                                         64 M
Installing dependencies:
 aspnetcore-runtime-3.0                                               x86_64                                        3.0.1-1                                          packages-microsoft-com-prod                                        7.5 M
 aspnetcore-targeting-pack-3.0                                        x86_64                                        3.0.1-1                                          packages-microsoft-com-prod                                        1.4 M
 dotnet-apphost-pack-3.0                                              x86_64                                        3.0.1-1                                          packages-microsoft-com-prod                                         66 k
 dotnet-host                                                          x86_64                                        3.0.1-1                                          packages-microsoft-com-prod                                         39 k
 dotnet-hostfxr-3.0                                                   x86_64                                        3.0.1-1                                          packages-microsoft-com-prod                                        147 k
 dotnet-runtime-3.0                                                   x86_64                                        3.0.1-1                                          packages-microsoft-com-prod                                         29 M
 dotnet-runtime-deps-3.0                                              x86_64                                        3.0.1-1                                          packages-microsoft-com-prod                                        2.8 k
 dotnet-targeting-pack-3.0                                            x86_64                                        3.0.1-1                                          packages-microsoft-com-prod                                        3.4 M

Transaction Summary
==============================================================================================================================================================================================================================================
Install  9 Packages

Total download size: 105 M
Installed size: 105 M
Is this ok [y/N]: y
```

This completed successfully, with the manual install of `sudo dnf install -y https://packages.microsoft.com/centos/7/prod/netstandard-targeting-pack-2.1.0-x64.rpm`

But I then got this error

```
15:50	Project 'Frank.EndToEndTests' load finished with warnings: The FrameworkReference 'Microsoft.NETCore.App' was not recognized at (264:5)
```

Which seemed rather odd.

I then manually installed this package `https://packages.microsoft.com/centos/7/prod/dotnet-targeting-pack-3.0.0-x64.rpm`

And everything worked!

![image](https://user-images.githubusercontent.com/1889973/69354391-f4726280-0c77-11ea-9399-a7d677c702c0.png)

* I think the dotnet-sdk-3.0 package should have a dependency on `dotnet-targeting-pack-3.0.0`, unless I'm missing something?
* It's more than a checksum issue, I think there are some issues with the yum repos

**Comment by craigjbass** [comment] 2019-11-21 16:06
Hmm - just relooking over the dnf transaction output - it does include `dotnet-targeting-pack-3.0`

![image](https://user-images.githubusercontent.com/1889973/69354849-b164bf00-0c78-11ea-9c17-ccabf51edb56.png)

These are for 3.0.1!

```Dependencies resolved.
==============================================================================================================================================================================================================================================
 Package                                                               Architecture                                       Version                                              Repository                                                Size
==============================================================================================================================================================================================================================================
Downgrading:
 dotnet-targeting-pack-3.0                                             x86_64                                             3.0.0-1                                              @commandline                                             3.4 M

Transaction Summary
==============================================================================================================================================================================================================================================
Downgrade  1 Package```

I think the packages are missing the minor version which is causing major confusion!

**Comment by dagood** [comment] 2019-11-21 18:57
@mdx0111, @Spaniol, that issue is a repro of https://github.com/dotnet/core/issues/3863, which I've reopened as https://github.com/dotnet/core/issues/3886 because although it might be fixed in some places, it's still a problem in others. We're working with the Microsoft linux repo admins to try to resolve these problems.

Closing as a duplicate of https://github.com/dotnet/core/issues/3863 and https://github.com/dotnet/core/issues/3886.

---

@craigjbass, that is an unrelated issue but very important, I'm going to copy your comments to https://github.com/dotnet/core/issues/3868 where the error message was reported earlier (but without enough context to understand it yet--your extra info was very useful to clear it up for me).

**Closed by dagood** 2019-11-21 18:57 UTC
