### ISSUE TITLE
.NET Core ARM SDK/Debugger

### ISSUE THREAD

**Issue by RoySalisbury** [dotnet/core#1143] opened 2017-12-09 21:37 UTC
I know the ARM builds of .NET Core 2.0 do not have a public SDK.  However, I would like you to consider releasing at least SOME portions for ARM.  Specifically, a way to remote debug.  It gets tedious having to go back to the old days of 'Console.WriteLine' to assist in debugging an application. Especially one that HAS to run on specific hardware.  

You already have it for Windows-ARM on the PI, so a Linux-arm version would seem to have the same performance.  

It does not have to even be a full featured debugger.  Just a way to add breakpoints and inspect variables would make me happy. 

Thanks!

**Comment by Petermarcu** [comment] 2017-12-11 17:13
There is a preview version of the debugger available. https://github.com/OmniSharp/omnisharp-vscode/issues/1562#issuecomment-348349242 give it a try :)

**Comment by Petermarcu** [comment] 2017-12-11 17:13
Closing this one as a duplicate of https://github.com/dotnet/core/issues/971

**Closed by Petermarcu** 2017-12-11 17:13 UTC
