### ISSUE TITLE
[Documentation] Outdated Fedora versions references on package install

### ISSUE THREAD

**Issue by Rubemlrm** [dotnet/core#3077] opened 2019-07-23 21:44 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/fedora28/sdk-2.2.301
Operating System: Linux Fedora 28 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

In the documentation there are references to Fedora 27 and 28 when both of those versions was discontinued. Besides this i've tried to use the following link https://packages.microsoft.com/config/fedora/30/prod.repo pointing to the Fedora 30 and its working fine. 
I've tried to find the documentation file to fix this, but without any success.

**Comment by danmosemsft** [comment] 2019-07-28 22:36
@leecow it looks like https://dotnet.microsoft.com/download/linux-package-manager/fedora28/sdk-2.2.301 needs an update. Is that your page?

**Comment by dagood** [comment] 2019-07-29 15:17
This is a known problem--there's a larger discussion/decision that needs to happen about keeping the distro list up to date: https://github.com/dotnet/core/issues/2576.

I would expect the "F27" feed to work for F30. We don't actually produce packages that are specific to F30--they're the same RPMs. @Rubemlrm, did you hit any installation problems, or is this only for the doc problem?

**Comment by Rubemlrm** [comment] 2019-07-30 08:33
@dagood it's working without any problem, this is a doc problem only. 
Thanks

**Comment by dagood** [comment] 2019-07-30 15:21
Thanks for confirming! I've updated the title of https://github.com/dotnet/core/issues/2576  and moved the comment about Fedora to the top to make it a little more visible, and I'm going to close this issue as a duplicate.

**Comment by dagood** [comment] 2019-07-30 15:22
Duplicate of #2576

**Closed by dagood** 2019-07-30 15:22 UTC
