### ISSUE TITLE
rider debug problem

### ISSUE THREAD

**Issue by zhangweilun** [dotnet/core#512] opened 2017-02-19 03:39 UTC
my rider ide tell me I can not debug the the dotnet core,and the jetbrains tell me the problem is about the license, I want to know why have this problem, dotnet core is not open source?

**Comment by svick** [comment] 2017-02-19 15:35
I think you're talking about the same issue as https://github.com/dotnet/core/issues/505, right? In that case, this issue should probably be closed as duplicate.

**Comment by Petermarcu** [comment] 2017-02-26 16:44
Closing as dupe of https://github.com/dotnet/core/issues/505

**Closed by Petermarcu** 2017-02-26 16:44 UTC
