### ISSUE TITLE
dotnet sdks not found on Jetson TX2

### ISSUE THREAD

**Issue by gauravagarwal28** [dotnet/core#1841] opened 2018-08-08 12:23 UTC
Followed the instructions here to setup dotnet as per the documentation here:
Platform: Jetson TX2 (aarch64)
OS: Ubunto 16.04

https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.302-linux-arm64-binaries

I copied the dotnet folder from my home to /usr/share

```
nvidia@tegra-ubuntu:/usr/share/dotnet$ ls
dotnet  host  LICENSE.txt  sdk  shared  ThirdPartyNotices.txt
```
As you can see, the dotnet sdk is present here in this folder:
```
nvidia@tegra-ubuntu:/usr/share/dotnet/sdk$ ls
2.1.302  NuGetFallbackFolder
```
```
nvidia@tegra-ubuntu:/usr/share/dotnet/sdk/2.1.302$ ls
15.0                                                        Microsoft.TestPlatform.Build.dll
AppHostTemplate                                             Microsoft.TestPlatform.CommunicationUtilities.dll
cs                                                          Microsoft.TestPlatform.CoreUtilities.dll
datacollector.deps.json                                     Microsoft.TestPlatform.CrossPlatEngine.dll
datacollector.dll                                           Microsoft.TestPlatform.PlatformAbstractions.deps.json
datacollector.dll.config                                    Microsoft.TestPlatform.PlatformAbstractions.dll
datacollector.runtimeconfig.json                            Microsoft.TestPlatform.targets
de                                                          Microsoft.TestPlatform.Utilities.dll
dotnet.deps.json                                            Microsoft.TestPlatform.VsTestConsole.TranslationLayer.dll
dotnet.dll                                                  Microsoft.TestPlatform.VsTestConsole.TranslationLayer.xml
dotnet.runtimeconfig.json                                   Microsoft.VisualBasic.CrossTargeting.targets
DotnetTools                                                 Microsoft.VisualBasic.CurrentVersion.targets
en                                                          Microsoft.VisualBasic.targets
es                                                          Microsoft.VisualStudio.TestPlatform.Client.dll
Extensions                                                  Microsoft.VisualStudio.TestPlatform.Common.dll
fr                                                          Microsoft.VisualStudio.TestPlatform.ObjectModel.dll
FSharp                                                      Microsoft.VisualStudioVersion.v11.Common.props
it                                                          Microsoft.VisualStudioVersion.v12.Common.props
ja                                                          Microsoft.VisualStudioVersion.v14.Common.props
ko                                                          minimumMSBuildVersion
Microsoft                                                   MSBuild.deps.json
Microsoft.ApplicationInsights.dll                           MSBuild.dll
Microsoft.AspNetCore.DeveloperCertificates.XPlat.dll        MSBuild.runtimeconfig.json
Microsoft.Build.dll                                         Newtonsoft.Json.dll
Microsoft.Build.Framework.dll                               NuGet.Build.Tasks.dll
Microsoft.Build.Tasks.Core.dll                              NuGet.CommandLine.XPlat.deps.json
Microsoft.Build.Utilities.Core.dll                          NuGet.CommandLine.XPlat.dll
Microsoft.CodeAnalysis.CSharp.dll                           NuGet.CommandLine.XPlat.runtimeconfig.json
Microsoft.CodeAnalysis.dll                                  NuGet.Commands.dll
Microsoft.Common.CrossTargeting.targets                     NuGet.Common.dll
Microsoft.Common.CurrentVersion.targets                     NuGet.Configuration.dll
Microsoft.Common.overridetasks                              NuGet.Credentials.dll
Microsoft.Common.targets                                    NuGet.DependencyResolver.Core.dll
Microsoft.Common.tasks                                      NuGet.Frameworks.dll
Microsoft.CSharp.CrossTargeting.targets                     NuGet.LibraryModel.dll
Microsoft.CSharp.CurrentVersion.targets                     NuGet.Packaging.Core.dll
Microsoft.CSharp.targets                                    NuGet.Packaging.dll
Microsoft.DotNet.Archive.dll                                NuGet.ProjectModel.dll
Microsoft.DotNet.Cli.CommandLine.dll                        NuGet.Protocol.dll
Microsoft.DotNet.Cli.Sln.Internal.dll                       NuGet.targets
Microsoft.DotNet.Cli.Utils.dll                              NuGet.Versioning.dll
Microsoft.DotNet.Configurer.dll                             package.deps.json
Microsoft.DotNet.InternalAbstractions.dll                   pl
Microsoft.DotNet.PlatformAbstractions.dll                   pt-BR
Microsoft.DotNet.ProjectJsonMigration.dll                   Roslyn
Microsoft.DotNet.Tools.MigrateCommand.dll                   ru
Microsoft.Extensions.CommandLineUtils.dll                   runtimes
Microsoft.Extensions.DependencyModel.dll                    SdkResolvers
Microsoft.NETCoreSdk.BundledCliTools.props                  Sdks
Microsoft.NETCoreSdk.BundledVersions.props                  System.Text.Encoding.CodePages.dll
Microsoft.NETFramework.CurrentVersion.props                 System.Xml.XPath.XmlDocument.dll
Microsoft.NETFramework.CurrentVersion.targets               Templates
Microsoft.NETFramework.props                                TestHost
Microsoft.NETFramework.targets                              tr
Microsoft.TemplateEngine.Abstractions.dll                   vstest.console.deps.json
Microsoft.TemplateEngine.Cli.dll                            vstest.console.dll
Microsoft.TemplateEngine.Core.Contracts.dll                 vstest.console.dll.config
Microsoft.TemplateEngine.Core.dll                           vstest.console.runtimeconfig.json
Microsoft.TemplateEngine.Edge.dll                           zh-Hans
Microsoft.TemplateEngine.Orchestrator.RunnableProjects.dll  zh-Hant
Microsoft.TemplateEngine.Utils.dll
```

The dotnet command works too:
```
nvidia@tegra-ubuntu:~$ whereis dotnet
dotnet: /usr/bin/dotnet /usr/share/dotnet /usr/share/dotnet/dotnet
nvidia@tegra-ubuntu:~$ dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
```

however, it is unable to find the dotnet sdk when I run dotnet --info
```
nvidia@tegra-ubuntu:~$ dotnet --info

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  No runtimes were found.

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by gauravagarwal28** [comment] 2018-08-08 12:29
This is my ~/.bashrc file:

```
nvidia@tegra-ubuntu:~$ cat ~/.bashrc
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
export PATH=/usr/local/cuda-9.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/share/dotnet
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:
export DOTNET_ROOT=$PATH:/usr/share/dotnet
nvidia@tegra-ubuntu:~$ 

```

**Comment by svick** [comment] 2018-08-08 13:04
Based on the output of `whereis`, it looks to me like you have two versions of the `dotnet` host installed: the one in `/usr/bin`, which does not contain the SDK, and the one in `/usr/share/dotnet`, which does. And since the one in `/usr/bin` is picked up when you run `dotnet`, it behaves as if you didn't have the SDK.

Can you try deleting the one in `/usr/bin`?

**Comment by joshfree** [comment] 2018-08-08 19:29
Thanks @svick for resolving this issue; and @gauravagarwal28 for posting the question.

As the issue is resolved, I'm closing out the bug.  @gauravagarwal28 feel free to reactivate this if there's any additional follow ups or unanswered questions.

Thanks

**Closed by joshfree** 2018-08-08 19:29 UTC
Labels: question
