### ISSUE TITLE
type inference in optimized netcore2.1 code differs from all other targets

### ISSUE THREAD

**Issue by gpomykala** [dotnet/core#2070] opened 2018-11-20 12:32 UTC
Platform: Windows  / Linux

runtime: dotnet 2.1.403

code optimization enabled

The code:

```c#
    [Test]
    public void BugRepro()
    {
      byte[] valueBytes = new byte[] { 0x7f, 0xff };

      byte firstByte = valueBytes[0];
      byte secondByte = valueBytes[1];

      // (firstByte << 8) should be inferred as int as in other targets and as without optimization
      ushort guilty = (ushort)((firstByte << 8) | secondByte);

      guilty.Should().Be(32767);
    }
```

Actual outcome: 
guilty == 255

Most likely (firstByte << 8) is inferred as byte with compile time optimization enabled,  and guilty is evalueated as (0 | 0xff)

It works as expected without code optimization in netcore2.1. All other targets: net462, mono, netcore2.0 produce expected result

**Comment by 0xd4d** [comment] 2018-11-20 15:09
This is a jitter bug and doesn't repro with .NET Core 3.0.

**Comment by gpomykala** [comment] 2018-11-20 20:32
Hello, 
Thanks for a quick reply. I appreciate that it's already fixed in netcore30. It seems like the only affected target is netcore2.1 - the same code was confirmed to work fine on .net up to 4.6.2, mono 4/5 an netcore2.0. 
Can it be fixed as part of netcore2.1 service release?
Cheers,
Greg

**Comment by karelz** [comment] 2018-11-26 04:56
@0xd4d do you know which bug it is?
cc @jkotas @RussKeldorph

**Comment by jkotas** [comment] 2018-11-26 05:00
@AndyAyersMS Does it ring a bell?

**Comment by AndyAyersMS** [comment] 2018-11-26 08:17
Seems like it could be dotnet/coreclr#18238.

**Comment by karelz** [comment] 2018-11-26 17:29
@AndyAyersMS what is our position on backporting it to 2.1 servicing? Do we need more upvotes / impact clarification?

**Comment by AndyAyersMS** [comment] 2018-11-26 20:13
I need to confirm this and look at what we did for a fix.

The bar for 2.1 is pretty high. So yes, it would be helpful to know more about the impact of this issue.

**Comment by AndyAyersMS** [comment] 2018-11-26 20:59
The actual issue was dotnet/coreclr#18235. 

I've verified that porting the fix for this (from dotnet/coreclr#18627) resolves this issue.

**Comment by AndyAyersMS** [comment] 2018-11-26 21:44
Also reported as dotnet/coreclr#20439.

@gpomykala can you say more about the impact this bug has on your usage of Core 2.1?

**Comment by gpomykala** [comment] 2018-11-27 14:37
@AndyAyersMS The impact is that the language fundamentals that are taken for granted suddenly return unexpected results. There are workarounds once the impacted user figures out what is happening, but it may go unnoticed in a so-so tested system (why would someone test the correctness of CLR?).
My app had been patched with a workaround therefore it is not a blocker for me anymore - if that was your question.

Best regards,
Greg

**Comment by AndyAyersMS** [comment] 2018-11-27 16:49
@gpomykala thanks.

**Comment by karelz** [comment] 2018-11-29 19:35
Duplicate of https://github.com/dotnet/coreclr/issues/18235

**Closed by karelz** 2018-11-29 19:35 UTC
