### ISSUE TITLE
csc.dll code 139 error when building project on .NET Core 2.1.302 Ubuntu 16.04 ARM64

### ISSUE THREAD

**Issue by gauravagarwal28** [dotnet/core#1845] opened 2018-08-10 06:13 UTC
I have downloaded .NET Core SDK for linux ARM64 on my Jetson TX2 running ubuntu 16.04.

```
nvidia@tegra-ubuntu:~$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-arm64
 Base Path:   /usr/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
nvidia@tegra-ubuntu:~$ 

```
However I am unable to run any dotnet application (even the hello world example) on my Jetson TX2.

```
nvidia@tegra-ubuntu:~$ dotnet new console -o myApp --force
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on myApp/myApp.csproj...
  Restoring packages for /home/nvidia/myApp/myApp.csproj...
  Generating MSBuild file /home/nvidia/myApp/obj/myApp.csproj.nuget.g.props.
  Generating MSBuild file /home/nvidia/myApp/obj/myApp.csproj.nuget.g.targets.
  Restore completed in 1.58 sec for /home/nvidia/myApp/myApp.csproj.

Restore succeeded.

```
```
nvidia@tegra-ubuntu:~/myApp$ dotnet run
/usr/share/dotnet/sdk/2.1.302/Roslyn/Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.dll" exited with code 139. [/home/nvidia/myApp/myApp.csproj]

The build failed. Please fix the build errors and run again.
```

**Comment by Petermarcu** [comment] 2018-09-06 20:55
@jkotas @jashook is this a duplicate of the other issue you were working on?

**Comment by jashook** [comment] 2018-09-06 20:56
Yes

**Comment by Petermarcu** [comment] 2018-09-06 20:59
Can you close this one with a link to the one you are using to track it?

**Comment by jashook** [comment] 2018-09-06 21:04
Tracked with https://github.com/dotnet/coreclr/issues/19578

**Closed by jashook** 2018-09-06 21:04 UTC
