### ISSUE TITLE
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install Operating System: Linux Ubuntu 19.04 - x64

### ISSUE THREAD

**Issue by mechatrona** [dotnet/core#2698] opened 2019-05-09 11:24 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 19.04 - x64

When I follow the tutorial provided to install dotnet sdk-2.2 after the last step I get the following error message:-
The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.4) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by dagood** [comment] 2019-05-09 15:20
Duplicate of #2526

**Closed by dagood** 2019-05-09 15:20 UTC
