### ISSUE TITLE
Version Information not added when EXE is published on Mac/Linux

### ISSUE THREAD

**Issue by cimnine** [dotnet/core#4964] opened 2020-07-20 11:16 UTC
# Version Information not added when published on Mac/Linux

We publish our binary as single file. When we build such an EXE on Linux or Mac, it does not contain the version number as metadata (i.e. `Right Click -> Properties -> Details`). When the EXE is built using the same command on a Windows machine, then the version information is retained.

The command in question is:

```bash
dotnet publish Project.Name -c Release -r win-x64 -o out -p:PublishSingleFile=true
```

When built on Mac/Linux:

![image](https://user-images.githubusercontent.com/804532/87931586-5777fb80-ca8a-11ea-900e-546d972bd1bd.png)

When built on Windows:

![image](https://user-images.githubusercontent.com/804532/87931822-b178c100-ca8a-11ea-9b21-d7a3d1460031.png)

# General

We define the version information via an Assembly.cs file:

```cs
[assembly: AssemblyVersion(Project.Name.AssemblyInfo.Version)]
[assembly: AssemblyFileVersion(Project.Name.AssemblyInfo.SimpleVersion)]
[assembly: AssemblyInformationalVersion(Project.Name.AssemblyInfo.InformationalVersion)]
[assembly: AssemblyCompany("XXX")]
[assembly: AssemblyCopyright("XXX")]
[assembly: AssemblyTitle("XXX")]
[assembly: AssemblyDescription("XXX")]

namespace Project.Name
{
    internal static class AssemblyInfo
    {
        /// <summary>
        /// Simple release-like version number, like 4.0.1.
        /// </summary>
        public const string SimpleVersion =
            ThisAssembly.Git.BaseVersion.Major
            + "."
            + ThisAssembly.Git.BaseVersion.Minor
            + "."
            + ThisAssembly.Git.BaseVersion.Patch;

        /// <summary>
        /// Full version, including commits since base version file, like 4.0.1.598.
        /// </summary>
        public const string Version = SimpleVersion + "." + ThisAssembly.Git.Commits;

        /// <summary>
        /// Full version, including commits since base version file and commit id, like 4.0.1.598-39cf84e.
        /// </summary>
        public const string InformationalVersion = Version + "-" + ThisAssembly.Git.Commit;
    }
}
```

The version number is provided by [_GitInfo_](https://www.nuget.org/packages/GitInfo). I was able to rule out a problem with GitInfo by changing the relevant lines as follows:

```patch
+ [assembly: AssemblyVersion("0.1.2.3")]
+ [assembly: AssemblyFileVersion("2.3.4.5")]
+ [assembly: AssemblyInformationalVersion("3.4.5.6")]
- [assembly: AssemblyVersion(Project.Name.AssemblyInfo.Version)]
- [assembly: AssemblyFileVersion(Project.Name.AssemblyInfo.SimpleVersion)]
- [assembly: AssemblyInformationalVersion(Project.Name.AssemblyInfo.InformationalVersion)]
```

**Comment by ricfre** [comment] 2020-07-29 17:16
I stumbled on the exact same thing today.

The additional detail I want to add is that the error seem to occur already during the **build** phase. 
If i do `dotnet build Project.Name -c Release -r win-x64 -o out` I can see that the resulting `.dll` file has the properties set correctly, but the corresponding `.exe` file does not. 

This is observed on Linux. Works as expected on Windows.

This is a comparison between the .dll and the .exe files when built on **Linux**:
![image](https://user-images.githubusercontent.com/9568871/88830987-fdd0a900-d1ce-11ea-9ab7-58ad4a3c67b4.png)

The same comparison when built on **Windows**:
![image](https://user-images.githubusercontent.com/9568871/88831402-9535fc00-d1cf-11ea-8012-243e4af88b62.png)

**Comment by hernandgr** [comment] 2020-10-09 21:37
I had the same issue in one of my pipelines and I just realized that it happens when I was using Ubuntu as image.

I created a [public repository on Azure DevOps](https://dev.azure.com/hernandgr/VersionNumberTest) with a web app and a couple of basic pipelines using Windows and Ubuntu that can show you the difference in the published artifacts.

![image](https://user-images.githubusercontent.com/2015653/95633637-b6c42700-0a4d-11eb-9cef-7fa10a7d59bd.png)

I hope this can help!

**Comment by dasMulli** [comment] 2020-10-09 22:19
Yes, this feature is only supported when building with windows as this uses APIs available in windows to modify the .exe file - https://github.com/dotnet/runtime/blob/0fa26b3b1452d11f131ebdb1f389bbf1a1c75faa/src/installer/managed/Microsoft.NET.HostModel/ResourceUpdater.cs#L177
/cc

**Comment by svdHero** [comment] 2021-09-29 12:13
Are there any plans to change this in the foreseeable future? I would not like to change my build environment just to be able to set the executable's version number. However, this is an important feature, because Windows users only check the EXE file for versioning when tech support requests come in.

**Comment by RandyLarson** [comment] 2022-02-11 02:18
This is super disappointing if absolutely true. `dotnet` can produce a Windows exe in all detail except a version number? This seems like a trivial oversight. I am glad that I found this thread after an hour of reproducing what has been said above:

I am using the `-p:Version=a.b.c.d` mechanism in an attempt to apply a version within our Jenkins pipeline. 

* versioning when targeting EXE output on a linux build env fails; works in Windows
* versioning when targeting DLL output works in linux and Windows

**Comment by RandyLarson** [comment] 2022-02-11 17:40
@svdHero - Since my last post I have not found anything regarding stamping the `.exe`. The thing that does work is the stamping of this given version onto `.dll`s. This is the route we took, as `dotnet` will emit a corresponding `.dll` for the `.exe` (e.g., `foo.dll` and `foo.exe` are both output files). Since the version is stamped correctly to the `.dll`, I've updated our code to use the `.dll` variant if available. We are fortunate that our needs are programmatic. I suppose users could be directed to the properties of the `.dll` variant.

**Comment by bradmoulder** [comment] 2022-03-28 21:52
Bump. Are there any updates here?

**Comment by bernatgy** [comment] 2022-04-29 10:30
This has been extremely annoying. Can we at least have attempts to fix this? Or any kind of discussions?

**Comment by joehacksalot** [comment] 2022-05-05 02:21
Also interested in updates here. We need this for automated build/deployment.

**Comment by mzros** [comment] 2022-07-15 15:24
Are there any updates here? We also need this for our ci/cd within github actions

**Comment by ngcdev** [comment] 2022-09-01 23:01
I just stumble upon this issue... App being build sometimes in Windows, sometimes in Ubuntu, and people reported wrong version. I couldn't believe it, until I did it manually and sure enough, in Ubuntu the version cannot be set. I don't know how this can be possible.

**Comment by DSchougaard** [comment] 2022-11-21 07:18
Any updates for this?

**Comment by chohoo89** [comment] 2022-11-23 09:01
AssemblyVersion, Version, icon, copyright, description, product name are all not applied.

**Comment by ManickaP** [comment] 2022-11-23 10:24
@vitek-karas any comments on this? Do you want me to transfer it?

**Comment by vitek-karas** [comment] 2022-11-23 11:05
The issue tracking this is https://github.com/dotnet/runtime/issues/3828

**Comment by ManickaP** [comment] 2022-11-23 11:11
Duplicate of https://github.com/dotnet/runtime/issues/3828

**Closed by ManickaP** 2022-11-23 11:11 UTC
Labels: area-runtime
