### ISSUE TITLE
SqlConnection.Open throws an InvalidOperationException

### ISSUE THREAD

**Issue by wuxubiao** [dotnet/core#2072] opened 2018-11-21 05:11 UTC
# SqlConnection throw an Exceoption by calling open Method

When I add this configuration to the project.csproj,whether the value is true or false

```xml
<ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Globalization.Invariant" Value="true" />
</ItemGroup>
```

```c#
SqlConnection throws an Exceoption by calling open Method
            var connection = new SqlConnection();
            connection.ConnectionString = "SomeConnectionString ";
            connection.Open();
```

InvalidOperationException: Internal connection fatal error.
```
System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, uint waitForMultipleObjectsTimeout, bool allowCreate, bool onlyOneCheckConnection, DbConnectionOptions userOptions, out DbConnectionInternal connection)
```

**Comment by karelz** [comment] 2018-11-26 04:53
@tarekgh any advice here?
cc @keeratsingh @AfsanehR @David-Engel

**Comment by tarekgh** [comment] 2018-11-26 16:57
SQL team need to take a look to know why the connection is failed. the issue here is not clear to me why this is failed.

**Comment by keeratsingh** [comment] 2018-11-26 17:20
@wuxubiao By the initial looks of the issue it seems quite similar to an existing issue #[29147](https://github.com/dotnet/corefx/issues/29147).
As per the discussions it seems like SqlClient currently doesn't support running with the `Globalization Invariant Mode`. The [workaround](https://github.com/dotnet/corefx/issues/29147#issuecomment-399375323) is to install the package `icu-libs` and set `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT`=false

If the issue still exists could you kindly share the following:
- Output of command dotnet --info.
- Repro with the csproj file that is being used. (includes the SqlClient version)
- Complete stack trace.

**Comment by karelz** [comment] 2018-11-26 17:40
Yes, either close it as dupe of existing CoreFX issue, or move it to CoreFX. Does it exist in CoreFX already?

**Comment by keeratsingh** [comment] 2018-11-26 17:45
#[29147](https://github.com/dotnet/corefx/issues/29147) already exists in CoreFX, however before I move/mark issue(#2072) as duplicate, I need more information form the user. I will proceed accordingly once I have the required information.

**Comment by karelz** [comment] 2018-11-26 17:56
In such case it is up to you if you want to track it here and then dupe it/move it, or move it right away to clarify in CoreFX.

**Comment by wuxubiao** [comment] 2018-11-27 07:51
> @wuxubiao By the initial looks of the issue it seems quite similar to an existing issue #[29147](https://github.com/dotnet/corefx/issues/29147).
> As per the discussions it seems like SqlClient currently doesn't support running with the `Globalization Invariant Mode`. The [workaround](https://github.com/dotnet/corefx/issues/29147#issuecomment-399375323) is to install the package `icu-libs` and set `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT`=false
> 
> If the issue still exists could you kindly share the following:
> 
> * Output of command dotnet --info.
> * Repro with the csproj file that is being used. (includes the SqlClient version)
> * Complete stack trace.

 install icu,it work

**Comment by keeratsingh** [comment] 2018-11-27 17:49
Duplicate of #[29147](https://github.com/dotnet/corefx/issues/29147). Closing issue.

**Closed by keeratsingh** 2018-11-27 17:49 UTC

**Comment by karelz** [comment] 2018-11-27 17:50
@keeratsingh I updated your above message - this way GH recognizes it as duplicate - see https://github.com/dotnet/core/issues/2072#event-1990313873
