### ISSUE TITLE
will .NET Core support ARM64 on Windows 10 client?

### ISSUE THREAD

**Issue by mosunchao** [dotnet/core#3622] opened 2019-10-15 00:20 UTC
# Issue Title

The .NET Core 3.0 is out, and I noticed the support OS and architecture for Windows 10 client only contains x86 and x64. With Windows 10 on ARM devices in multiple OEM's portfolio, is there a plan to support ARM64 on Windows 10?

# General

I'm asking this because we're trying to make our WPF app supporting in ARM. The x86 emulator in ARM approach proves that the performance of the app doesn't meet our standard, and I believe it's happening on a lot of other WPF apps. So we're considering alternatives, and instead of port everything to UWP, I learned that we can migrate a classic WPF app to .NET Core 3.0. But based on the ReadMe.md, it doesn't seem like we'll get the benefit of supporting ARM for now. Is that correct?

I'm not sure if this is the right place to ask this type of question, so my apology is provided ahead of time!

thanks!

**Comment by 0xd4d** [comment] 2019-10-15 12:10
https://github.com/dotnet/winforms/issues/2053

**Comment by scalablecory** [comment] 2019-10-15 17:29
Duplicate of https://github.com/dotnet/winforms/issues/2053

**Closed** 2019-10-15 17:29 UTC
