### ISSUE TITLE
Missing .dll

### ISSUE THREAD

**Issue by isnedd** [dotnet/core#3344] opened 2019-09-10 16:19 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
Trying to run dotnet from command prompt, error message indicates api-ms-win-crt-runtime-|1-1-0.dll is missing and to try re-installing this library. Any help as to where this library can be acquired would be very useful. OS is win8.1

Thanks in advance for any help

isnedd

**Comment by carlossanlop** [comment] 2019-09-11 18:28
@dagood does this sound like an install issue you could help with?

**Comment by dagood** [comment] 2019-09-11 18:39
This is a duplicate of https://github.com/dotnet/core/issues/2541.

You get this error when your machine is missing some prerequisites, namely patches. See https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x#net-core-dependencies for more info.

**Closed by dagood** 2019-09-11 18:39 UTC
