### ISSUE TITLE
"Multiple assemblies with equivalent identity have been imported" when importing more than one NuGet package referencing NuGet.Build.Packaging

### ISSUE THREAD

**Issue by ivan-vargas** [dotnet/core#1254] opened 2018-02-02 18:43 UTC
I came across this issue where a ASP.NET Core application would fail to build when installing certain NuGet packages with a bunch of these errors:

`/Users/user/projects/BugReport/Broken/CSC: Error CS1703: Multiple assemblies with equivalent identity have been imported: '/Users/user/.nuget/packages/breakmetwo/0.0.1/lib/netstandard2.0/System.Threading.Tasks.Parallel.dll' and '/Users/user/.nuget/packages/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Threading.Tasks.Parallel.dll'. Remove one of the duplicate references. (CS1703) (Broken)`

`/Users/user/projects/BugReport/Broken/CSC: Error CS1703: Multiple assemblies with equivalent identity have been imported: '/Users/user/.nuget/packages/breakmetwo/0.0.1/lib/netstandard2.0/System.Runtime.Serialization.Json.dll' and '/Users/user/.nuget/packages/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Runtime.Serialization.Json.dll'. Remove one of the duplicate references. (CS1703) (Broken)`

`/Users/user/projects/BugReport/Broken/Controllers/UselessController.cs(44,44): Error CS0731: The type forwarder for type 'System.Object' in assembly 'System.Runtime' causes a cycle (CS0731) (Broken)`

The NuGet packages are created in house. The NuGet packages are hosted on a shared drive. After a lot of hours of researching and troubleshooting this, I found out that NuGet packages created of projects referencing NuGet.Build.Packaging were causing those errors. The NuGet packages were created referencing NuGet.Build.Packaging 0.2.0 and also 0.2.2, both producing the same outcome.

These errors only showed up when more than one NuGet package references NuGet.Build.Packaging. The attached project contains two .NETStandard libraries (BreakMeOne and BreakMeTwo) referencing NuGet.Build.Packaging. If only one of either of those libraries is imported, the project builds fine. When the second library is imported, the build fails. If I regenerate either of the packages without the reference to NuGet.Build.Packaging, the project builds fine.

This is the output of dotnet --info of the machine where the packages were created:

```
$ dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54 
```

The build error happens on this machine (Mac OS X) as well as Windows 10 x64
 
Thanks

[BugReport.zip](https://github.com/dotnet/core/files/1690432/BugReport.zip)

**Comment by Eilon** [comment] 2018-07-11 19:00
@Petermarcu - this seems unlikely to be related to ASP.NET Core because the package in question is not even in ASP.NET Core's package graph.

Also, I wasn't able to reproduce this on my machine, so this might be fixed in newer builds anyway.

**Comment by Petermarcu** [comment] 2018-07-12 20:20
@weshaggard is this a corefx issue?

**Comment by weshaggard** [comment] 2018-07-12 21:32
I suspect this is because of the older toolset that doesn't support conflict resolution. @ivan-vargas please update your .NET SDK and try again I believe this will not be any issue for you.

**Closed by weshaggard** 2018-07-12 21:32 UTC
