### ISSUE TITLE
Unexpected failing install (Travis CI)

### ISSUE THREAD

**Issue by cloudrex** [dotnet/core#2670] opened 2019-05-02 13:31 UTC
I'm trying to setup continuous integration for a .NET core project using Travis CI on GitHub.

This is my `.travis.yml`:
```yml
language: csharp
mono: none
script:
  - wget -q https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.2
  - sudo dotnet restore
  - sudo dotnet build ./Ion/
  - sudo dotnet build ./Ion.Tests/
  - sudo dotnet test ./Ion.Tests/
```

However, I receive the following output:
```shell
...
Unpacking dotnet-sdk-2.2 (2.2.203-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/aspnetcore-runtime-2.2_2.2.4-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command "sudo apt-get install dotnet-sdk-2.2" exited with 100.
```
Any ideas? Interestingly, `$ dotnet run/restore/build/test` still works, it just messes up my build because it returns non-zero code.

**Comment by karelz** [comment] 2019-06-05 02:58
Are you able to reproduce it outside of Travis CI? On image which replicates its setup?
@dagood does it look familiar?

**Comment by dagood** [comment] 2019-06-05 17:56
This seems to be a duplicate of https://github.com/dotnet/core/issues/2381, where `dpkg` is out of date and has a bug that causes this.

Note that Ubuntu 14.04 is now EOL!

**Comment by dagood** [comment] 2019-06-05 17:56
Duplicate of #2381

**Closed by dagood** 2019-06-05 17:56 UTC
