### ISSUE TITLE
Install dotnet 2.2 on Ubuntu 19.04 missing dependencies

### ISSUE THREAD

**Issue by gertd** [dotnet/core#2627] opened 2019-04-23 15:59 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-10/sdk-current
Operating System: Linux Ubuntu 18.10 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Install of SDK fails with 
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.4) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

 sudo apt-get install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.4) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by jlrogee** [comment] 2019-04-23 18:58
Hi, this is my solution 
`wget -q https://packages.microsoft.com/config/ubuntu/18.10/packages-microsoft-prod.deb`
`sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list`
`sudo gedit /etc/apt/sources.list.d/microsoft-prod.list`
and change in string
`deb [arch=amd64] https://packages.microsoft.com/ubuntu/19.04/prod **xenial** main`
to 
`deb [arch=amd64] https://packages.microsoft.com/ubuntu/19.04/prod **disco** main`

**Comment by dagood** [comment] 2019-04-24 15:22
Duplicate of https://github.com/dotnet/core/issues/2526, we don't have packages for 19.04 quite yet.

**Closed by dagood** 2019-04-24 15:22 UTC

**Comment by anthonyhollings** [comment] 2019-05-05 01:23
Any news on when we will get 2.1 and 2.2 working for Ubuntu 19.04?
