### ISSUE TITLE
Fedora: Incorrect checksums for netstandard-targeting-pack RPM breaks package install/update

### ISSUE THREAD

**Issue by agc93** [dotnet/core#3867] opened 2019-11-20 06:30 UTC
The `netstandard-targeting-pack-2.1.0-x64.rpm` from the `https://packages.microsoft.com/fedora/30/prod/` repo has the incorrect checksum causing DNF to bail out, blocking system updates.

The calculated checksum of the package (when directly downloading the rpm) is `45e199caf1151a750d11d9c5c7669d6e23d8dbb33da54d1d90bde55745996480` which fails against the official F30 yum repo.

Full output below:

```text
Downloading Packages:
[MIRROR] netstandard-targeting-pack-2.1.0-x64.rpm: Downloading successful, but checksum doesn't match. Calculated: 45e199caf1151a750d11d9c5c7669d6e23d8dbb33da54d1d90bde55745996480(sha256)  Expected: fa194a8c12913dcec85c8d24bfc91686a7b93128b4c05346df16e2c641e2ba41(sha256) 
[FAILED] netstandard-targeting-pack-2.1.0-x64.rpm: No more mirrors to try - All mirrors were already tried without success                                                                                        

Error: Error downloading packages:
  Cannot download netstandard-targeting-pack-2.1.0-x64.rpm: All mirrors were tried
```

This can be replicated using the following Dockerfile (or run commands on a live F30 install)

```
FROM fedora:30
RUN curl https://packages.microsoft.com/config/fedora/30/prod.repo | tee /etc/yum.repos.d/microsoft-prod.repo
RUN dnf install -y netstandard-targeting-pack-2.1
```

**Comment by craigjbass** [comment] 2019-11-20 16:42
@dagood I think this is a dupe of #3853 just different RHEL-like flavours giving slightly different messages.

**Comment by dagood** [comment] 2019-11-20 16:47
That's probably true, I'm going to leave this one open as well until we know for sure though, and it might also be a useful signpost for anyone looking through issues who might skip over an issue with CentOS in the title when they're using a different RPM-using distro.

**Comment by dagood** [comment] 2019-11-21 20:15
I finally decided to rename https://github.com/dotnet/core/issues/3853 to reference each distro and include the more specific error messages for each distro. So, I'm closing this issue as a duplicate now.

(Sorry for the indecisiveness, I was hoping this would be resolved sooner so it wouldn't be as important to organize these.)

**Closed by dagood** 2019-11-21 20:15 UTC
Labels: area-setup
