### ISSUE TITLE
cannot install dotnet-sdk-2.2 on ubuntu 18.04

### ISSUE THREAD

**Issue by zhang0peter** [dotnet/core#2704] opened 2019-05-10 15:26 UTC
i run following commands, but cannot install dotnet-sdk-2.2
```js
sudo apt-get install -y gpg
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
wget -q https://packages.microsoft.com/config/ubuntu/18.04/prod.list
sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
sudo apt-get install -y apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-2.2
```
error is:
```js
E: Unable to locate package dotnet-sdk-2.2
E: Couldn't find any package by glob 'dotnet-sdk-2.2'
E: Couldn't find any package by regex 'dotnet-sdk-2.2'
```
i think it might be cpu version's problem:
```js
-> # uname -a
Linux ubuntu 4.15.0-1033-raspi2 #35-Ubuntu SMP PREEMPT Fri Mar 15 ... UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
```
so does dotnet-sdk-2.2 have arm64 version ?

**Comment by dagood** [comment] 2019-05-10 18:30
That's correct, we don't have a Debian package for arm/arm64 right now, you have to use the tarballs.

**Comment by dagood** [comment] 2019-05-10 18:30
Duplicate of #2622

**Closed by dagood** 2019-05-10 18:30 UTC
