### ISSUE TITLE
Runtime Performance Linux, Mac, Windows

### ISSUE THREAD

**Issue by IssueWorld** [dotnet/core#825] opened 2017-08-14 19:14 UTC
I created a simple asp.net core webapi application using .net core 2.0 preview 2. It is almost the generated sample project generated by the dotnet wepapi command. All this simple applications does is to return a list of 1.000.000 instances. Those 1 million instances are fix and only generated once.

SAMPLE CODE USED

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace print.Controllers
{
    [Route("api/[controller]")]
    public class PrintController : Controller
    {
        private PrintOutList list = null;

        // GET api/values
        [HttpGet]
        public IActionResult Get()
        {
            if (list == null)
            {
                list = new PrintOutList();
                list.Build(1000000);
            }
            return new OkObjectResult(list);
        }            
    }

    public enum Weekday
    {
        Monday = 1,
        Tuesday = 2,
        Wednesday = 3
    }

    public class PrintOut
    {
        public string Id { get; set; }
        public int ActorObjectTypeId { get;set;}
        public string ActorId { get; set;}
        public int PrintObjectTypeId { get ; set ;}
        public string PrintObjectId { get; set;}
        public string Text { get; set;}
        public Weekday Weekday { get; set; }
    }

    public class PrintOutList : List<PrintOut>
    {
        public void Build(int  count)
        {
            for(int index=0;index<count;index++)
            {
                PrintOut element = new PrintOut();

                if (index == 0) element.Id = "4711";
                else element.Id = Guid.NewGuid().ToString();
                element.ActorObjectTypeId = 100;
                element.ActorId = Guid.NewGuid().ToString();
                element.PrintObjectTypeId = 200;
                element.PrintObjectId = Guid.NewGuid().ToString();
                element.Text = "This is just a sample. " + index.ToString();
                element.Weekday = Weekday.Monday;
                Add(element);
            }

        }
    }
}
```

Windows 7: 3,8 seconds (Native Machine) - GOOD
Results on Windows 7 using "2.0.0-preview2-006497" 
This machine is using 8 GB RAM, 8 Cores, NOT Virtualized 
Starting the server: dotnet bin/release/netcoreapp2.0/publish/print.dll

```
$ curl -w "@curl-format.txt" -s http://10.40.10.23:5000/api/print -o /dev/null
          remote_ip:  10.40.10.23
           local_ip:  10.40.10.23
        num_connect:  1
      num_redirects:  0
    time_namelookup:  0,000000 Seconds
       time_connect:  0,000000 Seconds
    time_appconnect:  0,000000 Seconds
   time_pretransfer:  0,000000 Seconds
      time_redirect:  0,000000 Seconds
 time_starttransfer:  1,232000 Seconds
      size_download:  294888859 Bytes
        size_header:  148 Bytes
       size_request:  89 Bytes
     speed_download:  77479994,000 Bytes/s
----------------------------------------------
         time_total:  3,806000
```

RHEL 7.2: 24,78 seconds (Virtual Machine VMWare Workstation) - BAD
Results on RHEL 7.2 using "2.0.0-preview2-006497" 
This machine is runing within VMWARE Workstation using 2 GB RAM, 2 Cores
Starting the server: [root@node0 print]# /opt/dotnet/dotnet ./bin/release/netcoreapp2.0/publish/print.dll

```
[root@node0 ~]# curl -w "@curl-format.txt" -s http://10.40.10.59:5000/api/print -o /dev/null
          remote_ip:  10.40.10.59
           local_ip:  10.40.10.59
        num_connect:  1
      num_redirects:  0
    time_namelookup:  0.000 Seconds
       time_connect:  0.001 Seconds
    time_appconnect:  0.000 Seconds
   time_pretransfer:  0.001 Seconds
      time_redirect:  0.000 Seconds
 time_starttransfer:  21.286 Seconds
      size_download:  294888859 Bytes
        size_header:  148 Bytes
       size_request:  89 Bytes
     speed_download:  11937938.000 Bytes/s
----------------------------------------------
         time_total:  24.702
```

RHEL 7.4: 21,6 seconds (Virtual Machine ESX Server) - BAD
Results on RHEL 7.4 using "2.0.0-preview2-006497" 
This machine is runing within VMWARE Workstation using 4 GB RAM, 2 Cores 
Starting the server: [root@node0 print]# /opt/dotnet/dotnet ./bin/release/netcoreapp2.0/publish/print.dll

```
[root@node1 ~]# curl -w "@curl-format.txt" -s http://10.40.40.40:5000/api/print -o /dev/null
          remote_ip:  10.40.40.40
           local_ip:  10.40.40.40
        num_connect:  1
      num_redirects:  0
    time_namelookup:  0.000 Seconds
       time_connect:  0.000 Seconds
    time_appconnect:  0.000 Seconds
   time_pretransfer:  0.000 Seconds
      time_redirect:  0.000 Seconds
 time_starttransfer:  18.043 Seconds
      size_download:  294888859 Bytes
        size_header:  148 Bytes
       size_request:  89 Bytes
     speed_download:  13641913.000 Bytes/s
----------------------------------------------
         time_total:  21.616
```

OSX: 4,0 seconds (Native Machine) - GOOD
Results on OSX (current cersion) This machine is using 16 GB RAM, 4 Cores 
I just have a screenshot of the results. The total time was round about 4 seconds

On a Fedora 25 linux I also had the bad results of 25 seconds.

Maybe this is a bug, maybe not.
Hopefully there is any kind of of explanation.
I am waiting for cross plattform c# for ten years ;)

**Comment by IssueWorld** [comment] 2017-08-14 19:16
sorry for the bad text format :(

**Comment by benaadams** [comment] 2017-08-14 19:58
Most of the time seems to be in `time_starttransfer` on the linux versions?

**Comment by IssueWorld** [comment] 2017-08-14 20:12
Just make a little measurement on OSX Sierra 10.12.6
This time i was using the official release of .net core 2.0.
The result of 4,4 seconds is GOOD.

       remote_ip:  192.168.178.5
           local_ip:  192.168.178.5
        num_connect:  1
      num_redirects:  0
    time_namelookup:  0,004189 Seconds
       time_connect:  0,004691 Seconds
    time_appconnect:  0,000000 Seconds
     time_pretransfer:  0,004782 Seconds
           time_redirect:  0,000000 Seconds
   time_starttransfer:  1,810075 Seconds
        size_download:  294888859 Bytes
             size_header:  148 Bytes
            size_request:  91 Bytes
     speed_download:  66548592,000 Bytes/s
----------------------------------------------
         time_total:  4,431181

May the huge time difference on linux is the json serialization.
The applications start to convert the 1 million instances into a json string.
After that, the resulting string is transmitted to the requesting client.

**Comment by IssueWorld** [comment] 2017-08-14 22:36
I made one more test using Windows Server 2012 R2 Standard, 4 GB RAM, 2 Cores, hosted within VMWare Workstation 12 Pro. Within this test I was using the official release 2.0.0. Still GOOD.

$ curl -w "@curl-format.txt" -s http://192.168.178.117:5000/api/print -o /dev/null
          remote_ip:  192.168.178.117
           local_ip:  192.168.178.120
        num_connect:  1
      num_redirects:  0
    time_namelookup:  0,000000 Seconds
       time_connect:  0,000000 Seconds
    time_appconnect:  0,000000 Seconds
   time_pretransfer:  0,000000 Seconds
      time_redirect:  0,000000 Seconds
 time_starttransfer:  1,716000 Seconds
      size_download:  294888859 Bytes
        size_header:  148 Bytes
       size_request:  93 Bytes
     speed_download:  60789292,000 Bytes/s
----------------------------------------------
         time_total:  4,851000

This is a value I expected. I suspect there are some internal "things" within the JSON serialization in Linux. My test class has 7 properties. All togehter there are 7 millions "json strings" to create. BUT, maybe i am wrong and it's just a setting to activate on a linux machine.

Hopefully it's only this kind of tricky setting or a simple bug which can be fixed within a future release. For me, the availability of a cross plattform c# is a kind of dream, 10 years old :)

**Comment by omajid** [comment] 2017-08-15 01:08
@tmds this looks like something you were looking into recently.

**Comment by IssueWorld** [comment] 2017-08-15 08:35
On Windows Server 2016 Core (2 GB RAM, 4 Cores) running within VMware Workstation i get the following:

```
$ curl -w "@curl-format.txt" -s http://10.40.10.158:5000/api/print -o /dev/null
          remote_ip:  10.40.10.158
           local_ip:  10.40.10.23
        num_connect:  1
      num_redirects:  0
    time_namelookup:  0,000000 Seconds
       time_connect:  0,000000 Seconds
    time_appconnect:  0,000000 Seconds
   time_pretransfer:  0,000000 Seconds
      time_redirect:  0,000000 Seconds
 time_starttransfer:  1,295000 Seconds
      size_download:  294888859 Bytes
        size_header:  148 Bytes
       size_request:  90 Bytes
     speed_download:  59072287,000 Bytes/s
----------------------------------------------
         time_total:  4,992000
```

**Comment by tmds** [comment] 2017-08-16 12:25
> Those 1 million instances are fix and only generated once.

The repro code is not re-using the `list` across request.

> On Linux, the time is spent building the list.
```
                var startTime = Environment.TickCount;
                list = new PrintOutList();
                list.Build(1000000);
                System.Console.WriteLine($"Building list took {Environment.TickCount - startTime}ms");
```

outputs

```
Building list took 14672ms
```

The reproduces on Fedora 25 using .NET Core 2.0.

**Comment by tmds** [comment] 2017-08-16 12:35
Replacing `Guid.NewGuid()` with `Guid.Empty` makes it work fast.

**Comment by IssueWorld** [comment] 2017-08-16 16:04
@tmds Thanx. So its "only" a little problem with the NewGuid function. Hopefully it ca be fixed in a future release.

**Comment by benaadams** [comment] 2017-08-16 19:33
@IssueWorld you should raise and issue in https://github.com/dotnet/coreclr about NewGuid being slow on the platforms you have noticed it on.

**Comment by Petermarcu** [comment] 2017-10-06 17:59
@IssueWorld , were you able to open an issue on NewGuid performance? @stephentoub as FYI

I'm going to close this issue now because this one looks to be addressed...

**Closed by Petermarcu** 2017-10-06 17:59 UTC
