### ISSUE TITLE
Ubuntu 19.04 instructions don't add repo to list

### ISSUE THREAD

**Issue by NathanHannon** [dotnet/core#2787] opened 2019-05-24 23:12 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current
Operating System: Linux Ubuntu 19.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

After following the instructions, the repo doesn't show up in my list or when I do apt update.

However, I am able to add the repo manually by adding "https://packages.microsoft.com/ubuntu/19.04/prod disco InRelease" to the other software category in Software & Updates

**Comment by karelz** [comment] 2019-05-25 19:12
Duplicate of #2526

**Closed by karelz** 2019-05-25 19:12 UTC
