### ISSUE TITLE
NET Core Version Issues

### ISSUE THREAD

**Issue by rajames429** [dotnet/core#1669] opened 2018-06-07 06:14 UTC
I am running Windows 10 Pro and I am attempting to complete the 'Microservices hosted in Docker' (command-line based) tutorial located at:  
https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/microservices  

When I entered 'dotnet restore' I get an error -- warn : The folder ... does not contain a project to restore. 
When I entered 'dotnet run'  I get an error -- error DOTNET1017: Project file does not exist  

While looking for answers (Google search), I realized it might be a versioning issue, so I checked my installation and got the following (seemingly) contradictory information ?  

Can someone tell me how to fix this ?  

When I enter 'dotnet --info' in the project directory, I get 

.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

The global.json file contains:  (NOTE:  there is no project.json file)....
{
  "sdk": {
    "version": "1.0.0-rc4-004771"
  }
}

When I enter 'dotnet --info' from another directory, I get 

.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

**Comment by svick** [comment] 2018-06-07 11:16
It seems the `yo aspnet` generator is significantly outdated. Nobody should be using prerelease versions of .Net Core tools 1.0 anymore. There is already an issue about updating the tutorial (https://github.com/dotnet/docs/issues/5700), but in the meantime, what I think you should do is:

1. Use `dotnet new web` to create the application.
2. Copy the Dockerfile from the tutorial to your application.

---

If you're curious about more details about what the issue is: `yo aspnet` generates global.json that tells .Net Core to use version 1.0.0-rc4 of its tools. You don't have that installed, so instead version 1.0.0-preview2 is selected. But that version is so old that it doesn't support the "new" csproj project file, which is causing the error.

**Comment by Petermarcu** [comment] 2018-06-13 03:30
I'd also just remove the 1.0 preview from your machine and delete your global.json unless you have a strong reason for it.

**Comment by leecow** [comment] 2018-06-13 17:07
Closing this as it's gone quiet. Please re-open if you're still having issues.

**Closed by leecow** 2018-06-13 17:07 UTC
