### ISSUE TITLE
It was not possible to find 3.0.0-preview6.19307.2

### ISSUE THREAD

**Issue by mic3ael** [dotnet/core#2989] opened 2019-07-05 16:15 UTC
# 3.0.0-preview6
I tried to use dotnet preview6 on my Arch Linux machine and I couldn't find the way to run it the info is attached below.

# The information
dotnet run
```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '3.0.0-preview6.19307.2' was not found.
  - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download

```

dotnet --info 
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /opt/dotnet/sdk/3.0.100-preview6-012264/

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.2.105 [/opt/dotnet/sdk]
  3.0.0-preview6.19307.2 [/opt/dotnet/sdk]
  3.0.100-preview6-012264 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.3 [/opt/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
```

**Comment by dagood** [comment] 2019-07-06 06:23
Where did you get this build? (How did you install .NET Core?)

ASP.NET Core being missing might be because it's based on source-build, in which case this is a duplicate of https://github.com/dotnet/source-build/issues/1121.

**Comment by omajid** [comment] 2019-07-07 18:57
Given it's Arch, it's probably this build: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dotnet-core-preview

**Comment by dagood** [comment] 2019-07-08 15:19
Interesting, based on that, it looks like `aspnet-runtime-3.0` needs to be installed separately from the AUR, because that `dotnet-sdk-3.0` doesn't take a dependency on it.

(The Microsoft-built SDK packages, on the other hand, *do* depend on the ASP.NET Core runtime.)

**Comment by karelz** [comment] 2019-07-29 11:51
@dagood is there any action item left here?

**Comment by dagood** [comment] 2019-07-29 15:13
No, without more info from @mic3ael there isn't anything that can be done about this issue. If it's from the AUR as we suspect, the workaround seems likely to work, or an issue needs to be filed in the AUR for the person maintaining the Arch package to address.

**Closed by dagood** 2019-07-29 15:13 UTC
Labels: needs more info
