### ISSUE TITLE
i have a error saying: A Project With a output type of Class Library Cannot be directly started

### ISSUE THREAD

**Issue by TjoshgGaming123** [dotnet/core#5264] opened 2020-09-27 10:00 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by danmosemsft** [comment] 2020-09-30 22:53
duplicate of #5266

**Closed by danmosemsft** 2020-09-30 22:53 UTC
