### ISSUE TITLE
deps.json referencing missing packages in a published app.

### ISSUE THREAD

**Issue by tkstanczak** [dotnet/core#2471] opened 2019-03-19 12:24 UTC
We have released a self-contained version of our app for Linux
```
#!/bin/bash
RUNTIME=linux-x64
OUT=out/$RUNTIME
ECHO === Publishing $RUNTIME package ===
dotnet publish -c Release -r $RUNTIME -o $OUT
ECHO === Published $RUNTIME package ===
```

User reported:

> An assembly specified in the application dependencies manifest (Nethermind.Runner.deps.json) was not found:
> package: 'runtime.linux-x64.Microsoft.NETCore.App', version: '2.2.1'
> path: 'runtimes/linux-x64/native/createdump'

Looking at the generated deps.json we can see:

```
{
  "runtimeTarget": {
    "name": ".NETCoreApp,Version=v2.2/linux-x64",
    "signature": "83a51c22effe65ad844c5d103b015c97ac0b3b4f"
  },
  "compilationOptions": {
    "defines": [
      "TRACE",
      "RELEASE",
      "NETCOREAPP",
      "NETCOREAPP2_2"
    ],
    "languageVersion": "7.2",
    "platform": "x64",
    "allowUnsafe": false,
    "warningsAsErrors": false,
    "optimize": true,
    "keyFile": "",
    "emitEntryPoint": true,
    "xmlDoc": false,
    "debugType": "portable"
  },
  "targets": {
    ".NETCoreApp,Version=v2.2": {
      "Nethermind.Runner/1.0.0": {
        "dependencies": {
          "Microsoft.AspNetCore.App": "2.2.1",
          "Microsoft.Extensions.CommandLineUtils": "1.1.1",
          "Microsoft.NETCore.App": "2.2.1",
```

Publish script was running on a Windows machine with:

```
C:\Users\tksta>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.103\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

mscorlib published
![image](https://user-images.githubusercontent.com/498913/54606048-9c2cf600-4a42-11e9-807b-11ae362513af.png)

**Comment by tkstanczak** [comment] 2019-03-19 12:40
this may be related:
https://github.com/dotnet/cli/issues/6516

**Comment by leecow** [comment] 2019-03-19 21:49
@livarcocc - any ideas?

**Comment by livarcocc** [comment] 2019-03-19 21:53
@tkstanczak is there a repro that you can share with us? Perhaps a binlog for the failed build? Do keep in mind that in a binlog secrets and other sensitive information may be capture in the log. If that's the case, let us know and we can share an email that you can use to share the log directly to us instead of through a file attachment on github.

@peterhuene to help take a look.

**Comment by tkstanczak** [comment] 2019-03-20 14:12
Repo is here (tag v0.9.6):
https://github.com/NethermindEth/nethermind

This is the publish process:

> Build the packages using the provided script publish-all.sh under the Nethermind.Runner\scripts directory. Run the script from the root directory $ ./scripts/publish-all.sh
> cd src/Nethermind/Nethermind.Runner/scripts
> rm -rf out
> scripts/publish-all.sh

this is what user did:

> Linux (Ubuntu 16.04 18.04 - reach out on gitter for other distributions)
> 
> check if your CPU supports AVX2 -> grep avx /proc/cpuinfo (if not then reach out to us - we may suggest solutions)
> sudo apt-get update && sudo apt-get install libsnappy-dev libc6-dev libc6 unzip
> curl https://nethdev.blob.core.windows.net/builds/nethermind-linux-amd64-0.9.6-167dba6.zip --output nethermind.zip
> unzip nethermind.zip -d nethermind
> cd nethermind
> chmod +x Nethermind.Runner
> mkdir native && mkdir native/amd64 && cp librocksdb-5.15.10.so native/amd64
> ./Nethermind.Runner

Waiting for the user to provide their distro details

**Comment by karelz** [comment] 2019-03-30 18:34
@peterhuene can you please help here? What is the next step?

**Comment by peterhuene** [comment] 2019-03-30 19:06
I'm unable to reproduce the problem on my Arch system.  The contents of the linked zip look correct; `createdump` is present.  I'm able to run the `Nethermind.Runner` apphost without issue.

I don't see anything leaping out to me as incorrect in the deps file.

@tkstanczak do we have any additional information from the user?

**Comment by tkstanczak** [comment] 2019-04-03 15:52
@peterhuene, I have not received the details, I asked the user now once again to send the distro details, we will inform you if there is anybody else reporting this - if no update here for the next couple of days or so then we can close and I will be able to create a new issue and reference this one if it ever reoccurs

unfortunately we were not able to reproduce it on any of our systems neither

**Comment by peterhuene** [comment] 2019-04-03 15:56
Thanks, @tkstanczak! If we do get more details from your user, I will immediately investigate.

**Comment by zero-down2018** [comment] 2019-04-06 08:28
grep avx /proc/cpuinfo gave out following:

flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov          pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm c         onstant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aper         fmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm          pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pt         i ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida          arat pln pts flush_l1d
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov          pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm c         onstant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aper         fmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm          pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pt         i ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida          arat pln pts flush_l1d
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov          pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm c         onstant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aper         fmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm          pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pt         i ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida          arat pln pts flush_l1d
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov          pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm c         onstant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aper         fmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm          pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pt         i ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida          arat pln pts flush_l1d

not too often here, but will be informed about news

**Comment by tkstanczak** [comment] 2019-04-08 01:49
@zero-down2018, I think the CPU is not relevant here (it was relevant for another issue). We would need the Linux distribution information and ingo whethere there were any .NET Core SDKs installed on the machine manually (by running dotnet —info and dotnet —version)

**Comment by tkstanczak** [comment] 2019-05-20 15:07
seems that another user has a similar issue with the package that runs everywhere else (and was built as a self contained package)
https://github.com/NethermindEth/nethermind/issues/492

**Comment by karelz** [comment] 2019-06-05 04:05
@peterhuene amny udpate? It's been 2 months ...

**Comment by peterhuene** [comment] 2019-06-05 04:30
@karelz this is not an SDK issue as the files that so far that have been reported missing by the host have existed in their releases (i.e. they were published by the SDK), albeit @tkstanczak now appears to be distributing the `Nethermind.Runner` application using [warp](https://github.com/dgiagio/warp) as a single file.  Perhaps there is some problem unpacking the application?

@tkstanczak if a user is able to reproduce this again, have them run with the `COREHOST_TRACE` environment variable set to `1` and have them paste the output.  Perhaps it will shed light on why the dependencies aren't being found by the host.

**Comment by peterhuene** [comment] 2019-08-06 18:41
@tkstanczak I just wanted to follow-up and see if any of your other users have run into this issue (and whether or not we'd be able to trace the host's loading of dependencies with `COREHOST_TRACE`).  I haven't been able to reproduce the problem myself and the publish output I've inspected from your builds have seemed correct, thus I can't explain why the occasional user runs into a dependency load failure.

**Comment by carlossanlop** [comment] 2019-09-27 18:04
No comments since August. Closing.

**Closed by carlossanlop** 2019-09-27 18:04 UTC

**Comment by roninkaizen** [comment] 2019-10-11 23:37
update-
with ubuntu 19.04 i got a close related error from the system while starting,
it "goes like this":
The application to execute does not exist: '/home/ubuntu/.local/share/warp/packages/Nethermind.Runner/Nethermind.Runner.dll'.

**Comment by tkstanczak** [comment] 2019-10-12 01:41
this is unrelated @roninkaizen, we will track your issue in our repo
