### ISSUE TITLE
Dotnet webapi doesn't compile on fedora 32 podman

### ISSUE THREAD

**Issue by wkrea** [dotnet/core#5224] opened 2020-09-17 21:52 UTC
# Dotnet webapi doesn't compile on fedora 32 podman

When I just try to compile a webapi project created from CLI, i'm getting this message:
> /usr/lib64/dotnet/sdk/3.1.108/NuGet.targets(123,5): error : '32 (Container Image)' is not a valid version string. (Parameter 'value') [/home/dell/Escritorio/webApi/Podman/test/test.csproj]

Be as descriptive as you can with your title.

# General

I'm using podman online for testing purpose. I won't break my personal stable configuration on my OS; it just a simple test!!!, however not works like as [documentation says here!!!](https://docs.microsoft.com/en-us/dotnet/core/install/linux-fedora#supported-distributions)

## My personal enviroment
```bash
[dell@localhost webApi]$ cat /etc/os-release 
NAME=Fedora
VERSION="32 (KDE Plasma)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (KDE Plasma)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="KDE Plasma"
VARIANT_ID=kde
```
## Steps for reproduce the trouble

0. sudo dnf toolbox
1. toolbox create --release f32  --container netcore3.1
2. toolbox list 
3. toolbox -v enter netcore3.1
4. sudo dnf install -y dotnet-sdk-3.1 aspnetcore-runtime-3.1 dotnet-runtime-3.1
5. dotnet --info
6. dotnet new webapi -o hello-world
7. cd hello-world
8. dotnet restore && dotnet run

## Issue (Problem)
```bash
⬢[dell@toolbox test]$ dotnet build
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/lib64/dotnet/sdk/3.1.108/NuGet.targets(123,5): error : '32 (Container Image)' is not a valid version string. (Parameter 'value') [/home/dell/Escritorio/webApi/Podman/test/test.csproj]

Build FAILED.

/usr/lib64/dotnet/sdk/3.1.108/NuGet.targets(123,5): error : '32 (Container Image)' is not a valid version string. (Parameter 'value') [/home/dell/Escritorio/webApi/Podman/test/test.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.40
```

**Comment by omajid** [comment] 2020-09-17 22:32
This isn't a podman issue. It's a issue that happens because msbuild reads environment variables and uses those to initialize msbuild properties. The Fedora toolbox (Silverblue?) happens to define the environment variable `VERSION` with a value of `32 (Container Image)`. That breaks .NET because it doesn't know what to do with a space in this value.

To work around it, you can simply remove that environment variable: `unset VERSION`. Then all `dotnet` commands should work normally.

Duplicate of https://github.com/dotnet/msbuild/issues/5742. The real underlying issue is https://github.com/dotnet/msbuild/issues/2713

**Comment by carlossanlop** [comment] 2020-10-14 23:02
Since @omajid 's answer resolves the issue, I'm closing this.

**Closed by carlossanlop** 2020-10-14 23:02 UTC
