### ISSUE TITLE
when try to install .net framwork on my ubuntu 20.04 i got this error! anyone can help me?

### ISSUE THREAD

**Issue by juliandivakaran** [dotnet/core#6516] opened 2021-07-29 21:54 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: linux

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by safern** [comment] 2021-07-29 21:58
Hello @juliandivagaran12, could you please share the error you got and as much details as possible?

**Comment by juliandivagaran12** [comment] 2021-07-29 22:42
" 'dotnet' is not recognized as an internal or external command"
Sorry, I forgot to mention the problem. Now the problem is solved

**Comment by safern** [comment] 2021-07-29 23:20
Thanks for confirming. Will close the issue.

**Closed by safern** 2021-07-29 23:20 UTC
Labels: area-tutorials

**Comment by juliandivakaran** [comment] 2021-07-29 23:23
Thanks for your support 🤝
