### ISSUE TITLE
Dll missing

### ISSUE THREAD

**Issue by jitendradayma** [dotnet/core#2394] opened 2019-03-07 08:44 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

window 7 , message it shows is "The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix thuis problem." Don't know where to find this /

**Comment by karelz** [comment] 2019-03-19 01:21
Duplicate of https://github.com/dotnet/core-setup/issues/4388

**Closed by karelz** 2019-03-19 01:21 UTC
Labels: area-tutorials
