### ISSUE TITLE
Dotnet with HTTPS runs only as Superuser

### ISSUE THREAD

**Issue by scherenhaenden** [dotnet/core#1969] opened 2018-10-01 11:08 UTC
# Issue Title

Dotnet with HTTPS runs only as Superuser

# General
OS:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

.NetCoreVersion:
2.1 (2.1.402)

Problem:
For some reason, on my laptop, I can run dotnet core using HTTPS only as superuser. Is not the case of my PC. That is ofc an unwanted behavior. 
```
Error:
Using launch settings from /home/edward/Projects/Learning/DotNetCoreWebApi/Web/Properties/launchSettings.json...
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/home/edward/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Application is shutting down...

^CApplication is shutting down...
```

**Comment by scherenhaenden** [comment] 2018-10-01 14:01
I've solved the problem by changing the ownership of the folder ~/.dotnet/ to the user (in this case, to me)

**Comment by scherenhaenden** [comment] 2018-10-02 06:59
as far as i can tell... changing the ownership of  ~/.dotnet/ is not a real solution apparently. Everytime that the folder is generated, it has the root ownership, which is wrong.

**Comment by karelz** [comment] 2018-10-02 23:00
Are you able to reproduce this using official setup on more than 1 machine (e.g. a VM) @scherenhaenden? (trying to avoid weird one machine setup issues)

**Comment by scherenhaenden** [comment] 2018-10-04 07:41
The setup on both machines are the same... but on my laptop i cannot even run dotnet dev-https without root... then that creates credencials, but those have the root-ownership... I've installed my pc and my laptop exactly the same. I do not know what is happening :S

**Comment by davidfowl** [comment] 2018-10-04 07:43
cc @javiercn

**Comment by scherenhaenden** [comment] 2018-10-05 08:10
I've just installed both machines, at the very sametime with everything (really everything) equaly configured... but for some reason the Laptop has this weird issue...  I installed the machines with Kubuntu 18.04 and then i added the list of the packages to DPKG, everything got installed automatically... I've been looking for what could have gone wrong, but till now, i found nothing. 

I can do change the folder by my own. I'll be working today and the weekend, If I find something I'll let you guys know

**Comment by Eilon** [comment] 2018-10-09 17:19
@scherenhaenden , just checking in, did you find any more info on this?

**Comment by scherenhaenden** [comment] 2018-10-11 06:52
@javiercn  noup.

I'm gonna try to picture how I did everything. 

I've installed both machines at the very sametime witht he list (dpkg list) of programs. OS is kubuntu 18.04 + programs. Then i put the source of Mono, I installed mono, monodevelop and so on.

As i wanted to use dotnetcore, on my PC worked like a charm, but on the laptop it didnt work... I ran it as root and it work (ofc, after i saw that it was a permissions issue). 

then i deleted that folder, created that again and it had the root ownership. So i changed by myself... it is working... but if i create it again than belongs to the root. 

I don't know what can be doing that... but even trying to create the certificated, on my PC it works... on my Laptops, works only as root. Therefor, it creates the Folder with root ownership.

**Comment by javiercn** [comment] 2018-10-11 17:33
@scherenhaenden If the folder is being created with root permissions even when you aren't running under root I'm not sure what's going on in that machine, it might be an issue on the machine configuration or a bug on .net core.

I would try the following:
* Install the dotnet sdk on the clean box.
* Before running any dotnet command, check if the folder exists after installation and if it has the right permissions or root permissions.
  * If the folder is present it most likely means that the first run experience ran:
    * If the folder has the wrong permissions: It probably means that the first run experience ran under the wrong user. (This should not happen).
  * If the folder doesn't exist, **make sure you are not running under sudo** and run a dotnet command, like `dotnet new console`. You should see the first run experience displayed on the terminal.  
    * If the folder has the wrong permissions: It probably means that there is a bug in .NET Core setting the permissions for the folder.

**Comment by Eilon** [comment] 2018-10-17 20:54
Closing because we are unable to reproduce this and have not been able to determine the cause of the bug. If you find more info, please let us know. Thank you!

**Closed by Eilon** 2018-10-17 20:54 UTC
Labels: area-aspnet

**Comment by scherenhaenden** [comment] 2018-10-19 09:08
Sorry, I'm right full of things, i did not have time to try that solution. I'll try either today or at monday

**Comment by jbonnett92** [comment] 2023-02-11 19:26
I'm having the same issue:
```
jbonnett@Jamies-MacBook-Pro API.Gateway % dotnet --info
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.7
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.102/

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  7.0.102 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  /Users/jbonnett/Desktop/MicroserviceShopMono/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
  
  
jbonnett@Jamies-MacBook-Pro API.Gateway % dotnet dev-certs https --clean
Cleaning HTTPS development certificates from the machine. This operation might require elevated privileges. If that is the case, a prompt for credentials will be displayed.
HTTPS development certificates successfully removed from the machine.
jbonnett@Jamies-MacBook-Pro API.Gateway % dotnet dev-certs https --trust
Trusting the HTTPS development certificate was requested. If the certificate is not already trusted we will run the following command:
'security add-trusted-cert -p basic -p ssl -k <<login-keychain>> <<certificate>>'
This command might prompt you for your password to install the certificate on the keychain. To undo these changes: 'security remove-trusted-cert <<certificate>>'

Successfully created and trusted a new HTTPS certificate.


jbonnett@Jamies-MacBook-Pro API.Gateway % dotnet dev-certs https --check    
No valid certificate found.
```

**Comment by Eilon** [comment] 2023-02-13 17:57
This issue is several years old now. Can you please log a new issue with details if you're still experiencing a problem?
