### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by Rikisaraiva** [dotnet/core#5961] opened 2021-02-16 19:27 UTC
[Problem](url) encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.Microsoft Windows [Version 10.0.19041.804]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\Utilizador>dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

C:\Users\Utilizador>dotnet new console -o myApp
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

**Comment by mairaw** [comment] 2021-02-16 19:41
Duplicate of #5962

**Closed by mairaw** 2021-02-16 19:41 UTC
