### ISSUE TITLE
Installation Error on Latest Kali Linux build for both .NET Core and SDK

### ISSUE THREAD

**Issue by joshua-darby** [dotnet/core#2665] opened 2019-05-02 08:57 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/runtime-current
Operating System: Linux Debian 9 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

The message below was the error/issue I was running into. I have the latest version of Kali Linux installed and I am also trying to install the SDK file as well for my development.

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 aspnetcore-runtime-2.2 : Depends: dotnet-runtime-2.2 (>= 2.2.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by dagood** [comment] 2019-05-02 15:53
Kali Linux isn't a supported distro, but there are ways to get this to work--see https://github.com/dotnet/core/issues/2392:

> Kali is not an officially supported distro and this is likely a subtle system dependency difference.
> 
> Couple of things you can try that may work.
> 
> 1. install using the tar.gz instead of apt-get,
> 2. install using dotnet-install.sh,
> 3. install using our Snap.
> 
> Option 3 would be my first recommendation to try. Each of these methods are detailed in our [Linux Setup](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md) document.

**Comment by dagood** [comment] 2019-05-02 15:53
Duplicate of #2392

**Closed by dagood** 2019-05-02 15:53 UTC
