### ISSUE TITLE
Tutorial error code 1

### ISSUE THREAD

**Issue by Aidan-Bielenberg** [dotnet/core#6124] opened 2021-04-06 03:31 UTC
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: Linux (ubuntu)

I followed the instructions on the tutorial page and when I get about to running it, it returns this:
```
❯ dotnet watch run
watch : Started
Building...
/snap/dotnet-sdk/116/sdk/5.0.201/Sdks/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.CodeGeneration.targets(142,5): error MSB3231: Unable to remove directory "obj/Debug/net5.0/Razor/". Directory not empty [/home/aidan/myWebApp/myWebApp.csproj]

The build failed. Fix the build errors and run again.

watch : Exited with error code 1
watch : Waiting for a file to change before restarting dotnet...


```

I looked up the error code and it says it is because of a failure due to an application error.

**Comment by Jozkee** [comment] 2021-04-06 20:38
cc @wli3 @dsplaisted

**Comment by mairaw** [comment] 2021-04-06 20:59
I'll close this as a duplicate of #6107 given this is about running dotnet watch run with our activation tutorials

**Closed by mairaw** 2021-04-06 20:59 UTC
Labels: area-tutorials, duplicate
