### ISSUE TITLE
WebRequest is adding a space in Accept header

### ISSUE THREAD

**Issue by ClimberBear** [dotnet/core#3723] opened 2019-10-31 11:59 UTC
# Issue Title

WebRequest is adding a space between elements in Accept header

# General

Using Net Core 3.0.0 in MacOS Mojave

I create an simple web request with the following code

```
HttpWebRequest request = null;
HttpWebResponse response = null;

request = WebRequest.CreateHttp(_contentUrl);
// Automatic redirection enabled
request.AllowAutoRedirect = true;
// acept-encoding: deflate, gzip
request.AutomaticDecompression = DecompressionMethods.Deflate | DecompressionMethods.GZip;
request.Accept = "application/xml;notice=tree;
response = (HttpWebResponse)request.GetResponse();
```

As you see, there is no space between the elements in the accept (application/xml and notice).

But, if you trace the communication, you see that an space has been added before "notice" (and the server I'm using reports an error).

I have found the same bug reported by another developer in stackoverflow (see link https://stackoverflow.com/questions/40152607/httpclient-in-netcore-is-automatically-adding-a-space-in-header)

**Comment by scalablecory** [comment] 2019-10-31 23:10
Duplicate of https://github.com/dotnet/corefx/issues/39260

**Comment by scalablecory** [comment] 2019-10-31 23:12
This should not be a problem with a compliant HTTP server, but we are aware that some server has a problem with this. Please continue discussion at https://github.com/dotnet/corefx/issues/39260. If you can add which server you're using it'd help.

**Closed by scalablecory** 2019-10-31 23:12 UTC
