### ISSUE TITLE
installing Flash drive driver

### ISSUE THREAD

**Issue by siemoppe** [dotnet/core#2578] opened 2019-04-12 12:06 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by karelz** [comment] 2019-04-12 15:01
Unclear what the problem is, or if there is any. Closing. Feel free to reopen with additional details ...

**Closed by karelz** 2019-04-12 15:01 UTC
Labels: area-tutorials, needs more info

**Comment by siemoppe** [comment] 2019-04-14 07:29
> Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
> Operating System: windows
> 
> Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I  have an Acer Aspire E 17 running under Windows 8.1, that cannot run a card reader 3.0. I updated all my drivers, but that did not help.

**Comment by siemoppe** [comment] 2019-04-14 07:32
Oh yes,if I plug the device in, I shows on Windows explorer,but I can't open it.

**Comment by karelz** [comment] 2019-04-14 08:01
How is that related to .NET Core?

**Comment by siemoppe** [comment] 2019-04-14 08:04
don't know what you means(?)

**Comment by karelz** [comment] 2019-04-14 17:20
Same here. What is your question about? This is .NET Core GitHub repo.
If you don't know what .NET Core is, then you are in the wrong place.
