### ISSUE TITLE
Product version and file version are empty when building the project on linux

### ISSUE THREAD

**Issue by magicxor** [dotnet/core#3916] opened 2019-11-26 18:41 UTC
Steps to reproduce:

```
docker run -it --rm mcr.microsoft.com/dotnet/core/sdk:3.0 sh
cd ~
dotnet new console
dotnet publish -c Release -r win-x64 -p:Version=1.2.3.4
```

Then check root.exe (docker cp <container>:/root/bin/Release/netcoreapp3.0/win-x64/publish/root.exe C:\Users\<user>\Downloads\) - it has no version info.

The same for sdk:3.1.100-preview3

**Comment by magicxor** [comment] 2019-11-27 08:36
> Then check root.exe

run in pwsh:

```
PS /root> (Get-Command "/root/bin/Release/netcoreapp3.0/win-x64/publish/root.exe").Version

Major  Minor  Build  Revision
-----  -----  -----  --------
0      0      0      0

PS /root> (Get-Item "/root/bin/Release/netcoreapp3.0/win-x64/publish/root.exe").VersionInfo.FileVersion
PS /root> [System.Diagnostics.FileVersionInfo]::GetVersionInfo("/root/bin/Release/netcoreapp3.0/win-x64/publish/root.exe").FileVersion
PS /root>
```

**Comment by carlossanlop** [comment] 2019-12-12 17:56
@livarcocc @nguerrera is this something in your area?

**Comment by nguerrera** [comment] 2019-12-12 18:11
This is because the code to copy the resources to apphost is not currently portable. I believe there should be a warning about it. I also believe there’s an issue in core-setup tracking making it portable. Let me check...

**Comment by nguerrera** [comment] 2019-12-12 18:15
Duplicate of https://github.com/dotnet/core-setup/issues/8763

**Comment by nguerrera** [comment] 2019-12-12 18:16
This is tracked by https://github.com/dotnet/core-setup/issues/8763, you can upvote or comment there on the importance of this scenario for you.

**Closed by nguerrera** 2019-12-12 18:16 UTC
