### ISSUE TITLE
mcr.microsoft.com/dotnet/core/sdk:3.0.100-disco MSB1025: Microsoft.Build.BackEnd.NodeFailedToLaunchException: The FileName property should not be a directory unless UseShellExecute is set.

### ISSUE THREAD

**Issue by khteh** [dotnet/core#3509] opened 2019-09-30 07:34 UTC
# Issue Title
Use this docker image mcr.microsoft.com/dotnet/core/sdk:3.0.100-disco to build ASP.Net Core 3.0 results in Error MSB1025: Microsoft.Build.BackEnd.NodeFailedToLaunchException: The FileName property should not be a directory unless UseShellExecute is set.

Be as descriptive as you can with your title.
```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
Microsoft.Build.BackEnd.NodeFailedToLaunchException: The FileName property should not be a directory unless UseShellExecute is set.
 ---> System.ComponentModel.Win32Exception (0x80004005): The FileName property should not be a directory unless UseShellExecute is set.
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.LaunchNode(String msbuildLocation, String commandLineArgs)
   --- End of inner exception stack trace ---
   at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.LaunchNode(String msbuildLocation, String commandLineArgs)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.GetNode(String msbuildLocation, String commandLineArgs, Int32 nodeId, INodePacketFactory factory, Int64 hostHandshake, Int64 clientHandshake, NodeContextTerminateDelegate terminateNode)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProc.CreateNode(Int32 nodeId, INodePacketFactory factory, NodeConfiguration configuration)
   at Microsoft.Build.BackEnd.NodeManager.AttemptCreateNode(INodeProvider nodeProvider, NodeConfiguration nodeConfiguration)
   at Microsoft.Build.BackEnd.NodeManager.CreateNode(NodeConfiguration configuration, NodeAffinity nodeAffinity)
   at Microsoft.Build.Execution.BuildManager.PerformSchedulingActions(IEnumerable`1 responses)
   at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
   at Microsoft.Build.Execution.BuildManager.ProcessPacket(Int32 node, INodePacket packet)
   at Microsoft.Build.Execution.BuildManager.<>c__DisplayClass67_0.<Microsoft.Build.BackEnd.INodePacketHandler.PacketReceived>b__0()
   at Microsoft.Build.Execution.BuildManager.ProcessWorkQueue(Action action)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Build.Execution.BuildManager.EndBuild()
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, String[] inputResultsCaches, String outputResultsCache)
```
```
# dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.04
 OS Platform: Linux
 RID:         ubuntu.19.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
# General

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by khteh** [comment] 2019-09-30 08:10
Tried bionic image and get the same error. Linux kernel version in Bionic image:
```
# uname -a
Linux 71345097880e 5.0.0-29-generic #31-Ubuntu SMP Thu Sep 12 13:05:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dasMulli** [comment] 2019-09-30 08:14
Are you using an Ubuntu host? There are select kernel versions that have issues with executable paths in containers causing .NET builds to fail: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1843018

**Comment by khteh** [comment] 2019-09-30 08:17
No, I use containers "mcr.microsoft.com/dotnet/core/sdk:3.0.100-disco" to build on CircleCI.

**Comment by dasMulli** [comment] 2019-09-30 08:18
The issue is not with the container image but the host it runs on.

**Comment by khteh** [comment] 2019-09-30 08:19
Yes, "disco", "bionic" are Ubuntu release code names.

**Comment by dasMulli** [comment] 2019-09-30 08:20
According to reports on the linked ubuntu page the 5.0.0-29-generic kernel is also affected. So it looks like you are blocked until CircleCI updates their hosts 😢

**Comment by saikrishnav** [comment] 2019-10-03 23:14
I can confirm the same issue with dotnet 2.2 version but on Ubuntu 18.04. I am using Github Actions and ubuntu-latest that reproed this.

**Comment by carlossanlop** [comment] 2019-10-31 00:21
@saikrishnav do you have a repro that doesn't depend on CircleCI?
@dasMulli do you know if this is something that the .NET Core team should own?

**Comment by dasMulli** [comment] 2019-10-31 01:14
@carlossanlop no, this is purely a linux kernel bug in ubuntu and needs CI infrastructure providers to update their docker host machines (nothing to do for docker container images either). The previously linked corefx bug has been closed because there is nothing to do on the .NET side as well.
See https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1842382 which other bugs have been marked as a duplicate of and the patch submission for disco https://lists.ubuntu.com/archives/kernel-team/2019-September/103893.html

**Comment by dasMulli** [comment] 2019-10-31 01:15
The workarounds for GH actions or other providers would be to run on windows or mac agents until the CI provider updates their host machines..

**Comment by saikrishnav** [comment] 2019-10-31 02:13
@carlossanlop  - This doesn't repro anymore for me on my github actions. Previously, I reverted to 16.04 to fix original issue, but now 18.04 is working as well. Perhaps the agents were updated.

**Comment by dasMulli** [comment] 2019-10-31 02:19
They apparently were according to https://github.com/actions/virtual-environments/issues/2#issuecomment-541723484

**Comment by carlossanlop** [comment] 2019-10-31 16:54
Thank you @saikrishnav and @dasMulli . Closing the issue based on your replies.

**Closed by carlossanlop** 2019-10-31 16:54 UTC
