### ISSUE TITLE
Application crashes after .NET 6.0.10 was released

### ISSUE THREAD

**Issue by MortenOlsen-DNV** [dotnet/core#7882] opened 2022-10-17 05:58 UTC
### Description

Upgraded VS to 17.3.6, and thereby the newly .NET version 6.0.10.
Our application crashes with no exception thrown.
It happens when we check for existence of SqlCommand.Parameters using the Contains method.
When the collection is empty, it's OK, but when not, it crashes if we check for a parameter that does not exist.

We've nailed it down to our use of the "RuntimeHostConfigurationOption", "System.Globalization.AppLocalIcu"

### Configuration

Info from VS:
Microsoft Visual Studio Professional 2022
Version 17.3.6
VisualStudio.17.Release/17.3.6+32929.385
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.3.376.3011
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.3.376.3011
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.3.376.3011
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Node.js Tools   1.5.40629.1 Commit Hash:3f5cc0329815af3ffb948f08857446d206a9af36
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2232702+e1d654e792aa2fe6646a6935bcca80ff0aff4387
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62207.04100
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.10701.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22363.4+1b94f89d4d1f41f20f9be73c76f4b229d4e49078
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

### Other information

This zip-file contains a very simple console application where the crash is reproduced.
[ConsoleApp1.zip](https://github.com/dotnet/core/files/9797282/ConsoleApp1.zip)

Our workaround is to use the TimeZoneConverter library instead.

**Comment by greenEkatherine** [comment] 2022-10-19 11:23
@ericstj could you please have a look?

**Comment by ericstj** [comment] 2022-10-19 16:23
@MortenOlsen-DNV thank you for the report.

This is indeed a regression in 6.0.10.  @tarekgh identified the cause and has a fix in place in 7.0 that will also be included in the next release of 6.0 (6.0.11). https://github.com/dotnet/runtime/issues/77045

@tarekgh in the meantime is there any workaround that folks can use to unblock themselves?

**Comment by tarekgh** [comment] 2022-10-19 16:52
@MortenOlsen-DNV sorry for the inconvenience. As @ericstj mentioned the fix will be shipped in the next releases of .NET `6.0` and `7.0`. Could you talk more about your scenario? Just to see if we can suggest any workaround till you get the fix. 

- If you are using the ICU app-local feature to allow using ICU on OS's like `Windows Server 2019`, migration to .NET 7.0 would help as you don't have to use ICU app-local on such OS. We have supported loading ICU by default on `Windows Server 2019`. 
- If you still need to continue using ICU app-local: 
    - either you continue using `6.0.9` with publishing the runtime with your app/service to ensure running everywhere with that runtime version. 
    - or you can build the latest ICU bits https://github.com/unicode-org/icu and deploy it with your app/service instead of referencing the ICU NuGet package.
    - or wait a few weeks to get the fix we are going to release.

I am closing this issue as we already have the fix and planning to release it. Feel free to respond with any question and we'll be happy to assist you.

**Closed by tarekgh** 2022-10-19 16:52 UTC
Labels: area-runtime

**Comment by MortenOlsen-DNV** [comment] 2022-10-20 05:40
@tarekgh Thank you for your suggested workarounds. As I mentioned, we have selected to use the TImeZoneConverter library instead of AppLocalIcu as our workaround. That works fine for us.
