### ISSUE TITLE
cannot install dotnet in kali linux.

### ISSUE THREAD

**Issue by brijeshkamani11** [dotnet/core#2917] opened 2019-06-21 05:42 UTC
I run this following command and its givs error...
```
root@localhost:~# sudo apt-get install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.5) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.5) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```
i also tried this which does't work....
`root@localhost:~# sudo apt-get install dotnet-sdk-2.2.5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.2.5
E: Couldn't find any package by glob 'dotnet-sdk-2.2.5'
E: Couldn't find any package by regex 'dotnet-sdk-2.2.5'
`

**Comment by dagood** [comment] 2019-06-21 15:29
Kali isn't a supported distro, there are ways to make it work though: https://github.com/dotnet/core/issues/2392.

**Comment by dagood** [comment] 2019-06-21 15:29
Duplicate of https://github.com/dotnet/core/issues/2392

**Closed by dagood** 2019-06-21 15:29 UTC
