### ISSUE TITLE
CentOS7 yum download wrong package

### ISSUE THREAD

**Issue by b19901018** [dotnet/core#3861] opened 2019-11-20 13:48 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/runtime-current
Operating System: CentOS7

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

### Problem

After I run "yum upgrade" command on my server,the asp.net core program report " 'Microsoft.AspNetCore.App', version '2.2.0' was not found".

I run "dotnet --list-runtimes" command, the result doesn't have "Microsoft.AspNetCore.App 2.2.8" package.

I found yum download the wrong package:

yum install aspnetcore-runtime-2.2
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirror.constant.com
 * epel: ewr.edge.kernel.org
 * extras: centos.mirror.constant.com
 * nux-dextop: mirror.li.nux.ro
 * updates: mirror.atlanticmetro.net
Resolving Dependencies
--> Running transaction check
---> Package aspnetcore-runtime-2.2.x86_64 0:2.2.8-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

 Package                                               Arch                                  Version                                  Repository                                                  Size

Installing:
 aspnetcore-runtime-2.2                                x86_64                                2.2.8-1                                  packages-microsoft-com-prod                                 30 M

Transaction Summary
Install  1 Package

Total download size: 30 M
Installed size: 30 M
Is this ok [y/d/N]: y
**Downloading packages:
aspnetcore-runtime-2.2.8-rh.rhel.7-x64.rpm**                                                                                                                                      |  30 MB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : aspnetcore-runtime-2.2-2.2.8-1.x86_64                                                                                                                                               1/1
  Verifying  : aspnetcore-runtime-2.2-2.2.8-1.x86_64                                                                                                                                               1/1

Installed:
  aspnetcore-runtime-2.2.x86_64 0:2.2.8-1

### Result

Download package is "aspnetcore-runtime-2.2.8-rh.rhel.7-x64.rpm" ,
which install aspnetcore to "/opt/rh/rh-dotnet20/root/usr/lib64/dotnet/shared" not 
"/usr/share/dotnet/shared".

Sorry for my poor English,Thank you!

**Comment by dagood** [comment] 2019-11-20 17:15
Duplicate of https://github.com/dotnet/core/issues/3863, sorry for closing in the wrong direction (this issue was first!) but I saw the other one first and want to avoid notification noise for some folks I already pinged there. Thanks for the report!

**Closed by dagood** 2019-11-20 17:15 UTC
