### ISSUE TITLE
OmniSharp Failed to load project file - .net Ubuntu

### ISSUE THREAD

**Issue by ryanrazer** [dotnet/core#2553] opened 2019-04-09 11:07 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-10/sdk-current
Operating System: Linux Ubuntu 18.10 - x64

My issue:

"**Some projects have trouble loading. Please review the output for more details.**"
Gives me: 
_[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /home/ryan/Programiranje/C#/test/test.csproj
[warn]: OmniSharp.MSBuild.ProjectManager
        Failed to load project file '/home/ryan/Programiranje/C#/test/test.csproj'.
/home/ryan/Programiranje/C#/test/test.csproj(1,1)
Microsoft.Build.Exceptions.InvalidProjectFileException: The SDK 'Microsoft.NET.Sdk' specified could not be found.  /home/ryan/Programiranje/C#/test/test.csproj
.
.
.
[fail]: OmniSharp.MSBuild.ProjectManager
        Attempted to update project that is not loaded: /home/ryan/Programiranje/C#/test/test.csproj_

I've installed SDK .NET package and followed instructions. I also installed C# extension in VSCode. 

Then in initiated project:
```
-> mkdir test
-> cd test
-> dotnet new console
-> dotnet restore 
```
After opening folder i get messages posted above.

Trying to debug ignoring errors i get following message:
    _"WARNING02": "The C# extension was unable to automatically to decode projects in the current",
            "WARNING03": "workspace to create a runnable lanch.json file. A template launch.json file has",
            "WARNING04": "been created as a placeholder.",_

**Additional info:**
```
ryan@ryan-HP-Laptop:~/Programiranje/C#/test$ env | grep PATH
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
WINDOWPATH=2
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ryan/.dotnet/tools

ryan@ryan-HP-Laptop:~/Programiranje/C#/test$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.10
 OS Platform: Linux
 RID:         ubuntu.18.10-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.202/

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.2.202 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by ryanrazer** [comment] 2019-04-09 11:40
On a further note i checked the path of .net and found there is no tools folder as path suggestes:
_PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ryan/.dotnet/tools_

![Screenshot from 2019-04-09 13-39-48](https://user-images.githubusercontent.com/35896955/55797558-0dede200-5acd-11e9-8237-1b057c48466a.png)

**Comment by dasMulli** [comment] 2019-04-09 11:56
Duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/2965 ?

Try the 2.2.105 which should be compatible with the MSBuild / tooling version that OmniSharp uses at the moment.

**Comment by karelz** [comment] 2019-06-05 01:58
Duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/2965

**Comment by karelz** [comment] 2019-06-05 01:58
Thanks @dasMulli for your help!

**Closed by karelz** 2019-06-05 01:58 UTC
