### ISSUE TITLE
.net core does not install on ubuntu

### ISSUE THREAD

**Issue by fkhalikov** [dotnet/core#2937] opened 2019-06-25 14:33 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-2.2.203
Operating System: Linux Ubuntu 18.04 - x64

farid@farid-Virtual-Machine:~$ sudo apt-get install dotnet-sdk-2.2.203=2.2.203-1Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.2.203
E: Couldn't find any package by glob 'dotnet-sdk-2.2.203'
E: Couldn't find any package by regex 'dotnet-sdk-2.2.203'

Installed Ubuntu from Hyper-V quick install.

**Comment by carlossanlop** [comment] 2019-06-25 20:19
Hello @fkhalikov,

According to the instructions in the link you provided, you need to register the Microsoft key and feed, then add the universe repository, install a dependency, and finally updating apt-get, before attempting to install dotnet. Were you able to complete all those tasks?

**Comment by nguerrera** [comment] 2019-06-25 20:22
cc @leecow

**Comment by dagood** [comment] 2019-06-26 02:13
Duplicate of https://github.com/dotnet/core/issues/2936

**Closed by dagood** 2019-06-26 02:13 UTC
