### ISSUE TITLE
I can not download .net onto my macbook

### ISSUE THREAD

**Issue by jams1614** [dotnet/core#4107] opened 2020-01-10 15:39 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

My Macbook will not allow me to install .NET. error msg is:

**dotnet-sdk-3.1.100-osx-x64.pkg”** can’t be opened because Apple cannot check it for malicious software.**

**Comment by scalablecory** [comment] 2020-01-10 16:03
@dagood

**Comment by dagood** [comment] 2020-01-10 16:50
Duplicate of https://github.com/dotnet/core/issues/3943

**Closed by dagood** 2020-01-10 16:50 UTC
Labels: area-setup, area-tutorials
