### ISSUE TITLE
dotnet-sdk-3.1.101-osx-x64.pkg” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by deepuguptacp** [dotnet/core#4138] opened 2020-01-15 18:59 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by dagood** [comment] 2020-01-15 19:14
Duplicate of https://github.com/dotnet/core/issues/3943

**Closed by dagood** 2020-01-15 19:14 UTC
