### ISSUE TITLE
unable to open Pages/index.cshtml in notepad ++

### ISSUE THREAD

**Issue by NitroSisui** [dotnet/core#5541] opened 2020-11-10 12:47 UTC
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

i have saved the code in index in c->
![image](https://user-images.githubusercontent.com/74229185/98675889-da49fc80-2380-11eb-9cb8-c9d954e06b6b.png)

this seems to be no effect on the local host

**Comment by MatthewLymer** [comment] 2020-11-10 15:18
Not really sure what the problem is, aside from the extension should be `cshtml` instead of `html`.

This also doesn't seem to be an issue w/ .NET Core.

**Comment by mairaw** [comment] 2020-11-12 21:34
We're going to try to make improvements to the tutorial to make this a bit more clear. 

But under the myWebApp folder that was created for the app, you should see a sub-directory called Pages and inside there a file called Index.cshtml.

Let me know if that helps!

/cc @danroth27

**Comment by carlossanlop** [comment] 2020-11-25 23:05
The question seems to be answered. Closing now.

**Closed by carlossanlop** 2020-11-25 23:05 UTC
Labels: area-tutorials
