### ISSUE TITLE
Segfault on debian stretch

### ISSUE THREAD

**Issue by dvogel** [dotnet/core#171] opened 2016-06-28 04:57 UTC
On debian stretch, I get a segfault when I try to run `dotnet restore`:

```bash
/tmp/demoapp> ls

/tmp/demoapp> dotnet new
Created new C# project in /tmp/demoapp.

/tmp/demoapp> dotnet restore
log  : Restoring packages for /tmp/demoapp/project.json...
Segmentation fault

/tmp/demoapp> dmesg | tail -n1
[1825177.556685] traps: dotnet[11039] general protection ip:7f36808b9ddd sp:7f35cfbe0b40 error:0 in libcrypto.so.1.0.0[7f3680749000+230000]

/tmp/demoapp> file $(readlink -f $(which dotnet))
/home/dvogel/opt/dotnet/dotnet: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=db256f0ac90cd718d8ec2d157b29437ea8bcb37f, not stripped

/tmp/demoapp> ldd $(which dotnet)
        linux-vdso.so.1 (0x00007ffd53756000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffa4be1e000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffa4bc01000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ffa4b880000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffa4b582000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ffa4b36c000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffa4afc7000)
        /lib64/ld-linux-x86-64.so.2 (0x000055d4bd075000)
```

I get the same result when I put the project directory in my home directory.

**Comment by svick** [comment] 2016-07-01 18:55
The only supported version of Debian is 8.2, so the error might be caused by that.

**Comment by fogzot** [comment] 2016-07-12 08:02
I think the segfault is related to the kernel version: "dotnet new" (when populating the initial cache) and "dotnet restore" segfault on Debian 8.2 if running on newer kernels (tested with 4.5 and 4.6) but work with the original 3.16.

**Comment by blackdwarf** [comment] 2016-07-15 02:07
I believe that this issue is tracked on dotnet/dotnet-docker#61. It has to do with a bug that is present when using 4.6.x kernel. 

I will close this issue as a duplicate of that other one. If you believe this was in error, please reopen this issue on dotnet/cli.

**Closed by blackdwarf** 2016-07-15 02:07 UTC

**Comment by joshfree** [comment] 2016-08-04 17:37
CoreCLR issue is being tracked with: https://github.com/dotnet/coreclr/issues/6604
