### ISSUE TITLE
Linux dotnet publish fails to add metadata to exe

### ISSUE THREAD

**Issue by Fireant456** [dotnet/core#5338] opened 2020-10-13 12:51 UTC
Although my csproj contains the values to add to the file metadata, running dotnet publish on CentOS 7 Linux fails to apply metadata without any errors...
```
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <PackageIcon>favicon.ico</PackageIcon>
    <PackageId>SupportTool</PackageId>
    <Authors>Sonoran Software Systems LLC</Authors>
    <Product>Sonoran Support Tool</Product>
  </PropertyGroup>
```

When I build on Windows 10 it applies the metadata as expected.

On both OSes I use the following publish command...
`dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true`

**Comment by mairaw** [comment] 2020-10-13 23:39
win-x64 is a Windows identifier. If you're running on Linux and you want to specify a Linux runtime, then you should use the appropriate RID listed at https://docs.microsoft.com/dotnet/core/rid-catalog. Probably linux-x64 would be the right one for your machine.

**Comment by Fireant456** [comment] 2020-10-15 22:06
I am running the compiled code on Windows, not Linux. I did attempt to change that option on the compile command but that did not help with the metadata.

**Comment by Fireant456** [comment] 2020-10-16 20:48
@mairaw don't know if you subscribe to the issues you respond in. Pinging so that you can see I responded :)

**Comment by vitek-karas** [comment] 2020-10-23 19:13
This is a known problem - no Win32 resources will be added to the executable if built on non-Windows platform.

**Comment by mairaw** [comment] 2020-10-23 19:24
@vitek-karas is this by design or is there another issue capturing that?

**Comment by vitek-karas** [comment] 2020-10-23 20:43
There is an issue - I just can't find it right now :sad:

**Comment by vitek-karas** [comment] 2020-10-23 20:45
Finally found it - at least one (there are many copies of this, I'm trying to consolidate): https://github.com/dotnet/runtime/issues/3828

**Comment by mairaw** [comment] 2020-10-23 21:21
Thanks @vitek-karas. So closing this one as a duplicate.

**Closed by mairaw** 2020-10-23 21:21 UTC

**Comment by fabiang** [comment] 2023-05-17 10:32
For those reviewing the upstream issue: I've also have this problem when building inside a Windows Container (namely `mcr.microsoft.com/dotnet/sdk:6.0`) on Windows Server 2019.
