### ISSUE TITLE
Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/u/unixodbc/libodbc1_2.3.7_amd64.deb  404  Not Found [IP: 104.214.230.139 443]

### ISSUE THREAD

**Issue by rdzotz** [dotnet/core#6387] opened 2021-06-17 10:24 UTC
### Description

Failed to fetch  https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/u/unixodbc/libodbc1_2.3.7_amd64.deb 

Occurs after installing this package and running apt-get update.
https://packages.microsoft.com/config/ubuntu/14.04/packages-microsoft-prod.deb

Started getting this error when building a docker file in the last 24hours. Looks like this has happened before [https://github.com/dotnet/core/issues/2608](https://github.com/dotnet/core/issues/2608)

```
Err:1 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 libodbc1 amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]
Err:2 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 odbcinst amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]
Err:3 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 odbcinst1debian2 amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]
Err:4 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 unixodbc amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]
Err:5 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 msodbcsql17 amd64 17.7.2.1-1
  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/u/unixodbc/libodbc1_2.3.7_amd64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/u/unixodbc/odbcinst_2.3.7_amd64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/u/unixodbc/odbcinst1debian2_2.3.7_amd64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/u/unixodbc/unixodbc_2.3.7_amd64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/m/msodbcsql17/msodbcsql17_17.7.2.1-1_amd64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get update &&     apt-get install -y curl &&     curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - &&     curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list &&     apt-get update &&     ACCEPT_EULA=Y apt-get install -y msodbcsql17' returned a non-zero code: 100
```

**Comment by th0mk** [comment] 2021-06-17 10:58
Dupe of #6381

**Comment by michaelgsharp** [comment] 2021-06-17 17:23
This issue is being tracked with #6381. It should be fixed now, but some are still seeing slowdowns since everyone is trying to download it. Closing this issue.

**Closed by michaelgsharp** 2021-06-17 17:23 UTC
