### ISSUE TITLE
Unable to install dotnet-sdk-2.2

### ISSUE THREAD

**Issue by adeel-raza-azeemi** [dotnet/core#2654] opened 2019-04-29 06:55 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 19.04 - x64

sudo apt install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.4) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by Houuse** [comment] 2019-04-29 08:18
duplicate please take a look here [2526](https://github.com/dotnet/core/issues/2526)

**Comment by karelz** [comment] 2019-04-29 16:08
Duplicate of #2526

**Closed by karelz** 2019-04-29 16:08 UTC
Labels: area-tutorials

**Comment by SteveTeece** [comment] 2019-08-02 09:14
I'm getting
```

ubuntu@ubuntu:~$ sudo apt install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.2
E: Couldn't find any package by glob 'dotnet-sdk-2.2'
E: Couldn't find any package by regex 'dotnet-sdk-2.2'
```
