### ISSUE TITLE
Problem install on Centos 7

### ISSUE THREAD

**Issue by UDK** [dotnet/core#3865] opened 2019-11-20 16:13 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/sdk-3.0.101
Operating System: 

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Problem:
=====================================================================================================================
 Package                                Arch           Version             Repository                           Size
=====================================================================================================================
Installing:
 dotnet-sdk-3.0                         x86_64         3.0.101-1           packages-microsoft-com-prod          64 M
Installing for dependencies:
 aspnetcore-runtime-3.0                 x86_64         3.0.1-1             packages-microsoft-com-prod         7.5 M
 aspnetcore-targeting-pack-3.0          x86_64         3.0.1-1             packages-microsoft-com-prod         1.4 M
 dotnet-apphost-pack-3.0                x86_64         3.0.1-1             packages-microsoft-com-prod          66 k
 dotnet-host                            x86_64         3.0.1-1             packages-microsoft-com-prod          39 k
 dotnet-hostfxr-3.0                     x86_64         3.0.1-1             packages-microsoft-com-prod         147 k
 dotnet-runtime-3.0                     x86_64         3.0.1-1             packages-microsoft-com-prod          29 M
 dotnet-runtime-deps-3.0                x86_64         3.0.1-1             packages-microsoft-com-prod         2.8 k
 dotnet-targeting-pack-3.0              x86_64         3.0.1-1             packages-microsoft-com-prod         3.4 M
 libicu                                 x86_64         50.2-3.el7          base                                6.9 M
 netstandard-targeting-pack-2.1         x86_64         2.1.0-1             packages-microsoft-com-prod         2.1 M

Transaction Summary
=====================================================================================================================
Install  1 Package (+10 Dependent packages)

Total size: 114 M
Total download size: 2.1 M
Installed size: 132 M
Is this ok [y/d/N]: y
Downloading packages:
netstandard-targeting-pack-2.1 FAILED
https://packages.microsoft.com/centos/7/prod/netstandard-targeting-pack-2.1.0-x64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=packages-microsoft-com-prod clean metadata
Trying other mirror.

Error downloading packages:
  netstandard-targeting-pack-2.1-2.1.0-1.x86_64: [Errno 256] No more mirrors to try.

before that I havenstall required dependencies - sudo yum install dotnet-sdk-3.0 
Maybe I have not yet installed any dependencies?

**Comment by craigjbass** [comment] 2019-11-20 16:23
I can confirm I am also experiencing this

**Comment by craigjbass** [comment] 2019-11-20 16:24
```
> $ sudo dnf reinstall netstandard-targeting-pack-2.1                                           ⬡ 6.3.0 
Last metadata expiration check: 0:00:25 ago on Wed 20 Nov 2019 16:21:40 GMT.
Dependencies resolved.
=========================================================================================================
 Package                              Arch         Version       Repository                         Size
=========================================================================================================
Reinstalling:
 netstandard-targeting-pack-2.1       x86_64       2.1.0-1       packages-microsoft-com-prod       2.1 M

Transaction Summary
=========================================================================================================

Total download size: 2.1 M
Is this ok [y/N]: y
Downloading Packages:
[MIRROR] netstandard-targeting-pack-2.1.0-x64.rpm: Downloading successful, but checksum doesn't match. Calculated: 45e199caf1151a750d11d9c5c7669d6e23d8dbb33da54d1d90bde55745996480(sha256)  Expected: fa194a8c12913dcec85c8d24bfc91686a7b93128b4c05346df16e2c641e2ba41(sha256) 
[FAILED] netstandard-targeting-pack-2.1.0-x64.rpm: No more mirrors to try - All mirrors were already tried without success

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Cannot download netstandard-targeting-pack-2.1.0-x64.rpm: All mirrors were tried
```

**Comment by craigjbass** [comment] 2019-11-20 16:25
dupe of #3853

**Closed** 2019-11-20 16:30 UTC
