### ISSUE TITLE
No .deb for Disco Dingo

### ISSUE THREAD

**Issue by lapisdecor** [dotnet/core#2738] opened 2019-05-16 19:58 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Ubuntu 19.04
When trying to install  .net sdk, couldn't find a package for ubuntu 19.04

**Comment by dagood** [comment] 2019-05-17 20:59
The Debian package does exist, but the site lacks documentation for it at the moment. If you use the 18.10 instructions but replace 18.10 with 19.04, it should work for you.

**Comment by dagood** [comment] 2019-05-17 20:59
Duplicate of https://github.com/dotnet/core/issues/2728

**Closed by dagood** 2019-05-17 20:59 UTC
