### ISSUE TITLE
impossible to install not net core sdk 2.2 on linux ubuntu 19.04

### ISSUE THREAD

**Issue by paillave** [dotnet/core#2782] opened 2019-05-23 18:17 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current
Operating System: Linux Ubuntu 19.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I run into an issue trying to install .net core sdk 2.2 on linux ubuntu 19.04. 
I followed exactly what is documented in this page:
https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current

here is the full result of what happened:
```
stephane@stephane-VC60:~$ wget -q https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb
stephane@stephane-VC60:~$ sudo dpkg -i packages-microsoft-prod.deb
(Reading database ... 177139 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-ubuntu18.10.2) over (1.0-ubuntu18.10.2) ...
Setting up packages-microsoft-prod (1.0-ubuntu18.10.2) ...
stephane@stephane-VC60:~$ sudo apt-get install apt-transport-https
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be upgraded:
  apt-transport-https
1 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
Need to get 1,692 B of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://lu.archive.ubuntu.com/ubuntu disco-updates/universe amd64 apt-transport-https all 1.8.1 [1,692 B]
Fetched 1,692 B in 0s (30.8 kB/s)               
(Reading database ... 177139 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_1.8.1_all.deb ...
Unpacking apt-transport-https (1.8.1) over (1.8.0) ...
Setting up apt-transport-https (1.8.1) ...
stephane@stephane-VC60:~$ sudo apt-get update
Hit:1 http://lu.archive.ubuntu.com/ubuntu disco InRelease
Hit:2 http://lu.archive.ubuntu.com/ubuntu disco-updates InRelease
Hit:3 http://lu.archive.ubuntu.com/ubuntu disco-backports InRelease            
Ign:4 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:5 http://dl.google.com/linux/chrome/deb stable Release                     
Get:6 http://security.ubuntu.com/ubuntu disco-security InRelease [97.5 kB]     
Fetched 97.5 kB in 1s (161 kB/s)    
Reading package lists... Done
stephane@stephane-VC60:~$ sudo apt-get install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.2
E: Couldn't find any package by glob 'dotnet-sdk-2.2'
E: Couldn't find any package by regex 'dotnet-sdk-2.2'

```
To be sure that  I started from something "clean", I ran the following before trying again:

```
sudo apt-get install -y gpg
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
wget -q https://packages.microsoft.com/config/ubuntu/18.04/prod.list
sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
sudo apt-get install -y apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-2.2

```
But I get exactly the same result once I run the standard installation procedure again.

**Comment by paillave** [comment] 2019-05-23 19:32
I finally got it installed running the following:
```
sudo apt-get install -y gpg
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
wget -q https://packages.microsoft.com/config/ubuntu/19.04/prod.list
sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
sudo apt-get install -y apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-2.2
```

Still, it is not normal that the normal installation procedure doesn't work properly.

**Comment by karelz** [comment] 2019-05-25 19:13
Duplicate of #2526

**Comment by karelz** [comment] 2019-05-25 19:14
@dagood @leecow do we have some how-to for Ubuntu 19.04? Maybe entry in the issue template to avoid all these duplicates?

**Comment by dagood** [comment] 2019-05-26 06:42
This isn't quite a duplicate. @paillave, I see `18.04` in your first attempt to apply a workaround, were you applying the workaround from https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current?

If so, that's the right thing to try, and splicing in 19.04 like it looks like you did is the right fix. The 19.04 install page *should* have this workaround, but it's missing right now. There's an internal documentation repo PR waiting to merge that will add it in.

It's not ideal that this install problem still happens, but at least the workaround will be discoverable as soon as that merges. I'm reopening this issue to track when the change should be visible.

(The root of the problem, I believe, is a bug in an old version of the `packages-microsoft-prod.deb` package that messes up the install process when upgrading from it. I haven't been able to get more detail yet from the repo admins who produce that package.)

**Comment by dagood** [comment] 2019-05-28 16:59
The workaround is now displayed on the 19.04 package manager install page.

**Closed by dagood** 2019-05-28 16:59 UTC
