### ISSUE TITLE
dotnet sdk cannot be opened

### ISSUE THREAD

**Issue by IanCapo** [dotnet/core#4086] opened 2020-01-07 13:04 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos (catalina)

Trying to install the package I ran into this error:

“dotnet-sdk-3.1.100-osx-x64.pkg” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.

**Comment by scalablecory** [comment] 2020-01-07 16:30
@dagood

**Comment by dagood** [comment] 2020-01-07 17:00
This is documented as a known issue at https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-known-issues.md#net-core-installation-on-macos-catalina-1015, with a workaround. Also, https://github.com/dotnet/core/issues/3943.

**Comment by dagood** [comment] 2020-01-07 17:00
Duplicate of https://github.com/dotnet/core/issues/3943

**Closed by dagood** 2020-01-07 17:00 UTC
Labels: area-setup
