### ISSUE TITLE
MacOS Package not Signed 

### ISSUE THREAD

**Issue by jtsom** [dotnet/core#4234] opened 2020-02-06 22:31 UTC
# Issue Title

MacOS Package not Signed 

# General

When trying to install the latest version of the Dotnet SDK I'm getting a Gatekeeper error:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/13488/73984331-6f0d5e80-4906-11ea-8945-88bfac5d3cfb.png">

Right-clicking and choosing open, then clicking the Open button will let the install proceed, but it looks like the package is not signed correctly.

**Comment by dagood** [comment] 2020-02-13 16:12
Thanks for taking the time to file the issue. We are already aware, though, and it's filed as a known issue for 3.1 here: https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-known-issues.md#net-core-installation-on-macos-catalina-1015

**Comment by dagood** [comment] 2020-02-13 16:12
Duplicate of https://github.com/dotnet/core/issues/3943

**Closed by dagood** 2020-02-13 16:12 UTC
