### ISSUE TITLE
Unstable performance calling SOAP service

### ISSUE THREAD

**Issue by freworr** [dotnet/core#2078] opened 2018-11-27 11:37 UTC
# WSDL added as a connected service

We have ported an ASP .NET MVC 5 API to a .NET Core 2.1 API and we are experiencing some performance issues with the generated proxy class of a WSDL added as a connected service (added as a service reference in ASP .NET). We are running the APIs side-by-side until we have ported all of our clients to the new API. Both APIs are running as an app service on Azure. The only difference is that the generated proxy class in the .NET core API uses async calls and the MVC 5 API uses sync calls on the SOAP client.   

# Metrics
The snippets below show dependency call average duration in ms. The snapshot is taken from within a 24 hour period.

## .NET Core 2.1 
![sanntidapi_performance](https://user-images.githubusercontent.com/39900835/49072301-3832b780-f230-11e8-8da6-1a10548b617b.png)

## ASP .NET MVC 5
![sanntidappservice_performance](https://user-images.githubusercontent.com/39900835/49072315-3c5ed500-f230-11e8-9e87-d257021ddceb.png)

In comparison, the performance is way slower in the .NET Core API to the ASP .NET API which does not meet our performance requirements. Furthermore, we are seeing more connection timeouts in .NET Core compared to ASP .NET.  

# Sample code
The following is the code used in the new .NET core API:
```csharp
public static async Task<string> GetDepartures(string id)
{
    var client = new UserServicesSoapClient(CreateBinding(), new EndpointAddress(Constants.Urls.RealTimeUrl));
    var result = await client.getUserRealTimeForecastExByStopAsync(Authentication, HandShake, id, NForecast, NHours);
    var json = result.Body.getUserRealTimeForecastExByStopResult;
    await client.CloseAsync();
    return json;
}

private static BasicHttpBinding CreateBinding()
{
    return new BasicHttpBinding
    {
        MaxReceivedMessageSize = Constants.SoapClient.MaxReceivedMessageSize,
        MaxBufferSize = Constants.SoapClient.MaxBufferSize,
        SendTimeout = TimeSpan.FromSeconds(Constants.SoapClient.SchedulerTimeout),
        ReceiveTimeout = TimeSpan.FromSeconds(Constants.SoapClient.SchedulerTimeout),
        Security =
        {
            Mode = BasicHttpSecurityMode.Transport
        },
        ReaderQuotas = new XmlDictionaryReaderQuotas
        {
            MaxStringContentLength = Constants.SoapClient.MaxStringContentLength
        }
    };
}
```
Furthermore, this is how it is done in the ASP .NET API: 
```csharp
var realTimeClient = GetRealTimeClient();     
var json = realTimeClient.getUserRealTimeForecastExByStop(Authentication, HandShake, request.StopCode,
                                                        MAX_NUMBER_OF_REAL_TIME_RESULTS, NUMBER_OF_FORECASTING_HOURS);

protected UserServicesSoapClient GetRealTimeClient()
{
    var binding = CreateBinding();
    var endpoint = new EndpointAddress(REAL_TIME_SERVER_URL);
    return new UserServicesSoapClient(binding, endpoint);
}

private BasicHttpBinding CreateBinding()
{
    var binding = new BasicHttpBinding
    {
        MaxReceivedMessageSize = 20000000,
        MaxBufferSize = 20000000,
        SendTimeout = TimeSpan.FromSeconds(TimeoutSeconds),
        ReceiveTimeout = TimeSpan.FromSeconds(TimeoutSeconds),
        ReaderQuotas = new XmlDictionaryReaderQuotas
            {
                MaxStringContentLength = 2000000
            },
        Security = {Mode = BasicHttpSecurityMode.Transport}
    };
    return binding;
}
```
We have already tried to use the same connection pool for all dependency requests, but this yields slower performance and hence we ended up using scoped SOAP client.

How can we use the SOAP client to make it perform better in the .NET Core API? Is it possible for a future release of .NET Core to be able to generate both async and sync calls?

**Comment by karelz** [comment] 2018-11-27 18:17
@Lxiamail @mconnew can you please help route it to the right place?

**Comment by Lxiamail** [comment] 2018-11-27 22:06
@freworr This issue seems similar as https://github.com/dotnet/wcf/issues/3272. Can you try putting AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false); at the start. That way we can narrow down if this is a problem with the new SocketsHttpHandler implementation or if it's an issue somewhere in WCF.

**Comment by freworr** [comment] 2018-11-28 07:07
Thank you for the reply. It looks promising after load testing. We will try it out for a day or two and see if the performance will improve. @Lxiamail We will let you know if the switch improved the performance.

**Comment by karelz** [comment] 2018-11-29 19:36
Duplicate of https://github.com/dotnet/wcf/issues/3272

**Closed by karelz** 2018-11-29 19:36 UTC

**Comment by marquesoftware** [comment] 2018-12-10 16:37
Did you notice any significant improvement when disabling SocketsHttpHandler? Because I did tests enabling and disabling and did not get better.
