### ISSUE TITLE
dotnet-sdk.2.2 package not found

### ISSUE THREAD

**Issue by bradygaster** [dotnet/core#2646] opened 2019-04-27 01:40 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current
Operating System: Linux Debian 9 - x64

I tried the commands from the Debian distro on my Raspberry PI tonight and got errors saying the dotnet-sdk-2.2 package couldn't be found. Specific errors below:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.2
E: Couldn't find any package by glob 'dotnet-sdk-2.2'
E: Couldn't find any package by regex 'dotnet-sdk-2.2'
```

**Comment by karelz** [comment] 2019-04-27 18:39
Isn't Raspberry PI arm? Using x64 won't work ...
cc @dagood @richlander

**Comment by dagood** [comment] 2019-04-28 03:09
That's correct, at the moment you have to install using a "Binaries" link.

**Comment by dagood** [comment] 2019-04-28 03:09
Duplicate of #2622

**Closed by dagood** 2019-04-28 03:09 UTC
