### ISSUE TITLE
arm64  Running slowly

### ISSUE THREAD

**Issue by shouhujishu** [dotnet/core#2205] opened 2019-01-07 10:34 UTC
root@aml:# cd app
root@aml:/app# dotnet run
Hello World!

Get output after 7 seconds

Linux version 4.18.7-aml-s9xxx (root@aml) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)) #1 SMP PREEMPT Thu Jan 3 06:41:31 UTC 2019

RAM:2GB
ROM：KLM8G1GEME，8GB eMMC
CPU:Amlogic S905，ARM Cortex-A53

**Comment by karelz** [comment] 2019-01-08 04:06
Duplicate of #2122

**Closed by karelz** 2019-01-08 04:06 UTC
