### ISSUE TITLE
[apt] update:  File has unexpected size (66537 != 66619)

### ISSUE THREAD

**Issue by D3m0nKingx** [dotnet/core#3222] opened 2019-08-21 04:03 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current
Operating System: Linux Ubuntu 18.04 - x64

Upon running `apt update` the following err! occured:
![Screenshot from 2019-08-20 23-58-57](https://user-images.githubusercontent.com/18432686/63401856-e24a0500-c3a6-11e9-8a28-fe0eca40cd69.png)

**Comment by dagood** [comment] 2019-08-21 04:33
Duplicate of https://github.com/dotnet/core/issues/3221

**Closed by dagood** 2019-08-21 04:33 UTC
