### ISSUE TITLE
dotnet tutorial problem

### ISSUE THREAD

**Issue by Kirbybu1** [dotnet/core#2376] opened 2019-03-05 15:54 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: windows 7

Error message: "The program can't start becauseapi-ms-win-crt-runtime-|1-1-1.dll is missing from your computer.  Try reinstalling the program to fix this problem"

**Comment by karelz** [comment] 2019-03-05 16:04
@dagood @leecow is it a known issue?

**Comment by dagood** [comment] 2019-03-05 16:39
This is interesting. For `api-ms-win-crt-runtime-l1-1-0.dll`, this issue is known to be missing prereqs: https://github.com/dotnet/core-setup/issues/4388. I can't find any record of `api-ms-win-crt-runtime-|1-1-1.dll`.

@Kirbybu1 can you please:
* Check if you made a typo, if you typed this up manually? The `|` rather than `l` makes me think that's possible.
* Make sure you have the updates listed in the note at https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x#net-core-dependencies ?

**Comment by Kirbybu1** [comment] 2019-03-05 17:34
![dotneterror](https://user-images.githubusercontent.com/39200622/53824872-f4dc9900-3f42-11e9-8bdb-28a9dcb5b013.jpg)

Checking the updates now.

**Comment by dagood** [comment] 2019-03-05 18:13
Thanks! That is the 1-1-0 version with the known fix. I'm going to go ahead and close this issue because the cause is well-known, but please do let me know if following those instructions doesn't work.

To pass along a tip, pressing Control-C while a dialog box is focused should copy all the text inside it. Then you can paste it somewhere, rather than typing it up manually. It's really too bad Windows doesn't have a more obvious way to do this. 😄

**Closed by dagood** 2019-03-05 18:13 UTC
Labels: area-tutorials, needs more info
