### ISSUE TITLE
Unable to find a stable package System.Data.SqlClient with version (>= 4.6.1)

### ISSUE THREAD

**Issue by ufalak** [dotnet/core#2575] opened 2019-04-11 12:17 UTC
Unable to find a stable package System.Data.SqlClient with version (>= 4.6.1)

When i tried to pull the package i get the error 
Unable to find a stable package System.Data.SqlClient with version (>= 4.6.1)

**Comment by dnickless** [comment] 2019-04-12 07:30
I am seeing the same error message when trying to install v2.1.0 of the Microsoft.Windows.Compatibility NuGet into a .NET Standard 2.0 project.

**Comment by Danie-Brink** [comment] 2019-04-15 06:36
Same problem here on .NET Core 2.1

**Comment by dlutz52** [comment] 2019-04-15 15:30
Same problem here using .NET Core 2.2

**Comment by karelz** [comment] 2019-04-15 16:11
What are the minimal steps to reproduce? (some HelloWorld-style repro)

**Comment by dlutz52** [comment] 2019-04-15 16:22
Create .NET Core console app for .NET Core 2.2 using VS 2017 15.9.9
Use Package Manager console:
     Install-Package Microsoft.Windows.Compatibility -Version 2.1.0
Get error:
Install-Package : NU1103: Unable to find a stable package System.Data.SqlClient with version (>= 4.6.1)
  - Found 32 version(s) in nuget.org [ Nearest version: 4.7.0-preview.18571.3 ]
  - Found 3 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 4.3.1 ]
At line:1 char:1
+ Install-Package Microsoft.Windows.Compatibility -Version 2.1.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'ConsoleApp1'.
At line:1 char:1
+ Install-Package Microsoft.Windows.Compatibility -Version 2.1.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
![image](https://user-images.githubusercontent.com/10506538/56148706-b255a580-5f5f-11e9-8699-c99ff019bfad.png)

**Comment by dlutz52** [comment] 2019-04-15 16:27
Plus this, if it is of any help at all:
![image](https://user-images.githubusercontent.com/10506538/56149143-bc2bd880-5f60-11e9-93f4-54a7694b96b2.png)

**Comment by abelykh0** [comment] 2019-04-15 17:49
Same issue exists in Visual Studio 2019 16.0.1, .Net Core SDK 2.2.202 (x64)

**Comment by grantwinney** [comment] 2019-04-16 01:10
Most likely related: https://github.com/dotnet/corefx/issues/36902

**Comment by karelz** [comment] 2019-05-17 21:53
@joperezr @ericstj is it a known problem?
cc @divega

**Comment by joperezr** [comment] 2019-05-17 21:59
System.Data.SqlClient version 4.6.1 was shipped to NuGet 3 days ago. This probably means that somebody that depended on this package internally shipped to NuGet before it was supposed to, but I believe that this problem shouldn't be happening now.

**Comment by ericstj** [comment] 2019-05-17 22:05
Yeah, dup of https://github.com/dotnet/corefx/issues/36902.

**Comment by karelz** [comment] 2019-05-17 22:26
Duplicate of https://github.com/dotnet/corefx/issues/36902

**Closed by karelz** 2019-05-17 22:26 UTC
