### ISSUE TITLE
Api Call Not Working

### ISSUE THREAD

**Issue by dexterhussain** [dotnet/core#1138] opened 2017-12-08 10:19 UTC
**Development Machines**
Windows
**Production Machines** 
Ubuntu/Windows

**Reproduction link**

https://github.com/hmuhdkamran/Cms
Live Website Working at
sqanetcore.thetowertech.com

**Steps to reproduce**

Just open the website and open chrome console window it will start showing error.
What is expected?

It should run properly and start working as it is working in development server.
**What is actually happening?**

I am making a website on Vue using aspnetcore 2.0 which i am using development there is no bug no issues it is working perfectly fine when I am rolling it out to production it is giving me error
http://192.168.7.14/api/culture/SupportedCultures 500 (Internal Server Error)
192.168.7.14/:1 Uncaught (in promise)
{messageTypeId: "Error", text: "Request failed with status code 500", title: "Code:undefined. Error"}
messageTypeId
:
"Error"
text
:
"Request failed with status code 500"
title
:
"Code:undefined. Error"
proto
:
Object

**Comment by richlander** [comment] 2017-12-08 14:53
I read that there is a problem with your service. An HTTP 500 error is highly suggestive that the focus should be on the service. The act that you can reproduce the same service error outside the website suggests that the issue has nothing to do with website. I'd focus on your service. Have you tried to debug your service to better understand what is causing it to return HTTP 500?

**Comment by hmuhdkamran** [comment] 2017-12-09 17:37
If the issue is in service then it should be in developer mode also, but in developer mode the application runs smoothly, while after publishing the application produces service error.
After production the service cant be called from any rest client, you can even check [https://github.com/hmuhdkamran/Cms](url)

**Comment by Petermarcu** [comment] 2017-12-09 19:52
@Eilon @davidfowl @muratg

**Comment by dexterhussain** [comment] 2017-12-11 07:02
We as a team need real support here. I and @hmuhdkamran work as a team. We are totally stuck here. @Eilon @davidfowl  @muratg  @Petermarcu @richlander @AArnott

**Comment by Petermarcu** [comment] 2017-12-11 17:16
You will likely get more help in the aspnet/home repo. I'm going to help you move this there.

**Comment by Petermarcu** [comment] 2017-12-11 17:18
opened this issue to track this in a place where more eyes with ASP.NET expertise are around. https://github.com/aspnet/Home/issues/2304

**Comment by muratg** [comment] 2017-12-11 18:34
@dexterhussain @hmuhdkamran It's not guaranteed that that an app running in developer mode would run the same way in production mode. For example, in your example, you're running some additional code in your Startup.cs in dev mode only.  Have you tried running the app locally, in production mode?   At the very least, if you get the error, you'd be viewing it from a developer exception page.

**Comment by muratg** [comment] 2017-12-11 18:35
You guys can also request official support from https://connect.microsoft.com/

**Comment by richlander** [comment] 2017-12-11 22:15
I should have asked earlier ... are you trying to access a 192. IP address in production? If so, that could certainly be the reason why the service call fails.

**Comment by dexterhussain** [comment] 2017-12-12 05:32
@richlander  192 ip is the ip of the machine on which it is running locally

**Comment by Petermarcu** [comment] 2017-12-12 16:43
Meant to close this issue here to it can be tracked by aspnet/Home#2304

**Closed by Petermarcu** 2017-12-12 16:43 UTC
