### ISSUE TITLE
Unable to install .NET Core 3.1 SDK into Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by AllwinSamuelJeba** [dotnet/core#4618] opened 2020-04-25 14:33 UTC
# Issue Title

Unable to install the .NET Core 3.1 SDK into Ubuntu 20.04

cooljeba@Blue:~/Projects/ConsoleTest$ sudo apt-get install dotnet-sdk-3.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: **Unable to locate package dotnet-sdk-3.1**
E: Couldn't find any package by glob 'dotnet-sdk-3.1'
E: Couldn't find any package by regex 'dotnet-sdk-3.1'

# General

Tried all the steps mentioned in the page https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-2004
including Troubleshoot the package manager 

get the following error.

E: Unable to locate package dotnet-sdk-3.1
E: Couldn't find any package by glob 'dotnet-sdk-3.1'
E: Couldn't find any package by regex 'dotnet-sdk-3.1'

**Comment by omajid** [comment] 2020-04-25 16:32
Duplicate of #4360

**Closed** 2020-04-25 17:38 UTC
Labels: duplicate
