### ISSUE TITLE
Package rh-dotnet30-dotnet-runtime-3.0 seems to be missing System.Drawing.Common.dll

### ISSUE THREAD

**Issue by davidgemel** [dotnet/core#3734] opened 2019-11-01 23:13 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel/runtime-current
Operating System: Linux RHEL 7 - x64

When installing rh-dotnet30-dotnet-runtime-3.0 as suggested here:
https://dotnet.microsoft.com/download/linux-package-manager/rhel/runtime-current

The folder:  /opt/rh/rh-dotnet30/root/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App/3.0.0
is missing System.Drawing.Common.dll

Which is part of the AspNetCore binaries here:
https://dotnet.microsoft.com/download/dotnet-core/3.0

**Comment by tmds** [comment] 2019-11-04 14:23
> The folder: /opt/rh/rh-dotnet30/root/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App/3.0.0
is missing System.Drawing.Common.dll

There is a `System.Drawing.dll` at `shared/Microsoft.NETCore.App/3.0.0/System.Drawing.dll`. This is part of the regular .NET Core runtime, not ASP.NET Core.
What are you trying that uses System.Drawing.**Common**.dll?

**Comment by davidgemel** [comment] 2019-11-04 15:06
I am not concerned with System.Drawing.dll We are using this assembly (System.Drawing.Common.dll) to edit png images.

When I install rh-dotnet30 it also installs the Microsoft.AspNetCore.App.  Below is the list runtimes command I run after I installed.

![image](https://user-images.githubusercontent.com/45462607/68131219-a96ff580-feea-11e9-801e-0b4ba9bb64b0.png)


![image](https://user-images.githubusercontent.com/45462607/68130794-fdc6a580-fee9-11e9-8467-19f5b5bc073a.png)

It is part of ASP.NET Core Binaries x64 binaries in the image above located:
aspnetcore-runtime-3.0.0-linux-x64 \shared\Microsoft.AspNetCore.App\3.0.0\System.Drawing.Common.dll

However the rh-dotnet30 seems to only be partially installing the Microsoft.AspNetCore.App runtimes.

Thanks for the help.

**Comment by tmds** [comment] 2019-11-04 15:16
> It is part of ASP.NET Core Binaries x64 binaries in the image above located:
aspnetcore-runtime-3.0.0-linux-x64 \shared\Microsoft.AspNetCore.App\3.0.0\System.Drawing.Common.dll

@dagood @crummel this is a difference between source-build and Microsoft build. I'm also surprised ASP.NET Core would pack a System.Drawing.*.dll, and not get it from corefx shared framework.

@davidgemel what doesn't work for you because this dll is missing? Is it the editing of the pngs? Or does that work? I'd expect some System.Drawing things to not work on RHEL7 because there is no native libgdiplus library available.

**Comment by dagood** [comment] 2019-11-04 15:36
> I'm also surprised ASP.NET Core would pack a System.Drawing.*.dll, and not get it from corefx shared framework.

What's included in the NETCoreApp shared framework vs. shipped as platform extension packages is determined by CoreFX, I'm not sure where to find what the decisions are. Hearing that a `.Common` extra assembly is pulled into ASP.NET's sharedfx from a CoreFX platform extension package doesn't seem strange to me though. (The name "Common" sounds weird in this context, but I don't know the reasoning behind that name either.)

I don't think there's any good reason for source-build to be different, somehow [the dependency](https://github.com/aspnet/AspNetCore/blob/aee5e4080331553ea9dfb7fb388b6d72f715bf6a/eng/SharedFramework.External.props#L69) may have broken?

**Comment by davidgemel** [comment] 2019-11-04 16:13
We are getting error that the assembly is missing.  Right now I am just suggesting to to copy the runtime over as workaround.  If assembly is in the folder everything works for me.

**Comment by dagood** [comment] 2019-11-04 16:23
Filed https://github.com/dotnet/source-build/issues/1343 to track investigating/fixing this issue in future releases.

**Comment by tmds** [comment] 2019-11-04 16:54
> We are getting error that the assembly is missing.

When do you get this error? Are you executing some step using the sdk? Using some API in your application?

**Comment by davidgemel** [comment] 2019-11-04 19:57
Looks like we are referencing System.Drawing.FontStyle, and System.Drawing.Imaging.ImageFormat.ImageFormat in System.Drawing.Common.  When we try and use these it will fail.

**Comment by scalablecory** [comment] 2020-09-02 22:30
@dagood @dseefeld can we close this issue as duplicate of the new issue? Is there more to do here?

**Closed** 2020-09-03 05:26 UTC
