### ISSUE TITLE
app.config not getting transformed after install and uninstall of nuget package

### ISSUE THREAD

**Issue by gittadesushil** [dotnet/core#2288] opened 2019-02-06 14:53 UTC
# Issue Title

app.config not getting transformed after install and uninstall of nuget package

# General
I am having sdk project which is published as nuget package. My package name is Printer. This project has two config file App.config.xdt.install and App.config.xdt.uninstall. I want these file should modify the project original App.config who is going to consume this package.

I have another project which is .net framework project where Printer package will get consume. Once Printer get's install the App.config for this project is not getting modified.

**Comment by karelz** [comment] 2019-02-17 09:12
@nguerrera @dsplaisted do you know where to route this question / bug report? Is it by design?

**Comment by nguerrera** [comment] 2019-02-17 16:14
@nkolev92 @rrelyea  I am not familiar with this NuGet feature. Is this something that happens with packages.config, but not PackageReference? Should we move this to NuGet/Home?

**Comment by nguerrera** [comment] 2019-02-17 16:32
cc @vijayrkn as I think there is some support for web.config transforms in web sdk.

**Comment by vijayrkn** [comment] 2019-02-17 16:50
>  Is this something that happens with packages.config, but not PackageReference? 

Yes, Running the transform is only supported with packages.config. This feature is not available with PackageReference. Both NuGet and Websdk uses the same Xml document transformation technology. 

https://www.nuget.org/packages/Microsoft.Web.Xdt/

You can use the Xdt to run your own transforms. This specific issue should go to NuGet/Home

**Comment by gittadesushil** [comment] 2019-02-17 18:18
@vijayrkn ok can I tranform the xml with package reference then? Where can I write the logic to tranform the xml using xdt? considering that NuGet doesn't support the tranformation in package reference. I am using package reference.

**Comment by rrelyea** [comment] 2019-02-17 20:46
Nuget 5.0p3 just shipped support for making build assets transitive.
Using targets, it is possible to do xdt transforms.

May have example if you work with us at nuget/home

**Comment by rrelyea** [comment] 2019-02-17 21:07
See https://github.com/NuGet/Home/issues/5954

**Comment by karelz** [comment] 2019-02-18 04:07
OK, closing as dupe of https://github.com/NuGet/Home/issues/5954
If it is incorrect, please file a new issue on NuGet/Home where it seems to belong. Or let me know if I missed something. Thanks!

**Closed by karelz** 2019-02-18 04:07 UTC

**Comment by ryno1234** [comment] 2019-04-20 01:38
@rrelyea, is your comment about https://github.com/NuGet/Home/issues/5954 related to capabilities of Nuget 5.0p3 or an alternative solution regardless of 5.0p3? 

I have tried to implement https://github.com/NuGet/Home/issues/5954 but the solution provided does not seem to work for our situation and are looking for insight and / or other solutions. Any more info on 5.0p3 that could help us?
