### ISSUE TITLE
Failed to load the dll from [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\6.0.0-rc.2.21480.5\hostpolicy.dll], HRESULT: 0x800700C1 An error occurred while loading required library hostpolicy.dll from [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\6.0.0-rc.2.21480.5]

### ISSUE THREAD

**Issue by muneerah1418** [dotnet/core#6862] opened 2021-11-03 10:30 UTC
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by muneerah1418** [comment] 2021-11-03 10:31
Failed to load the dll from [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\6.0.0-rc.2.21480.5\hostpolicy.dll], HRESULT: 0x800700C1
An error occurred while loading required library hostpolicy.dll from [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\6.0.0-rc.2.21480.5]

**Comment by eerhardt** [comment] 2021-11-03 16:53
Duplicate of #6861.

**Closed by eerhardt** 2021-11-03 16:53 UTC
