### ISSUE TITLE
DOTNET_CLI_UI_LANGUAGE - Not all messages are in English

### ISSUE THREAD

**Issue by AdvancedPowerArmor** [dotnet/core#2717] opened 2019-05-13 12:10 UTC
# DOTNET_CLI_UI_LANGUAGE - Not all messages are in English

# Details

I set environment variable `DOTNET_CLI_UI_LANGUAGE` to `en` but not all messages are in this language. I would like to have everything in English (messages, comments and so on).

```
OS: Windows 10.0.17763 x64
OS Language: Polish
OS Region: Default (for Poland)
Editor: Visual Studio Code 1.33.1 x64
```

dotnet --info

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.202\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

dotnet new console -n ExampleApp

```
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on ExampleApp\ExampleApp.csproj...
  Ukończono przywracanie w elemencie 5,71 sec (C:\Users\admin\Desktop\netcore\ExampleApp\ExampleApp.csproj).

Restore succeeded.
```

dotnet build

```
Microsoft (R) Build Engine 16.0.450+ga8dc7f1d34 dla platformy .NET Core
Copyright (C) Microsoft Corporation. Wszelkie prawa zastrzeżone.

  Ukończono przywracanie w elemencie 60,75 ms (C:\Users\admin\Desktop\netcore\ExampleApp\ExampleApp.csproj).
  ExampleApp -> C:\Users\admin\Desktop\netcore\ExampleApp\bin\Debug\netcoreapp2.2\ExampleApp.dll

Kompilacja powiodła się.
    Ostrzeżenia: 0
    Liczba błędów: 0

Czas, który upłynął: 00:00:22.17
```

dotnet run

`Hello World!`

dotnet publish --configuration Release

```
Microsoft (R) Build Engine 16.0.450+ga8dc7f1d34 dla platformy .NET Core
Copyright (C) Microsoft Corporation. Wszelkie prawa zastrzeżone.

  Ukończono przywracanie w elemencie 58,12 ms (C:\Users\admin\Desktop\netcore\ExampleApp\ExampleApp.csproj).
  ExampleApp -> C:\Users\admin\Desktop\netcore\ExampleApp\bin\Release\netcoreapp2.2\ExampleApp.dll
  ExampleApp -> C:\Users\admin\Desktop\netcore\ExampleApp\bin\Release\netcoreapp2.2\publish\
```

Two environment variables fot .NET Core were added (disabled telemetry and English UI language).

```
Name                           Value                                                               
----                           -----      
...

DOTNET_CLI_TELEMETRY_OPTOUT    1                                                                   
DOTNET_CLI_UI_LANGUAGE         en                                                                  

...
```

I hope we could find a way to fix it.

**Comment by AdvancedPowerArmor** [comment] 2019-05-14 18:59
Does anyone have any idea how to solve problem?

**Comment by karelz** [comment] 2019-05-17 21:36
@livarcocc @nguerrera any thoughts? It seems to be from msbuild ...

**Comment by nguerrera** [comment] 2019-05-17 23:09
Duplicate of https://github.com/microsoft/msbuild/issues/1596

**Closed by nguerrera** 2019-05-17 23:09 UTC
