### ISSUE TITLE
UseDotNet@2 cant find sdk version matching 3.x

### ISSUE THREAD

**Issue by justinswork** [dotnet/core#3633] opened 2019-10-15 18:20 UTC
# UseDotNet@2 cant find sdk version matching 3.x

In Azure DevOps task UseDotNet@2, the build compiler is unable to find a matching version of DotNetCore sdk

# General

##[error]Failed while getting version 3.x from channel 3.1 with error: {}
##[error]sdk version matching: 3.x could not be found

Including parameter **includePreviewVersions** finds the latest preview version of 3.1, but I want the latest current version. (currently 3.0.100)

**Comment by justinswork** [comment] 2019-10-15 18:47
https://github.com/microsoft/azure-pipelines-tasks/issues/11569

**Comment by scalablecory** [comment] 2019-10-18 18:38
Closing as duplicate of https://github.com/microsoft/azure-pipelines-tasks/issues/11569, thanks.

**Closed by scalablecory** 2019-10-18 18:38 UTC
