### ISSUE TITLE
Cannot install .NET Core on Ubuntu 20.04 (missing dependency)

### ISSUE THREAD

**Issue by kedare** [dotnet/core#4588] opened 2020-04-19 09:50 UTC
Following the standard intrucstion, .NET core 3.1 cannot be installed on Ubuntu 20.04 because of a missing dependency.

After doing some investigation, it is because it depends on versions of libicu that are not available on this version of Ubuntu :

```
The following packages have unmet dependencies:
 dotnet-runtime-deps-3.1 : Depends: libicu but it is not installable or
                                    libicu63 but it is not installable or
                                    libicu60 but it is not installable or
                                    libicu57 but it is not installable or
                                    libicu55 but it is not installable or
                                    libicu52 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

This version of Ubuntu only provides libicu66 (which is not declared as a dependency)
https://packages.ubuntu.com/search?suite=focal&keywords=libicu

**Comment by dagood** [comment] 2020-04-19 16:08
We don't quite have packages ready for Ubuntu 20.04 on the package repository. Check out https://github.com/dotnet/core/issues/4360 for more info including a workaround.

I want to point out, though, there are no "standard" instructions for 20.04 yet--the page hasn't been created: https://github.com/dotnet/docs/issues/17638.

**Comment by dagood** [comment] 2020-04-19 16:08
Duplicate of https://github.com/dotnet/core/issues/4360

**Closed by dagood** 2020-04-19 16:08 UTC

**Comment by Dutchglory** [comment] 2020-05-03 16:36
solution here: https://github.com/dotnet/core/issues/4616#issuecomment-619361732
