### ISSUE TITLE
error NETSDK1177: 无法对 Apphost 进行签名，错误代码为 0

### ISSUE THREAD

**Issue by Chianti1** [dotnet/core#7483] opened 2022-05-25 04:44 UTC
(base) chixshdeMacBook-Pro:MyApp chixsh$ dotnet run
/usr/local/share/dotnet/sdk/6.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(554,5): error NETSDK1177: 无法对 Apphost 进行签名，错误代码为 0: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun [/Users/chixsh/works/code_workspace/C_workspace/MyApp/MyApp.csproj]
/usr/local/share/dotnet/sdk/6.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(554,5): error NETSDK1177: /Users/chixsh/works/code_workspace/C_workspace/MyApp/obj/Debug/net6.0/apphost: the codesign_allocate helper tool cannot be found or used [/Users/chixsh/works/code_workspace/C_workspace/MyApp/MyApp.csproj]
/usr/local/share/dotnet/sdk/6.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(554,5): error NETSDK1177:  [/Users/chixsh/works/code_workspace/C_workspace/MyApp/MyApp.csproj]

生成失败。请修复生成错误并重新运行。

**Comment by michaelgsharp** [comment] 2022-05-26 23:29
Looks like your xcode is out of date or corrupted. See https://github.com/dotnet/sdk/issues/24593 for more info.

Closing as its a dupe of https://github.com/dotnet/sdk/issues/24593.

**Closed by michaelgsharp** 2022-05-26 23:29 UTC
