### ISSUE TITLE
Problems installing DOTNET on UBUNTU 19.04

### ISSUE THREAD

**Issue by jorgenfhlarsen** [dotnet/core#2763] opened 2019-05-21 15:33 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current
Operating System: Linux Ubuntu 19.04 - x64

Hi

Trouble installing DOTNET on UBUNTU 19.04

pi@pi:~$ sudo apt-get install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.5) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.5) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

And going down to the lowest dependecy:

pi@pi:~$ sudo apt-get install dotnet-runtime-deps-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-deps-2.2 : Depends: libicu63 but it is not installable
E: Unable to correct problems, you have held broken packages.
pi@pi:~$ ^C
pi@pi:~$ 

Any help appriciated..

Thanks,-

/Jorgen

**Comment by karelz** [comment] 2019-05-21 16:16
Duplicate of #2526

**Closed by karelz** 2019-05-21 16:16 UTC
