### ISSUE TITLE
Windows Update error 0x80070643 trying to install "2021-11 .NET Core 3.1.21 Update for x64 Client (KB5007885)"

### ISSUE THREAD

**Issue by conioh** [dotnet/core#7093] opened 2022-01-06 23:19 UTC
### Description
  
  * Please share a clear and concise description of the problem.
  
  ![image](https://user-images.githubusercontent.com/10606081/148465201-6b21719d-e0f4-4f0e-af83-c0596f063b44.png)
  
  * What behavior are you seeing, and what behavior would you expect?
  Tried to install "update" to 3.1.21 even when I have runtime 3.1.22 installed (from the latest SDK download) or when I don't have .NET 3 at all.
  I expect that update to succeed if needed, and in case I have a newer version or don't have .NET 3 at all not to get an "update" at all.
  
  ### Configuration
  
  * What OS and version, and for Linux, what distro?
  Windows 11 build 22000.376
  
  * What is the architecture (x64, x86, ARM, ARM64)?
  x64
  
  * Do you know whether it is specific to that configuration?
  No.
  
  ### Regression?
  
  Absolutely.
  
  ### Other information
  
  The error code is similar to the one mentioned in #7044 but:
  - The workaround of updating the Visual Studio installer is irrelevant (there were no updates, uninstalling VS 2019 didn't help, my VS 2022 doesn't include .NET 3 as an installed component, etc.)
  - Installing the latest SDK didn't help. Windows Update actually tries to "update" 3.1.22 to 3.1.21, whatever that means.
  
  ![image](https://user-images.githubusercontent.com/10606081/148465691-864d6dd3-c526-4c9c-8a9b-3d2c3f7c4a69.png)

**Comment by Liwindo** [comment] 2022-01-06 23:48
This issue is also hitting me on Windows 10, tried the same workarounds but no solution. Please fix it asap.

**Comment by buyaa-n** [comment] 2022-01-07 00:27
Tagging @rbhanda for further triage, JFYI i have transferred the other similar issue into SDK repo, maybe it was supposed to stay in this repo

**Comment by zzto1118** [comment] 2022-01-07 09:44
I also have this problem (.NET Core 3.1.21 for x64 KB5007885), I deleted any new version and then on this website (https://www.catalog.update.microsoft.com/DownloadDialog.aspx)

Install (dotnet-sdk-3.1.415-win-x64_8b088c0e40d1317aa1b1b2613a3226b58012e505.exe) to solve the problem

The idea is that you must install the version shown by the problem code, and delete the newer and lower versions

**Comment by nattlip** [comment] 2022-01-07 10:24
i see on my update history . 2021-11 .NET Core 3.1.21 Update for x64 Client (KB5007885) is installed on 10-11, why does windows update install it again, i am in windows 11 insiders

**Comment by clyburnw** [comment] 2022-01-07 14:02
Same problem on same OS and VS (2022) configurations. I had the same issue last time, but it went away after a VS update, only to re-occur the next time Windows Update wanted to install these .Net updates.

**Comment by ESClemens** [comment] 2022-01-07 23:07
Same problem on a Windows 7 machine.  I didn't even know I had .NET Core installed!

**Comment by AcidVienna** [comment] 2022-01-07 23:22
Same here (Win11x64)....

**Comment by skykharkov** [comment] 2022-01-08 08:38
Same here Windows 10 Pro 21H1 build 19043.1415

**Comment by gnovos** [comment] 2022-01-08 10:13
same here, win 11 x64

**Comment by Truandale** [comment] 2022-01-08 14:10
> ### Description
> * Please share a clear and concise description of the problem.
> 
> ![image](https://user-images.githubusercontent.com/10606081/148465201-6b21719d-e0f4-4f0e-af83-c0596f063b44.png)<img alt="" width="16" height="16" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAFIGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDAgNzkuMTYwNDUxLCAyMDE3LzA1LzA2LTAxOjA4OjIxICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOCAoTWFjaW50b3NoKSIgeG1wOkNyZWF0ZURhdGU9IjIwMTktMDItMDhUMTc6NTU6MzcrMDM6MDAiIHhtcDpNb2RpZnlEYXRlPSIyMDE5LTAyLTA4VDE3OjU3OjUxKzAzOjAwIiB4bXA6TWV0YWRhdGFEYXRlPSIyMDE5LTAyLTA4VDE3OjU3OjUxKzAzOjAwIiBkYzpmb3JtYXQ9ImltYWdlL3BuZyIgcGhvdG9zaG9wOkNvbG9yTW9kZT0iMyIgcGhvdG9zaG9wOklDQ1Byb2ZpbGU9InNSR0IgSUVDNjE5NjYtMi4xIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOmNiYTVhNGRhLTIwNjAtNDViOS1hZjI5LTgyZWIzNDdmMTA2MSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDpjYmE1YTRkYS0yMDYwLTQ1YjktYWYyOS04MmViMzQ3ZjEwNjEiIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpjYmE1YTRkYS0yMDYwLTQ1YjktYWYyOS04MmViMzQ3ZjEwNjEiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJjcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOmNiYTVhNGRhLTIwNjAtNDViOS1hZjI5LTgyZWIzNDdmMTA2MSIgc3RFdnQ6d2hlbj0iMjAxOS0wMi0wOFQxNzo1NTozNyswMzowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTggKE1hY2ludG9zaCkiLz4gPC9yZGY6U2VxPiA8L3htcE1NOkhpc3Rvcnk+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+7vX+RAAAAdZJREFUOI2Vk19IU1Ecxz/n7mqUpGSDBWIOId3UgSCMCowIo38QPTlEXBT4aO3Sky+10XPUQ+9RDz1L0EviU4nWQxBtZmSDqBiUbc11d7me3Z0edJPd7UL9Hn/f8/me7/kdfgJ33ZyZparmgEiTVitBDqE94VD/bb1BmItf1zQxf/rsmbZAt9+TL5nlfUtLi+etQhZR787HD2NW109OTNgfpNlTkLanwQGfzsj+rs03LxblXgJTpfyBQDYj/0SLctsTBig7FdJW0Y8CbSf6tSEg1jMaCRXlNipmoGIGF44EAYgHwziTCVTMIDl8vG4CNQMh7/cPDnxZN4ud7tviwTCPoufQhCCVXiGZWW3QdRJXL2mCY3qwt9cu5RvE6b4QU30hT3gnQdW5Nzw2Zm2U8rpbnA6Gm2BdCJcB8NXcsqseA0ulV7i79hoVM5g6OoicTLgMNN+t32ufuhBUWsHJzCqVXejpiYstnvDg8XOUs0H223IrGODKy2ce+Wq/oNoMcptDOE7BDetCsDB+2dNgbyI3Zh6Kzo6IGhk45XnaXctvdxMAdIg7assMU7Y+/xNsyxyCnK/eePXOIjr6ix/5cboP/qS93XubbJnj/cfvVNWCaBL/c53/AottuNjod6B9AAAAAElFTkSuQmCC">
> 
> * What behavior are you seeing, and what behavior would you expect?
>   Tried to install "update" to 3.1.21 even when I have runtime 3.1.22 installed (from the latest SDK download) or when I don't have .NET 3 at all.
>   I expect that update to succeed if needed, and in case I have a newer version or don't have .NET 3 at all not to get an "update" at all.
> 
> ### Configuration
> * What OS and version, and for Linux, what distro?
>   Windows 11 build 22000.376
> * What is the architecture (x64, x86, ARM, ARM64)?
>   x64
> * Do you know whether it is specific to that configuration?
>   No.
> 
> ### Regression?
> Absolutely.
> 
> ### Other information
> The error code is similar to the one mentioned in #7044 but:
> 
> * The workaround of updating the Visual Studio installer is irrelevant (there were no updates, uninstalling VS 2019 didn't help, my VS 2022 doesn't include .NET 3 as an installed component, etc.)
> * Installing the latest SDK didn't help. Windows Update actually tries to "update" 3.1.22 to 3.1.21, whatever that means.
> 
> ![image](https://user-images.githubusercontent.com/10606081/148465691-864d6dd3-c526-4c9c-8a9b-3d2c3f7c4a69.png)<img alt="" width="16" height="16" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAFIGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDAgNzkuMTYwNDUxLCAyMDE3LzA1LzA2LTAxOjA4OjIxICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOCAoTWFjaW50b3NoKSIgeG1wOkNyZWF0ZURhdGU9IjIwMTktMDItMDhUMTc6NTU6MzcrMDM6MDAiIHhtcDpNb2RpZnlEYXRlPSIyMDE5LTAyLTA4VDE3OjU3OjUxKzAzOjAwIiB4bXA6TWV0YWRhdGFEYXRlPSIyMDE5LTAyLTA4VDE3OjU3OjUxKzAzOjAwIiBkYzpmb3JtYXQ9ImltYWdlL3BuZyIgcGhvdG9zaG9wOkNvbG9yTW9kZT0iMyIgcGhvdG9zaG9wOklDQ1Byb2ZpbGU9InNSR0IgSUVDNjE5NjYtMi4xIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOmNiYTVhNGRhLTIwNjAtNDViOS1hZjI5LTgyZWIzNDdmMTA2MSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDpjYmE1YTRkYS0yMDYwLTQ1YjktYWYyOS04MmViMzQ3ZjEwNjEiIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpjYmE1YTRkYS0yMDYwLTQ1YjktYWYyOS04MmViMzQ3ZjEwNjEiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJjcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOmNiYTVhNGRhLTIwNjAtNDViOS1hZjI5LTgyZWIzNDdmMTA2MSIgc3RFdnQ6d2hlbj0iMjAxOS0wMi0wOFQxNzo1NTozNyswMzowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTggKE1hY2ludG9zaCkiLz4gPC9yZGY6U2VxPiA8L3htcE1NOkhpc3Rvcnk+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+7vX+RAAAAdZJREFUOI2Vk19IU1Ecxz/n7mqUpGSDBWIOId3UgSCMCowIo38QPTlEXBT4aO3Sky+10XPUQ+9RDz1L0EviU4nWQxBtZmSDqBiUbc11d7me3Z0edJPd7UL9Hn/f8/me7/kdfgJ33ZyZparmgEiTVitBDqE94VD/bb1BmItf1zQxf/rsmbZAt9+TL5nlfUtLi+etQhZR787HD2NW109OTNgfpNlTkLanwQGfzsj+rs03LxblXgJTpfyBQDYj/0SLctsTBig7FdJW0Y8CbSf6tSEg1jMaCRXlNipmoGIGF44EAYgHwziTCVTMIDl8vG4CNQMh7/cPDnxZN4ud7tviwTCPoufQhCCVXiGZWW3QdRJXL2mCY3qwt9cu5RvE6b4QU30hT3gnQdW5Nzw2Zm2U8rpbnA6Gm2BdCJcB8NXcsqseA0ulV7i79hoVM5g6OoicTLgMNN+t32ufuhBUWsHJzCqVXejpiYstnvDg8XOUs0H223IrGODKy2ce+Wq/oNoMcptDOE7BDetCsDB+2dNgbyI3Zh6Kzo6IGhk45XnaXctvdxMAdIg7assMU7Y+/xNsyxyCnK/eePXOIjr6ix/5cboP/qS93XubbJnj/cfvVNWCaBL/c53/AottuNjod6B9AAAAAElFTkSuQmCC">

I solved this problem. Delete manually all old versions of .NET Runtime and install manually new version from https://dotnet.microsoft.com/en-us/download/dotnet/3.1

**Comment by pstimpel** [comment] 2022-01-08 18:48
> I solved this problem. Uninstall manually all old versions of .NET Runtime 3.1 and install manually new version .NET Runtime 3.1 from https://dotnet.microsoft.com/en-us/download/dotnet/3.1

worked fine

**Comment by cooperdk** [comment] 2022-01-09 13:03
> I also have this problem (.NET Core 3.1.21 for x64 KB5007885), I deleted any new version and then go this site
> 
> Install ([dotnet-sdk-3.1.415-win-x64_8b088c0e40d1317aa1b1b2613a3226b58012e505.exe](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-3.1.415-windows-x64-installer)) to solve the problem
> 
> The idea is that you must install the version shown by the problem code, and delete the newer and lower versions

The link you're giving there is for the SDK, not for the core. That won't work.

That said, this will not resolve the issue either. Windows will still try to apply patch 3.1.21, even though you have a newer one installed, and it will still fail.

**Comment by ViRuSTriNiTy** [comment] 2022-01-09 14:03
> > I also have this problem (.NET Core 3.1.21 for x64 KB5007885), I deleted any new version and then go this site
> > Install ([dotnet-sdk-3.1.415-win-x64_8b088c0e40d1317aa1b1b2613a3226b58012e505.exe](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-3.1.415-windows-x64-installer)) to solve the problem
> > The idea is that you must install the version shown by the problem code, and delete the newer and lower versions
> 
> The link you're giving there is for the SDK, not for the core. That won't work.
> 
> That said, this will not resolve the issue either. Windows will still try to apply patch 3.1.21, even though you have a newer one installed, and it will still fail.

That statement is most likely not correct as I could fix the install error by basically uninstalling existing products and reinstalling them.

The procedure is as follows:

- Visit https://www.catalog.update.microsoft.com/
- Enter the KB... number that fails on auto-update, here for example `KB5007885`
- Click `Download` displayed next to the search result to open a window with all the installers associated with the KB number, one of these installers fail and you need to find out which one, so ...
- Download all installers linked in the upcoming window
- Now try to run all these installers

When an installer fails, it will display the actual reason. On my side it was something along lines of `Another version is already installed` hence I uninstalled the associated version followed by a second try of running the installer ... and guess what, it installed the product. After running all the installer successfully, update the Windows Update dialog and hopefully, like in my case, the error is gone.

**Comment by GaryFurash** [comment] 2022-01-09 15:54
Didnt' work. I manually downlaoded KB5007885 and KB5007884 and installed them manually and they were fine, but widnows update keeps trying to install them.

**Comment by pstimpel** [comment] 2022-01-09 16:54
> Didnt' work. I manually downlaoded KB5007885 and KB5007884 and installed them manually and they were fine, but widnows update keeps trying to install them.

had to uninstall all other v3 .net stuff first, then reinstalled again after a reboot, and after another reboot windows update made its thing and turned green again.

**Comment by GaryFurash** [comment] 2022-01-09 16:59
I'm getting the error for both 3 and 5

![image](https://user-images.githubusercontent.com/15006133/148692379-3f2f25cc-77cb-40dd-b347-d04bdf25feb9.png)

I'm not sure which of the DotNet runtimes (right, it's runtime, not SDK) I need to uninstall

![image](https://user-images.githubusercontent.com/15006133/148692407-1bdc99c4-5afb-4aae-a384-a674cdd97172.png)

**Comment by pstimpel** [comment] 2022-01-09 17:00
I kicked all I found.

**Comment by MatthewGP** [comment] 2022-01-09 17:10
Something has occurred to cause Windows update to attempt to install 2021-11 .NET Core 3.1.21 Update for x64 Client (KB5007885) again on January 5, 2022 after it had already been successfully installed on November 8, 2021.

![image](https://user-images.githubusercontent.com/24598677/148692728-1297ce27-3381-4417-a8e6-320771e98ed9.png)

**Comment by bplasmeijer** [comment] 2022-01-09 17:57
same here:

**Comment by R4to0** [comment] 2022-01-09 19:56
Same, Win10 21H1 64-bit.

![image](https://user-images.githubusercontent.com/3608184/148698412-284f986d-70a6-4c47-9e17-0eb91c9e197b.png)

**Comment by conioh** [comment] 2022-01-10 01:30
> > > I also have this problem (.NET Core 3.1.21 for x64 KB5007885), I deleted any new version and then go this site
> > > Install ([dotnet-sdk-3.1.415-win-x64_8b088c0e40d1317aa1b1b2613a3226b58012e505.exe](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-3.1.415-windows-x64-installer)) to solve the problem
> > > The idea is that you must install the version shown by the problem code, and delete the newer and lower versions
> > 
> > 
> > The link you're giving there is for the SDK, not for the core. That won't work.
> > That said, this will not resolve the issue either. Windows will still try to apply patch 3.1.21, even though you have a newer one installed, and it will still fail.
> 
> That statement is most likely not correct as I could fix the install error by basically uninstalling existing products and reinstalling them.
> 
> The procedure is as follows:
> 
> * Visit https://www.catalog.update.microsoft.com/
> * Enter the KB... number that fails on auto-update, here for example `KB5007885`
> * Click `Download` displayed next to the search result to open a window with all the installers associated with the KB number, one of these installers fails on auto-update and you need to find out which one, so ...
> * Download all installers linked in the upcoming window
> * Now try to run all these installers
> 
> When an installer fails, it will display the actual reason. On my side it was something along lines of `Another version is already installed` hence I uninstalled the associated version followed by a second try of running the installer ... and guess what, it installed the product. After running all the installer successfully, update the Windows Update dialog and hopefully, like in my case, the error is gone.


That's a nice idea but it doesn't actually work.

I downloaded the 10 files, even the x86 ones from the Microsoft Catalog. Installed all of them. All of them succeeded. No errors. No issue to fix.

Now what?

![image](https://user-images.githubusercontent.com/10606081/148709141-2d022f4e-045f-4559-b83f-dd1f57c3b1d5.png)

![image](https://user-images.githubusercontent.com/10606081/148709169-21966084-f92f-4e06-b8fb-faa0479d6547.png)

![image](https://user-images.githubusercontent.com/10606081/148709328-8a88c473-1cad-485a-9658-4adfe7e538a6.png)

**Comment by cooperdk** [comment] 2022-01-10 01:50
But there's no need to install the SDK unless you need it for development, that's my point.

Also, installing version 3.1.22 did not work for me. Windows still tried to update to version 3.1.21.

Den 10. jan. 2022 02.30, fra 02.30, conioh ***@***.***> skrev:

**Comment by rbhanda** [comment] 2022-01-10 02:08
Hello everyone, Thanks a lot for reporting this issue. We have a request if you could share the logs with us for this failure:

•	Run http://aka.ms/vscollect.exe and share the resulting vslogs.zip that is created in %temp%
•	Run the powershell cmdlet Get-WindowsUpdateLog and share the resulting windowsupdate.log file that is created on your desktop

You can either email them to rbhanda@microsoft.com or attach them here in the comments.

**Comment by conioh** [comment] 2022-01-10 02:34
@rbhanda after an incredible amount of work I managed to make the error in Windows Update go away, but now it installs these versions of .NET SDK and Runtimes (including the Desktop runtime) non-stop.
I remove them through the control panel and Windows Update installs them back.
Is that the intended behavior? All versions (3, 5, 6) of .NET SDK and Runtimes are necessary components of Windows?

**Comment by conioh** [comment] 2022-01-10 03:43
@rbhanda, I'd like to make it clear, since the message may have gotten lost, that currently I'm getting KB5007884 and KB5007885:
(a) even if I have newer versions of .NET runtimes installed
(b) even if I don't have any version of these major versions installed (i.e. no .NET 3 or 5 installed at all)
(c) including SDK and not only runtimes

None of this is expected according to: https://devblogs.microsoft.com/dotnet/net-core-updates-coming-to-microsoft-update/

The only thing that _might_ compatible with that post is installing a 3/5 runtime when 6 is already installed, according to the emphasized part:
> These updates will be installed via Microsoft Update to computers with a Client operating system that have a supported major/minor version such as .NET Core 2.1, 3.1 or .NET 5.0 already installed.

But that's a peculiar interpretation. A reasonable interpretation would be "for each X for which there's .NET X installed you'll get the latest .NET X" or "for each (X, Y) for which there's .NET X.Y installed you'll get the latest .NET X.Y" but not "if you have _any_ supported .NET version (for example 6) you'll get 'updates' for _all_ other supported .NET versions (for example, 3 and 5)". Not to mention the rest of the sentence - "... with outdated version of those 3 and 5 and we'll push the SDKs too!"

**Comment by rbhanda** [comment] 2022-01-10 04:51
Hi @conioh if you have any logs you could share it will be very helpful. I am working with the other team members who will be able to help us here. My apologies for a delayed response.

**Comment by Rogerdlin** [comment] 2022-01-10 06:19
I have emailed you both the vslog.zip and WindowsUpdate.log 7 minutes ago, hope you already have it.

**Comment by Rogerdlin** [comment] 2022-01-10 06:30
@rbhanda I have sent you both the log you were asking, do you have them now?

**Comment by Trezore** [comment] 2022-01-10 06:50
Nice to have found this page!!! I too am having the same issue...
Figuring I will wait and keep track of progress.  Do let me know if you want my logs as well. But from the looks of it, other logs will have it covered! :)

**Comment by thesilverdragon** [comment] 2022-01-10 15:38
For me also, it seems that this specific update has already been installed on November 2021, but now Windows Update suddenly wants to install it again.

![image](https://user-images.githubusercontent.com/26805991/148793510-4cabe624-1756-48ac-beff-675d4db66998.png)

**Comment by IGR2014** [comment] 2022-01-10 16:12
Windows 11 (10.0.22000.194), x64, same here

**Comment by Makru** [comment] 2022-01-10 17:13
Hi, i have the same issue with 2021-11 .NET Core 3.1.21 Update for x64 Client (KB5007885) -> Installationsfehler – 0x80070643.
I tried 20 different "solutions" from Google, without success. Also manual deinstallation and installation doesn't work.  
Hopefully there is soon a solution....

**Comment by rbhanda** [comment] 2022-01-10 19:53
Hello Everyone,

Thank you for reporting this issue.  We have root caused it and it seems our December updates were unpublished causing previous November updates to be offered.  We expect to publish a solution tomorrow morning, January 11th at 10am PST.

**Comment by Makru** [comment] 2022-01-10 20:34
Thanks in advance :-)

**Comment by richardevcom** [comment] 2022-01-11 01:26
> The procedure is as follows:
> 
>     * Visit https://www.catalog.update.microsoft.com/
> 
>     * Enter the KB... number that fails on auto-update, here for example `KB5007885`
> 
>     * Click `Download` displayed next to the search result to open a window with all the installers associated with the KB number, one of these installers fails on auto-update and you need to find out which one, so ...
> 
>     * Download all installers linked in the upcoming window
> 
>     * Now try to run all these installers

**☝️Underrated solution.** 
The issue is indeed that it conflicts with other versions if installed.
So what I did was:
1. I opened up corresponding packages in catalog https://www.catalog.update.microsoft.com/Search.aspx?q=KB5007885
2. then I uninstalled conflicting packages
3. and to be safe removed `C:\Windows\SoftwareDistribution` folder (sometimes Windows Update service has to be stopped so you don't get error that some files are being used)
4. for extra step do clean reboot

**Comment by Froosh** [comment] 2022-01-11 03:04
Updating Visual Studio to current version (I'm still using VS2019, so v16.11.8) solved the .NET 5.0.12 and .NET 3.1.21 issues for me.

**Comment by Monarch73** [comment] 2022-01-11 17:13
I had the same issue. The Problem is that Windows Update wants to install 3.1.21 and 5.0.12 while new versions of the 3.1.x and 5.0.x core sdks where already installed by visual studio installer. 

You can fix this error by checking the installers that were downloaded by Windows Update in the folder C:\Windows\SoftwareDistribution\Download\Install and run them manually. They will fail but they will tell you, what went wrong by providing you with a logfile. 

You basicaly have to uninstall newer versions of the core sdks and run the installer manually.

**Comment by cooperdk** [comment] 2022-01-11 21:07
This did not work for me either, Windows Update determined that it still needed to update the already updated versions, and failed. I have now hidden the failed updates.
This issue has occured for me in at least the past one to two years with various versions of this software.

⁣Hent BlueMail til Android ​

Den 11. jan. 2022 18.13, fra 18.13, "Niels Hüsken" ***@***.***> skrev:

**Comment by rbhanda** [comment] 2022-01-11 21:49
Hello,
The December updates are live again. This issue should be resolved now

**Comment by AcidVienna** [comment] 2022-01-11 22:53
@rbhanda Thx Rahul - issue is fixed, all updates now installed without problems! (Win11x64)

**Closed** 2022-01-12 18:54 UTC
Labels: area-setup
