### ISSUE TITLE
Wrong package in repo dotnet-host-3.1.0-x64.rpm preview only

### ISSUE THREAD

**Issue by angus7216** [dotnet/core#4115] opened 2020-01-14 01:31 UTC
Wrong package dotnet-host-3.1.0-x64.rpm in repo

# General

Hey, i am l trying to install the new version of dotnet-host 3.1 from here https://packages.microsoft.com/rhel/7/prod/ and here https://packages.microsoft.com/centos/7/prod/ the package that is in the repos (dotnet-host-3.1.0-x64.rpm) is still the preview version even though it has the same date as then the 3.1 full version got released (04-Dec-2019 22:34) can this please be looked into as i need the non preview version of dotnet-host-3.1

When i installed the above package it is only the preview version and not the new version that got released on the 4th December 2019.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).
![Capture](https://user-images.githubusercontent.com/59853946/72305969-5da3ae80-36da-11ea-97ab-832b450a65c4.JPG)

**Comment by dagood** [comment] 2020-01-14 16:53
This isn't actually the old 3.1.0 Preview 3 build, it's a 3.1.0 build that is branded that way due to some issues in the release process. It's safe to use. This is a known issue with 3.1.0 across a lot of artifacts and endpoints and will be fixed with 3.1.1.

**Comment by dagood** [comment] 2020-01-14 16:54
Duplicate of https://github.com/dotnet/core/issues/3975

**Closed by dagood** 2020-01-14 16:54 UTC

**Comment by angus7216** [comment] 2020-01-14 20:01
Awesome thanks for that !
