### ISSUE TITLE
Unable to install aspnet core 2.1 on CentOS 7

### ISSUE THREAD

**Issue by dhuyvett** [dotnet/core#2559] opened 2019-04-09 21:11 UTC
Trying to install aspnetcore 2.1 on a clean centos image as per: https://dotnet.microsoft.com/download/linux-package-manager/centos/runtime-2.1.10

`# rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm`
 succeeds

`# yum update`
 succeeds

`# yum install aspnetcore-runtime-2.1`
 fails

```
# yum install aspnetcore-runtime-2.1
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirrors.usc.edu
 * extras: mirror.sfo12.us.leaseweb.net
 * updates: mirror.hostduplex.com
Resolving Dependencies
--> Running transaction check
---> Package aspnetcore-runtime-2.1.x86_64 0:2.1.10-1 will be installed
--> Processing Dependency: dotnet-runtime-2.1 >= 2.1.10 for package: aspnetcore-runtime-2.1-2.1.10-1.x86_64
--> Running transaction check
---> Package dotnet-runtime-2.1.x86_64 0:2.1.10-1 will be installed
--> Processing Dependency: dotnet-hostfxr-2.1 >= 2.1.10 for package: dotnet-runtime-2.1-2.1.10-1.x86_64
--> Processing Dependency: dotnet-runtime-deps-2.1 >= 2.1.10 for package: dotnet-runtime-2.1-2.1.10-1.x86_64
--> Running transaction check
---> Package dotnet-hostfxr-2.1.x86_64 0:2.1.10-1 will be installed
--> Processing Dependency: dotnet-host >= 2.1.10 for package: dotnet-hostfxr-2.1-2.1.10-1.x86_64
---> Package dotnet-runtime-deps-2.1.x86_64 0:2.1.10-1 will be installed
--> Processing Dependency: libicu for package: dotnet-runtime-deps-2.1-2.1.10-1.x86_64
--> Running transaction check
---> Package dotnet-host.x86_64 0:2.2.4-1 will be installed
---> Package libicu.x86_64 0:50.1.2-17.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================================================================================================================
 Package                                         Arch                           Version                               Repository                                           Size
================================================================================================================================================================================
Installing:
 aspnetcore-runtime-2.1                          x86_64                         2.1.10-1                              packages-microsoft-com-prod                          28 M
Installing for dependencies:
 dotnet-host                                     x86_64                         2.2.4-1                               packages-microsoft-com-prod                          44 k
 dotnet-hostfxr-2.1                              x86_64                         2.1.10-1                              packages-microsoft-com-prod                         196 k
 dotnet-runtime-2.1                              x86_64                         2.1.10-1                              packages-microsoft-com-prod                          27 M
 dotnet-runtime-deps-2.1                         x86_64                         2.1.10-1                              packages-microsoft-com-prod                         2.8 k
 libicu                                          x86_64                         50.1.2-17.el7                         base                                                6.9 M

Transaction Summary
================================================================================================================================================================================
Install  1 Package (+5 Dependent packages)

Total download size: 62 M
Installed size: 79 M
Is this ok [y/d/N]: y
Downloading packages:
dotnet-host-2.2.4-x64.rpm      FAILED                                                                                                         ]  0.0 B/s |    0 B  --:--:-- ETA 
https://packages.microsoft.com/rhel/7/prod/dotnet-host-2.2.4-x64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=packages-microsoft-com-prod clean metadata
Trying other mirror.
dotnet-hostfxr-2.1.10-x64.rpm  FAILED                                          
https://packages.microsoft.com/rhel/7/prod/dotnet-hostfxr-2.1.10-x64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=packages-microsoft-com-prod clean metadata
Trying other mirror.
warning: /var/cache/yum/x86_64/7/packages-microsoft-com-prod/packages/aspnetcore-runtime-2.1.10-rh.rhel.7-x64.rpm: Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY04 ETA 
Public key for aspnetcore-runtime-2.1.10-rh.rhel.7-x64.rpm is not installed
(1/6): aspnetcore-runtime-2.1.10-rh.rhel.7-x64.rpm                                                                                                       |  28 MB  00:00:02     
(2/6): dotnet-runtime-deps-2.1.10-rhel.7-x64.rpm                                                                                                         | 2.8 kB  00:00:00     
(3/6): libicu-50.1.2-17.el7.x86_64.rpm                                                                                                                   | 6.9 MB  00:00:00     
dotnet-runtime-2.1.10-x64.rpm  FAILED                                          ===========================================================-   ]  10 MB/s |  59 MB  00:00:00 ETA 
https://packages.microsoft.com/rhel/7/prod/dotnet-runtime-2.1.10-x64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=packages-microsoft-com-prod clean metadata
Trying other mirror.


Error downloading packages:
  dotnet-runtime-2.1-2.1.10-1.x86_64: [Errno 256] No more mirrors to try.
  dotnet-hostfxr-2.1-2.1.10-1.x86_64: [Errno 256] No more mirrors to try.
  dotnet-host-2.2.4-1.x86_64: [Errno 256] No more mirrors to try.

```

Tried : `yum --enablerepo=packages-microsoft-com-prod clean metadata`
  no help

**Comment by dhuyvett** [comment] 2019-04-09 21:22
possibly related and possibly a separate issue: yum update on a centos 7 system with 2.1.9 installed also fails: 

```Updating:
 aspnetcore-runtime-2.1   x86_64  2.1.10-1   packages-microsoft-com-prod   28 M
 dotnet-host              x86_64  2.2.4-1    packages-microsoft-com-prod   44 k
 dotnet-hostfxr-2.1       x86_64  2.1.10-1   packages-microsoft-com-prod  196 k
 dotnet-runtime-2.1       x86_64  2.1.10-1   packages-microsoft-com-prod   27 M
 dotnet-runtime-deps-2.1  x86_64  2.1.10-1   packages-microsoft-com-prod  2.8 k

Transaction Summary
================================================================================
Upgrade  5 Packages

Total download size: 55 M
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
Package dotnet-host-2.2.4-x64.rpm is not signed```

**Comment by fafairuz** [comment] 2019-04-10 02:26
Having the same issue.

But I can install dotnet-sdk-2.1.4 just fine. Something wrong in the rpm spec?

**Comment by cuibty** [comment] 2019-04-10 04:02
+1

**Comment by abowen** [comment] 2019-04-10 05:39
Side note, if it helps anyone else that is dependent on this in AWS.

For our deployment, we were installing .NET core to a Linux AMI.

Until this is fixed, we are using AMI : amzn2-ami-hvm-2.0.20180622.1-x86_64-gp2-dotnetcore-2018.12.12

**Comment by michalhainc** [comment] 2019-04-10 07:59
+1

**Comment by kedf** [comment] 2019-04-10 13:21
+1

**Comment by lionzhou1981** [comment] 2019-04-10 15:28
+1

**Comment by karelz** [comment] 2019-04-10 15:30
@dagood can you please take a look or route it?
Looks serious

cc @omajid @tmds

**Comment by dagood** [comment] 2019-04-10 15:36
I asked @leecow about this (https://github.com/dotnet/core-setup/issues/5759) and the RPMs weren't signed correctly for this release. @vivmishra is working on fixing it.

**Comment by karelz** [comment] 2019-04-10 15:39
Duplicate of https://github.com/dotnet/core-setup/issues/5759

**Closed by karelz** 2019-04-10 15:39 UTC
