### ISSUE TITLE
MAC - Scoped dependency persist states in others request 

### ISSUE THREAD

**Issue by Dongata** [dotnet/core#1856] opened 2018-08-13 20:20 UTC
## General

I have a handler that is in charge of notifing messages to every layer of the application for each http request, the problem is that, this one is keeping the state on different requests, in one particular layer.

## Steps

* have a command handler in one layer, and a controller in other layer
* have the command handler setted as transient
* have the notificationhandler setted as scoped
* both have a notification handler injected
* Start a request
* add a notification in the scope of the command handler
* controller does not have the notification
* send another request
* check notifications on the command handler
* command handler has previuos request notification
* add another one
* controller still does not have any notification

##  Env
 We only see this problem on a dev machine under macOS 10.13.6 (17G65) , with .netcore sdk 2.1.301

**Comment by mmijovilcevich** [comment] 2018-08-20 18:16
I'm having the same issue

**Comment by morenoisidro** [comment] 2018-08-20 18:18
same here...

**Comment by maghidini** [comment] 2018-08-20 18:19
Same issue on my macOS High Sierra, huge blocker too

**Comment by Eilon** [comment] 2018-08-21 21:26
@Dongata do you have a sample app that can reproduce this issue? If you can share your app in a GitHub repo that would be ideal. Same goes to anyone else who can show us a broken app.

**Comment by Dongata** [comment] 2018-08-22 17:18
I'll try to make one exaple for you on friday, if it's that ok with you c:

**Comment by Eilon** [comment] 2018-08-22 17:27
Thanks, we'll take a look when you have that ready.

**Comment by Eilon** [comment] 2018-08-27 20:14
@Dongata did you have a chance to get to this?

**Comment by Dongata** [comment] 2018-08-27 20:16
Sorry @Eilon, really i was really busy, i'll try to make an exaple this week

**Comment by Eilon** [comment] 2018-09-10 17:34
Closing for now because we don't have a repro. If you have a change to get this done, please open a new issue at https://github.com/aspnet/Home/issues

**Closed by Eilon** 2018-09-10 17:34 UTC
Labels: area-aspnet
