### ISSUE TITLE
Port localhost:5000 not released causing error System.IO.IOException: Failed to bind to address http://127.0.0.1:5000: address already in use. 

### ISSUE THREAD

**Issue by foo-baar** [dotnet/core#948] opened 2017-09-07 08:06 UTC
Hi,

I installed dotnet core on Mac Sierra in order to build .net mvc application & while build a project I learned that donet\kestrel doesn't release the port 5000 after I stop a project causing port already in use error on next run.

I couldn't find any command\manual way to release\stop the port 5000 or localhost:500.

Please enlighten me if any such commend exists or any other possible solution.
error:
`System.IO.IOException: Failed to bind to address http://127.0.0.1:5000: address already in use. ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.AddressInUseException: Error -48 EADDRINUSE address already in use ---> Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException: Error -48 EADDRINUSE address already in use`

Thanks much 👍

**Comment by davidfowl** [comment] 2017-09-07 08:10
How did you run the application?

**Comment by foo-baar** [comment] 2017-09-07 08:12
@davidfowl hey, using vscode, 'Start Debugging' command, and stopped the same way: Ctrl + C o 'Stop Debugging'

**Comment by hugobritobh** [comment] 2017-09-07 10:47
It has happened to me and what I did was change the port. Try using the command

```
        WebHost.CreateDefaultBuilder(args)
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseUrls("http://*:5001")
                .UseStartup<Startup>()
                .Build();
```

**Comment by foo-baar** [comment] 2017-09-07 12:05
@hugobritobh I don't think your understood the issues: Port has not been released by Kestrel, irrespective of whichever one you use.

**Comment by Petermarcu** [comment] 2017-09-07 15:45
@Eilon

**Comment by wfurt** [comment] 2017-09-07 17:09
Did you check with netstat -an| grep 5000 what state the port is in @foo-baar

**Comment by foo-baar** [comment] 2017-09-08 05:21
@wfurt: I try with `lsof -i:5000` it shows occupied by dotnet, so I kill it manually and then continue.
![screen shot 2017-09-08 at 10 51 30 am](https://user-images.githubusercontent.com/13655874/30197175-b6248ab2-9483-11e7-975c-498a978086c3.png)

**Comment by wfurt** [comment] 2017-09-08 06:17
Thanks @foo-baar It really looks like the dotnet process is hogging the port. 
I wanted to make sure this is not a race condition closing the port.

**Comment by davidfowl** [comment] 2017-09-08 06:22
It's likely something to do with how the process is being launched. `dotnet run` doesn't forward control + c to the child process.

**Comment by foo-baar** [comment] 2017-09-08 06:45
@wfurt : Welcome man, I have tested most of the basic features rest all happens to work fine, its my first time with core on mac, will check in case I face anything else.

@davidfowl : Hey, I have been launching it via vscode (not manually) However running kestrel server has no stop command, besides general `Ctrl + C`.
On a separate note I have posted it to kestrel team however I believe since its not a mainstream component for them I doubt they'll focus on it much.

Thanks ✌️

**Comment by omajid** [comment] 2017-09-08 17:51
Ah, sounds like the old `Ctrl-C` is killing parent but not `dotnet` children: https://github.com/dotnet/cli/issues/7426

**Comment by foo-baar** [comment] 2017-09-08 18:39
@omajid What is documented there makes sense, but I havn't had a chance to loot into the dohet processes hence can't comment anything on that.

**Comment by Petermarcu** [comment] 2017-10-07 17:49
Is there anything else that needs to be done here or can we close this issue out?

**Comment by foo-baar** [comment] 2017-10-08 04:39
@Petermarcu I think we can close the issue, though it continue to exists today workaround is how to execute the code, i.e doing dotnet clean\build\run form terminal just runs fine, but if someone tries from Vs Code, then it runs into these issues.

Thanks anyhow ✌️

**Comment by Petermarcu** [comment] 2017-10-09 01:06
@DustinCampbell any thoughts on where we could track making this experience better for VS Code users?

**Comment by DustinCampbell** [comment] 2017-10-09 17:29
> @DustinCampbell any thoughts on where we could track making this experience better for VS Code users?

I think this is primarily a debugging question, yes? Including @gregg-miskelly in case he has any ideas.

**Comment by Petermarcu** [comment] 2017-10-12 06:29
@gregg-miskelly any thoughts? I'm going to close this issue here now but if there is a followup for the debugger, we can open an issue in the right repo.

**Closed by Petermarcu** 2017-10-12 06:29 UTC

**Comment by davidfowl** [comment] 2017-10-12 06:32
@foo-baar if you hit stop debugging it works fine.

**Comment by gregg-miskelly** [comment] 2017-10-12 14:51
@foo-baar does David's suggestion work for you? 

If not - does the process you are debugging get killed when you stop debugging? (diff the process list before and after)
If the process you are debugging gets killed - does your process spawn child processes?

**Comment by foo-baar** [comment] 2017-10-12 20:04
@gregg-miskelly Well the thing is process never got killed by any vscode commands, I did it manually every time from terminal.

**Comment by gregg-miskelly** [comment] 2017-10-12 21:52
@foo-baar Thanks. In that case can you file a bug at https://github.com/omnisharp/omnisharp-vscode/issues and we can see why you are running into this problem.

**Comment by MatheusGoncalvs** [comment] 2018-02-02 00:30
Just close it the vscode and open it again.

**Comment by davisgreg1** [comment] 2018-07-10 19:41
This same thing happened to me. I went into inspect mode at http://localhost:5000 and went into the Application tab, and clicked Clear Site Data at the bottom. Hope this works for you.

**Comment by johnmelodyme** [comment] 2018-12-10 02:05
So silly that I am, I commanded "killall" in my ssh terminal , and now I have to reset all. The issues raised here kind of helpful tho..

**Comment by seba-i** [comment] 2019-05-27 23:14
I had to kill all processes on the port, see [this link](https://til.hashrocket.com/posts/e4c8c665a8-find-and-kill-all-processes-listening-on-a-port).

**Comment by jeffnyman** [comment] 2019-06-17 19:39
This currently happens to me all the time as well, with a fresh install of dotnet. The project is here:

https://github.com/jeffnyman/testing-aspnet-core

Running `dotnet run` works just fine with this project on Windows, not at all on Mac (either Sierra, High Sierra or Mojave).

It initially tells me port 5000 is in use. It's not; I've checked. But I did run the kill steps on anything on the port as provided by seba-i. I then added the following line to `Startup.cs`:

```
.UseUrls("http://*:5001")
```
When I do that, then it tells me port 5001 is already in use. I realize the issue is closed but a lot of people are going to probably end up here as they experiment.

**Comment by wfurt** [comment] 2019-06-17 19:42
run ` lsof -i`on Mac. That will tell you what ports are opened and what process holds them.

**Comment by joakimvf** [comment] 2019-06-27 08:45
I got it to work again when I uninstalled "Visual Studio Build Tools 2017 (2)". I had the same problem where TCPView didn't even list the process using that specific port, I tried everything.

Why I tried to uninstall stuff was because my applications were able to start in safe mode (Windows 10). It made me think that something takes up the ports as soon as I log in.

**Comment by tmacharia** [comment] 2019-10-12 18:52
> Just close it the vscode and open it again.

Same for Visual Studio.

**Comment by aengingokce** [comment] 2019-11-12 20:20
> Just close it the vscode and open it again.

This one worked for me :) thx

**Comment by IaamRich** [comment] 2019-11-28 09:08
You need just off or kill all network adapters and run it again - and all will be good.

**Comment by AKA285066112** [comment] 2019-12-05 01:26
asp.net core 3.0  on CentOS7
error : Failed to bind to address http://127.0.0.1:5000: address already in use.

**Comment by PandaonMars** [comment] 2020-02-27 19:49
Here is what I did. After changing applicationUrl from "https://localhost:5001;http://localhost:5000" to "https://localhost:4001;http://localhost:4000", the application output told me that 
"The ASP.NET Core developer certificate is in an invalid state. To fix this issue, run the following commands 'dotnet dev-certs https --clean' and 'dotnet dev-certs https' to remove all existing ASP.NET Core development certificates and create a new untrusted developer certificate. On macOS or Windows, use 'dotnet dev-certs https --trust' to trust the new certificate."

I run  'dotnet dev-certs https --trust' and put in my computer's password fixed the issue.

**Comment by utsabshrestha** [comment] 2020-04-12 11:46
### So here is the solution, if you are working on linux
while running the **dotnet run** if you stop the server  using **ctr + z** then it _Ctrl+z_ sends the SIGTSTP (Signal Tty SToP) signal to the foreground job but don't actually stop the running kestrel server, so you have to mannualy end the process of the kestrel server.
**SOLLUTION**  Only use **ctr + c** to stop the kestrel server, actually its even displayed on the shell while you run dotnet run.

To mannually kill the kestrel server use this command to see the running process and it pid on the port 5000

sudo lsof -iTCP -sTCP:LISTEN -P | grep :5000

then kill it with 

sudo kill -9 PID

**Comment by robertwt7** [comment] 2020-08-15 09:28
Hey guys i'm still having this problem actually... not sure why is this closed. Should we stop dotnet application manually everytime? I ran it with dotnet cli and its still happening

**Comment by rogerpolvr** [comment] 2020-08-25 23:27
> ### So here is the solution, if you are working on linux
> while running the **dotnet run** if you stop the server using **ctr + z** then it _Ctrl+z_ sends the SIGTSTP (Signal Tty SToP) signal to the foreground job but don't actually stop the running kestrel server, so you have to mannualy end the process of the kestrel server.
> **SOLLUTION** Only use **ctr + c** to stop the kestrel server, actually its even displayed on the shell while you run dotnet run.
> 
> To mannually kill the kestrel server use this command to see the running process and it pid on the port 5000
> 
> sudo lsof -iTCP -sTCP:LISTEN -P | grep :5000
> 
> then kill it with
> 
> sudo kill -9 PID

Thanky you! worked for me.

**Comment by ryanmorse901** [comment] 2021-01-04 03:28
I know this is already closed but wanted to add my experience with this issue. I was having the same error. I had originally used ctr + c to shut down the server. And when I tried to use dotnet run again that is when I got the error. I found I needed to manually pause and stop the application within the editor window, then retry the dotnet run.

**Comment by MojoDaHacker** [comment] 2021-02-27 02:39
> I know this is already closed but wanted to add my experience with this issue. I was having the same error. I had originally used ctr + c to shut down the server. And when I tried to use dotnet run again that is when I got the error. I found I needed to manually pause and stop the application within the editor window, then retry the dotnet run.

Bingo lol, thanks man.

**Comment by lonix1** [comment] 2022-03-13 01:53
`kill -9` works but is a last resort.

Does kestrel respond to any of the other kill signals?

**Comment by daryl-clarke** [comment] 2023-01-16 09:15
I'm getting this same issue but only when deploying to an Azure app service. I've stopped all other app the the service plan, tried multiple port numbers using useUrls(https://*:5020) 5010,11 etc, even tried a few ports with WEBSITES_PORT=8082 8083 etc
Anyone had the same and managed to resolve?

**Comment by davidfowl** [comment] 2023-01-17 00:16
On azure app service, why are you hard coding ports to listen to in the first place? Does it happen when you don't specify any ports?

**Comment by daryl-clarke** [comment] 2023-01-17 09:05
Originally I had no ports and was getting the issue, trying to override it by hard coding the ports but with still no luck

**Comment by davidfowl** [comment] 2023-01-17 16:58
Can you show the problem you're having on app service with 0 added configuration and 0 added code to manage ports?

**Comment by JosueBCe** [comment] 2024-06-12 13:29
The message is self-explanatory. The port is already in use, just kill it and rebuild the solution and run it again: 
1. Open CMD as administrator
2. run: `netstat -ano | findstr <Portnumber being  used>`
3. kill port: `taskkill /PID <Port ID> /F`
You're done

**Comment by JosueBCe** [comment] 2024-06-12 13:34
You can also try in Windows 10

Open CMD as administrator and run:
```
net stop hns
net start hns
```

**Comment by Waseely** [comment] 2025-02-03 16:06
Run exe.Mark shutdown server.Exe -r -h -a wget 08138137948

![Image](https://github.com/user-attachments/assets/e118d170-4188-4cd8-aab4-ce43f38673df)

 exicute data to run
