### ISSUE TITLE
Problemas pacote dotnet-sdk-2.2

### ISSUE THREAD

**Issue by FelipeBaum** [dotnet/core#2643] opened 2019-04-26 12:57 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Debian 9 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Translated text:**
```
Need to Execuntar an application on Raspberry Pi with DIETPI and when running apt-get install dotnet-SDK-2.2 Returns the following error:
E: Unable to find the package dotnet-SDK-2.2
E: Couldn't find any package by glob'dotnet-SDK-2.2 '
E: Could not find the package through regular expression ' dotnet-sdk-2.2 '

I followed the steps presented on the site
```

**Original text:**
```
preciso execuntar uma aplicação em raspberry pi com dietpi e ao executar apt-get install dotnet-sdk-2.2 retorna o seguinte erro:
E: Impossível encontrar o pacote dotnet-sdk-2.2
E: Couldn't find any package by glob 'dotnet-sdk-2.2'
E: Não foi possível encontrar o pacote através da expressão regular 'dotnet-sdk-2.2'

Eu segui os passos apresentados no site
```

**Comment by karelz** [comment] 2019-04-27 18:43
Duplicate of #2646

**Comment by karelz** [comment] 2019-04-27 18:44
@FelipeBaum please use English in your reports in future (at least through machine translators), we do not scale to communicate in additional languages. Thank you!

**Closed by karelz** 2019-04-27 18:43 UTC
