### ISSUE TITLE
.NET Core 3.1 - RijndaelManaged - Initialization vector 256 bits not supported

### ISSUE THREAD

**Issue by dericferreira** [dotnet/core#4751] opened 2020-05-28 12:37 UTC
.NET Core 3.1 - RijndaelManaged - Initialization vector 256 bits not supported

RijndaelManaged does not support Initialization vector 256 bits in .NET CORE.

Hey,

If .NET Core 3.1 still does not support 256 initialization vector why documentation does not reflect that?

Look at this:

//RijndaelManaged
// Legal min key size = 128
// Legal max key size = 256
// Legal min block size = 128
// Legal max block size = 256

Anybody can't get the same result! Why does the documentation is not refleting the truth?

https://docs.microsoft.com/pt-br/dotnet/api/system.security.cryptography.symmetricalgorithm.legalkeysizes?view=netcore-3.1

**Comment by mairaw** [comment] 2020-05-30 01:26
@bartonjs should I transfer this to the api docs repo or runtime?

**Comment by vcsjones** [comment] 2020-05-30 15:17
@mairaw this looks like a duplicate of https://github.com/dotnet/runtime/issues/37127

**Comment by GrabYourPitchforks** [comment] 2020-05-30 23:16
Closing as dupe.

**Closed by GrabYourPitchforks** 2020-05-30 23:16 UTC
