### ISSUE TITLE
Error When Creating an AKS cluster

### ISSUE THREAD

**Issue by RafaelJovel** [dotnet/core#4766] opened 2020-05-31 05:27 UTC
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/azure-resources
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

`PS C:\WINDOWS\system32> az aks create --resource-group myMicroserviceResources --name myMicroserviceCluster --node-count 1 --enable-addons http_application_routing --generate-ssh-keys`

```
Finished service principal creation[##################################]  100.0000%
Operation failed with status: 'Bad Request'. Details: The VM size of AgentPoolProfile:nodepool1 is not allowed in your subscription in location 'westus'. The available VM sizes are Standard_A2,Standard_A3,Standard_A4,Standard_A5,Standard_A6,Standard_A7,Standard_D1,Standard_D11,Standard_D12,Standard_D13,Standard_D14,Standard_D16_v3,Standard_D16s_v3,Standard_D2,Standard_D2_v3,Standard_D2s_v3,Standard_D3,Standard_D32_v3,Standard_D32s_v3,Standard_D4,Standard_D48_v3,Standard_D48s_v3,Standard_D4_v3,Standard_D4s_v3,Standard_D64_v3,Standard_D64s_v3,Standard_D8_v3,Standard_D8s_v3,Standard_E16_v3,Standard_E16s_v3,Standard_E2_v3,Standard_E2s_v3,Standard_E32-16s_v3,Standard_E32-8s_v3,Standard_E32_v3,Standard_E32s_v3,Standard_E48_v3,Standard_E48s_v3,Standard_E4_v3,Standard_E4s_v3,Standard_E64-16s_v3,Standard_E64-32s_v3,Standard_E64_v3,Standard_E64i_v3,Standard_E64is_v3,Standard_E64s_v3,Standard_E8_v3,Standard_E8s_v3,Standard_F16s_v2,Standard_F2s_v2,Standard_F32s_v2,Standard_F48s_v2,Standard_F4s_v2,Standard_F64s_v2,Standard_F72s_v2,Standard_F8s_v2,Standard_H16,Standard_H16m,Standard_H16mr,Standard_H16r,Standard_H8,Standard_H8m,Standard_L16s_v2,Standard_L32s_v2,Standard_L48s_v2,Standard_L64s_v2,Standard_L80s_v2,Standard_L8s_v2 For more details, please visit https://aka.ms/cpu-quota
```

**Comment by mairaw** [comment] 2020-07-08 02:10
The PM suggested on https://github.com/dotnet/core/issues/3824#issuecomment-640771552 that you ask about this on the AKS forum:
https://docs.microsoft.com/answers/topics/azure-kubernetes-service.html

If you post it there, share a link with us in case someone else runs into the same issue.

**Comment by mairaw** [comment] 2020-07-08 02:11
Duplicate of #3824

**Closed by mairaw** 2020-07-08 02:10 UTC
