### ISSUE TITLE
publishing from cmd line looses embedded resource

### ISSUE THREAD

**Issue by alexms2001** [dotnet/core#3119] opened 2019-07-30 13:35 UTC
Publishing from cmd line looses embedded resource

Binary published from within Visual Studio extracts embedded resource correctly; publishing thru "dotnet publish" command DOES NOT.

Sample project is attached, test results:

/***    TextResource when the app is published by PublishReleaseX64ExeDotNetPublished.cmd command:
//      (embedded text file contents is not extracted at all)
C:\...ceTest\FileAsEmbeddedResourceTest\ReleaseX64ExeDotNetPublished>FileAsEmbeddedResourceTest.exe
StringAsTextResource = 'Contents of StringAsResource'
TextResource='**..\TextResource.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8**'
Press ENTER to terminate...
/***/
/***    TextResource when the app is published using ReleaseX64ExeVisualStudioPublished.pubxml profile from inside Visual Studio
//      (embedded text file contents is extracted correctly)
C:\...\FileAsEmbeddedResourceTest\ReleaseX64ExeVisualStudioPublished>FileAsEmbeddedResourceTest.exe
StringAsTextResource = 'Contents of StringAsResource'
TextResource='**Contents of TextResource.txt**'
Press ENTER to terminate...
/***/
/***    TextResource when the app is published by PublishReleaseX86ExeDotNetPublished.cmd command:
//      (embedded text file contents is not extracted at all)
C:\...esourceTest\FileAsEmbeddedResourceTest\ReleaseX86ExeDotNetPublished>FileAsEmbeddedResourceTest.exe
StringAsTextResource = 'Contents of StringAsResource'
TextResource='**..\TextResource.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8**'
Press ENTER to terminate...
/***    TextResource when the app is published using ReleaseX86ExeVisualStudioPublished.pubxml profile from inside Visual Studio
//      (embedded text file contents is extracted correctly)
C:\...urceTest\FileAsEmbeddedResourceTest\ReleaseX86VisualStudioPublished>FileAsEmbeddedResourceTest.exe
StringAsTextResource = 'Contents of StringAsResource'
TextResource= '**Contents of TextResource.txt**'
Press ENTER to terminate...
/***/

[FileAsEmbeddedResourceTest.zip](https://github.com/dotnet/core/files/3446983/FileAsEmbeddedResourceTest.zip)

**Comment by carlossanlop** [comment] 2019-07-31 20:39
@livarcocc @nguerrera would you be the best contacts to help with this issue using "dotnet publish"?

**Comment by dasMulli** [comment] 2019-07-31 20:59
This is likely a dupe of https://github.com/microsoft/msbuild/issues/2221 - only the 3.0 SDK on netcoreapp3.0 can deal with non-string resources. Meanwhile only the "full" msbuild.exe can embed files.

**Comment by alexms2001** [comment] 2019-07-31 23:06
@carlossanlop: not sure I understand your comment. The whole point is in publishing vs msbuild, One side of my comparison is exactly "dotnet publish".
@dasMulli As for "string" vs "non-string" resources - the problem in .NET Core 2.2 is that it does not treat not "non-string" but files that have an extension different from ".txt" (?!). Yes, file name EXTENSION, of all things, determines whether the embedded file will be extracted correctly. "myScript.sql" will not, "myScript.txt with identical contents will (??!!). 
So it looks that it's not "string/non-string". Btw, binaries embed themselves just fine (MyPicture.png and friends).
But for the process to depend on FILE NAME EXTENSION? I'd prefer humidity or wind direction as a factor.

**Comment by carlossanlop** [comment] 2019-09-27 18:50
No followup since July. @dasMulli mentioned a possible dupe. Closing. @alexms2001 please open an issue in that repo if you are still seeing problems.

**Closed by carlossanlop** 2019-09-27 18:50 UTC
