### ISSUE TITLE
did anyone bvt this documentation ?

### ISSUE THREAD

**Issue by maxcli** [dotnet/core#4123] opened 2020-01-14 23:17 UTC
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by maxcli** [comment] 2020-01-14 23:18
invalid yaml. Is this --- the probelm ?

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mymicroservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mymicroservice
    spec:
      containers:
      - name: mymicroservice
        image: [YOUR DOCKER ID]/mymicroservice:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
---

**Comment by maxcli** [comment] 2020-01-14 23:21
seems to work after removing the  ---  in 2 locations.
Yes , i did change my 'YOUR DOCKER ID'

**Comment by carlossanlop** [comment] 2020-01-15 00:10
@maxcli doesn't seem to be actionable from our side since you seem to have found the root cause. Closing, but feel free to reopen if there's a specific question for us to help you with.

**Closed by carlossanlop** 2020-01-15 00:10 UTC
