### ISSUE TITLE
dependencies issues linux ubuntu 18.04

### ISSUE THREAD

**Issue by sname** [dotnet/core#2628] opened 2019-04-23 16:17 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/runtime-current
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

---------------------------------------------------------------------------------------

sudo apt-get install aspnetcore-runtime-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 aspnetcore-runtime-2.2 : Depends: dotnet-runtime-2.2 (>= 2.2.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

------------------------------------------------------------------------------------------
sudo apt-get install aspnetcore-runtime-2.2 dotnet-runtime-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-2.2 : Depends: dotnet-runtime-deps-2.2 (>= 2.2.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

------------------------------------------------------------------------------------------
sudo apt-get install aspnetcore-runtime-2.2 dotnet-runtime-2.2 dotnet-runtime-deps-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-deps-2.2 : Depends: libssl1.0.0 but it is not installable
                           Depends: libicu60 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by dagood** [comment] 2019-04-24 15:50
Odd... `libssl1.0.0` and `libicu60` are normally available for Ubuntu 18.04.

* Have you disabled any package repos?
* Are you running a different distro and following the 18.04 instructions because they seem to be the closest?

This is where they should be coming from, in a typical install:

```
...
Get:2 http://archive.ubuntu.com/ubuntu bionic/main amd64 libicu60 amd64 60.2-3ubuntu3 [8054 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libssl1.0.0 amd64 1.0.2n-1ubuntu5.3 [1088 kB]
...
```

**Comment by Half-Shot** [comment] 2019-04-24 21:33
I wonder if @sname meant 19.04, because that is the issue I am seeing: Ubuntu 19.04 now includes *only* `libssl1.1.0` and `libicu64`

**Comment by dagood** [comment] 2019-04-24 21:45
If so, this is a duplicate of https://github.com/dotnet/core/issues/2526. My understanding is it's `libssl1.1`/`libicu63`, not `libssl1.1.0`/`libicu64`, though.

**Comment by karelz** [comment] 2019-04-27 18:59
@sname any udpate?

**Comment by karelz** [comment] 2019-05-17 20:41
No response, closing.

**Closed by karelz** 2019-05-17 20:41 UTC
Labels: needs more info

**Comment by luipir** [comment] 2019-06-12 11:04
new dependency erro rin Ubuntu 18.04 (sorry in spanish... but dependencies are clear)... at the end can't find libicu55

***************

root@dev-laptop:/tmp# apt-get install dotnet-sdk-2.2
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
No se pudieron instalar algunos paquetes. Esto puede significar que
usted pidió una situación imposible o, si está usando la distribución
inestable, que algunos paquetes necesarios aún no se han creado o se
han sacado de «Incoming».
La siguiente información puede ayudar a resolver la situación:

Los siguientes paquetes tienen dependencias incumplidas:
 dotnet-sdk-2.2 : Depende: aspnetcore-runtime-2.2 (>= 2.2.5) pero no va a instalarse
                  Depende: dotnet-runtime-2.2 (>= 2.2.5) pero no va a instalarse
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos.
root@dev-laptop:/tmp# apt install dotnet-runtime-2.2
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
No se pudieron instalar algunos paquetes. Esto puede significar que
usted pidió una situación imposible o, si está usando la distribución
inestable, que algunos paquetes necesarios aún no se han creado o se
han sacado de «Incoming».
La siguiente información puede ayudar a resolver la situación:

Los siguientes paquetes tienen dependencias incumplidas:
 dotnet-runtime-2.2 : Depende: dotnet-runtime-deps-2.2 (>= 2.2.5) pero no va a instalarse
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos.
root@dev-laptop:/tmp# apt install dotnet-runtime-deps-2.2
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
No se pudieron instalar algunos paquetes. Esto puede significar que
usted pidió una situación imposible o, si está usando la distribución
inestable, que algunos paquetes necesarios aún no se han creado o se
han sacado de «Incoming».
La siguiente información puede ayudar a resolver la situación:

Los siguientes paquetes tienen dependencias incumplidas:
 dotnet-runtime-deps-2.2 : Depende: libicu55 pero no es instalable
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos.
root@dev-laptop:/tmp# apt install libicu55
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
El paquete libicu55 no está disponible, pero algún otro paquete hace referencia
a él. Esto puede significar que el paquete falta, está obsoleto o sólo se
encuentra disponible desde alguna otra fuente

E: El paquete «libicu55» no tiene un candidato para la instalación

**Comment by luipir** [comment] 2019-06-12 11:06
cvhecjking if https://github.com/dotnet/core-setup/issues/4703

**Comment by luipir** [comment] 2019-06-12 13:40
> checking if [dotnet/core-setup#4703](https://github.com/dotnet/core-setup/issues/4703)

works!
