### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by mahdi16110** [dotnet/core#7054] opened 2021-12-18 08:08 UTC
The problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything relevant. The IDE is crushing in a short moment

**Comment by jeffhandley** [comment] 2021-12-22 06:10
Hi @mahdi16110. I was unable to reproduce this issue from that tutorial. I'm going to close this issue, but if you can provide more details such as which IDE/version you were using, and any other information that could help us investigate, please submit a new issue.

**Closed by jeffhandley** 2021-12-22 06:10 UTC
