### ISSUE TITLE
.net installation problem

### ISSUE THREAD

**Issue by anupshivram** [dotnet/core#3223] opened 2019-08-21 04:26 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by dagood** [comment] 2019-08-21 04:33
Duplicate of https://github.com/dotnet/core/issues/3221

**Comment by dagood** [comment] 2019-08-21 04:33
Let us know if the duplicate isn't correct, there isn't enough info in the issue to know for sure.

**Closed by dagood** 2019-08-21 04:33 UTC
