### ISSUE TITLE
Problem running dotnet run command

### ISSUE THREAD

**Issue by jgp023** [dotnet/core#4093] opened 2020-01-08 18:34 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

hello world does not populate in the terminal. the error message says 
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly '/Users/jordan_g.o.a.t./myApp/bin/Debug/netcoreapp3.1/myApp.dll'. The system cannot find the file specified.
<img width="1439" alt="Screen Shot 2020-01-08 at 12 34 00 PM" src="https://user-images.githubusercontent.com/39812030/72005408-2719ef80-3213-11ea-9563-5be9690543f4.png">

File name: '/Users/jordan_g.o.a.t./myApp/bin/Debug/netcoreapp3.1/myApp.dll'

**Comment by scalablecory** [comment] 2020-01-14 20:56
@jeffschwMSFT what would cause this?

**Comment by jeffschwMSFT** [comment] 2020-01-14 21:02
@lpereira did we investigate paths that have '.'s at the end?  What was the outcome?

**Comment by lpereira** [comment] 2020-01-14 21:06
We did; the issue is that Windows ignores the `.` in a path name if it precedes a `/`, so the function to convert a Unix path name to a Windows pathname will strip it.  I decided not to fix this in order to keep it compatible with Windows; however, I remember @mateoatr looking at this right after he joined the team and sending a PR to not strip that dot on Unix.  I think that PR has been merged.

**Comment by mateoatr** [comment] 2020-01-14 21:45
[This](https://github.com/dotnet/runtime/pull/459) is the PR for reference.

**Comment by carlossanlop** [comment] 2020-02-21 21:25
The fix for this issue has been merged. @mateoatr, in which version should we expect the fix to be available?

**Comment by mateoatr** [comment] 2020-02-24 16:02
This should've been working since 3.1.1, however I just ran into the same problem. I'll take a look at it.

**Comment by carlossanlop** [comment] 2020-09-09 23:15
@mateoatr did you get a chance to take a look?

**Comment by mateoatr** [comment] 2020-09-15 23:52
> @mateoatr did you get a chance to take a look?

The aforementioned PR was merged for .NET 5 - not .NET Core 3.1 (my bad); so this is currently working. If necessary I can backport the PR to 3.1.

**Closed by mateoatr** 2020-09-15 23:52 UTC

**Comment by mairaw** [comment] 2020-09-15 23:57
The tutorials on the dotnet.microsoft.com won't be upgraded until we reach .NET 6, since we'll keep using the LTS version. 
Is that a common issue?

**Comment by mateoatr** [comment] 2020-09-16 00:07
I don't know how common it is, I'd guess not too common. And, realistically, it only affects Unix, since ending a directory name with a period violates Windows' naming conventions.
