### ISSUE TITLE
Add git tags for the actual release version

### ISSUE THREAD

**Issue by eerhardt** [dotnet/core#5748] opened 2020-12-09 19:29 UTC
For 5.0, so far we have shipped 2 released versions (see https://dotnet.microsoft.com/download/dotnet/5.0):

* 5.0.0
* 5.0.1

However, the git tags in https://github.com/dotnet/runtime/tags don't have these versions. Instead, they appear to have daily builds:

![image](https://user-images.githubusercontent.com/8291187/101676612-0066c900-3a21-11eb-859f-26eae5376b95.png)

Instead, we should have tags whose names match the version that was shipped, so users can `git checkout v5.0.0`, and have the exact code that was used to release that version.

Every other major OSS product I'm aware of does it this way:

* https://github.com/microsoft/vscode/tags
* https://github.com/torvalds/linux/tags
* https://github.com/chromium/chromium/tags
* https://github.com/tensorflow/tensorflow/tags
* https://github.com/apache/spark/tags

cc @Anipik @leecow @richlander

**Comment by Anipik** [comment] 2020-12-14 18:51
tags are fixed for runtime, moving to core

**Comment by ViktorHofer** [comment] 2020-12-14 19:09
Did you leave the old git tags to not break people who already rely on them?

**Comment by Anipik** [comment] 2020-12-14 19:23
No i deleted them. This was more of a regression as in 3.1 and 2.1 we never used the build number in tags. 
I thought we should not keep the wrong release tags as there is an easy workaround. 

We can bring the old tags back if we are worried that its not the correct approach. cc @ericstj

**Comment by ViktorHofer** [comment] 2020-12-14 19:35
Deleting a tag is a breaking change, you can't argue about that. The whole reason why git tags exist is to allow depending on a node without hardcoding the SHA. Please undo the deletion.

**Comment by eerhardt** [comment] 2021-01-04 20:35
> moving to core

Why was this moved? Why wasn't it just closed in `dotnet/runtime`?

**Comment by mairaw** [comment] 2021-01-05 03:21
@Anipik I also don't think this issue makes sense in the dotnet/core repo.

**Comment by Anipik** [comment] 2021-01-11 18:38
@rbhanda told me to move this one to core. probably because other repos are also hitting this.

> Why wasn't it just closed in dotnet/runtime?

the tooling around this still needs to be fixed

**Comment by rbhanda** [comment] 2021-02-04 04:31
https://github.com/dotnet/runtime/releases/tag/v5.0.2 - This issue should be resolved going forward.

**Closed by rbhanda** 2021-02-04 04:31 UTC
