### ISSUE TITLE
about default interface method?

### ISSUE THREAD

**Issue by cc1072027237** [dotnet/core#7814] opened 2022-09-19 17:28 UTC
this doesn't seem normal, is it my problem?

.NET CORE 6.0 / VISUAL STUDIO 2022

`
        interface TestInterface : IDisposable, IAsyncDisposable
        {
            ValueTask IAsyncDisposable.DisposeAsync()
            {
                this.Dispose();
                return ValueTask.CompletedTask;
            }
        }

        class TestClass : TestInterface
        {
            public void Dispose()
            {
                // nothing to do
            }
        }

        void Test()
        {
            TestClass testClass = new TestClass();
            testClass.DisposeAsync(); // ERROR: CS1061 can't find method

            TestInterface testInterface = testClass;
            testInterface.DisposeAsync(); // OK
        }
`

**Comment by vitek-karas** [comment] 2022-09-27 20:41
Defining method like this:
```C#
class Test : IAsyncDisposable
{
    ValueTask IAsyncDisposable.DisposeAsync()
    {
        return ValueTask.CompletedTask;
    }
}

void Test()
{
    Test t = new ();
    t.DisposeAsync(); <-- doesn't exist
    ((IAsyncDisposable)t).DisposeAsync();  <-- works
}
```

The explicit interface implementation will create a method which is sort of "hidden" and is only supposed to be called through the interface it belongs to.

This should have no dependency on default interface methods, this behavior should be the same on normal classes as well.

**Comment by GrabYourPitchforks** [comment] 2022-10-25 23:57
Appears to have been answered. Please close the issue if the issue is resolved or respond back if you require further assistance. Thanks!

**Closed** 2022-10-31 19:10 UTC
Labels: needs-more-info, area-csharp
