### ISSUE TITLE
dotnet sdk unable

### ISSUE THREAD

**Issue by photharlay** [dotnet/core#4637] opened 2020-05-03 02:13 UTC
# Issue Title

Be as descriptive as you can with your title.
Unable to locate package dotnet-sdk-3.1
# General

Provide details on the problem you are experiencing including the .NET Core version, operating system version and anything else that is relevant.

Please provide a code sample for your issue if it is relevant, either inline, link to a gist (or similar) or add it as a zipped attachment.

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

ubuntu 20.04 lts version unable to locate package dotnet-sdk-3.1 and other.please, do you give me this problems?

**Comment by svick** [comment] 2020-05-03 07:46
See https://github.com/dotnet/core/issues/4360. There are no official packages for Ubuntu 20.04 yet, though if you want, you can try the workarounds mentioned in that issue.

**Comment by mairaw** [comment] 2020-05-03 19:16
Duplicate of #4360

**Closed by mairaw** 2020-05-03 19:16 UTC
