### ISSUE TITLE
Slow build times with .NET Core SDK 3.0 preview2

### ISSUE THREAD

**Issue by henkmollema** [dotnet/core#2323] opened 2019-02-16 20:56 UTC
I'm experiencing very slow build times (20+) seconds when building (clean) projects with the .NET Core 3.0 preview2 SDK.

Repro steps:
1. `dotnet new console`
2. `dotnet build`

Incremental builds are fast as expected. After `dotnet clean` they're slow. This happens for all kind of projects, console, ASP.NET Core, Razor Components, etc.

Example with performance output:

```
❯ dotnet build /clp:PerformanceSummary
Microsoft (R) Build Engine version 16.0.385-preview+g966cdf2ac6 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 14,59 ms for C:\tmp\console30\console30.csproj.
C:\Program Files\dotnet\sdk\3.0.100-preview-010184\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [C:\tmp\console30\console30.csproj]
  console30 -> C:\tmp\console30\bin\Debug\netcoreapp3.0\console30.dll

Project Evaluation Performance Summary:
      206 ms  C:\tmp\console30\console30.csproj          3 calls

Project Performance Summary:
    21282 ms  C:\tmp\console30\console30.csproj          7 calls
                190 ms  Restore                                    1 calls
                  1 ms  _IsProjectRestoreSupported                 2 calls
                  1 ms  _GenerateRestoreProjectPathWalk            1 calls
                 48 ms  _GenerateRestoreGraphProjectEntry          1 calls
                  4 ms  _GenerateProjectRestoreGraph               1 calls
              21039 ms  Build                                      1 calls

Target Performance Summary:
        <omitted irrelevant targets>
        4 ms  PrepareForBuild                            1 calls
        4 ms  _HandlePackageFileConflicts                1 calls
        4 ms  _GetAllRestoreProjectPathItems             1 calls
        5 ms  RunProduceContentAssets                    1 calls
        7 ms  CopyFilesToOutputDirectory                 1 calls
        9 ms  FindReferenceAssembliesForReferences       1 calls
       13 ms  _CopyOutOfDateSourceItemsToOutputDirectory   1 calls
       14 ms  ResolvePackageAssets                       1 calls
       17 ms  _GetRestoreSettings                        1 calls
       21 ms  GenerateBuildDependencyFile                1 calls
       21 ms  ResolveTargetingPacks                      1 calls
       23 ms  ResolveFrameworkReferences                 2 calls
       36 ms  _CreateAppHost                             1 calls
       39 ms  GenerateBuildRuntimeConfigurationFiles     1 calls
       41 ms  ResolveProjectReferences                   1 calls
       54 ms  _FilterRestoreGraphProjectInputItems       1 calls
       55 ms  _GenerateRestoreGraph                      1 calls
       68 ms  Restore                                    1 calls
      135 ms  ResolveAssemblyReferences                  1 calls
    20653 ms  CoreCompile                                1 calls

Task Performance Summary:
       <omitted irrelevant tasks>
        4 ms  ResolvePackageFileConflicts                1 calls
        4 ms  GetPackageDirectory                        2 calls
        4 ms  ProduceContentAssets                       1 calls
        5 ms  WarnForInvalidProjectsTask                 1 calls
       13 ms  ResolvePackageAssets                       1 calls
       17 ms  GetRestoreSettingsTask                     1 calls
       19 ms  Copy                                       3 calls
       20 ms  GenerateDepsFile                           1 calls
       22 ms  ResolveFrameworkReferences                 2 calls
       35 ms  CreateAppHost                              1 calls
       39 ms  GenerateRuntimeConfigurationFiles          1 calls
       68 ms  RestoreTask                                1 calls
       95 ms  MsBuild                                    7 calls
      134 ms  ResolveAssemblyReference                   1 calls
    20651 ms  Csc                                        1 calls

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:21.47
```

As you can see the compile task tasks about 20 seconds. Is it possible that some time-out is causing this issue, similar to the issue described here: https://github.com/aspnet/Razor/issues/2406. There was a problem with creating named pipes and spaces in one's username.

Building with debug verbosity hangs at this part:

```
Building target "CoreCompile" completely.
Output file "obj\Debug\netcoreapp3.0\console30.dll" does not exist.
Using "Csc" task from assembly "C:\Program Files\dotnet\sdk\3.0.100-preview-010184\Roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll".
Task "Csc"
   C:\Program Files\dotnet\dotnet.exe exec "C:\Program Files\dotnet\sdk\3.0.100-preview-010184\Roslyn\bincore\csc.dll" <the compiler args...>
Using shared compilation with compiler from directory: C:\Program Files\dotnet\sdk\3.0.100-preview-010184\Roslyn\bincore
```

Then after 20 seconds the compile tasks completes with:
```
         Microsoft (R) Visual C# Compiler version 3.0.19.6714 (359844cc)
         Copyright (C) Microsoft Corporation. All rights reserved.

       Done executing task "Csc".
       Task "CallTarget" skipped, due to false condition; ('$(TargetsTriggeredByCompilation)' != '') was evaluated as ('' != '').
   1:7>Done building target "CoreCompile" in project "console30.csproj".
```

It seems like it takes 20 seconds to load Roslyn.

**.NET Core version**

```
❯ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010184
 Commit:    c57bde4593
```

<details><summary>Full output</summary>

```
❯ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010184
 Commit:    c57bde4593

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-010184\

Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010184 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27325-3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

</details>

**Comment by karelz** [comment] 2019-02-17 08:56
Are you able to reproduce it on more than 1 machine?
Are you able to reproduce it on more than 1 project? (what about some dummy HelloWorld?)

**Comment by henkmollema** [comment] 2019-02-17 10:42
> Are you able to reproduce it on more than 1 machine?
I'm unable to test it on another machine today. I'll let you know tomorrow.

> Are you able to reproduce it on more than 1 project? (what about some dummy HelloWorld?)

Yes, it repros with every project I create using .NET Core 3.0. Using .NET Core 2.2 the build times are fast as expected.

**Comment by henkmollema** [comment] 2019-02-17 11:23
Building apps with Razor views/pages takes 40+ seconds (twice as much) and hangs twice at loading Roslyn. Once for compiling C# code and once for compiling the Razor views.

**Comment by henkmollema** [comment] 2019-02-17 13:32
@karelz update: I've been able to reproduce this issue on another machine. The issue occurs when I'm using a user account with a space in the username (e.g. `henk mollema`). The problem goes away when I change to another account (on the same machine) *without* a space in the username (e.g. `henk`).

**Comment by henkmollema** [comment] 2019-02-17 15:20
Removing the whitespace from my username resolved the issue.

**Comment by karelz** [comment] 2019-02-18 04:17
@livarcocc @nguerrera can you please help route it?

**Comment by livarcocc** [comment] 2019-02-18 04:20
@jaredpar to comment. I believe this issue is actually on roslyn and the vbcscompiler.

**Comment by davidfowl** [comment] 2019-02-18 04:22
cc @rynowak @pranavkm

**Comment by nguerrera** [comment] 2019-02-18 04:24
Duplicate of https://github.com/dotnet/roslyn/issues/33452

**Closed** 2019-02-18 04:25 UTC
Labels: needs more info
