### ISSUE TITLE
[FAIL] Nuget crashing on restoring all packages, was working 30 minutes ago. SSL error!!! (The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain)

### ISSUE THREAD

**Issue by darkguy2008** [dotnet/core#5884] opened 2021-01-27 12:24 UTC
### Description

It all boils down to these errors coming from https://api.nuget.org/v3/index.json . I can't build or even work anymore. **HELP!**

The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain

The author primary signature validity period has expired.

### Configuration

.NET 5

### Regression?

It worked 30 minutes ago. Working on CI/CD...

### Other information

```
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
API.csproj : error NU3028: Package 'System.Security.Cryptography.Cng 4.5.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
API.csproj : error NU3037: Package 'System.Security.Cryptography.Cng 4.5.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
API.csproj : error NU3028: Package 'System.Security.Cryptography.Cng 4.5.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
Dependency.csproj : error NU3028: Package 'Microsoft.CSharp 4.5.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [API.csproj]
Dependency.csproj : error NU3037: Package 'Microsoft.CSharp 4.5.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired. [API.csproj]
Dependency.csproj : error NU3028: Package 'Microsoft.CSharp 4.5.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [API.csproj]
Dependency.csproj : error NU3028: Package 'Microsoft.IdentityModel.Tokens 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [API.csproj]
Dependency.csproj : error NU3037: Package 'Microsoft.IdentityModel.Tokens 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired. [API.csproj]
Dependency.csproj : error NU3028: Package 'Microsoft.IdentityModel.Tokens 6.7.1' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [API.csproj]
Dependency.csproj : error NU3028: Package 'Microsoft.IdentityModel.JsonWebTokens 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [API.csproj]
Dependency.csproj : error NU3037: Package 'Microsoft.IdentityModel.JsonWebTokens 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired. [API.csproj]
Dependency.csproj : error NU3028: Package 'Microsoft.IdentityModel.JsonWebTokens 6.7.1' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [API.csproj]
Dependency.csproj : error NU3028: Package 'Microsoft.IdentityModel.Protocols 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [API.csproj]
Dependency.csproj : error NU3037: Package 'Microsoft.IdentityModel.Protocols 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired. [API.csproj]
Dependency.csproj : error NU3028: Package 'Microsoft.IdentityModel.Protocols 6.7.1' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [API.csproj]
Dependency.csproj : error NU3028: Package 'System.IdentityModel.Tokens.Jwt 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [API.csproj]
Dependency.csproj : error NU3037: Package 'System.IdentityModel.Tokens.Jwt 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired. [API.csproj]
Dependency.csproj : error NU3028: Package 'System.IdentityModel.Tokens.Jwt 6.7.1' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [API.csproj]
Dependency.csproj : error NU3028: Package 'Microsoft.AspNetCore.Authentication.JwtBearer 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [API.csproj]
Dependency.csproj : error NU3028: Package 'Microsoft.IdentityModel.Protocols.OpenIdConnect 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [API.csproj]
Dependency.csproj : error NU3037: Package 'Microsoft.AspNetCore.Authentication.JwtBearer 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired. [API.csproj]
Dependency.csproj : error NU3037: Package 'Microsoft.IdentityModel.Protocols.OpenIdConnect 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired. [API.csproj]
Dependency.csproj : error NU3028: Package 'Microsoft.AspNetCore.Authentication.JwtBearer 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [API.csproj]
Dependency.csproj : error NU3028: Package 'Microsoft.IdentityModel.Protocols.OpenIdConnect 6.7.1' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [API.csproj]
Dependency.csproj : error NU3028: Package 'Microsoft.IdentityModel.Logging 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [API.csproj]
Dependency.csproj : error NU3037: Package 'Microsoft.IdentityModel.Logging 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired. [API.csproj]
Dependency.csproj : error NU3028: Package 'Microsoft.IdentityModel.Logging 6.7.1' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [API.csproj]
API.csproj : error NU3028: Package 'Microsoft.IdentityModel.Protocols 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
API.csproj : error NU3037: Package 'Microsoft.IdentityModel.Protocols 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
API.csproj : error NU3028: Package 'Microsoft.IdentityModel.Protocols 6.7.1' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
API.csproj : error NU3028: Package 'Microsoft.IdentityModel.Tokens 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
API.csproj : error NU3037: Package 'Microsoft.IdentityModel.Tokens 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
API.csproj : error NU3028: Package 'Microsoft.IdentityModel.Tokens 6.7.1' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
API.csproj : error NU3028: Package 'System.IdentityModel.Tokens.Jwt 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
API.csproj : error NU3037: Package 'System.IdentityModel.Tokens.Jwt 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
API.csproj : error NU3028: Package 'System.IdentityModel.Tokens.Jwt 6.7.1' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
API.csproj : error NU3028: Package 'Microsoft.AspNetCore.Authentication.JwtBearer 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
API.csproj : error NU3037: Package 'Microsoft.AspNetCore.Authentication.JwtBearer 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
API.csproj : error NU3028: Package 'Microsoft.AspNetCore.Authentication.JwtBearer 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
API.csproj : error NU3028: Package 'Microsoft.IdentityModel.Protocols.OpenIdConnect 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
API.csproj : error NU3037: Package 'Microsoft.IdentityModel.Protocols.OpenIdConnect 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
API.csproj : error NU3028: Package 'Microsoft.IdentityModel.Protocols.OpenIdConnect 6.7.1' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
API.csproj : error NU3028: Package 'Microsoft.IdentityModel.JsonWebTokens 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
API.csproj : error NU3037: Package 'Microsoft.IdentityModel.JsonWebTokens 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
API.csproj : error NU3028: Package 'Microsoft.IdentityModel.JsonWebTokens 6.7.1' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
Dependency.csproj : error NU3028: Package 'System.Security.Cryptography.Cng 4.5.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [API.csproj]
Dependency.csproj : error NU3037: Package 'System.Security.Cryptography.Cng 4.5.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired. [API.csproj]
Dependency.csproj : error NU3028: Package 'System.Security.Cryptography.Cng 4.5.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [API.csproj]
API.csproj : error NU3028: Package 'Microsoft.CSharp 4.5.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
API.csproj : error NU3037: Package 'Microsoft.CSharp 4.5.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
API.csproj : error NU3028: Package 'Microsoft.CSharp 4.5.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
API.csproj : error NU3028: Package 'Microsoft.IdentityModel.Logging 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
API.csproj : error NU3037: Package 'Microsoft.IdentityModel.Logging 6.7.1' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
API.csproj : error NU3028: Package 'Microsoft.IdentityModel.Logging 6.7.1' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
  Failed to restore API.csproj (in 2.43 sec).
  Failed to restore Dependency.csproj (in 2.42 sec).

Build FAILED.
```

**Comment by TomyCesaille** [comment] 2021-01-27 13:29
Same, this is related to <https://devblogs.microsoft.com/nuget/microsoft-author-signing-certificate-update/>

It seems the official docker images aren't signing the new certificate.

**Comment by dasMulli** [comment] 2021-01-27 13:31
Duplicate of https://github.com/NuGet/Home/issues/10491

**Comment by mairaw** [comment] 2021-01-27 18:37
Closing since there's another issue for this in the nuget org.

**Closed by mairaw** 2021-01-27 18:37 UTC
Labels: duplicate

**Comment by darkguy2008** [comment] 2021-01-28 00:01
Thanks, managed to fix it by switching my build from `buster-slim` to `focal`. Great support! :)

**Comment by sguryev** [comment] 2021-01-30 15:37
https://github.com/NuGet/Home/issues/10491#issuecomment-769610324

**Comment by errorsolve** [comment] 2021-02-02 13:45
All Possible Solution added At [[solved] The author primary signature’s timestamp found a chain building issue: UntrustedRoot: self-signed certificate in certificate chain](https://exerror.com/the-author-primary-signatures-timestamp-found-a-chain-building-issue-untrusted/)

**Comment by rebeccapowell** [comment] 2021-02-25 18:24
The root cause of this error is that the root certificate that was tied to the intermediary CA, and thus the package signer, is missing from the machine and dotnet restore cannot validate the signer without it.

In order to establish which package and which root certificate is missing you can use `dotnet restore` in the following configuration, replacing your path and solution name (you can also target a specific csproj file as well):

```
dotnet restore "./src/Your-Solution.sln" -v d
```

The output of that will show you the certificate chain where the problem lies:

```
Package 'Newtonsoft.Json 10.0.1' from source 'https://api.nuget.org/v3/index.json': Verifying the repository primary signature with certificate: 
           Subject Name: CN=NuGet.org Repository by Microsoft, O=NuGet.org Repository by Microsoft, L=Redmond, S=Washington, C=US
           SHA1 hash: 8FB6D7FCF7AD49EB774446EFE778B33365BB7BFB
           SHA256 hash: 0E5F38F57DC1BCC806D8494F4F90FBCEDD988B46760709CBEEC6F4219AA6157D
           Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
           Valid from: 10/04/2018 01:00:00 to 14/04/2021 13:00:00
         
         Package 'Newtonsoft.Json 10.0.1' from source 'https://api.nuget.org/v3/index.json':       Subject Name: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
               SHA1 hash: 92C1588E85AF2201CE7915E8538B492F605B80C6
               SHA256 hash: 51044706BD237B91B89B781337E6D62656C69F0FCFFBE8E43741367948127862
               Issued by: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
               Valid from: 22/10/2013 13:00:00 to 22/10/2028 13:00:00
         
                     Subject Name: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
                     SHA1 hash: 0563B8630D62D75ABBC8AB1E4BDFB5A899B24D43
                     SHA256 hash: 3E9099B5015E8F486C00BCEA9D111EE721FABA355A89BCF1DF69561E3DC6325C
                     Issued by: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
                     Valid from: 10/11/2006 00:00:00 to 10/11/2031 00:00:00
         
         
         Package 'Newtonsoft.Json 10.0.1' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's certificate chain validation failed with error(s): UntrustedRoot, RevocationStatusUnknown, OfflineRevocation
```

It is indented so that you can see the signing certificate chain. The last of which is the root certification authority. This root certificate needs to be installed on the server or machine that is restoring the packages. On Windows that can be done using the "Certificate Manager", accessible using `certmgr.exe` or `MMC.exe` and adding the snap-in "Certificates". You want to add the missing root certificate (assuming you trust it) to the "Trusted Root Certification Authorities" -> Certificates -> All Tasks -> Import.

In order to find the right certificate, you need to refer to the error message and then check the name, then download it from the respective authority. In this case the root authority is "DigiCert Assured ID Root CA" the OU is set to DigitCert.com. You can find the DigitCert certificates here: https://www.digicert.com/kb/digicert-root-certificates.htm

Find the right name in the list and download the CRT file to your machine. Then in the MMC Certificate manager import it to your local machine (not user certificates). Before you import it, you should check the SHA hashes / thumbprint match beforehand to double check you are installing the matching certificate. The package restore highlights the following:

```
SHA1 hash: 0563B8630D62D75ABBC8AB1E4BDFB5A899B24D43
SHA256 hash: 3E9099B5015E8F486C00BCEA9D111EE721FABA355A89BCF1DF69561E3DC6325C
```

And the DigiCert website highlights the following:

```
Serial #: 0C:E7:E0:E5:17:D8:46:FE:8F:E5:60:FC:1B:F0:30:39
SHA1 Fingerprint: 05:63:B8:63:0D:62:D7:5A:BB:C8:AB:1E:4B:DF:B5:A8:99:B2:4D:43
SHA256 Fingerprint: 3E:90:99:B5:01:5E:8F:48:6C:00:BC:EA:9D:11:1E:E7:21:FA:BA:35:5A:89:BC:F1:DF:69:56:1E:3D:C
```

Ignore the formatting. and the hashes match. You should probably check the downloaded certificate before installing it. Double clicking the CRT file in Windows allows you to open it in certificate view and the details tab shows the fingerprint. You could also use openssl on the command line (choco install openssl to install), but that's outside the scope of this comment.

If you are sure that you are happy to install this root certificate, you can then continue in the Certificates Manager. The CRT file will be imported in the Trusted Root Certification Authorities. The NuGet package will then be trusted when it gets restored because it can negotiate the certificate chain and validate the signer.

This is different to a common SSL error regarding certificate chains for nuget.org that some out of date server have. In that case the certificate root authority relating to the SSL certificate is missing from your machine, which changed back in November 2020. The same process applies. You can source the certificate from nuget.org in the browser and viewing the certificate chain and exporting the certificate, then reimporting it into your build server.

**Comment by jegasape** [comment] 2021-03-07 18:58
I'm having this same problem, when I try to run a **webapi** on my ubuntu machine and I get this error.

error NU3028: Package 'Microsoft.OpenApi 1.2.3' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain

error NU3037: Package 'Microsoft.OpenApi 1.2.3' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.

------------------------------------------------------------------------------------------------------------------------------------------------------------------------

.NET SDK (reflecting any global.json):
 Version:   5.0.200
 Commit:    70b3e65d53

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.10
 OS Platform: Linux
 RID:         ubuntu.20.10-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.200/

Host (useful for support):
  Version: 5.0.3
  Commit:  eae88cc11b

.NET SDKs installed:
  5.0.200 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Thanks!
