### ISSUE TITLE
NAudio broken with the latest update.

### ISSUE THREAD

**Issue by element109** [dotnet/core#6341] opened 2021-06-08 23:37 UTC
https://github.com/naudio/NAudio

NAudio 2 was working in version Core 5 until this update. It still works under Core 3.1 with its' latest update and in the .Net 4.8. 

The error is an access violation in native Win32.

**Comment by mairaw** [comment] 2021-06-08 23:58
Then please file an issue at their repo.

**Comment by element109** [comment] 2021-06-09 01:53
The behavior suggests a regression or the bug that was fixed may still exist in 2 other products.

**Comment by mairaw** [comment] 2021-06-09 04:43
Do you work on the naudio project? We'd need more information to be able to investigate the issue. Do you have different sources targeting the different TFMs?

**Comment by element109** [comment] 2021-06-09 13:46
I prepared a sample for you. The first solution is .Net Core and the second is .Net Framework the same code will run on .Net Core 3.0, 3.1, 5.06 but not 5.07. The code will also run on all versions of the .Net Framework. I created the projects and solutions in the same directory and Visual Studio 2019 does not behave well in this scenario. The workaround is to delete the obj folder when switching between the 2 solutions. I tested the app by opening an mp3 file in each version of the frameworks.

If you want to know more try adding both projects to the same solution and watch Visual Studio 2019's head explode.
[NAudio.zip](https://github.com/dotnet/core/files/6624192/NAudio.zip)

**Comment by michaelgsharp** [comment] 2021-06-14 23:43
This has been reported in NAudio as well. see https://github.com/naudio/NAudio/issues/789. The code works fine in the preview version of .net 6. Still trying to determine exactly what is causing this to direct it correctly.

**Comment by wzchua** [comment] 2021-06-15 04:54
The issue is being tracked in the runtime repo https://github.com/dotnet/runtime/issues/54132

**Comment by mairaw** [comment] 2021-06-15 05:08
Thanks @wzchua. Closing as dupe then.

**Closed by mairaw** 2021-06-15 05:08 UTC
