### ISSUE TITLE
Task.ContinueWith not called when using Task.Run on an async action

### ISSUE THREAD

**Issue by roy-t** [dotnet/core#2706] opened 2019-05-10 22:10 UTC
We've reduced the problem to the following few lines. Fails both in .net core 2.2 and .Net Framework 4.7.2 (using C# language level 7.3). On Windows 10 Pro 64bit (1809).

**Code:**
```c#
        static async Task Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            Foo(async () => throw new Exception("Oops"));            

            Console.ReadLine();
        }

        static void Foo(Action action)
        {
            Task.Run(action).ContinueWith(t =>
            {                
               Console.WriteLine(t.Exception);
            }, TaskContinuationOptions.OnlyOnFaulted);
        }
```

**Expected behavior:** 
The task fails, and continues by writing the exception to the console. Then the application resumes normally.

**Actual behavior**
The task fails and immediately crashes with an Unhandled Exception:

```
Unhandled Exception: System.Exception: Oops
   at ConsoleApp1.Program.<>c.<<Main>b__0_0>d.MoveNext() in D:\Projects\C#\ConsoleApp1\ConsoleApp1\Program.cs:line 12
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

If I remove the `async` modifier on line 5 everything works as expected. If I change `Action` on line 10 in `Func<Task>` again everything works as expected.

**Comment by SixFive7** [comment] 2019-05-10 22:12
I can confirm this behaviour on our environment:
Windows 10
.NET Core 2.2
C# 7.3
C#  (Visual Studio 2017)
Console app and also .NET Web API template

**Comment by roy-t** [comment] 2019-05-11 11:08
In hindsight this is probably an issue for CoreFX. So @SixFive7 has cross posted it to: https://github.com/dotnet/corefx/issues/37602

**Comment by karelz** [comment] 2019-06-05 03:34
Duplicate of https://github.com/dotnet/corefx/issues/37602

**Closed by karelz** 2019-06-05 03:34 UTC
