### ISSUE TITLE
While writing the command dotnet new console I am getting an error like this "It was not possible to find any installed .NET Core SDKs   Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:"

### ISSUE THREAD

**Issue by shantanu-joshi** [dotnet/core#6283] opened 2021-05-20 08:07 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by GrabYourPitchforks** [comment] 2021-05-21 21:49
Possible duplicate of https://github.com/dotnet/core/issues/5962. Review the discussion at that issue and see if the resolution steps detailed there work for you. If they don't, please respond back here and we'll try to assist further. Thanks!

**Closed** 2021-05-28 22:39 UTC
Labels: area-setup, needs-more-info
