### ISSUE TITLE
Ubuntu 18.04, Debian 9 can't update Microsoft linux package repository, "Mirror sync in progress?"

### ISSUE THREAD

**Issue by CommonLoon102** [dotnet/core#4179] opened 2020-01-24 22:52 UTC
I want to install .NET Core on Ubuntu but mirror sync in progress.
I could use snap but it is not possible to use snap in a dockerfile (because it would require a reboot, lol).

**Comment by setheen** [comment] 2020-01-24 22:58
FWIW, I'm seeing a similar issue
```
Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.gz  File has unexpected size (99442 != 99036). Mirror sync in progress? [IP: 40.76.35.62 443]
```

**Comment by CommonLoon102** [comment] 2020-01-24 23:00
Yes, same here:
```
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.gz  File has unexpected size (99442 != 99036). Mirror sync in progress? [IP: 13.80.10.205 443]
   Hashes of expected file:
    - Filesize:99036 [weak]
    - SHA512:4abba0aa1cf9eb4c98e14d41fc2bb9e2afb286815362bd5cbf3ec518fa9574bea40f0f767209c74bb903ee3338f71677ae5326bc04c1e692d09ecdc9909e3a2f
    - SHA256:81d40beca06cd32630406b3d769b6971b98e6c021a363cb92115bb55bb04a197
    - SHA1:f658c167b999091d90cbdcf2fd0d2c52ec60587b [weak]
    - MD5Sum:ff63a693e991eca112980b5348e7b069 [weak]
   Release file created at: Thu, 23 Jan 2020 17:58:24 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

```

**Comment by dagood** [comment] 2020-01-24 23:29
This is unfortunately known to happen from time to time: https://github.com/dotnet/core/issues/4167. It's been > 30 minutes since you filed this so I'll go ahead and file an IcM issue to get the team responsible for these repos on it. (I can also repro the problem right now.) Thanks for filing.

@CommonLoon102, we have some docs on alternate ways to install specifically tailored to Dockerfiles if you'd like to try it out: https://github.com/dotnet/dotnet-docker/blob/master/samples/snippets/installing-dotnet.md#ways-to-install-net-core

**Comment by shonk-msft** [comment] 2020-01-24 23:52
@dagood Is there an eta for resolution?

**Comment by dagood** [comment] 2020-01-24 23:54
Not yet, the team hasn't acknowledged the ticket so far. I'll keep this issue updated with the latest info I can get.

**Comment by robsgreen** [comment] 2020-01-25 00:07
I'm also seeing this issue in a docker build using debian buster (python3.7-slim-buster):
```
Err:5 https://packages.microsoft.com/debian/9/prod stretch/main amd64 Packages
  File has unexpected size (73307 != 72896). Mirror sync in progress? [IP: 13.91.48.226 443]
  Hashes of expected file:
   - Filesize:72896 [weak]
   - SHA512:29d29a280aba2f0ee4f4b23375ab236a1c1000bc00474d761f95288e698ff897f95607aab391fed3c28c52b5225ff9bd5af0152a871153d4f3fdd3a176562176
   - SHA256:5f4c1c5e7c6bbd935da728a274ebe509a8f67c06561ad8ff528fd34838a847c3
   - SHA1:1c43c51bee2f71e4f36b8cde2b9e0f227828feec [weak]
   - MD5Sum:60045479c796d66d2fb677ea5327a378 [weak]
  Release file created at: Tue, 21 Jan 2020 21:32:06 +0000
```

**Comment by dagood** [comment] 2020-01-25 00:17
Thanks, I'm able to reproduce that too. Filed an additional ticket for Debian 9.

**Comment by SidShetye** [comment] 2020-01-25 01:49
A simple [google search](https://www.google.com/search?ei=IZ4rXpHVPIW6tAb8tKdo&q=E%3A+Failed+to+fetch+https%3A%2F%2Fpackages.microsoft.com%2Fubuntu%2F18.04%2Fprod%2Fdists%2Fbionic%2Fmain%2Fbinary-amd64%2FPackages.bz2&oq=E%3A+Failed+to+fetch+https%3A%2F%2Fpackages.microsoft.com%2Fubuntu%2F18.04%2Fprod%2Fdists%2Fbionic%2Fmain%2Fbinary-amd64%2FPackages.bz2) shows this has happened multiple times in the past. Assuming there are some lessons learnt, what's the plan to prevent this from happening in the future? 

It's kinda FUBAR'd our CI/CD operations and we're going to miss our weekend release window over this.  Needless to say, it's unacceptable in a software driven economy ...

**Comment by dagood** [comment] 2020-01-25 03:24
This instance of the problem seems to be fixed. `apt update` works for me on Ubuntu 18.04 and Debian 9, and the person assigned to the IcM tickets has marked them mitigated. Don't hesitate to ping me and/or open new issues if they still aren't working on your machine.

---

> Assuming there are some lessons learnt, what's the plan to prevent this from happening in the future?

We (.NET Core) have been trying very hard to work with the team responsible for this service since what I'd consider the landmark incident December 12, 2019 (https://github.com/dotnet/core/issues/3988). That effort to get some improvement is tracked at #4167.

**Closed by dagood** 2020-01-25 03:24 UTC
Labels: area-setup

**Comment by kthouz** [comment] 2020-10-16 05:17
This is happening to me as well in a docker deployment. From what I can see, there was a new release file `created at: Tue, 13 Oct 2020 22:37:20 +0000` . Would this be the reason?

```
E: Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-amd64/Packages.gz  File has unexpected size (34272 != 34103). Mirror sync in progress? [IP: 104.42.185.173 443]
   Hashes of expected file:
    - Filesize:34103 [weak]
    - SHA512:03535224e21b7d764e4a5683b314e5c7ade42cc1fb867d0971428324b08548c9338c0e014656eb6f994f1cbbbd9b21fa3be17fcb4c48ac53e9f9d36e81e966a5
    - SHA256:af87c84a025cd3a4777cf184d316f8cfa358685fd323475b565406d11b6fac4a
    - SHA1:1487c68359752eb6c9bbeeb158b34d7597e391df [weak]
    - MD5Sum:ef3b0918fca2da4c0b3213db7cd12984 [weak]
   Release file created at: Tue, 13 Oct 2020 22:37:20 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'web' failed to build : The command '/bin/sh -c apt-get -qq update' returned a non-zero code: 100
```
