### ISSUE TITLE
dotnet add package error in 5.0.202

### ISSUE THREAD

**Issue by henry-js** [dotnet/core#6193] opened 2021-04-26 06:04 UTC
### Description
1. Installed dotnet on a clean installation of Win 10. Cloned github repository and ran `dotnet restore`. Failed with error NU1100.
2. Created a new project with `dotnet new razor`
3. Ran` dotnet add package Microsoft.EntityFrameworkCore`
4. Output: 
```
Determining projects to restore...
  Writing C:\Users\henry\AppData\Local\Temp\tmp89FC.tmp
info : Adding PackageReference for package 'Microsoft.EntityFrameworkCore' into project 'C:\Users\henry\code\c#\console\console.csproj'.
error: There are no versions available for the package 'Microsoft.EntityFrameworkCore'.
```
5. Same issue attempting to add any Nuget package reference

### Configuration

.NET: 5.0.202
OS: Windows 10 19042.928
Arch: x64

### Regression?

Worked fine on my work laptop last week. Will double check the specific dotnet version that was.

**Comment by mairaw** [comment] 2021-04-26 16:36
This might be a duplicate of https://github.com/dotnet/sdk/issues/16720 where the error was caused by special characters in the path (the # character). Maybe try creating the project on a path without the # to see if the issue goes away?

**Comment by henry-js** [comment] 2021-04-27 06:15
Output from latest attempt with no special characters:
![image](https://user-images.githubusercontent.com/79054685/116193985-1e12a180-a728-11eb-8b7e-67fb82438f94.png)

And my .csproj is the default from `dotnet new web`

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

</Project>
```

**Comment by mairaw** [comment] 2021-04-27 07:49
Can you check the file %appdata%\NuGet\NuGet.Config and see if it has the package source configured it correctly?
Similar to what is explained here for a different issue https://stackoverflow.com/questions/62102318/hello-world-dotnet-core-example-not-working

You can also try to specify the source option as a workaround similar to what is explained at https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/395#issuecomment-300759239

let me know if any of these work

**Comment by henry-js** [comment] 2021-04-27 22:29
That fixed it thanks. My nuget.config was:

```xml
<configuration>
  <packageSources>
  </packageSources>
</configuration>
```
Running `dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org` fixed it for me.
Any ideas why this happened?

**Comment by mairaw** [comment] 2021-04-27 22:58
Glad to hear the workaround worked.

@rrelyea @nkolev92 can you help here? I'm not sure why the nuget.config could have no sources configured.

**Comment by nkolev92** [comment] 2021-04-27 23:00
@henry-js 

Did you install chocolatey by any chance? 

https://github.com/chocolatey/choco/issues/2233

**Comment by henry-js** [comment] 2021-04-28 08:47
I did yes, looks like that explains it

**Closed** 2021-04-28 14:33 UTC
