### ISSUE TITLE
DotNet error

### ISSUE THREAD

**Issue by Lahiru-Malshan** [dotnet/core#6720] opened 2021-09-20 13:07 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by tannergooding** [comment] 2021-09-21 16:44
Closing as duplicate of https://github.com/dotnet/core/issues/6721

**Closed by tannergooding** 2021-09-21 16:44 UTC
