### ISSUE TITLE
No support for Ubuntu 19.04 yet - does not install because of broken dependencies

### ISSUE THREAD

**Issue by zegracia** [dotnet/core#2753] opened 2019-05-20 02:29 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current
Operating System: Linux Ubuntu 19.04 - x64

After performing installation commands, I get the following output:

The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.4) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by karelz** [comment] 2019-05-21 16:16
Duplicate of #2526

**Closed by karelz** 2019-05-21 16:16 UTC
