### ISSUE TITLE
i need help to complete this 

### ISSUE THREAD

**Issue by vangitech** [dotnet/core#6321] opened 2021-06-02 09:23 UTC
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/modify
Operating System: windows

Open Pages/Index.cshtml in any text editor and replace all of the code with the following, then save the file.

**Comment by ManickaP** [comment] 2021-06-02 13:06
@vangitech could you add more info in the original issue #6320? I asked you there few specific questions to answer. Closing this as a dupe.

Duplicate of https://github.com/dotnet/core/issues/6320

**Closed by ManickaP** 2021-06-02 13:06 UTC
