### ISSUE TITLE
AddJsonFile with reloadOnChange set to true not working on azure linux app service

### ISSUE THREAD

**Issue by Ghyath-Serhal** [dotnet/core#6665] opened 2021-09-07 11:39 UTC
I am trying to change the configuration at runtime using the below code.
config.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);

It is working normally on a windows app service, however it is not working working on a linux app service

**Comment by Ghyath-Serhal** [comment] 2021-10-01 05:33
Actually I solved it in the way mentioned below. Check it, it might help you.
[](https://bartwullems.blogspot.com/2021/03/kubernetes-reload-your-aspnet-core.html)
[](https://github.com/fbeltrao/ConfigMapFileProvider)

**Comment by tmds** [comment] 2021-10-04 08:06
@Ghyath-Serhal great that you found a solution.

The issue is fixed in .NET 6 by https://github.com/dotnet/runtime/pull/55664.

**Comment by mairaw** [comment] 2021-10-04 19:45
It seems that a solution was found and a fix is coming, so closing the issue. Let me know if I missed anything.

**Closed by mairaw** 2021-10-04 19:45 UTC
