### ISSUE TITLE
I can't install the editor of Unity Hub

### ISSUE THREAD

**Issue by lrjc5752** [dotnet/core#8830] opened 2023-10-10 19:13 UTC
Problem encountered on https://dotnet.microsoft.com/es-es/learn/games/unity-tutorial/install
Operating System: windows
I can't install the editor of Unity Hub

**Comment by liveans** [comment] 2023-10-10 19:23
Hello @lrjc5752, it's a duplicate of #8824, can you post your information related to the issue over there?

**Closed by liveans** 2023-10-10 19:23 UTC
