### ISSUE TITLE
Environment.ProcessorCount wrong inside docker container

### ISSUE THREAD

**Issue by JMan7777** [dotnet/core#2714] opened 2019-05-12 23:41 UTC
Hi,

I have a project using .NET Core 3.0 Preview 4 which I just migrated to Preview 5.

I recognized that under .NET Core 3.0 Preview 5 the Environment.ProcessorCount variable value is 99% of the time wrong. It most of the time returning 1 instead of correct count but sometimes it reports the correct count (in 1% of the cases). 

I'm running .Net Core in a Linux docker container using the following images:

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-bionic AS base
FROM mcr.microsoft.com/dotnet/core/sdk:3.0-bionic AS build

The container app is running inside Azure but even when I run under a local docker environment the issue is still the same. In all the older  .NET Core 3.0 Previews the issue did not exist. It only happens with .NET Core 3.0 Preview 5.

Thx.

**Comment by karelz** [comment] 2019-05-17 21:49
@joperezr would you know if there were any changes in the area?

**Comment by joperezr** [comment] 2019-05-17 22:17
I do see some changes on this area recently https://github.com/dotnet/corefx/commits/release/3.0/src/System.Diagnostics.Process so I would suggest logging a new 3.0 issue in corefx and mention that this seems to be a regression. @JMan7777 if you could provide a small repro that would be ideal.

**Comment by JMan7777** [comment] 2019-05-18 02:26
Hi,

Thx for looking into this. It's easy to replicate. I attach you a Visual Studio 2019 project for testing.

I'm running in the following environment (for testing):

**Windows 10:**
`Version 1809 (OS Build 17763.503)`

**Visual Studio (Windows)**
`VisualStudioVersion = 16.0.4`

**Docker Desktop (Windows):**
`Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3`

**Docker Container (Linux) environment details:**
`DOTNET_VERSION	3.0.0-preview5-27626-15`
`ASPNETCORE_ENVIRONMENT	Development`
`ASPNETCORE_HTTPS_PORT	44369`
`ASPNETCORE_URLS	https://+:443;http://+:80`
`ASPNETCORE_VERSION	3.0.0-preview5-19227-01`
`DOTNET_RUNNING_IN_CONTAINER	true`
`DOTNET_USE_POLLING_FILE_WATCHER	1`

**Test URL (Local):**
`https://localhost:44369/api/values`

**Test URL Output (Example):**
`Framework: .NET Core 3.0.0-preview5-27626-15`
`OS Architecture: X64`
`OS Description: Linux 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018`
`Process Architecture: X64`
`Running in Docker: True`
`Processor Count: 1`
`Start Time: 05/18/2019 01:58`

Sometimes (mostly direct after startup) it shows the correct Docker configured CPU count but in 99% it's always wrong and shows: 1. 
If it shows the correct count and you just refresh the test URL in the browser it will switch from the correct count to 1.
When running outside a Docker container it shows always the correct processor count.

Hope you can find the issue as I rely on correct processor counts for some performance tuning I need ;).

Thx a lot.

**Test Project:**
[Test.zip](https://github.com/dotnet/core/files/3193555/Test.zip)

**Comment by omajid** [comment] 2019-05-18 19:53
cc @tmds

**Comment by tmds** [comment] 2019-05-20 07:52
@JMan7777 I'm trying to reproduce what you are seeing with a smaller application:

Program.cs:
```
using System;

class Program
{
	static void Main()
	{
		while (true)
		{
			Console.WriteLine("ProcessorCount: " + Environment.ProcessorCount);
			System.Threading.Thread.Sleep(1000);
		}
	}
}
```
Dockerfile:
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.0
RUN dotnet new console -o console
COPY Program.cs console/Program.cs
RUN dotnet publish -c Release console
CMD ["dotnet", "console/bin/Release/netcoreapp3.0/publish/console.dll"]
```
Test:
```
$ docker build . -t dotnet_app
$ docker run --rm dotnet_app
ProcessorCount: 4
ProcessorCount: 4
ProcessorCount: 4
...
$ docker run --rm --cpu-period 1000 --cpu-quota 2000 dotnet_app
ProcessorCount: 2
ProcessorCount: 2
ProcessorCount: 2
...
```
The output is what is expected. Can you reproduce using this Program?

cc @luhenry @janvorli

**Comment by JMan7777** [comment] 2019-05-20 12:59
@tmds I will give it a try tomorrow. 

Maybe you also can check the example project I gave to you. 
As I mentioned earlier I have the same issue running my app in a Linux Docker container in Azure.

Will keep you updated.

Thx.

**Comment by JMan7777** [comment] 2019-05-21 04:30
@tmds I did a small test with your example.

It works as it should. My Docker environment is configured to use 3 CPU's (Physically I have 4 CPU's).

The output is correct:

`C:\Temp>docker build . -t dotnet_app`
`Sending build context to Docker daemon  3.072kB`
`Step 1/5 : FROM mcr.microsoft.com/dotnet/core/sdk:3.0`
` ---> 1ff83de4bdba`
`Step 2/5 : RUN dotnet new console -o console`
` ---> Using cache`
` ---> 77e85f991ba8`
`Step 3/5 : COPY Program.cs console/Program.cs`
` ---> 247c5f75d6dc`
`Step 4/5 : RUN dotnet publish -c Release console`
` ---> Running in 9cbeffc1ba13`
`Microsoft (R) Build Engine version 16.0.462+g62fb89029d for .NET Core`
`Copyright (C) Microsoft Corporation. All rights reserved.`

` Restore completed in 29 ms for /console/console.csproj.`
`/usr/share/dotnet/sdk/3.0.100-preview5-011568/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(157,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [/console/console.csproj]`
`  console -> /console/bin/Release/netcoreapp3.0/console.dll`
`  console -> /console/bin/Release/netcoreapp3.0/publish/`
`Removing intermediate container 9cbeffc1ba13`
`---> 8d14fa0881f0`
`Step 5/5 : CMD ["dotnet", "console/bin/Release/netcoreapp3.0/publish/console.dll"]`
` ---> Running in 9128aa7ac1ca`
`Removing intermediate container 9128aa7ac1ca`
` ---> 8b0521f96357`
`Successfully built 8b0521f96357`
`Successfully tagged dotnet_app:latest`
`SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.`

`C:\Temp>docker run --rm dotnet_app`
`ProcessorCount: 3`
`ProcessorCount: 3`
`ProcessorCount: 3`
`ProcessorCount: 3`
`ProcessorCount: 3`
`ProcessorCount: 3`
`ProcessorCount: 3`
`ProcessorCount: 3`
`ProcessorCount: 3`
`ProcessorCount: 3`
`ProcessorCount: 3`
`ProcessorCount: 3`

`C:\Temp>docker run --rm --cpu-period 1000 --cpu-quota 2000 dotnet_app`
`ProcessorCount: 2`
`ProcessorCount: 2`
`ProcessorCount: 2`
`ProcessorCount: 2`
`ProcessorCount: 2`
`ProcessorCount: 2`
`ProcessorCount: 2`
`ProcessorCount: 2`
`ProcessorCount: 2`
`ProcessorCount: 2`

`C:\Temp>`


So something must be different between my example and your one.
I see you are using:
`FROM mcr.microsoft.com/dotnet/core/sdk:3.0`
while I'm using:
`FROM mcr.microsoft.com/dotnet/core/sdk:3.0-bionic`.

So I also tested with my sdk image above and the result is still the same (correct).
Very strange. 
There must be something going on when using the ProcessorCount function in a web app project.

Please kindly use my provided project to check further.

Thx a million.

**Comment by tmds** [comment] 2019-05-21 05:10
@JMan7777 I can reproduce the issue.

The ProcessorCount 1 value comes from sched_getaffinity returning 1 cpu.
@janvorli maybe this is caused by changes in https://github.com/dotnet/coreclr/pull/23824?

**Comment by tmds** [comment] 2019-05-21 07:37
This reproduces also outside Docker.

Looking at the strace, it seems getaffinity with pid zero is returning the affinity of the current thread and not the process:
```
[pid 19302] sched_getaffinity(0, 128, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]) = 8
[pid 19302] sched_setaffinity(19302, 128, [4]) = 0
[pid 19302] sched_getaffinity(0, 128, [4]) = 8
```
So if ProcessorCount is called on a thread that has affinity with a specific processor, it will return 1.

**Comment by tmds** [comment] 2019-05-21 12:56
@karelz @joperezr can you move this one to coreclr please?

**Comment by karelz** [comment] 2019-05-21 15:20
@tmds  given the back and forth, maybe it would be better to just file a new issue with clear repro in CoreCLR and then close this one as dupe ...

**Comment by tmds** [comment] 2019-05-21 15:40
@karelz created https://github.com/dotnet/coreclr/issues/24686

**Comment by karelz** [comment] 2019-05-21 16:12
Duplicate of https://github.com/dotnet/coreclr/issues/24686

**Comment by karelz** [comment] 2019-05-21 16:12
Thanks @tmds

**Closed by karelz** 2019-05-21 16:12 UTC
Labels: bug
