### ISSUE TITLE
no provider of dotnet-sdk-3.0 and libicu found

### ISSUE THREAD

**Issue by Dan347** [dotnet/core#3695] opened 2019-10-25 16:57 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/opensuse42-3/sdk-curent
Operating System: Linux openSUSE 42.3 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Hello, I ran into an issue where I keep getting the error 'no provider of 'dotnet-sdk-3.0' found and 'no provider of libicu found'. I have the output below:

<<<
dan@linux-zc3g:~> sudo zypper install libicu
Loading repository data...
Reading installed packages...
'libicu' not found in package names. Trying capabilities.
No provider of 'libicu' found.
Resolving package dependencies...

Nothing to do.

dan@linux-zc3g:~> sudo zypper install dotnet-sdk-3.0
Loading repository data...
Reading installed packages...
'dotnet-sdk-3.0' not found in package names. Trying capabilities.
No provider of 'dotnet-sdk-3.0' found.
Resolving package dependencies...

Nothing to do.

>>>

Please let me know how to resolve; thank you!

**Comment by dagood** [comment] 2019-10-25 18:45
Can you post the output of these commands to diagnose what the state of your system is?

```
cat /etc/os-release
zypper search libicu
```

There is a similar issue https://github.com/dotnet/core/issues/3500 that happens when running openSUSE Tumbleweed.

**Comment by Dan347** [comment] 2019-10-25 18:59
Thanks: Here's the output:

Dan@linux-zc3g:~> cat /usr/lib/os-release
NAME="openSUSE Tumbleweed"
# VERSION="20191023"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20191023"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20191023"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
LOGO="distributor-logo"

dan@linux-zc3g:~> cat /etc/os-release
NAME="openSUSE Tumbleweed"
# VERSION="20191023"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20191023"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20191023"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
LOGO="distributor-logo"
doshea@linux-zc3g:~> zypper search libicu
Loading repository data...
Reading installed packages...

S | Name                  | Summary                               | Type   
--+-----------------------+---------------------------------------+--------
  | libicu-devel          | Development files for the ICU library | package
  | libicu-devel-32bit    | Development files for the ICU library | package
  | libicu-doc            | Documentation for the ICU library     | package
i | libicu-suse64_2       | International Components for Unicode  | package
  | libicu-suse64_2-32bit | International Components for Unicode  | package
  | libicu64_2-bedata     | Rule databases and tables for ICU     | package
i | libicu64_2-ledata     | Rule databases and tables for ICU     | package

**Comment by dagood** [comment] 2019-10-25 19:10
Thanks! That confirmed you're on Tumbleweed, so that part of the problem is a duplicate of https://github.com/dotnet/core/issues/3500. The short of it is that .NET Core isn't supported on Tumbleweed, but it should be fine to use `libicu-suse64_2` (which you already have installed) and ignore the dependency that .NET Core has on versionless `libicu`.

It looks like the reason you're missing `dotnet-sdk-3.0` is that you haven't run the four steps after `sudo zypper install libicu`. Those are what set up the Microsoft package repository.

**Comment by Dan347** [comment] 2019-10-25 19:31
I did do those steps originally and I have done them again as far as I know. Maybe I'm doing zypper update wrong?
Output below:
 
dan@linux-zc3g:~> sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
dan@linux-zc3g:~> wget -q https://packages.microsoft.com/config/opensuse/42.3/prod.repo
dan@linux-zc3g:~> sudo mv prod.repo /etc/zypp/repos.d/microsoft-prod.repo
dan@linux-zc3g:~> sudo chown root:root /etc/zypp/repos.d/microsoft-prod.repo
dan@linux-zc3g:~> sudo zypper update
Loading repository data...
Reading installed packages...

Nothing to do.
dan@linux-zc3g:~> sudo zypper install dotnet-sdk-3.0
Loading repository data...
Reading installed packages...
'dotnet-sdk-3.0' not found in package names. Trying capabilities.
No provider of 'dotnet-sdk-3.0' found.
Resolving package dependencies...

Nothing to do.
dan@linux-zc3g:~>

**Comment by dagood** [comment] 2019-10-25 20:00
Ah, sorry, the problem is the 42.3 feed. That's an old version of openSUSE, we only support 15.0+ for .NET Core 3.0.

Try `zypper search dotnet-sdk` and you should see 2.1 and 2.2, but not 3.0.

The steps here should get you going: https://dotnet.microsoft.com/download/linux-package-manager/opensuse15/sdk-current

**Comment by Dan347** [comment] 2019-10-25 20:08
Thanks. So, for tumbleweed, is that considered less than version 42.3 then? I'm surprised by that because I thought it was latest version. But if there is no way to get .net core 3.0 on this, are there instructions for compiling from source? I was looking for that but couldn't find anything.

**Comment by Dan347** [comment] 2019-10-25 20:14
Sorry I think I misunderstood your message. The instructions you sent me looke didentical to the ones I ran for 42.3, but I ran them anyway and have the same issue:
no provider of 'dotnet-sdk-3.0' found.

Is this something I need to compile from source? If so, how would I do that?

**Comment by dagood** [comment] 2019-10-25 20:28
To my understanding, Tumbleweed and Leap are independent release trains, there's no numeric relationship--because yeah, Tumbleweed updates freely.

(Leap recently went backwards from Leap 42.3 => Leap 15.0 to align with other versions, in case it isn't clear why we don't support 42.3 but we do support 15+.)

The freely updating versions are why don't support Tumbleweed: we don't have the resources to keep up. If .NET Core were built from source for Tumbleweed development (through the [source-build](https://github.com/dotnet/source-build) effort) then it would keep up without as much effort.

There are alternative ways to install, like snaps or a tar.gz of binaries. More info at [Linux Setup](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md). Building from source is unfortunately not easy yet.

---

> The instructions you sent me looke didentical to the ones I ran for 42.3, but I ran them anyway and have the same issue:
> no provider of 'dotnet-sdk-3.0' found.

The difference is the repo: `wget -q https://packages.microsoft.com/config/opensuse/15/prod.repo`

I've had some problem with "stickiness" due to `wget` downloading to `prod.repo.1` if `prod.repo` already exists, and silliness like that. I suggest getting a clean copy of `prod.repo` and making sure that's what you have at `/etc/zypp/repos.d/microsoft-prod.repo`. It should contain `baseurl=https://packages.microsoft.com/opensuse/15/prod/`.

What does `zypper search dotnet-sdk` give you? Nothing, or the 2.1 and 2.2 SDKs?

**Comment by Dan347** [comment] 2019-10-25 20:32
Sorry, zypper search dotnet-sdk doe sgive me 2.1 and 2.2 sdks. I'll look at the linux setup, the instructions to get from a tar file look very helpful. That should answer my questions. I think this can be resolved.

Thank you for your time!

**Comment by dagood** [comment] 2019-10-25 20:41
Well, seeing 2.1 and 2.2 SDKs means that somehow zypper is still seeing the 42.3 repo somehow. You should be able to see 3.0 if you're on the 15 repo. If you'd like to debug a bit more, the contents of `/etc/zypp/repos.d/microsoft-prod.repo` are the next thing to look at. Using the package manager can be nice because you can get updates through it via `zypper update` rather than having to hear about the new version and install a new tarball manually. 🙂 

(Closing for now if that's more trouble than it's worth.)

**Closed by dagood** 2019-10-25 20:41 UTC
Labels: needs more info
