### ISSUE TITLE
Demo service build to .net core 3.1, docker setup points to sdk:2.1 and aspnet:2.1

### ISSUE THREAD

**Issue by ferdeen** [dotnet/core#4110] opened 2020-01-11 16:06 UTC
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/microservice-tutorial/run-docker
Operating System: windows

I had to go out to docker to get the images for 3.1 to complete the demo on the above page.

https://hub.docker.com/_/microsoft-dotnet-core-aspnet/

**Comment by scalablecory** [comment] 2020-01-13 15:40
Duplicate of https://github.com/dotnet/core/issues/4071

**Closed by scalablecory** 2020-01-13 15:40 UTC
