### ISSUE TITLE
Crash while debugging writing to large array (AccessViolationException)

### ISSUE THREAD

**Issue by Robert-Laverick** [dotnet/core#2094] opened 2018-12-02 00:06 UTC
# General

With .net Core 2.1 (and I think the same is happening with 2.2 preview 3) when I try to write to a large array with a debugger attached the program crashes with a AccessViolcationException

Sample Program:
```c#
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var bigArray = new double[40000, 20000];
            for (int i = bigArray.GetLowerBound(0); i < bigArray.GetUpperBound(0); i++)
            {
                for (int j = bigArray.GetLowerBound(1); j < bigArray.GetUpperBound(1); j++)
                {
                    bigArray[i, j] = double.MinValue;
                }
            }

            Console.WriteLine($"Hello World! {bigArray[14,14]}");
        }
    }
}
```

I'm just creating a large 2D array and filling it with double.MinValue; (This is my minimum test case I'm doing more in my real app)

Just open this in Visual Studio, run with debugging and it'll crash while trying to write to (13421, 15456) this also happens if you do the same operation in a XUnit test even from outside of visual studio "dotnet test"

```c#
namespace XUnitTestProject1
{
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
            var bigArray = new double[40000, 20000];
            for (int i = bigArray.GetLowerBound(0); i < bigArray.GetUpperBound(0); i++)
            {
                for (int j = bigArray.GetLowerBound(1); j < bigArray.GetUpperBound(1); j++)
                {
                    bigArray[i, j] = double.MinValue;
                }
            }
        }
    }
}
```

Interestingly the program works just fine if you compile it in release mode and run it from bin/Release directory via dotnet ./ConsoleApp1.dll so it's clearly something relating to the compiled debug version.

> System.AccessViolationException
>   HResult=0x80004003
>   Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

**Comment by Robert-Laverick** [comment] 2018-12-05 00:13
Tested against today's final release of .net core 2.2.0, confirmed still same behaviour.

To be specific the presented code crashes with an AccessViolationException if compiled without optimisations enabled.

**Comment by karelz** [comment] 2019-01-08 04:46
Duplicate of https://github.com/dotnet/coreclr/issues/20657

**Closed by karelz** 2019-01-08 04:46 UTC
