### ISSUE TITLE
[BUG] FileInfo seems locking files

### ISSUE THREAD

**Issue by Banyc** [dotnet/core#5077] opened 2020-08-15 17:08 UTC
# FileInfo seems locking files

FileInfo is not supposed to lock a file. However, in this case, the scope of FileInfo did trigger unintended file locking.

## Reproduce

1. Go to `appsettings.json`
1. Set `SecondsBeforeTimeout` to 1
1. Uncomment out the statements <https://github.com/Banyc/LinkDownloader/blob/master/src/LinkDownloader/App.cs#L83-L84>
1. Comment out the statements <https://github.com/Banyc/LinkDownloader/blob/master/src/LinkDownloader/App.cs#L88-L89>
1. run `dotnet run`
1. Wait for a while.

**Comment by danmosemsft** [comment] 2020-08-25 20:22
Can you please reduce this to a simple few line repro app?

**Comment by Banyc** [comment] 2020-08-26 17:03
> Can you please reduce this to a simple few line repro app?

I tried removing `WebClient` object and it works well without having IO exceptions. Therefore, `WebClient` must be included.

Most of the codes are unrelated to this problem. The main logic only happens here `https://github.com/Banyc/LinkDownloader/blob/master/src/LinkDownloader/App.cs#L69-L162` and the `FileInfo` extension.

**Comment by carlossanlop** [comment] 2020-11-06 19:33
@Banyc if you can find a way to simplify the repro to a minimal one, that would be great.

What OS are you running this in?

Since this is in a loop, I wonder if the issue is because of a race condition - the code is expecting to move or copy much faster than the OS can handle it. AFAIK, there is no guarantee the OS will perform the requested task exactly when you make the call, it may be queued.

cc @Jozkee

**Comment by Banyc** [comment] 2020-11-07 08:56
I was running it on Windows. Since it was too long ago, I am not currently engaged in this issue. By the way, as in the other issue I have raised, they said `WebClient` is not recommended.

**Comment by carlossanlop** [comment] 2020-11-09 20:48
Ok thanks, @Banyc. I'll close the issue.

**Closed by carlossanlop** 2020-11-09 20:48 UTC
