### ISSUE TITLE
Install fails at final step on Ubuntu 19.04

### ISSUE THREAD

**Issue by pjenney58** [dotnet/core#3453] opened 2019-09-24 17:20 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-3.0.100
Operating System: Linux Ubuntu 19.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

After following all the documented steps, the process failed at the end.

> sudo apt-get install dotnet-sdk-3.0
> 
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package dotnet-sdk-3.0
> E: Couldn't find any package by glob 'dotnet-sdk-3.0'
> E: Couldn't find any package by regex 'dotnet-sdk-3.0'

**Comment by dagood** [comment] 2019-09-24 20:41
Are you sure the `sudo apt-get update` step or another earlier step didn't fail? The errors don't always show up in an obvious way (in my experience).

Can you paste the output from every command you ran during the install?

Could you also try this command to see which repos you have installed on your machine, in case the Microsoft repo didn't install correctly?

```
# Shows the repositories you have configured. Source: https://askubuntu.com/a/741948
grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
```

**Comment by dagood** [comment] 2019-09-30 14:36
It's quite possible this was caused by a failed `apt update` due to https://github.com/dotnet/core/issues/3513. Closing as a probable duplicate and due to lack of information.

**Closed by dagood** 2019-09-30 14:36 UTC
Labels: needs more info
