### ISSUE TITLE
Parallel.ForEach failing on Linux instance but works on Windows machine.

### ISSUE THREAD

**Issue by karanrn** [dotnet/core#3859] opened 2019-11-20 11:13 UTC
# Issue Title

Parallel.ForEach construct/method is failing with *Task was canceled* error on Linux instance but works flawlessly on Windows machine.

# General

We have an application, which pulls data from S3 and writes to the database. In the application, we are opening threads for concurrency/parallelism where each thread pulls from a particular S3 key.

The original application code was written in .Net framework 4.6.1, we migrated the codebase to .Net core 3.0. It was an easy transition.

Below is the code snippet for Parallel.ForEach for pulling data and processing:
```
Parallel.ForEach(PotentialFiles.Rows.OfType<DataRow>(), (row) =>
{
    if (ProcessFile(row[1].ToString(), Date, 15))
    {
        LastFileID = Math.Max(LastFileID, Convert.ToInt32(row[0]));
        FirstFileID = Math.Min(FirstFileID, Convert.ToInt32(row[0]));
    }
});
```
We are getting aggregation exception:
> System.AggregateException: One or more errors occurred. (One or more errors occurred. (A task was canceled.))

`ProcessFile` method includes S3 get objects from AWSSDK.S3 which is the asynchronous method.
But the same piece of code runs flawlessly on Windows.

We could fix the issue using Partitioner:
```
var tasks = System.Collections.Concurrent.Partitioner.Create(PotentialFiles.AsEnumerable())
                .GetPartitions(10)
                .Select(partition => Task.Run(() =>
                {
                    using (partition)
                    {
                        while (partition.MoveNext())
                        {
                            var row = partition.Current;
                            if (ProcessFile(row[1].ToString(), Date, 15))
                            {
                                LastFileID = Math.Max(LastFileID, Convert.ToInt32(row[0]));
                                FirstFileID = Math.Min(FirstFileID, Convert.ToInt32(row[0]));
                            }
                        }
                    }
                })).ToArray();

await Task.WhenAll(tasks);
```
With the above piece of code, it works on the Linux instance.

If .Net Core is cross-platform, then why the same piece of code does not work on different platforms (Windows and Linux). Is it the issue with Task scheduler being different on different platforms?
What am I missing here?

**Comment by svick** [comment] 2019-11-20 11:31
Can you include the full exception information here, including stack trace and inner exceptions?

**Comment by karanrn** [comment] 2019-11-20 11:57
System.AggregateException: One or more errors occurred. (One or more errors occurred. (A task was canceled.))
 ---> System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at AWSSynch.DailyTelemetryData.ProcessFile(String FileKey, DateTime Date, Int32 NumOfAttempts) in /home/ubuntu/MigratedCodeBase/AWSSynch/DailyTelemetryData.cs:line 156
   at AWSSynch.DailyTelemetryData.<ProcessDailyData>b__12_0(DataRow row) in /home/ubuntu/MigratedCodeBase/AWSSynch/DailyTelemetryData.cs:line 91
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at AWSSynch.DailyTelemetryData.ProcessDailyData() in /home/ubuntu/MigratedCodeBase/AWSSynch/DailyTelemetryData.cs:line 87
   at AWSSynch.DailyTelemetryData..ctor(DateTime Date, Logger log) in /home/ubuntu/MigratedCodeBase/AWSSynch/DailyTelemetryData.cs:line 44
   at AWSSynch.DailyTelemetryData.ProcessOldestDay(Logger log) in /home/ubuntu/MigratedCodeBase/AWSSynch/DailyTelemetryData.cs:line 55
   at AWSSynch.Program.Main(String[] args) in /home/ubuntu/MigratedCodeBase/AWSSynch/Program.cs:line 27

**Comment by scalablecory** [comment] 2019-11-21 20:52
Your stack trace is showing the exception is being thrown inside of `ProcessFile`, not by `Parallel.ForEach`.

Unrelated, you have a race condition here as LastFileID and FirstFileID will be used by multiple threads:
```c#
        LastFileID = Math.Max(LastFileID, Convert.ToInt32(row[0]));
        FirstFileID = Math.Min(FirstFileID, Convert.ToInt32(row[0]));
```

**Comment by karanrn** [comment] 2019-11-22 03:05
In the `ProcessFile` method, we are calling async operation for pulling objects from S3.
But the same piece of code worked on Windows but not on Linux, even with a clean build. Based on my reading, we should not be using `Parallel.ForEach` for async operations which I totally agree with.

My concern is about .Net core application running on Windows but not on Linux, I had it make it work on Linux using the `Partitioner`. And I did not see any race condition, either in .Net framework (previous codebase before migrating to .Net Core) or after the fix.

**Comment by scalablecory** [comment] 2019-11-22 09:19
Okay, the next step is to get a small repro that demonstrates the problem.

**Comment by scalablecory** [comment] 2019-12-04 02:07
Closing this out -- I hope you were able to find the cause. Please re-open if you're able to provide a repro.

**Closed by scalablecory** 2019-12-04 02:07 UTC
Labels: needs more info
