### ISSUE TITLE
After I ran deployment: kubectl apply -f deploy.yaml, I got this error: Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by huipingli2009** [dotnet/core#6397] opened 2021-06-18 18:26 UTC
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/deploy-microservice-tutorial/deploy
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by michaelgsharp** [comment] 2021-06-18 19:07
This is a duplicate of your other issue #6393, closing this one so we can track the issue in place.

**Closed by michaelgsharp** 2021-06-18 19:07 UTC
