### ISSUE TITLE
How can a .NET Core console app running on Ubuntu Linux access a file share using Windows Authentication?

### ISSUE THREAD

**Issue by KennyChen0909** [dotnet/core#2247] opened 2019-01-24 09:18 UTC
# Issue Title
How can a .NET Core console app running on Ubuntu Linux access a file share using Windows Authentication?

# General

We are able to get a file share directory using the below code in windows machines:

```c#
using System.Diagnostics;
using System;

///   <summary> 
///  connet to remote share folder 
///   </summary> 
///   <param name="remotehost"> remote server ip or machinename.domain name </param> 
///   <param name="sharename"> share name </param> 
///   <param name="username"> user name of remote share access account </param> 
///   <param name="password"> password of remote share access account </param> 
///   <returns> connect result </returns>          
///   

namespace ConsoleApp1
{
    class Program
    {

        public static bool connect(string remotehost, string sharename, string username, string password)
        {
            bool flag = false;
            Process proc = new Process();
            try
            {
                proc.StartInfo.FileName = " cmd.exe ";
                proc.StartInfo.UseShellExecute = false;
                proc.StartInfo.RedirectStandardInput = true;
                proc.StartInfo.RedirectStandardOutput = true;
                proc.StartInfo.RedirectStandardError = true;
                proc.StartInfo.CreateNoWindow = true;
                proc.Start();
                string dosline = @" net use \\ " + remotehost + @" \ " + sharename + "  /user: " + username + "   " + password + "  /persistent:yes ";
                proc.StandardInput.WriteLine(dosline);
                proc.StandardInput.WriteLine(" exit ");
                while (!proc.HasExited)
                {
                    proc.WaitForExit(1000);
                }

                string errormsg = proc.StandardError.ReadToEnd();
            
                proc.StandardError.Close();
                if (string.IsNullOrEmpty(errormsg))
                {
                    flag = true;
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                proc.Close();
                proc.Dispose();
            }
            return flag;
        }
    }
}
```

However, it is using CMD shell which is not available on Linux.

**Comment by gortok** [comment] 2019-01-24 15:11
@KennyChen0909 The deeper issue you're having is that you want a way for your Console program to access a Windows file share from an Ubuntu Server.  To make that happen, you'd need to mount that windows network share using [the instructions here](https://wiki.ubuntu.com/MountWindowsSharesPermanently).

What's your deployment scenario? Is this a console program in an environment you control (where you can set up this share before hand) or is this in an environment you don't control (where you'd need to script setting up the share in C#?)

**Comment by KennyChen0909** [comment] 2019-01-28 07:07
@gortok  Is there a way to access a Windows file share programmatically? We have been working around the issue by mounting a network share in the same way as the instructions you linked, but it doesn't scale if you have 10s or 100s of network shares to access with potentially different credentials as well.

Our deployment scenario is .NET Core deployed on Ubuntu base images as Docker containers. The containers are meant to audit the file shares that are configured within the system. We have used the Docker bind method to mount the shares to the containers, but again that is a fairly manual process when we have multiple shares to configure. 

Is there some .NET Core way to dynamically access a network share on-demand, instead of using mounts?

**Comment by gavinmckay** [comment] 2019-01-30 13:09
@karelz do you need more information beyond what has been provided? The issue is currently marked as "needs more info".

**Comment by gortok** [comment] 2019-01-30 13:19
@KennyChen0909 you’d have to write the code to programmatically access the shares. If they’re dynamic then your code would be the rules that determine the dynamic logic to use. If they aren’t dynamic you could always try to use the configuration provider in .NET Core to load them.

**Comment by leecow** [comment] 2019-02-14 00:59
@gortok is pointing in the right direction. You're code will need to deal with a platforms file share access idioms, eg, clear unc on Windows or smb / cfs on Linux. I believe I have seen libraries available to help on Linux, or you can programmatically mount/unmount the shares.

**Closed by leecow** 2019-02-14 00:59 UTC
