### ISSUE TITLE
The tutorial should not recommend --no-https

### ISSUE THREAD

**Issue by Tratcher** [dotnet/core#4495] opened 2020-04-01 16:54 UTC
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create#
Operating System: windows

https is the default in modern browsers. Excluding it in the demo causes customers to hit browser security warnings and errors, and leads to issues like this:
https://github.com/dotnet/aspnetcore/issues/20404

**Comment by irlcatgirl** [comment] 2020-04-01 17:02
While I agree it’s a bad practice. Many people have a web server like Nginx terminate SSL and run ASP binded to localhost. It’s a good idea to warn them but still teach them how for deployment purposes.

**Comment by Tratcher** [comment] 2020-04-01 17:09
@irlcatgirl sure, there are configurations where https is handled in other ways, but in the context of these tutorials https really should be enabled for direct browser interaction.

**Comment by irlcatgirl** [comment] 2020-04-01 17:11
> @irlcatgirl sure, there are configurations where https is handled in other ways, but in the context of these tutorials https really should be enabled for direct browser interaction.

I agree but somewhere in the tutorial should still mention how to disable it. I’m sure the ASP team would consider a PR 😉

**Comment by carlossanlop** [comment] 2020-04-07 18:37
@Pilchie do you know who can comment on this?

**Comment by mairaw** [comment] 2020-04-07 18:43
@blowdart what do you think?

**Comment by Pilchie** [comment] 2020-04-07 18:47
I think @Tratcher is right.  Since Chrome and other browsers now treat http as "Not Secure" by default, our tutorials should default to the secure option.

**Comment by blowdart** [comment] 2020-04-07 21:09
Agreed

**Comment by mairaw** [comment] 2020-04-07 21:36
Sounds good. I'll make the changes!

**Comment by mairaw** [comment] 2020-04-13 16:15
Please see this comment from @shirhatti on the PR:
https://github.com/dotnet/website/pull/1875#issuecomment-611069647

The default template (without the --no-https flag):

- Requires a dev certificate for https
- Will redirect from http to https

Given that the dev cert experience doesn't work on Linux, I think it was a conscious choice not to change the tutorial. If we want to change, I'd only do so on the Win/macOS versions of the tutorial.

---

I think this would complicate the getting started process for new developers if we remove the flag from the two tutorials that use them.

Also, I discussed the triage process with the folks doing the triage here on dotnet/core and we'll no longer transfer tutorial related issues to the product repos, unless we consider it's a product bug.

**Comment by irlcatgirl** [comment] 2020-04-13 16:41
> Please see this comment from @shirhatti on the PR:
> [dotnet/website#1875 (comment)](https://github.com/dotnet/website/pull/1875#issuecomment-611069647)
> 
> The default template (without the --no-https flag):
> 
> * Requires a dev certificate for https
> * Will redirect from http to https
> 
> Given that the dev cert experience doesn't work on Linux, I think it was a conscious choice not to change the tutorial. If we want to change, I'd only do so on the Win/macOS versions of the tutorial.
> 
> I think this would complicate the getting started process for new developers if we remove the flag from the two tutorials that use them.
> 
> Also, I discussed the triage process with the folks doing the triage here on dotnet/core and we'll no longer transfer tutorial related issues to the product repos, unless we consider it's a product bug.

I disagree. We shouldn’t encourage a security anti-practice on Linux because “it’s too hard for developers”, we can provide instructions to create and trust the dev cert or find a way to streamline the process. I’d argue for the first, if you’re using a Linux desktop you’re a poweruser and will have to put on a little more effort to get things working. This is a valuable learning opportunity for developers. Why waste it?

**Comment by Pilchie** [comment] 2020-04-13 17:19
As I understand it, part of the problem is that there is no standard way to trust the dev cert on Linux.  It's different for each distro.

**Comment by irlcatgirl** [comment] 2020-04-13 17:23
> As I understand it, part of the problem is that there is no standard way to trust the dev cert on Linux. It's different for each distro.

The ASP team can only provide general guidance. We can’t possibly support every Linux distribution and should focus on the most popular ones.

**Comment by Tratcher** [comment] 2020-04-13 17:32
> I'd only do so on the Win/macOS versions of the tutorial.

It makes sense to start with the Windows tutorial where the dev cert experience is the best. We can use that to gather feedback about the change.

> * Will redirect from http to https

I don't see how that's a problem, this is transparent to users.

**Comment by brockallen** [comment] 2020-04-14 13:19
There are lots of great tools for developers to create their own certs, e.g.: https://github.com/FiloSottile/mkcert. Perhaps mention this one (or another of your vetting).

**Comment by mairaw** [comment] 2020-07-08 02:20
@danroth27 you ran user studies recently and you also decided to use the --no-https for the new Blazor tutorial. Adding https does complicates things for newbies right?

**Comment by danroth27** [comment] 2020-07-08 03:21
> Adding https does complicates things for newbies right?

@mairaw Correct. While I certainly agree that developers doing any sort of serious web development should use HTTPS by default, in user testing we've seen that setting new users up with HTTPS by default often causes more problems than good. The issue is establishing trust for the developer certificate. We have support on Windows and macOS for establishing this trust using a the `dev-certs` command-line tool, but it adds additional steps and depending on the user's environment might fail in confusing ways. For example, Firefox last I checked has its own separate certificate trust rules. On Linux there is no established way of setting up trust for the developer certificate. All of the intro ASP.NET Core tutorials currently specify the `--no-https` option to avoid users getting entangled in these issues.

Passing `--no-https` is admittedly a crude solution to this problem. We should explore ways to leave HTTPS enabled by providing mitigations for the various issues users may run into. It's in our best interest to understand all of the potential issues.

Here's a strawman proposal:

- Update the Windows & macOS versions of the tutorials to no longer pass `--no-https`, and provide instructions for running the `dev-certs` tool. Provide a link to a platform specific troubleshooting doc for figuring out dev cert issues (like dealing with Firefox)
- Leave the `--no-https` option in the Linux based tutorials, but add some text saying that we generally recommend using HTTPS during development and provide a link to documentation on how to setup the dev certificate on various popular Linux distros and with common browsers.

**Comment by Anutrix** [comment] 2023-11-17 00:51
Is the sentiment(of keeping --no-https) still same now in 2023 where http is becaming rarer?

**Comment by mairaw** [comment] 2024-02-02 18:14
Closing this issue. The Razor tutorial was replaced with a Blazor one:
VS version: https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/intro
CLI version: https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-cli-tutorial/intro

The CLI version uses the default settings, which in .NET 8 changed to not use HTTPS by default, so the flag is no longer needed.

**Closed by mairaw** 2024-02-02 18:14 UTC
Labels: area-tutorials
