### ISSUE TITLE
Core 3.0.100-preview8-013656 building netstandard2.0 project with CLI fails

### ISSUE THREAD

**Issue by HarkinsDave** [dotnet/core#3205] opened 2019-08-16 23:13 UTC
# Issue Title
Using Core 3.0.100-preview8-013656 building netstandard2.0 project with CLI fails.  However building through VS 2019 (16.2.2 or 16.3 Preview 2.0) works.

# General
.NET Core Version : 3.0.100-preview8-013656
OS: Windows 10 Pro (1809)
Visual Studios Installed
2019 (16.2.2)
2019 (16.3 Preview 2)

TLDR:  
If you build from CLI it fails until you build from within Visual Studio and then the CLI will build properly also.

Solution that fails to build contains:
-  One netstandard2.0 project and it is set to generate a NuGet package on build.  
- Trace is defined.
- From command shell (regular or VS) running a dotnet build -c {Debug|Release} --framework netstandard2.0 will yield a build error.
- dotnet restore says it completed successfully
- msbuild /t:restore says it completed successfully
- dotnet build -c {Debug|Release} --framework netstandard2.0

 yields build error
- dotnet clean yields success
- dotnet build -c {Debug|Release} --framework netstandard2.0 yields build error

The following build output has been redacted slightly but has no effect on error:

Microsoft (R) Build Engine version 16.3.0-preview-19377-01+dd8019d9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 19.76 ms for C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018: The "WriteCodeFragment" task failed unexpectedly. [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018: System.FormatException: Input string was not in a correct format. [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018:    at System.Text.StringBuilder.FormatError() [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018:    at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args) [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018:    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args) [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018:    at System.String.Format(String format, Object[] args) [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018:    at Microsoft.Build.Tasks.WriteCodeFragment.GenerateCodeCoreClr(String& extension) [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018:    at Microsoft.Build.Tasks.WriteCodeFragment.Execute() [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]

Build FAILED.

C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018: The "WriteCodeFragment" task failed unexpectedly. [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018: System.FormatException: Input string was not in a correct format. [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018:    at System.Text.StringBuilder.FormatError() [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018:    at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args) [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018:    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args) [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018:    at System.String.Format(String format, Object[] args) [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018:    at Microsoft.Build.Tasks.WriteCodeFragment.GenerateCodeCoreClr(String& extension) [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018:    at Microsoft.Build.Tasks.WriteCodeFragment.Execute() [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Users\dave\source\repos\Integrate.Test\Integrate.Autogen\Integrate.Autogen.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.49

Error  dotnet build -c Debug --framework netstandard2.0 --force -v d.txt  shows the verbose of the build error.

Basically the error is:
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.GenerateAssemblyInfo.targets(133,5): error MSB4018: The "WriteCodeFragment" task failed unexpectedly. 

The relevant portion of that file is as follows
`    <WriteCodeFragment AssemblyAttributes="@(AssemblyAttribute)" Language="$(Language)" OutputFile="$(GeneratedAssemblyInfoFile)">
      <Output TaskParameter="OutputFile" ItemName="Compile" />
      <Output TaskParameter="OutputFile" ItemName="FileWrites" />
    </WriteCodeFragment>`

Long story short: If you build from CLI it fails until you build from within Visual Studio and then the CLI will build properly also.

[Integrate.Test.zip](https://github.com/dotnet/core/files/3511366/Integrate.Test.zip)
[Error  dotnet build -c Debug --framework netstandard2.0 --force -v d.txt](https://github.com/dotnet/core/files/3511367/Error.dotnet.build.-c.Debug.--framework.netstandard2.0.--force.-v.d.txt)

**Comment by nguerrera** [comment] 2019-08-20 15:25
Looking

**Comment by nguerrera** [comment] 2019-08-20 15:28
Duplicate of https://github.com/microsoft/msbuild/issues/937

**Comment by nguerrera** [comment] 2019-08-20 15:37
The implementation of WriteCodeFragment on .NET Core doe not deal with escaping correctly. Fixing that is tracked by https://github.com/microsoft/msbuild/issues/937. Originally, the port of msbuild to Core could not be used due to lack of CodeDom, and a quick and dirty substitute was used. Now it should be possible to switch to the CodeDom implementation on Core. I will make a note that we have a customer report. I spotted this bug by inspection years ago but it didn't get prioritized without a customer report.

Your options until that is fixed.

1. Build with `msbuild` or VS instead of `dotnet`
2. Simplify the Decription property in .csproj which is currently a long piece of text including code snippets to not have "special" characters.
3. Set GenerateAssemblyDescriptionAttribute=false in .csproj.

(3) is probably your best bet. I doubt that you want or need this long description in the assembly attribute, and pack will still pick up your description for the .nupkg.

**Closed by nguerrera** 2019-08-20 15:37 UTC

**Comment by nguerrera** [comment] 2019-08-20 16:03
It looks like most "special" characters were made to work, but the braces from the  code snippets are what's triggering the problem. I fixed up microsoft/msbuild#937. to reflect this with up-to-date repro steps.
