### ISSUE TITLE
ASP.NET Core 1.6 and Visual Studio 2017

### ISSUE THREAD

**Issue by gimlichael** [dotnet/core#360] opened 2016-11-22 15:30 UTC
![2016-11-22_1704](https://cloud.githubusercontent.com/assets/8550919/20531300/9fc7c446-b0d6-11e6-9e1f-6703d0abed2e.png)
I am trying to write out a 304 response using HttpResponseMessage that takes a System.Net.HttpStatusCode. Unfortunately there is an ambiguous reference in both System.Net.Primitives and System, and I cannot figure out what causes the problem.

`CS0433	The type 'HttpStatusCode' exists in both 'System.Net.Primitives, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'`

On another matter, I had to download the 1.1 SDK (dotnet-dev-win-x64.1.0.0-preview2-1-003177.exe) as the Visual Studio 2017 RC did not know about NETCOREAPP1.1 and crashed when starting, although you insist to do this through the Visual Studio Installer (but it was already installed).

I had really hoped these errors belonged to the past giving the matured platform.

**Comment by svick** [comment] 2016-11-22 16:20
Can you post your project file?

**Comment by gimlichael** [comment] 2016-11-22 16:30
Now this is weird; after to much frustration, I pulled the plug and restarted the machine.
The problem seems to have disappeared?!

Maybe NuGet caching issue or similar?
Also, a folder (which I cannot delete) has emerged in my project: 
![2016-11-22_1728](https://cloud.githubusercontent.com/assets/8550919/20532176/591bf186-b0d9-11e6-80e7-0606dae268ee.png)


[Unknown.zip](https://github.com/dotnet/core/files/606928/Unknown.zip)

**Comment by gimlichael** [comment] 2016-11-22 20:44
I believe there is a bug hidden somewhere in Visual Studio 2017, but I don't believe there is a problem with the ASP.NET Core 1.1 anymore. Also, I learned that an EmptyResult() is the way to go in terms of 304 response. You can decide if the VS 2017 team should know about this odd behavior or not :-)

**Comment by ciel** [comment] 2016-12-03 01:05
This behavior is affecting me all over too, and I'm having a lot of trouble with it. I can't pin down exactly what is wrong, but it seems to happen when I reference one project in another within the same solution.

I'm a novice, so I'm not fully aware of how it all works, but it is only happening with classes and such in my own code. Things from the GAC and NuGet don't appear affected.

Will try to make reproduction steps and post them here. This is really frustrating, though. I know it's just a release candidate and not the RTM, so I should expect bugs, but this is a pretty critical one.

Until I can sit down and work out greater specifics in a bit, this is how I've reproduced it before... I'm using `net46` because it's what I was on when I first began to encounter it, but I can repro this in `net45[1,2]` as well as `netstandard1.[5,6,7]` and `netcoreapp1.0` as well.

1) create a new project `Class Library (.NET Standard)`
2) open the `csproj` and change the FTM to `net46`
3) create a new class or two.
4) create another project `Class Library (.NET Standard)` in the same solution.
5) create a new class or two in the new project
6) in the solution explorer, navigate to the `References` node, right click it and select `Add Reference`
7) start creating code in the project that references the other project, making sure you use the classes in both
8) hit build a few times.

At first, it appears fine - but after some point, it begins to start underlining my classes and says "Ambiguous Reference" when I hover over them.

I'll try to prepare a video, too. I'm pretty sure this is a problem with Visual Studio 2017 RC, not .NET Core specifically though. But I'm not completely sure where to file this bug for the Visual Studio team.

**Comment by wcdeich4** [comment] 2016-12-12 21:35
I had a similar error.  As an experiment, I created a "Class Library (.NET Core)" project in Visual Studio Enterprise 2015 & tried to add OpenTK & I got this error:
Errors in C:\CODE\WinOpenGL\OpenTKExamples.NETCore\Entities\Entities.xproj
Package OpenTK 2.0.0 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package OpenTK 2.0.0 supports: net20 (.NETFramework,Version=v2.0)

When do you think .NET Core will be at least up to .NETFramework, Version = v2.0 ?

**Comment by Petermarcu** [comment] 2017-01-05 00:38
@wcdeich4, .NET Standard 2.0 will have a ton of API's added back. There are two things to try.

1. Try to add an imports clause to force NuGet to pick the net20 asset and run in on .NET Core. That may just work. Many libraries do depending on which code paths you use.

2. If it doesn't, I'd be curious what the gaps are and whether .NET Standard 2.0 support in .NET Core 2.0 will address it. @danmosemsft 

@gimlichael @ciel, I've sent an email to the Visual Studio folks about the errant folder to make sure they are aware of it and to get it investigated.

**Comment by Petermarcu** [comment] 2017-01-05 00:48
The folder issue is known and being tracked by the Visual Studio team. I believe it will be fixed in the next release.

I'm going to close this as I believe all the feedback in here has been farmed out or addressed. Thanks All!

**Closed by Petermarcu** 2017-01-05 00:48 UTC
