### ISSUE TITLE
Can't able to use frameworklibrary of .NET 4.5.2.

### ISSUE THREAD

**Issue by Applebit** [dotnet/core#187] opened 2016-06-30 11:48 UTC
![screenshot from 2016-06-30 17-19-35](https://cloud.githubusercontent.com/assets/11220070/16487211/f1a258e2-3ee6-11e6-8313-5e561a573d01.png)
Here is my project.json file

{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {},
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        },
	"System.Net.Security": "4.0.0.0"
      }
    },
    "net452":{
	"frameworkAssemblies":{
      	"System.Linq" : "4.0.0.0",
	"System.IO" : "4.0.0.0",
	"System.Runtime.ExceptionServices": "4.0.0.0",
	"System.Security": "4.0.0.0",
	"System.Collections": "4.0.0.0"
	}
      }
    },
   "imports": "dnxcore50"
}

Here is Program.cs

﻿using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.IO;
using System.Linq;
using System.Runtime.ExceptionServices;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace decryptepcm
{
    class Program
    {

        static string KInfo = @"<RSAKeyValue><Modulus>tAcQgHExAXikaUc1/cg64FmxZ6Dnwi0OzFcVQmTsYwxOafloQvtoC8szV3VNDNABHrUglN/EhabpUIz3DYliQef3+nmWVsNsAntcCVxgK0pQFYhOfNvCGcBYA+QdvYtjrQD3pRLZWVS4QJ6fIxjSigmL6DtecaiF01jaOPY4k80=</Modulus><Exponent>AQAB</Exponent><P>xrE1w+QCVEBuzU8/5jm+XQhjvmOCGJT/HCoNGovJLLa2DnKIiYJHWbJYNJ4W7Y+xdUDyRXvL6zPNBsjZBjLwRQ==</P><Q>5/O39MLFAdXqBiclajHgvAy4qa2CEEq+esA7UffNWaNJhAw5sjpGlKv3wDNt20yjoi7kx1wJYkD5BjPk4wch6Q==</Q><DP>oL/yfb/U2pEek+CQFBWXm/ETsY8UTAsPspua6mU5p4FTHbEwIgBS9ZDCqB9W8XAV5IVc/TZBLtNEBz8rxkYj+Q==</DP><DQ>sLfr4GwAAt0Clrt+cwEbUspyarwJyvXXV9hbmaCtcGzKlvNlhdeGbMD0WhgUy68BQJBvtz/02kncMJCbAyks+Q==</DQ><InverseQ>Mr6Wf5ADjUnP+9G18zu/hTSiMDy4GudO6iX5js95xVxBaJw1EDfi49LXwlPesFMlCgt9LfIw4q/+AG7dCJYx7w==</InverseQ><D>Bb+6AQKxrW8u/5D/bONxhIuTX5CjBgTkAEDW/sqemop15erJ2mW74gXdqwZ7F5R8N1ZSZt6pyxjUQjcWMUT4sb4C5G6JgpDbwkddzSTNQj1/jsgUSR/xRunTGsBMLcB6mXgPJ931tJsdS9L9rCINOzibY9hoAmM4GAQbBlxuXjE=</D></RSAKeyValue>";

        static string PubKey = @"<RSAKeyValue><Modulus>tAcQgHExAXikaUc1/cg64FmxZ6Dnwi0OzFcVQmTsYwxOafloQvtoC8szV3VNDNABHrUglN/EhabpUIz3DYliQef3+nmWVsNsAntcCVxgK0pQFYhOfNvCGcBYA+QdvYtjrQD3pRLZWVS4QJ6fIxjSigmL6DtecaiF01jaOPY4k80=</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>";

        static Dictionary<string, string> listOfFinalDictionary = new Dictionary<string, string>();

        public static Dictionary<string, string> GEtFinalDictionary(string path)
        {
            List<string> infoList = GetInfoDictionary(path);
            List<string> audioList = GetAudioFiles(path);

            foreach (var audioFile in audioList)
            {
                string result = "";
                if (audioFile.Length >= 12)
                {
                    string partName = audioFile.Substring(0, 12);
                    result = infoList.FirstOrDefault(s => s.Contains(partName));
                }
                if (!string.IsNullOrEmpty(audioFile) && !string.IsNullOrEmpty(result) && !listOfFinalDictionary.ContainsKey(audioFile))
                {
                    listOfFinalDictionary.Add(audioFile, result);
                }
            }
            return listOfFinalDictionary;
        }

        /// <summary>
        /// Main Entry point of application
        /// </summary>
        /// <param name="args"></param>
	[HandleProcessCorruptedStateExceptions]
        private static void Main(string[] args)
        {
            //string path = @"F:\WavFile";
            string path = @"F:\test";
            listOfFinalDictionary = GEtFinalDictionary(path);

            Decrypt(listOfFinalDictionary);

            Console.ReadLine();

        }

        private static void Decrypt(Dictionary<string, string> files)
        {
            foreach (var file in files)
            {
                string kInfo = Path.Combine(@"F:\test", file.Value);
                string epcm = Path.Combine(@"F:\test", file.Key);
                FileInfo fi = new FileInfo(kInfo);
                var iDict = ReadInfoFile(fi);
                string outputFile = @"F:\output.wav";
                RijndaelManaged crypto = new RijndaelManaged { KeySize = 256, Padding = PaddingMode.None};

                // Select target CSP
                CspParameters cspParams = new CspParameters(2048) { ProviderType = 1 };
                // PROV_RSA_FULL 
                //cspParams.ProviderName; // CSP name
                RSACryptoServiceProvider rsaProvider = new RSACryptoServiceProvider(cspParams);
                rsaProvider.FromXmlString(KInfo);

                string cryptoiv = iDict["civ"];

                string cryptokey = iDict["key"];

                byte[] cryptoIv = Convert.FromBase64String(cryptoiv);

                crypto.IV = rsaProvider.Decrypt(cryptoIv, false);

                byte[] cryptoKey = Convert.FromBase64String(cryptokey);
                crypto.Key = rsaProvider.Decrypt(cryptoKey, false);

                // Create a corresponding decryptor and epcm reader..
                ICryptoTransform ictd = crypto.CreateDecryptor();
                //32960 is chunksize used at the client end
                const int chunkSize = 32960;
                byte[] cipherTextBytes = File.ReadAllBytes(epcm);
                Stream epcmStream = File.OpenRead(epcm);
                byte[] lbytes = new byte[4];
                epcmStream.Read(lbytes, 0, 4);
                long length = BitConverter.ToUInt32(lbytes, 0);
                cipherTextBytes = cipherTextBytes.Skip(4).ToArray();
                byte[] plainTextBytes;
                try
                {
                    using (MemoryStream memoryStream = new MemoryStream(cipherTextBytes))
                    using (MemoryStream dataOut = new MemoryStream())
                    using (CryptoStream cryptoStream = new CryptoStream(memoryStream, ictd, CryptoStreamMode.Read))
                    using (var decryptedData = new BinaryReader(cryptoStream))
                    {
                        byte[] buffer = new byte[chunkSize];
                        int count;
                        while ((count = decryptedData.Read(buffer, 0, buffer.Length)) != 0)
                            dataOut.Write(buffer, 0, count);

                        plainTextBytes = dataOut.ToArray();
                    }

                    File.WriteAllBytes(outputFile, plainTextBytes);
                }
                catch (CryptographicException e)
                {
                    Console.WriteLine(e);
                }

            }

        }

        public static List<string> GetInfoDictionary(string path)
        {
            DirectoryInfo fdirInfo = new DirectoryInfo(path);
            List<string> fisMetaData = fdirInfo.EnumerateFiles("*.info", SearchOption.TopDirectoryOnly).OrderBy(file => file.LastWriteTimeUtc).Select(file => file.Name).ToList();
            return fisMetaData;
        }

        public static List<string> GetAudioFiles(string path)
        {
            DirectoryInfo fdirInfo = new DirectoryInfo(path);
            List<string> fisMetaData = fdirInfo.EnumerateFiles("*.epcm", SearchOption.TopDirectoryOnly).OrderBy(file => file.LastWriteTimeUtc).Select(file => file.Name).ToList();
            return fisMetaData;
        }

        public static Dictionary<String, String> ReadInfoFile(FileInfo infoFile)
        {
            if ((infoFile == null) || (infoFile.Directory == null))
                throw new ArgumentNullException("infoFile");

            string[] info;
            string[] pcfg;
            try
            {

                if (File.Exists(infoFile.FullName))
                {
                    info = File.ReadAllLines(infoFile.FullName);

                    //if (info.Length < RecordingTaskManager.InfoFileLines)
                    {
                        string[] tinfo = new string[13];
                        info.CopyTo(tinfo, 0);
                        info = tinfo;
                    }
                }
                else
                {
                    info = new string[13];
                }
                // info file arrangement is as follows:
                //AgentId
                //CampaignName
                //ProjectId
                //LeadName
                //PhoneNumber
                //ResultCode
                //TimeStamp (yyyyMMdd)
                //CallCenterId
                //UploadUrl
                //FileName
                //Upload retries
                for (int idx = 0; idx < info.Length; idx++)
                {
                    if (String.IsNullOrEmpty(info[idx]) || (info[idx] == " "))
                    {
                        switch (idx)
                        {
                            case 0:
                                info[0] = "";
                                break;
                            case 1:
                                info[1] = String.Empty;
                                break;
                            case 2:
                                info[2] = "";
                                break;
                            case 3:
                            case 4:
                            case 5:
                                info[idx] = String.Empty;
                                break;
                            case 6:
                                info[6] = DateTime.Now.ToString("yyyyMMdd");
                                break;
                            case 7:
                                info[7] = "";
                                break;
                            case 8:
                                info[8] = "";
                                break;
                            case 9:
                                info[9] = Path.GetFileNameWithoutExtension(infoFile.FullName);
                                break;
                            case 10:
                                info[10] = "0";
                                break;
                            case 11:
                                info[11] = string.Empty;
                                break;
                            case 12:
                                info[12] = string.Empty;
                                break;
                            default:
                                info[idx] = String.Empty;
                                break;
                        }
                    }
                }
            }
            catch (IOException)
            {
                throw;
            }
            catch (Exception ex)
            {
                // Logger.WriteFormat(LogLevel.Error, "Error reading info {0} due to {1}", infoFile.FullName, ex);
                return null;
            }

            Dictionary<string, string> idict = new Dictionary<string, string>(11);

            idict["aid"] = info[0];
            idict["cid"] = info[1];
            idict["pid"] = info[2];
            idict["lid"] = info[3];
            idict["phn"] = info[4];
            idict["res"] = info[5];
            idict["tim"] = info[6];
            idict["ccn"] = info[7];
            idict["url"] = info[8];
            idict["fil"] = info[9];
            idict["try"] = info[10];
            idict["civ"] = info[11];
            idict["key"] = info[12];

            return idict;
        }

        private static void CaptureCryptoInfo(out string CryptoIV, out string CryptoKey)
        {
            RijndaelManaged crypto;

            // Create a symmetric cryto provider
            crypto = new RijndaelManaged();

            crypto.KeySize = 256;

            // Generate keys & IVR. These can also be seeded into crypto from outside.
            crypto.GenerateIV();
            crypto.GenerateKey();

            // Select target CSP
            CspParameters cspParams = new CspParameters(2048);
            cspParams.ProviderType = 1; // PROV_RSA_FULL 
            //cspParams.ProviderName; // CSP name
            RSACryptoServiceProvider rsaProvider = new RSACryptoServiceProvider(cspParams);

            rsaProvider.FromXmlString(PubKey);
            CryptoIV = Convert.ToBase64String(rsaProvider.Encrypt(crypto.IV, false));
            CryptoKey = Convert.ToBase64String(rsaProvider.Encrypt(crypto.Key, false));

            //  Logger.Write(string.Format("CallManager :: StartShmRecording flowID {2},fileName {3} ", flow.ShmRecordingInfo.CryptoIV, flow.ShmRecordingInfo.CryptoKey, flow.FlowId, fileName),Component.WebAstra,LogLevel.Information);
        }

    }
}
![screenshot from 2016-06-30 17-19-35](https://cloud.githubusercontent.com/assets/11220070/16487246/244c0612-3ee7-11e6-893f-c47aa11fda45.png)

**Comment by svick** [comment] 2016-06-30 14:38
I can't reproduce this. When I try to run your code, the only errors I get are:

> Program.cs(48,2): error CS0246: The type or namespace name 'HandleProcessCorruptedStateExceptionsAttribute' could not be found (are you missing a using directive or an assembly reference?)
Program.cs(48,2): error CS0246: The type or namespace name 'HandleProcessCorruptedStateExceptions' could not be found (are you missing a using directive or an assembly reference?)

These errors seem valid, since that attribute does not seem to be exposed in .Net Core.

**Comment by Applebit** [comment] 2016-06-30 14:57
OK just comment HandleProcessCorruptedStateExceptions. You will be easily able to produce.

**Comment by svick** [comment] 2016-06-30 15:41
Ok, after doing that, I get the same errors as you do. Some of those errors can be fixed by adding `"System.Security.Cryptography.Csp": "4.0.0"` as a dependency. But it seems `RijndaelManaged` and `RSACryptoServiceProvider.FromXmlString` do not exist in .Net Core, so your code won't run under .Net Core.

**Comment by Applebit** [comment] 2016-06-30 17:36
Ok glad that you helped me. 

Thanks for confirmation.

**Closed** 2016-07-01 06:41 UTC
