### ISSUE TITLE
dotnet publish output directory changed

### ISSUE THREAD

**Issue by TOMKT** [dotnet/core#3524] opened 2019-10-01 20:37 UTC
Seems like the output parameter -O is now relative against the invocation directory and not to the csproj directory anymore.

Before update:
![image](https://user-images.githubusercontent.com/9083191/65998605-ee43df00-e49b-11e9-97dd-d26d96e1ee09.png)

Now:
![image](https://user-images.githubusercontent.com/9083191/65998526-c0f73100-e49b-11e9-829b-b8a429cc8698.png)

So the same command is now producing the same output but in a different directory. not very handy on a build server

**Comment by dasMulli** [comment] 2019-10-01 21:54
This was an intentional change in 3.0 since the previous behaviour was confusing

**Comment by dasMulli** [comment] 2019-10-01 22:00
@mairaw suggest to duplicate against https://github.com/dotnet/docs/issues/12486 for documentation?..

**Comment by danielloczi** [comment] 2019-10-18 07:37
I have the same problem and it causes issues to me when building my solution with Azure DevOps.
I have a solution with  a lot of projects. Each project is a dedicated app for a docker container. Previously (2.2.105), when executed the command:
`dotnet publish project.sln -c Release -o out `

The output was related to the project, so in the per project Dockerfile is easily referenced to the out folder.
Now, with Dotnet Core 3.0, executing the same command all project generates the output into the very same folder located in the solution folder, which is a mess.

```
d:\Git\ViBE\ViBE>dotnet --version
2.2.105
d:\Git\ViBE\ViBE>dotnet publish ViBE.sln -c Release -o out
 ... 
 (log shortened)
 ....
 ViBE.Device.GPIO -> d:\Git\ViBE\ViBE\ViBE.Device.GPIO\out\
 ViBE.Device.HardwarePanel.TestHarness -> d:\Git\ViBE\ViBE\ViBE.Device.HardwarePanel.TestHarness\out\
d:\Git\ViBE\ViBE>dotnet --version
3.0.100
d:\Git\ViBE\ViBE>dotnet publish ViBE.sln -c Release -o out
 ... 
 (log shortened)
 ....
ViBE.Device.HardwarePanel.TestHarness -> d:\Git\ViBE\ViBE\out\
 ViBE.Device.GPIO -> d:\Dropbox\Git\ViBE\ViBE\out\
```

I understand that was an intentional change in 3.0, but I really disagree with that.

How can I achieve the same result with dotnet core 3.0? 
Is there any way?

**Comment by derekgreer** [comment] 2019-10-21 18:34
@danielloczi As mentioned in the thread for [docs issue 12486](https://github.com/dotnet/docs/issues/12486), you can place a global.json file in the the folder (or parent folder) specifying the SDK version to use when `dotnet.exe` executes.  For example, in a parent folder containing all your projects/repos, execute the following command:

```dotnet new globaljson --sdk-version 2.2.402```

This will generate a global.json file with will cause `dotnet.exe` to use version 2.2.402.

**Comment by StephenShamakian** [comment] 2019-10-30 15:47
I just ran into this same problem! This is a horrible design decision as now its really hard to package up particular projects in a solution in a CI/CD pipeline on the build server....

Is there anyway to get this to function the way it did in 2.x? But still support future versions?

**Comment by carlossanlop** [comment] 2019-10-31 00:12
Closing as duplicate of dotnet/docs#12486
Please continue the discussion in that thread.

**Closed by carlossanlop** 2019-10-31 00:12 UTC
