### ISSUE TITLE
dotnet-sdk 2.2

### ISSUE THREAD

**Issue by CliffordOzewell** [dotnet/core#2919] opened 2019-06-21 19:16 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current
Operating System: Linux Ubuntu 18.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
OS:No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
 
Issue: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.0
E: Couldn't find any package by glob 'dotnet-sdk-2.0'
E: Couldn't find any package by regex 'dotnet-sdk-2.0'

**Comment by carlossanlop** [comment] 2019-06-25 21:12
Hello @CliffordOzewell ,
The problem is that you are trying to download version 2.0, which has reached it's end of life and it no longer supported: https://dotnet.microsoft.com/download/dotnet-core
You should try downloading 2.2 instead.

**Comment by carlossanlop** [comment] 2019-06-25 21:12
Closing as resolved, but feel free to reopen it if you have any more questions.

**Closed by carlossanlop** 2019-06-25 21:12 UTC
