### ISSUE TITLE
dotnet run

### ISSUE THREAD

**Issue by RPJack** [dotnet/core#4131] opened 2020-01-15 08:27 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/edit
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by scalablecory** [comment] 2020-01-15 15:42
Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by HebaruSan** [comment] 2020-01-16 01:17
Looks like the problem they experience is the Continue button is too close to the "I ran into an issue" button, and they don't know what GitHub is, so they click the button to submit an issue with an empty description in the hopes of continuing the tutorial.

![image](https://user-images.githubusercontent.com/1559108/72484906-86f03780-37cb-11ea-8cf5-75d6718cc175.png)

**Comment by dagood** [comment] 2020-01-16 17:09
Impressive theory... since users are directed to type `dotnet run` on that part of the tutorial, and typing "dotnet run" an pressing enter submits an issue just like this, it all adds up. I've filed https://github.com/dotnet/website/issues/1703 (private repo) to track investigating a fix with people working on the site. I'm personally not sure how to clarify this, will be interesting to see what comes up.

**Comment by dagood** [comment] 2020-01-21 20:57
With some discussion in https://github.com/dotnet/website/issues/1703, we think that left aligning the buttons, putting Continue first, and separating the buttons a little more might help clarify this. We've done that, and the page now looks like this at the end:

> ![image](https://user-images.githubusercontent.com/12819531/72842278-a66ce180-3c5d-11ea-9f7e-e13e0ad9d787.png)

Another idea that came out of the thread is auto-closing issues that only have template text in the description, which I've filed https://github.com/dotnet/core/issues/4166 for. (Cutting down the work of manually sorting through these.)

Thanks again for pointing out a potential root cause, @HebaruSan. 😄

---

Closing this issue due to lack of information about the original issue, and no response.

**Closed by dagood** 2020-01-21 20:57 UTC
Labels: needs more info
