### ISSUE TITLE
Windows Hosting Bundle for dotnet 2.2 Failed to Install on Windows Server 2008 R2

### ISSUE THREAD

**Issue by amansulaiman** [dotnet/core#2201] opened 2019-01-04 08:49 UTC
# Windows Hosting Bundle for dotnet 2.2 Failed to Install on Windows Server 2008 R2

dotnet-hosting-2.2.0-win.exe failed to install on Windows Server 2008 R2 with error0x80070570 The file or directory is corrupted and unreachable

# Log File

[2364:207C][2019-01-04T09:35:39]i001: Burn v3.11.1.2318, Windows v6.1 (Build 7601: Service Pack 1), path: C:\Users\spadmin\AppData\Local\Temp\3\{D4667C7F-4C38-46B0-8CDF-97A88969424A}\.cr\dotnet-hosting-2.2.0-win.exe
[2364:207C][2019-01-04T09:35:39]i000: Initializing string variable 'BundleNameShort' to value 'Microsoft .NET Core 2.2.0'
[2364:207C][2019-01-04T09:35:39]i000: Initializing string variable 'BundleNameSub' to value 'Windows Server Hosting'
[2364:207C][2019-01-04T09:35:39]i000: Initializing numeric variable 'OPT_NO_ANCM' to value '0'
[2364:207C][2019-01-04T09:35:39]i000: Initializing numeric variable 'OPT_NO_FTS' to value '0'
[2364:207C][2019-01-04T09:35:39]i000: Initializing numeric variable 'OPT_NO_LTS' to value '0'
[2364:207C][2019-01-04T09:35:39]i000: Initializing numeric variable 'OPT_NO_SHAREDFX' to value '0'
[2364:207C][2019-01-04T09:35:39]i000: Initializing numeric variable 'OPT_NO_RUNTIME' to value '0'
[2364:207C][2019-01-04T09:35:39]i000: Initializing numeric variable 'OPT_NO_X86' to value '0'
[2364:207C][2019-01-04T09:35:39]i000: Initializing string variable 'InstallResetIISState' to value 'disable'
[2364:207C][2019-01-04T09:35:39]i000: Initializing string variable 'InstallNoIISState' to value 'disable'
[2364:207C][2019-01-04T09:35:39]i000: Initializing string variable 'ModifyResetIISState' to value 'disable'
[2364:207C][2019-01-04T09:35:39]i000: Initializing string variable 'ModifyNoIISState' to value 'disable'
[2364:207C][2019-01-04T09:35:39]i009: Command Line: '-burn.clean.room=C:\Users\spadmin\Downloads\dotnet-hosting-2.2.0-win.exe -burn.filehandle.attached=208 -burn.filehandle.self=216'
[2364:207C][2019-01-04T09:35:39]i000: Setting string variable 'WixBundleOriginalSource' to value 'C:\Users\spadmin\Downloads\dotnet-hosting-2.2.0-win.exe'
[2364:207C][2019-01-04T09:35:39]i000: Setting string variable 'WixBundleOriginalSourceFolder' to value 'C:\Users\spadmin\Downloads\'
[2364:207C][2019-01-04T09:35:39]i000: Setting string variable 'WixBundleLog' to value 'C:\Users\spadmin\AppData\Local\Temp\dd_dd_DotNetCoreWinSvrHosting__20190104093539.log'
[2364:207C][2019-01-04T09:35:39]i000: Setting string variable 'WixBundleManufacturer' to value 'Microsoft Corporation'
[2364:1918][2019-01-04T09:35:39]i000: Setting numeric variable 'WixStdBALanguageId' to value 1033
[2364:1918][2019-01-04T09:35:39]i000: Setting version variable 'WixBundleFileVersion' to value '2.2.0.0'
[2364:207C][2019-01-04T09:35:39]i100: Detect begin, 8 packages
[2364:207C][2019-01-04T09:35:39]i000: Setting string variable 'IISCoreWebEngineInstalled_x86' to value '1'
[2364:207C][2019-01-04T09:35:39]i000: Setting string variable 'IISW3SVCInstalled_x86' to value '1'
[2364:207C][2019-01-04T09:35:39]i000: Setting string variable 'IISCoreWebEngineInstalled_x64' to value '1'
[2364:207C][2019-01-04T09:35:39]i000: Setting string variable 'IISW3SVCInstalled_x64' to value '1'
[2364:207C][2019-01-04T09:35:39]i052: Condition 'NOT (((IISCoreWebEngineInstalled_x86=1) AND (IISW3SVCInstalled_x86=1)) OR ((IISCoreWebEngineInstalled_x64=1) AND (IISW3SVCInstalled_x64=1)))' evaluates to false.
[2364:207C][2019-01-04T09:35:39]i052: Condition '((IISCoreWebEngineInstalled_x86=1) AND (IISW3SVCInstalled_x86=1)) OR ((IISCoreWebEngineInstalled_x64=1) AND (IISW3SVCInstalled_x64=1))' evaluates to true.
[2364:207C][2019-01-04T09:35:39]i000: Setting string variable 'InstallResetIISState' to value '1'
[2364:207C][2019-01-04T09:35:39]i052: Condition 'NOT (((IISCoreWebEngineInstalled_x86=1) AND (IISW3SVCInstalled_x86=1)) OR ((IISCoreWebEngineInstalled_x64=1) AND (IISW3SVCInstalled_x64=1)))' evaluates to false.
[2364:207C][2019-01-04T09:35:39]i052: Condition '((IISCoreWebEngineInstalled_x86=1) AND (IISW3SVCInstalled_x86=1)) OR ((IISCoreWebEngineInstalled_x64=1) AND (IISW3SVCInstalled_x64=1))' evaluates to true.
[2364:207C][2019-01-04T09:35:39]i000: Setting string variable 'ModifyResetIISState' to value '1'
[2364:207C][2019-01-04T09:35:39]i103: Detected related package: {1E13A8DE-E869-47F2-8D43-8564D18B1B69}, scope: PerMachine, version: 12.1.18298.0, language: 0 operation: MajorUpgrade
[2364:207C][2019-01-04T09:35:39]i103: Detected related package: {1E13A8DE-E869-47F2-8D43-8564D18B1B69}, scope: PerMachine, version: 12.1.18298.0, language: 0 operation: MajorUpgrade
[2364:207C][2019-01-04T09:35:39]i052: Condition 'DotNetRedistLtsProductVersion_x64 = v16.128.27110' evaluates to false.
[2364:207C][2019-01-04T09:35:39]i052: Condition 'DotNetRedistLtsProductVersion_x86 = v16.128.27110' evaluates to false.
[2364:207C][2019-01-04T09:35:39]i101: Detected package: AspNetCoreModule_x86, state: Absent, cached: None
[2364:207C][2019-01-04T09:35:39]i101: Detected package: AspNetCoreModule_x64, state: Absent, cached: None
[2364:207C][2019-01-04T09:35:39]i101: Detected package: AspNetCoreModuleV2_x86, state: Absent, cached: None
[2364:207C][2019-01-04T09:35:39]i101: Detected package: AspNetCoreModuleV2_x64, state: Absent, cached: None
[2364:207C][2019-01-04T09:35:39]i101: Detected package: DotNetRedistLts_x64, state: Absent, cached: None
[2364:207C][2019-01-04T09:35:39]i101: Detected package: DotNetRedistLts_x86, state: Absent, cached: None
[2364:207C][2019-01-04T09:35:39]i101: Detected package: AspNetCoreSharedFramework_x86, state: Absent, cached: None
[2364:207C][2019-01-04T09:35:39]i101: Detected package: AspNetCoreSharedFramework_x64, state: Present, cached: Complete
[2364:207C][2019-01-04T09:35:39]i199: Detect complete, result: 0x0
[2364:1918][2019-01-04T09:35:39]i000: Disable control ModifyNoIIS
[2364:207C][2019-01-04T09:35:42]i200: Plan begin, 8 packages, action: Repair
[2364:207C][2019-01-04T09:35:42]i052: Condition 'NOT VersionNT64 AND (VersionNT >= v6.1) AND (IISCoreWebEngineInstalled_x86=1) AND (IISW3SVCInstalled_x86=1) AND (NOT OPT_NO_ANCM)' evaluates to false.
[2364:207C][2019-01-04T09:35:42]i052: Condition 'VersionNT64 AND (VersionNT64 >= v6.1) AND (IISCoreWebEngineInstalled_x64=1) AND (IISW3SVCInstalled_x64=1) AND (NOT OPT_NO_ANCM)' evaluates to true.
[2364:207C][2019-01-04T09:35:42]i000: Setting string variable 'WixBundleRollbackLog_AspNetCoreModule_x64' to value 'C:\Users\spadmin\AppData\Local\Temp\dd_dd_DotNetCoreWinSvrHosting__20190104093539_000_AspNetCoreModule_x64_rollback.log'
[2364:207C][2019-01-04T09:35:42]i000: Setting string variable 'WixBundleLog_AspNetCoreModule_x64' to value 'C:\Users\spadmin\AppData\Local\Temp\dd_dd_DotNetCoreWinSvrHosting__20190104093539_000_AspNetCoreModule_x64.log'
[2364:207C][2019-01-04T09:35:42]i052: Condition 'NOT VersionNT64 AND (VersionNT >= v6.1) AND (IISCoreWebEngineInstalled_x86=1) AND (IISW3SVCInstalled_x86=1) AND (NOT OPT_NO_ANCM)' evaluates to false.
[2364:207C][2019-01-04T09:35:42]i052: Condition 'VersionNT64 AND (VersionNT64 >= v6.1) AND (IISCoreWebEngineInstalled_x64=1) AND (IISW3SVCInstalled_x64=1) AND (NOT OPT_NO_ANCM)' evaluates to true.
[2364:207C][2019-01-04T09:35:42]i000: Setting string variable 'WixBundleRollbackLog_AspNetCoreModuleV2_x64' to value 'C:\Users\spadmin\AppData\Local\Temp\dd_dd_DotNetCoreWinSvrHosting__20190104093539_001_AspNetCoreModuleV2_x64_rollback.log'
[2364:207C][2019-01-04T09:35:42]i000: Setting string variable 'WixBundleLog_AspNetCoreModuleV2_x64' to value 'C:\Users\spadmin\AppData\Local\Temp\dd_dd_DotNetCoreWinSvrHosting__20190104093539_001_AspNetCoreModuleV2_x64.log'
[2364:207C][2019-01-04T09:35:42]i052: Condition 'VersionNT64 AND (NOT OPT_NO_RUNTIME)' evaluates to true.
[2364:207C][2019-01-04T09:35:42]w321: Skipping dependency registration on package with no dependency providers: DotNetRedistLts_x64
[2364:207C][2019-01-04T09:35:42]i000: Setting string variable 'WixBundleLog_DotNetRedistLts_x64' to value 'C:\Users\spadmin\AppData\Local\Temp\dd_dd_DotNetCoreWinSvrHosting__20190104093539_002_DotNetRedistLts_x64.log'
[2364:207C][2019-01-04T09:35:42]i052: Condition '(NOT OPT_NO_RUNTIME) AND (NOT OPT_NO_X86)' evaluates to true.
[2364:207C][2019-01-04T09:35:42]w321: Skipping dependency registration on package with no dependency providers: DotNetRedistLts_x86
[2364:207C][2019-01-04T09:35:42]i000: Setting string variable 'WixBundleLog_DotNetRedistLts_x86' to value 'C:\Users\spadmin\AppData\Local\Temp\dd_dd_DotNetCoreWinSvrHosting__20190104093539_003_DotNetRedistLts_x86.log'
[2364:207C][2019-01-04T09:35:42]i052: Condition '(NOT OPT_NO_SHAREDFX) AND (NOT OPT_NO_X86)' evaluates to true.
[2364:207C][2019-01-04T09:35:42]i000: Setting string variable 'WixBundleRollbackLog_AspNetCoreSharedFramework_x86' to value 'C:\Users\spadmin\AppData\Local\Temp\dd_dd_DotNetCoreWinSvrHosting__20190104093539_004_AspNetCoreSharedFramework_x86_rollback.log'
[2364:207C][2019-01-04T09:35:42]i000: Setting string variable 'WixBundleLog_AspNetCoreSharedFramework_x86' to value 'C:\Users\spadmin\AppData\Local\Temp\dd_dd_DotNetCoreWinSvrHosting__20190104093539_004_AspNetCoreSharedFramework_x86.log'
[2364:207C][2019-01-04T09:35:42]i052: Condition 'VersionNT64 AND (NOT OPT_NO_SHAREDFX)' evaluates to true.
[2364:207C][2019-01-04T09:35:42]i000: Setting string variable 'WixBundleLog_AspNetCoreSharedFramework_x64' to value 'C:\Users\spadmin\AppData\Local\Temp\dd_dd_DotNetCoreWinSvrHosting__20190104093539_005_AspNetCoreSharedFramework_x64.log'
[2364:207C][2019-01-04T09:35:42]i201: Planned package: AspNetCoreModule_x86, state: Absent, default requested: Absent, ba requested: Absent, execute: None, rollback: None, cache: No, uncache: No, dependency: None
[2364:207C][2019-01-04T09:35:42]i201: Planned package: AspNetCoreModule_x64, state: Absent, default requested: Repair, ba requested: Repair, execute: Install, rollback: Uninstall, cache: Yes, uncache: No, dependency: Register
[2364:207C][2019-01-04T09:35:42]i201: Planned package: AspNetCoreModuleV2_x86, state: Absent, default requested: Absent, ba requested: Absent, execute: None, rollback: None, cache: No, uncache: No, dependency: None
[2364:207C][2019-01-04T09:35:42]i201: Planned package: AspNetCoreModuleV2_x64, state: Absent, default requested: Repair, ba requested: Repair, execute: Install, rollback: Uninstall, cache: Yes, uncache: No, dependency: Register
[2364:207C][2019-01-04T09:35:42]i201: Planned package: DotNetRedistLts_x64, state: Absent, default requested: Repair, ba requested: Repair, execute: Install, rollback: None, cache: Yes, uncache: No, dependency: None
[2364:207C][2019-01-04T09:35:42]i201: Planned package: DotNetRedistLts_x86, state: Absent, default requested: Repair, ba requested: Repair, execute: Install, rollback: None, cache: Yes, uncache: No, dependency: None
[2364:207C][2019-01-04T09:35:42]i201: Planned package: AspNetCoreSharedFramework_x86, state: Absent, default requested: Repair, ba requested: Repair, execute: Install, rollback: Uninstall, cache: Yes, uncache: No, dependency: Register
[2364:207C][2019-01-04T09:35:42]i201: Planned package: AspNetCoreSharedFramework_x64, state: Present, default requested: Repair, ba requested: Repair, execute: Repair, rollback: None, cache: No, uncache: No, dependency: Register
[2364:207C][2019-01-04T09:35:42]i299: Plan complete, result: 0x0
[2364:207C][2019-01-04T09:35:42]i300: Apply begin
[2364:207C][2019-01-04T09:35:42]i010: Launching elevated engine process.
[2364:207C][2019-01-04T09:35:43]i011: Launched elevated engine process.
[2364:207C][2019-01-04T09:35:44]i012: Connected to elevated engine.
[2168:2BF4][2019-01-04T09:35:44]i358: Pausing automatic updates.
[2168:2BF4][2019-01-04T09:35:44]i359: Paused automatic updates.
[2168:2BF4][2019-01-04T09:35:44]i360: Creating a system restore point.
[2168:2BF4][2019-01-04T09:35:44]i362: System restore disabled, system restore point not created.
[2168:2BF4][2019-01-04T09:35:44]i371: Updating session, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{3f5ccba0-5ea7-42bc-8da7-827b48abf6c9}, resume: Active, restart initiated: No, disable resume: No
[2364:3F7C][2019-01-04T09:35:44]i336: Acquiring container: WixAttachedContainer, copy from: C:\Users\spadmin\Downloads\dotnet-hosting-2.2.0-win.exe
[2364:3F7C][2019-01-04T09:35:44]i000: Setting string variable 'WixBundleLastUsedSource' to value 'C:\Users\spadmin\Downloads\'
[2364:1CF8][2019-01-04T09:35:44]e000: Error 0x80070570: Failed to extract all files from container, erf: 1:4:0
[2364:3F7C][2019-01-04T09:35:44]e000: Error 0x80070570: Failed to begin and wait for operation.
[2364:3F7C][2019-01-04T09:35:44]e000: Error 0x80070570: Failed to extract payload: a4 from container: WixAttachedContainer
[2364:3F7C][2019-01-04T09:35:44]e312: Failed to extract payloads from container: WixAttachedContainer to working path: C:\Users\spadmin\AppData\Local\Temp\3\{8C544A9D-6875-4DF3-8476-4D9496A40879}\01AEA8E63E2B213C1B3988B323775FA3F6141C78, error: 0x80070570.
[2364:207C][2019-01-04T09:35:44]e000: Error 0x80070570: Cache thread exited unexpectedly.
[2168:2BF4][2019-01-04T09:35:44]i372: Session end, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{3f5ccba0-5ea7-42bc-8da7-827b48abf6c9}, resume: ARP, restart: None, disable resume: No
[2168:2BF4][2019-01-04T09:35:44]i371: Updating session, registration key: SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{3f5ccba0-5ea7-42bc-8da7-827b48abf6c9}, resume: ARP, restart initiated: No, disable resume: No
[2364:207C][2019-01-04T09:35:44]i399: Apply complete, result: 0x80070570, restart: None, ba requested restart:  No

**Comment by karelz** [comment] 2019-01-05 20:42
Are you able to reproduce it on more than 1 machine?

**Comment by TobbeM** [comment] 2019-01-07 09:31
We have the same problem. Tried to install on both Win Server 2012 R2 and Win Server 2016 with the same result.
![image](https://user-images.githubusercontent.com/46441716/50760162-4f20ec80-1267-11e9-8b5f-678bfddc875e.png)

**Comment by karelz** [comment] 2019-01-08 04:07
@rakeshsinghranchi is it a known issue? Should we move it to core-setup repo?

**Comment by rakeshsinghranchi** [comment] 2019-01-08 09:12
@natemcmaster  , @joeloff  - can you take a look into this issue ? Also,can you please move this issue to appropriate repo ?

**Comment by amansulaiman** [comment] 2019-01-08 10:12
@karelz I resolved my issue by redownloading the exe file on a different network and a different Server. I observed my network breaks the downloaded file that's why I am getting the error.

@TobbeM Please, can you check your downloaded file and try reinstalling?

**Comment by karelz** [comment] 2019-01-08 16:17
OK, closing until it is confirmed that it is caused by something else than installer corruption.
Thanks @amansulaiman for the info!

**Closed by karelz** 2019-01-08 16:17 UTC
Labels: bug
