### ISSUE TITLE
Why does this code have different results on different OS

### ISSUE THREAD

**Issue by crystal-lz** [dotnet/core#5522] opened 2020-11-05 10:34 UTC
```
string strText = "1123\r\ntest\tabc";
Console.WriteLine($"TEXT[{strText}]\r\n");
Console.WriteLine($"IndexOf [\\r] {strText.IndexOf("\r")}");
Console.WriteLine($"IndexOf [\\n] {strText.IndexOf("\n")}");
Console.WriteLine($"IndexOf [\\t] {strText.IndexOf("\t")}");

//==output=====[mac or ubuntu]=======

TEXT:[1123
test    abc]

IndexOf [\r] 4
IndexOf [\n] -1
IndexOf [\t] 10
//---------------------------------------
-1  ?????????? 
```

**Comment by carlossanlop** [comment] 2020-11-06 19:03
@GrabYourPitchforks I think you may have some context on this question. Can you please help?

**Comment by GrabYourPitchforks** [comment] 2020-11-09 01:08
Dupe of https://github.com/dotnet/runtime/issues/43736.

In a nutshell, the overload of `string.IndexOf` that's being called is performing a _culture-sensitive_ check, when an _ordinal_ check is intended.

There are two suggested workarounds:

1. If you're searching for a single char (e.g., `'\n'`), change the code from `strText.IndexOf("\n")` to `strText.IndexOf('\n')` instead. Searching for single chars will be ordinal.
2. If you're searching for a literal substring, change the code from `strText.IndexOf("text")` to `strText.IndexOf("text", StringComparison.Ordinal)` instead.

The code analyzer rules __CA1307__ and __CA1309__ can assist with this. See https://github.com/dotnet/docs/issues/21249, section "Option 1: Enable code analyzers to help detect possibly-buggy call sites" for more information.

**Closed by GrabYourPitchforks** 2020-11-09 01:08 UTC
Labels: question
