### ISSUE TITLE
dotnet-sdk-2.2 does not install because of missing libssl1.0 in Ubuntu 19.04

### ISSUE THREAD

**Issue by zegracia** [dotnet/core#2769] opened 2019-05-21 22:53 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current
Operating System: Linux Ubuntu 19.04 - x64

Ubuntu 19.04 has libssl1.1, and not 1.0. This results in broken packages error, so dotnet-sdk-2.2 does not install.

**Comment by karelz** [comment] 2019-05-22 20:49
Duplicate of #2526

**Closed by karelz** 2019-05-22 20:49 UTC
