### ISSUE TITLE
Broken reference to .NET Standard 2.1 library in .NET Core 3.0 preview 6

### ISSUE THREAD

**Issue by hez2010** [dotnet/core#2878] opened 2019-06-14 17:25 UTC
# Broken reference to .NET Standard 2.1 library in .NET Core 3.0 preview 6

After upgrading to .NET Core 3.0 preview 6, .NET Core 3.0 apps cannot use .NET Standard 2.1 libraries anymore. 

# General

For example, see https://github.com/hez2010/HLib. It won't build if I upgrade to .NET Standard 2.1. 
Works fine on .NET Standard 2.0.

**Comment by karelz** [comment] 2019-06-14 18:11
@joperezr @ericstj can you lease advice where to route it?

**Comment by ericstj** [comment] 2019-06-14 20:13
I was unable to reproduce any problem.
```
C:\scratch\HLib>dotnet build
Microsoft (R) Build Engine version 16.2.0-preview-19278-01+d635043bd for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 24.61 ms for C:\scratch\HLib\src\HLib.csproj.
  Restore completed in 46.13 ms for C:\scratch\HLib\test\HLib.Test.csproj.
C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(158,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [C:\scratch\HLib\test\HLib.Test.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(158,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [C:\scratch\HLib\src\HLib.csproj]
  HLib -> C:\scratch\HLib\src\bin\Debug\netstandard2.1\HLib.dll
  HLib.Test -> C:\scratch\HLib\test\bin\Debug\netcoreapp3.0\HLib.Test.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.92
```

Can you share more information about what sort of failure you are seeing?

Do things like provide the dotnet --info output, and the error you are seeing.

**Comment by joperezr** [comment] 2019-06-14 20:18
If this is a build-time failure that you are seeing, then can you please also attach a binlog file? to produce one, simply run the following on a developer command prompt: `msbuild yourProject.csproj /t:rebuild /bl` which will generate a msbuild.binlog file.

If this is a runtime failure, do you mind sharing either exact repro steps or at least failure/call stack details?

**Comment by hez2010** [comment] 2019-06-15 03:17
It works while using .NET Core cl tools, but if you use MSBuild, it will fail.

using dotnet command lines:
```
C:\Users\hez20\source\repos\HLib>dotnet build
Microsoft (R) Build Engine version 16.2.0-preview-19278-01+d635043bd for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 71.07 ms for C:\Users\hez20\source\repos\HLib\src\HLib.csproj.
  Restore completed in 797.46 ms for C:\Users\hez20\source\repos\HLib\test\HLib.Test.csproj.
C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(158,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [C:\Users\hez20\source\repos\HLib\test\HLib.Test.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(158,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [C:\Users\hez20\source\repos\HLib\src\HLib.csproj]
  HLib -> C:\Users\hez20\source\repos\HLib\src\bin\Debug\netstandard2.1\HLib.dll
  HLib.Test -> C:\Users\hez20\source\repos\HLib\test\bin\Debug\netcoreapp3.0\HLib.Test.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:29.09
```

using MSBuild:
```
C:\Users\hez20\source\repos\HLib>msbuild HLib.sln
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 6/15/2019 11:15:58 AM.
Project "C:\Users\hez20\source\repos\HLib\HLib.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Any CPU".
Project "C:\Users\hez20\source\repos\HLib\HLib.sln" (1) is building "C:\Users\hez20\source\repos\HLib\src\HLib.csproj"
(2) on node 1 (default targets).
_CheckForNETCoreSdkIsPreview:
C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInfer
ence.targets(158,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-
preview [C:\Users\hez20\source\repos\HLib\src\HLib.csproj]
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the i
nput files.
CoreCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /unsafe- /
  checked- /nowarn:1701,1702,1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:TRACE;DEBUG;NETSTANDARD;NETSTANDA
  RD2_1 /nullable:enable /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\
  netstandard2.1\Microsoft.Win32.Primitives.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.
  0-preview6-27804-01\ref\netstandard2.1\mscorlib.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Re
  f\2.1.0-preview6-27804-01\ref\netstandard2.1\netstandard.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.L
  ibrary.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.AppContext.dll" /reference:"C:\Program Files\dotnet\pack
  s\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Buffers.dll" /reference:"C:\Program Files
  \dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Collections.Concurrent.dll" /
  reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Co
  llections.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstand
  ard2.1\System.Collections.NonGeneric.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-pre
  view6-27804-01\ref\netstandard2.1\System.Collections.Specialized.dll" /reference:"C:\Program Files\dotnet\packs\NETSt
  andard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.ComponentModel.Composition.dll" /reference:"C:\P
  rogram Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.ComponentModel.dl
  l" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\Syste
  m.ComponentModel.EventBasedAsync.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview
  6-27804-01\ref\netstandard2.1\System.ComponentModel.Primitives.dll" /reference:"C:\Program Files\dotnet\packs\NETStan
  dard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.ComponentModel.TypeConverter.dll" /reference:"C:\P
  rogram Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Console.dll" /ref
  erence:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Core.
  dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\Sys
  tem.Data.Common.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\ne
  tstandard2.1\System.Data.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-
  01\ref\netstandard2.1\System.Diagnostics.Contracts.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library
  .Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Diagnostics.Debug.dll" /reference:"C:\Program Files\dotnet\pac
  ks\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Diagnostics.FileVersionInfo.dll" /refere
  nce:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Diagnost
  ics.Process.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netsta
  ndard2.1\System.Diagnostics.StackTrace.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-p
  review6-27804-01\ref\netstandard2.1\System.Diagnostics.TextWriterTraceListener.dll" /reference:"C:\Program Files\dotn
  et\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Diagnostics.Tools.dll" /reference:
  "C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Diagnostics.
  TraceSource.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netsta
  ndard2.1\System.Diagnostics.Tracing.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-prev
  iew6-27804-01\ref\netstandard2.1\System.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-
  preview6-27804-01\ref\netstandard2.1\System.Drawing.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Librar
  y.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Drawing.Primitives.dll" /reference:"C:\Program Files\dotnet\p
  acks\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Dynamic.Runtime.dll" /reference:"C:\Pr
  ogram Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Globalization.Cale
  ndars.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2
  .1\System.Globalization.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-0
  1\ref\netstandard2.1\System.Globalization.Extensions.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Libra
  ry.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.IO.Compression.dll" /reference:"C:\Program Files\dotnet\pack
  s\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.IO.Compression.FileSystem.dll" /reference
  :"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.IO.Compress
  ion.ZipFile.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netsta
  ndard2.1\System.IO.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref
  \netstandard2.1\System.IO.FileSystem.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-pre
  view6-27804-01\ref\netstandard2.1\System.IO.FileSystem.DriveInfo.dll" /reference:"C:\Program Files\dotnet\packs\NETSt
  andard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.IO.FileSystem.Primitives.dll" /reference:"C:\Pro
  gram Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.IO.FileSystem.Watch
  er.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\
  System.IO.IsolatedStorage.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804
  -01\ref\netstandard2.1\System.IO.MemoryMappedFiles.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library
  .Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.IO.Pipes.dll" /reference:"C:\Program Files\dotnet\packs\NETSta
  ndard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.IO.UnmanagedMemoryStream.dll" /reference:"C:\Prog
  ram Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Linq.dll" /reference
  :"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Linq.Expres
  sions.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2
  .1\System.Linq.Parallel.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-0
  1\ref\netstandard2.1\System.Linq.Queryable.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1
  .0-preview6-27804-01\ref\netstandard2.1\System.Memory.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Libr
  ary.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Net.dll" /reference:"C:\Program Files\dotnet\packs\NETStand
  ard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Net.Http.dll" /reference:"C:\Program Files\dotnet\p
  acks\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Net.NameResolution.dll" /reference:"C:
  \Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Net.NetworkInfo
  rmation.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandar
  d2.1\System.Net.Ping.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\r
  ef\netstandard2.1\System.Net.Primitives.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-
  preview6-27804-01\ref\netstandard2.1\System.Net.Requests.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.L
  ibrary.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Net.Security.dll" /reference:"C:\Program Files\dotnet\pa
  cks\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Net.Sockets.dll" /reference:"C:\Program
   Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Net.WebHeaderCollection
  .dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\Sy
  stem.Net.WebSockets.Client.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-2780
  4-01\ref\netstandard2.1\System.Net.WebSockets.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\
  2.1.0-preview6-27804-01\ref\netstandard2.1\System.Numerics.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard
  .Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Numerics.Vectors.dll" /reference:"C:\Program Files\dot
  net\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.ObjectModel.dll" /reference:"C:\P
  rogram Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Reflection.Dispat
  chProxy.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandar
  d2.1\System.Reflection.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01
  \ref\netstandard2.1\System.Reflection.Emit.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1
  .0-preview6-27804-01\ref\netstandard2.1\System.Reflection.Emit.ILGeneration.dll" /reference:"C:\Program Files\dotnet\
  packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Reflection.Emit.Lightweight.dll" /ref
  erence:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Refle
  ction.Extensions.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\n
  etstandard2.1\System.Reflection.Primitives.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1
  .0-preview6-27804-01\ref\netstandard2.1\System.Resources.Reader.dll" /reference:"C:\Program Files\dotnet\packs\NETSta
  ndard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Resources.ResourceManager.dll" /reference:"C:\Pro
  gram Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Resources.Writer.dl
  l" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\Syste
  m.Runtime.CompilerServices.VisualC.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-previ
  ew6-27804-01\ref\netstandard2.1\System.Runtime.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref
  \2.1.0-preview6-27804-01\ref\netstandard2.1\System.Runtime.Extensions.dll" /reference:"C:\Program Files\dotnet\packs\
  NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Runtime.Handles.dll" /reference:"C:\Program
   Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Runtime.InteropServices
  .dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\Sy
  stem.Runtime.InteropServices.RuntimeInformation.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Re
  f\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Runtime.Numerics.dll" /reference:"C:\Program Files\dotnet\packs\N
  ETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Runtime.Serialization.dll" /reference:"C:\Pr
  ogram Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Runtime.Serializat
  ion.Formatters.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\net
  standard2.1\System.Runtime.Serialization.Json.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\
  2.1.0-preview6-27804-01\ref\netstandard2.1\System.Runtime.Serialization.Primitives.dll" /reference:"C:\Program Files\
  dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Runtime.Serialization.Xml.dll"
   /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.
  Security.Claims.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\ne
  tstandard2.1\System.Security.Cryptography.Algorithms.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Libra
  ry.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Security.Cryptography.Csp.dll" /reference:"C:\Program Files\
  dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Security.Cryptography.Encoding
  .dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\Sy
  stem.Security.Cryptography.Primitives.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-pr
  eview6-27804-01\ref\netstandard2.1\System.Security.Cryptography.X509Certificates.dll" /reference:"C:\Program Files\do
  tnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Security.Principal.dll" /referen
  ce:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Security.
  SecureString.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netst
  andard2.1\System.ServiceModel.Web.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-previe
  w6-27804-01\ref\netstandard2.1\System.Text.Encoding.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Librar
  y.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Text.Encoding.Extensions.dll" /reference:"C:\Program Files\do
  tnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Text.RegularExpressions.dll" /re
  ference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Thre
  ading.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2
  .1\System.Threading.Overlapped.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-
  27804-01\ref\netstandard2.1\System.Threading.Tasks.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library
  .Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Threading.Tasks.Extensions.dll" /reference:"C:\Program Files\d
  otnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Threading.Tasks.Parallel.dll" /
  reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Th
  reading.Thread.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\net
  standard2.1\System.Threading.ThreadPool.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-
  preview6-27804-01\ref\netstandard2.1\System.Threading.Timer.dll" /reference:"C:\Program Files\dotnet\packs\NETStandar
  d.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Transactions.dll" /reference:"C:\Program Files\dotnet
  \packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.ValueTuple.dll" /reference:"C:\Progr
  am Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Web.dll" /reference:"
  C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Windows.dll"
  /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.X
  ml.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\
  System.Xml.Linq.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\ne
  tstandard2.1\System.Xml.ReaderWriter.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-pre
  view6-27804-01\ref\netstandard2.1\System.Xml.Serialization.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard
  .Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Xml.XDocument.dll" /reference:"C:\Program Files\dotnet
  \packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Xml.XmlDocument.dll" /reference:"C:\
  Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\System.Xml.XmlSerialize
  r.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\netstandard2.1\S
  ystem.Xml.XPath.dll" /reference:"C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0-preview6-27804-01\ref\ne
  tstandard2.1\System.Xml.XPath.XDocument.dll" /debug+ /debug:portable /filealign:512 /optimize- /out:obj\Debug\netstan
  dard2.1\HLib.dll /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Static Analysis T
  ools\\Rule Sets\MinimumRecommendedRules.ruleset" /target:library /warnaserror- /utf8output /deterministic+ /langversi
  on:8.0 Functional\Currying\CurryingExtensions.cs Tasks\TaskExtensions.cs "C:\Users\hez20\AppData\Local\Temp\.NETStand
  ard,Version=v2.1.AssemblyAttributes.cs" obj\Debug\netstandard2.1\HLib.AssemblyInfo.cs /warnaserror+:NU1605
  Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\
  MSBuild\Current\Bin\Roslyn
CopyFilesToOutputDirectory:
  Copying file from "C:\Users\hez20\source\repos\HLib\src\obj\Debug\netstandard2.1\HLib.dll" to "C:\Users\hez20\source\
  repos\HLib\src\bin\Debug\netstandard2.1\HLib.dll".
  HLib -> C:\Users\hez20\source\repos\HLib\src\bin\Debug\netstandard2.1\HLib.dll
  Copying file from "C:\Users\hez20\source\repos\HLib\src\obj\Debug\netstandard2.1\HLib.pdb" to "C:\Users\hez20\source\
  repos\HLib\src\bin\Debug\netstandard2.1\HLib.pdb".
Done Building Project "C:\Users\hez20\source\repos\HLib\src\HLib.csproj" (default targets).

Project "C:\Users\hez20\source\repos\HLib\HLib.sln" (1) is building "C:\Users\hez20\source\repos\HLib\test\HLib.Test.cs
proj" (3) on node 1 (default targets).
C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.TargetingPackResol
ution.targets(185,5): error NETSDK1073: The FrameworkReference 'NETStandard.Library' was not recognized [C:\Users\hez20
\source\repos\HLib\test\HLib.Test.csproj]
Done Building Project "C:\Users\hez20\source\repos\HLib\test\HLib.Test.csproj" (default targets) -- FAILED.

Done Building Project "C:\Users\hez20\source\repos\HLib\HLib.sln" (default targets) -- FAILED.


Build FAILED.

"C:\Users\hez20\source\repos\HLib\HLib.sln" (default target) (1) ->
"C:\Users\hez20\source\repos\HLib\test\HLib.Test.csproj" (default target) (3) ->
(ResolveTargetingPacks target) ->
  C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.TargetingPackRes
olution.targets(185,5): error NETSDK1073: The FrameworkReference 'NETStandard.Library' was not recognized [C:\Users\hez
20\source\repos\HLib\test\HLib.Test.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:21.72
```


binlog: [msbuild.zip](https://github.com/dotnet/core/files/3292659/msbuild.zip)

**Comment by joperezr** [comment] 2019-06-17 16:46
This is a wierd one, seems to be a problem with the sdk where it isn't copying metadata of transitive framework references. This is not something I'm super familiar with, @dsplaisted do you mind taking a look? It is very weird that this works fine when building with the CLI but doesn't work with MSBuild given that MSBuild still seems to be using the SDK. @hez2010 just wondering, have you tried updating your VS 2019 to the very latest preview?

**Comment by dsplaisted** [comment] 2019-06-17 16:49
This looks like [this bug](https://github.com/dotnet/cli/issues/11378), which should be fixed in the latest VS preview.

There is also a workaround [here](https://github.com/dotnet/cli/issues/11378#issuecomment-499988244)

**Comment by joperezr** [comment] 2019-06-17 18:29
Given that there is a workaround and that the issue is fixed in latest version, I'll go ahead and close this one for now. @hez2010 if this still repros even after the workaround or updating VS, then please reopen and we will investigate further.

**Comment by ralmsdeveloper** [comment] 2019-06-25 02:16
@joperezr 
I have the same problem with the most up-to-date version of VS 2019 Enterprise

**Comment by ericstj** [comment] 2019-06-25 03:50
@ralmsdeveloper did you see the details in https://github.com/dotnet/cli/issues/11378?  Did you install the latest Preview6 SDK?

**Closed** 2019-06-25 03:50 UTC
Labels: needs more info

**Comment by ralmsdeveloper** [comment] 2019-06-25 04:02
@ericstj,

I've tried, but it does not work, I'm with VS2019 Enterprise and also the preview version, both do not work!
See the complete log.
https://github.com/aspnet/EntityFrameworkCore/issues/16230

**Comment by mc0re** [comment] 2019-11-05 13:20
November 2019, I still cannot use a .NET Standard 2.1 library from a .NET Core 3 project...

**Comment by dsplaisted** [comment] 2019-11-05 17:20
@mc0re We are not aware of any issues with this in the 3.0.100 .NET Core SDK.  If you are hitting this, please file a new issue with the details.  Thanks!
