### ISSUE TITLE
Installation is fine; cannot run file. 

### ISSUE THREAD

**Issue by Dylanthemachine** [dotnet/core#7634] opened 2022-07-25 18:07 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: linux/Ubuntu

When I run the "hello world" dotnet file, nothing happens. I don't get an error warning. Just nothing happens. 
I also need to run as a superuser. Might be related; might not, 

![dotnetfailure](https://user-images.githubusercontent.com/67968703/180843946-829354ee-d254-40e2-98ee-12c9c1ce99ae.png)

**Comment by mairaw** [comment] 2022-07-25 22:11
Did you install via snap? We do see a lot of issues with that, if that's the case.

**Comment by Dylanthemachine** [comment] 2022-07-25 22:18
I don't think so. I installed this a few weeks ago when I was on boarding
and didn't check . I use apt.

**Comment by mairaw** [comment] 2022-07-25 23:21
seems like a duplicate of #7627

**Comment by Dylanthemachine** [comment] 2022-07-25 23:42
I doubt it; I just reinstalled dotnet according to that ticket and still am getting the same issue

**Comment by pratikkabade** [comment] 2022-07-26 02:39
@Dylanthemachine I've encountered the same issue
Refer [this](https://github.com/dotnet/core/issues/7627#issuecomment-1193504250)

**Comment by GODINME** [comment] 2022-07-29 05:38
On Linux distribution like ubuntu: 
Install the .NET Core SDK  with snapcraft (snap package manager) as demonstrated following steps bellow:

A. Installing it for the first time on your machine / on a new machine:

1. sudo snap install dotnet-sdk --classic
2. sudo ln -s /snap/dotnet-sdk/current/dotnet /usr/local/bin/dotnet


B. Not for the first time / installed previous version before:

1. sudo snap install dotnet-sdk --classic
2. sudo rm /usr/local/bin/dotnet
3. sudo ln -s /snap/dotnet-sdk/current/dotnet /usr/local/bin/dotnet

**Comment by mairaw** [comment] 2024-02-22 02:08
Closing based on this comment from @leecow last year:
https://github.com/dotnet/core/issues/7627#issuecomment-1585176247

But please let us know if you still can't install it via the instructions on https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu

**Closed by mairaw** 2024-02-22 02:08 UTC
Labels: area-setup
