### ISSUE TITLE
Support WCF server in .net core

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/core#2522] opened 2019-03-29 17:06 UTC
I am asking that the .net core team add WCF server support to .net core. I have been looking for the last year and half for this support and checked out the alternatives. The latest I have reviewed is grpc dotnet, which hail back to the days of creating messages in the early 90s. I don't want to provide the message structures to define an rpc. I want to hand the interface and let the software figure it out. Please look at some form of WCF server that provides this feature. It does not have to support all of the old protocols. Anything of this form would help developers. We are trying to switch completely to .net core 3, but WCF is the sticking point.

**Comment by karelz** [comment] 2019-03-29 18:36
gRPC is the officially supported RPC solution on .NET Core (or will be soon in 3.0 time frame).

@glennc do we have official answer for WCF server yet?

**Comment by karelz** [comment] 2019-03-29 18:36
Duplicate of https://github.com/dotnet/wcf/issues/1200

**Closed by karelz** 2019-03-29 18:36 UTC

**Comment by dgxhubbard** [comment] 2019-03-29 18:56
I realize this is a duplicate of [dotnet/wcf#1200](https://github.com/dotnet/wcf/issues/1200) but the question of some simplified replacement for server side wcf should not be closed. I have opened a similar question of grpc [grpc-dotnet](https://github.com/grpc/grpc-dotnet/issues/189). RPC is a ground up rebuild and really not a good one. Trying to find some middle ground to make porting easier would definitely help. @glennc this is a discussion that will help a lot of developers. We would love to switch to .net core 3. We spent quite a bit of time switching what we could in our apps to .net core 2, but we really cannot go any farther without the simplifications the WCF api brings. A simplified replacement is what is needed not throwing out all our WCF to build on grpc.

**Comment by dgxhubbard** [comment] 2019-03-29 19:07
As a note saying that grpc dotnet is not a good solution is not a comment on the developers of grpc dotnet. They were given a task of building grpc on .net. I question the choice of grpc as the solution to the problem. Given some way of taking an interface and creating a proxy and a service endpoint purely in code is what I would like as the solution. Using the WCF API is one approach that minimizes the work of developers who want to port .net core 3.
