### ISSUE TITLE
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run

### ISSUE THREAD

**Issue by jgochoa1** [dotnet/core#8702] opened 2023-08-21 04:59 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment] 2023-08-21 05:38
Duplicate of #8701

**Closed by mairaw** 2023-08-21 05:38 UTC
