### ISSUE TITLE
Fail to install dotnet core 3.1.11 on SLES 12 SP5

### ISSUE THREAD

**Issue by rtssrl** [dotnet/core#5856] opened 2021-01-15 17:56 UTC
Following instructions at https://docs.microsoft.com/en-us/dotnet/core/install/linux-sles:

`zypper in aspnetcore-runtime-3.1`

got:
```
Installation of dotnet-runtime-3.1-3.1.11-1.x86_64 failed:
Error: Subprocess failed. Error: RPM failed: error: unpacking of archive failed on file /usr/share/dotnet/shared/Microsoft.NETCore.App/3.1.11/Microsoft.VisualBasic.Core.dll;6001d5be: cpio: read failed - No such file or directory
error: dotnet-runtime-3.1-3.1.11-1.x86_64: install failed
```

Version 3.1.10 is OK

**Comment by mairaw** [comment] 2021-01-15 18:39
@leecow @dagood can you help here?

**Comment by dagood** [comment] 2021-01-15 18:48
@rbhanda maybe this is related to other 3.1.11 packages.microsoft.com issues? https://github.com/dotnet/core/issues/5838
/cc @NikolaMilosavljevic

**Comment by rbhanda** [comment] 2021-01-15 19:02
I was able to install .NET 5.0.102 SDK on a SLES linux machine. I wonder if this is related to folks hitting a different mirror and that is why I am not able to repro this.

**Comment by rtssrl** [comment] 2021-01-18 14:25
Now, I noticed that http://packages.microsoft.com/sles/12/prod/dotnet-runtime-3.1.11-x64.rpm is tiny compared to others

![repository_screenshot](https://user-images.githubusercontent.com/46020480/104926407-69d2e380-59a0-11eb-9c81-f09c424ce949.png)

**Comment by rbhanda** [comment] 2021-01-18 19:16
Thanks for pointing this out @rtssrl 
I have re-uploaded this file and  I can download the file with 28.7 MB size

**Comment by rtssrl** [comment] 2021-01-19 08:21
OK, Thanks!
Now error seems to be with aspnetcore-runtime-3.1.11-x64.rpm

![error_aspnetcore_runtime](https://user-images.githubusercontent.com/46020480/105004589-7d2f8e80-5a34-11eb-80cd-e022b0014d48.png)

I've tried to removed packages, cleared zypper cache and re-run zypper in aspnetcore-runtime-3.1

aspnetcore-runtime-3.1.11-x64.rpm looks a bit smaller than aspnetcore-runtime-3.1.10-x64.rpm

**Comment by rbhanda** [comment] 2021-01-19 18:09
hi @rtssrl thanks a lot for reporting this. I am trying to get to the root cause of these files getting corrupted. I will keep this thread updated with the progress.

**Comment by rbhanda** [comment] 2021-01-19 19:09
The aspnetcore-runtime-3.1.11-x64.rpm corruption issue should be resolved now.

**Comment by beanotj** [comment] 2021-01-19 20:22
Don't know if this is related, but:
![image](https://user-images.githubusercontent.com/1418261/105088586-b6322800-5a61-11eb-8166-febd1e4831b2.png)

**Comment by rbhanda** [comment] 2021-01-19 21:44
Thanks a lot for reporting @beanotj . I have updated the file and it should get reflected on packages,microsoft.com in some time (~20 mins)

**Comment by beanotj** [comment] 2021-01-19 22:16
@rbhanda: Everything looks good, thanks!

**Comment by rtssrl** [comment] 2021-01-20 07:53
Hi @rbhanda, now zypper in aspnetcore-runtime-3.1 is OK, thanks!

**Comment by Chardrazle** [comment] 2021-01-20 20:17
We're still seeing issues trying to acquire a non-corrupted version of: _dotnet-sdk-3.1.405-x64.rpm_
The corrupted version appears to have spread around the Azure nodes.
Sometimes we've got lucky and acquired the correct package, but most times not.  Depends on which mirror we ultimately hit, I guess.

For example:
`wget http://csd-apt-weu-d-4.westeurope.cloudapp.azure.com/yumrepos/microsoft-rhel7.3-prod/dotnet-sdk-3.1.405-x64.rpm -O- | md5sum`

The corrupted version returns the checksum: 5eb9c4854342778b93d5ef55e83d265a
This file is 68MB and fails to install.

The correct version returns the checksum: 3d4b099cbc73b62e673c9c84a234f0a2

**Comment by Chardrazle** [comment] 2021-02-04 20:06
To follow up, we've not had any occurrences of the corrupt version for at least a week now.  So it looks like the correct one has propagated.

**Comment by danmoseley** [comment] 2021-02-15 07:54
Ok good. Closing. Thanks for the report!

**Closed by danmoseley** 2021-02-15 07:54 UTC
Labels: area-setup
