### ISSUE TITLE
How to share assembly memory between copies of the same App ?

### ISSUE THREAD

**Issue by SolidSoft-Lda** [dotnet/core#2463] opened 2019-03-15 14:39 UTC
How to implement a shared memory strategy for .NET Core assemblies like this:
https://visualstudiomagazine.com/articles/2017/11/29/improve-startup-time.aspx ?

**Comment by karelz** [comment] 2019-03-19 01:29
What kind of shared memory do you expect? (skimming the article didn't clarify it)

**Comment by SolidSoft-Lda** [comment] 2019-03-19 09:34
When one have several ASP.NET (.NET Framework) apps replicated and based on the same assemblies, each one consumes memory for load his assemblies, so there are repetition of this process.
.NET Framework provides at least 2 options:
1. Deploy this applications on the same application pool;
2. Starting .NET 4.5, use the tool aspnet_intern to create a symbolic link and the framework will reuse the loaded assemblies from memory on the several similar applications.

On the other hand on .NET Core we don't have a similar approach.
I couldn't find an option or tool to reuse the same loaded assemblies between different folders that are the same application assemblies (only with different configuration options and data bases but the same application).

Without reuse the memory, this all several applications will take several GB ram and impossible to use .NET Core on the server.

**Comment by Eilon** [comment] 2019-03-19 16:03
Dup of https://github.com/aspnet/AspNetCore/issues/8552. Please try not to open the same exact bug in 2 places because it creates duplicate work.

**Comment by karelz** [comment] 2019-03-19 17:43
Duplicate of https://github.com/aspnet/AspNetCore/issues/8552

**Closed by karelz** 2019-03-19 17:43 UTC
Labels: area-aspnet, needs more info
