### ISSUE TITLE
Cannot find compilation library location for package 'Microsoft.NETCore.App' 2.0.7

### ISSUE THREAD

**Issue by knopa** [dotnet/core#1474] opened 2018-04-24 07:57 UTC
After uprading Microsoft.NETCore.App to 2.0.7 got next issue

InvalidOperationException: Cannot find compilation library location for package 'Microsoft.NETCore.App'
Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List<string> assemblies)

When remove <RuntimeFrameworkVersion>2.0.7</RuntimeFrameworkVersion> it works ok.

**Comment by karelz** [comment] 2018-10-03 17:43
Looks like we missed following up on this issue :(. Sorry for that!
.NET Core 2.0 is out of support as of 10/1 - see https://github.com/dotnet/core/blob/master/microsoft-support.md#out-of-support-net-core-releases

If you hit the same issue on .NET Core 2.1 (or earlier versions), please let us know - e.g. file a new issue with steps to reproduce.
Closing this one.

**Closed by karelz** 2018-10-03 17:43 UTC
Labels: needs more info
