### ISSUE TITLE
Unistall the Server Bundle not uninstalling the .NET Core versions too

### ISSUE THREAD

**Issue by RomBrz** [dotnet/core#4047] opened 2019-12-27 00:13 UTC
# Issue Title

When i unistall the Server Bundle, the respective .NET Core versions of that Bundle does not uninstall too, and there's no option to make things easy

# General

I would like to suggest that, when you want to uninstall a Server Bundle .NET Core package, you could choose to remove the respective .NET Core versions too.

For example, if i download and install the Windows Server Bundle for .NET Core 3.1.0, it will install, with one "installer", the Server Bundle "app", plus the .NET Core 3.1.0 x86 and the .NET Core 3.1.0 x64.

Why when i want to uninstall the same Windows Server Bundle for .NET Core 3.1.0 i could not choose to remove both .NET Core 3.1.0 (x86 and x64) with the same "uninstall button"?

As i posted on the other issue, i cannot se why install it's so easy and the uninstall i have 3x more 
work.

Thanks for the attention

**Comment by dagood** [comment] 2020-01-06 21:38
There's some discussion about this already at https://github.com/dotnet/core/issues/3778, basically it has to do with how the installer is authored that the nested .NET Core Runtimes aren't uninstalled when you uninstall the Hosting Bundle. In the end, we plan to offer cleanup tooling to help with this situation.

**Comment by dagood** [comment] 2020-01-06 21:39
Duplicate of https://github.com/dotnet/core/issues/3778

**Closed by dagood** 2020-01-06 21:39 UTC
