### ISSUE TITLE
Don't know if this is related, but I'm having a similar issue with dotnet-sdk-3.1-3.1.405-1.x86_64:

### ISSUE THREAD

**Issue by Rezaclipper** [dotnet/core#5914] opened 2021-02-04 06:38 UTC
Don't know if this is related, but I'm having a similar issue with dotnet-sdk-3.1-3.1.405-1.x86_64:
![image](https://user-images.githubusercontent.com/1418261/105088586-b6322800-5a61-11eb-8166-febd1e4831b2.png)

Same file size issue:
![image](https://user-images.githubusercontent.com/1418261/105090255-d19e3280-5a63-11eb-9544-f0923f5db5a9.png)

_Originally posted by @beanotj in https://github.com/dotnet/core/issues/5856#issuecomment-763108525_

**Comment by dagood** [comment] 2021-02-04 16:19
beanotj reported this issue was resolved in https://github.com/dotnet/core/issues/5856#issuecomment-763176708.

@Rezaclipper, Maybe you meant to copy @Chardrazle's comment from later in https://github.com/dotnet/core/issues/5856? It's the last comment in the thread (no resolution) and has to do with the same package:

> We're still seeing issues trying to acquire a non-corrupted version of: _dotnet-sdk-3.1.405-x64.rpm_
> The corrupted version appears to have spread around the Azure nodes.
> Sometimes we've got lucky and acquired the correct package, but most times not. Depends on which mirror we ultimately hit, I guess.
> 
> For example:
> `wget http://csd-apt-weu-d-4.westeurope.cloudapp.azure.com/yumrepos/microsoft-rhel7.3-prod/dotnet-sdk-3.1.405-x64.rpm -O- | md5sum`
> 
> The corrupted version returns the checksum: 5eb9c4854342778b93d5ef55e83d265a
> This file is 68MB and fails to install.
> 
> The correct version returns the checksum: 3d4b099cbc73b62e673c9c84a234f0a2

I'm not able to reproduce the issue after 30 downloads from my machine, but you never know when mirrors are involved.

@rbhanda

**Comment by dagood** [comment] 2021-02-04 20:42
I'm going to close this now: it looks like that other issue has also been resolved (at least, it appears to have been working ok for a week): https://github.com/dotnet/core/issues/5856#issuecomment-773572078

@Rezaclipper, if you're running into a similar issue, please open a new issue with some more details and make sure to include the IP address and/or specific server and URL you're downloading from, so we can follow up. (Like `http://csd-apt-weu-d-4.westeurope.cloudapp.azure.com/yumrepos/microsoft-rhel7.3-prod/dotnet-sdk-3.1.405-x64.rpm`)

**Closed by dagood** 2021-02-04 20:42 UTC
