### ISSUE TITLE
dotnet run error

### ISSUE THREAD

**Issue by mazogbonna5** [dotnet/core#8859] opened 2023-10-25 18:28 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Hey all! I am new to coding and am using VScode. I ran into an error trying to establish the "Hello World!" introductory code. After the initial install I was able to get the code correctly, but then after using cd a couple times and trying to create new folders I have not been able to get a working code and even tried to get the Hello World code and still cannot. Every time I dotnet run I get errors;

"
/Users/mazogbonna/VSCODE Project1/ClassLibrary1/Class1.cs(5,21): error CS1514: { expected [/Users/mazogbonna/VSCODE Project1/ClassLibrary1/ClassLibrary1.csproj]
/Users/mazogbonna/VSCODE Project1/ClassLibrary1/Class1.cs(5,21): error CS1513: } expected [/Users/mazogbonna/VSCODE Project1/ClassLibrary1/ClassLibrary1.csproj]
"

The build failed. Fix the build errors and run again.

I have been trying to reverse text as an exercise and the code that inputted was this 

"
public class Class1 System.string Reverse(string input){
    if (string.IsNullOrEmpty(input)){
        return input;
    }
}

    StringBuilder reversed = new StringBuilder(input.Length);
    for (int i = input.Length - 1; i >= 0; i--){
        reversed.Append(input[i]);
    }
        {return reversed.ToString();}
    

    Console.WriteLine(Racecar);
"

Thanks in advance!

**Comment by michaelgsharp** [comment] 2023-10-25 22:30
The problem is that your code isn't formatted correct. Here is something to get you started.
```
public class Class1
{
    public static string Reverse(string input)
    {
        if (string.IsNullOrEmpty(input))
        {
            return input;
        }

        StringBuilder reversed = new StringBuilder(input.Length);
        for (int i = input.Length - 1; i >= 0; i--)
        {
            reversed.Append(input[i]);
        }
        return reversed.ToString();


    }
}
Console.WriteLine(Class1.Reverse("Racecar"));
```

I'm gonna close the issue, but good luck on learning to code!

**Closed by michaelgsharp** 2023-10-25 22:30 UTC
