### ISSUE TITLE
error

### ISSUE THREAD

**Issue by asharaful2020** [dotnet/core#9099] opened 2024-01-26 23:51 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment] 2024-01-30 19:25
Duplicate of #9100

**Closed** 2024-01-30 19:25 UTC
