### ISSUE TITLE
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install

### ISSUE THREAD

**Issue by FindingNemoRas** [dotnet/core#7272] opened 2022-03-11 23:30 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant. 

C:\>dotnet
'dotnet' is not recognized as an internal or external command,
operable program or batch file
[Microsoft_.NET_SDK_6.0.201_(arm64)_20220312012637 log file.txt](https://github.com/dotnet/core/files/8236444/Microsoft_.NET_SDK_6.0.201_.arm64._20220312012637.log.file.txt)
.

**Comment by FindingNemoRas** [comment] 2022-03-11 23:56
Good day, I am in desperate need of assistance. I am running about 25 miners at my facility and have a suspicion that someone is tampering with the hashrates. So i am doing a lot of reading etc to try and catch up with the ever changing world of technology and services etc. I have read something about the SSL and the port that is not secure so i am trying to get to the root of the problem but also trying to learn at the same time and not only downloading anything or anything i see on the internet as so many sites are extremely misleading. So i ended up reading this article to make sure my SSL connection is safe and what i need to have installed to get everything secured and running 100% I am new to the Crypto scene, well let say 2 years but have only been mining with machines set up by an ex-friend of mine who took a lot of money and machines from me without me even knowing, and running firmware on my machines at my own facility which i was not aware of. So i am trying to get all traces of firmnware and backdoor entry and whatever more there may be for me to learn what else i should run or check to ensure my network is secure aetc etc. Will it be possible for anyone to assist me to ensure i am setting up this .NET_SDK software correctly and if this is in fact the correct thing to do. I will forever be gratefull and thankful. I have read a lot about this community and have gained a lot of respect for what you are trying to achieve. With the exception of the odd ones out here and there. After all who am i to trust in these terrible times where people are misled and scammed around every corner. I dont know what else to do as i am ready to give up on this entire endevour. I am certain this is not what Nakamoto had in mind when developing the coin of the future that is supposed to be bringing wealth and knowledge and a better world for all. So sorry if Im saying things that is not related. I just need to start somewhere to try and fix the issues i have with my network and miners and the rest, trying to learn everyday, never anticipating for so much bad  things happening all at once. I suppose that is the route to knowledge bumping your head a million times or i might just be not educated enough, as i have come to see in this technologically advanced era, I know absolutely nothing, but am eager and hungry to learn everyday. Please can you assist me or direct me  to a possible solution. I thank you in advance from the bottom of my heart.

**Comment by mairaw** [comment] 2022-03-12 02:06
It's not clear what the issue is and not sure what .NET has to do with crypto mining.

Are you trying to learn how to code?

For now I'm closing the issue, unless we get more information from you.

**Closed by mairaw** 2022-03-12 02:06 UTC
