### ISSUE TITLE
Self contained exe publish does not create app.config

### ISSUE THREAD

**Issue by ganeshmj** [dotnet/core#3334] opened 2019-09-09 08:13 UTC
Not able to change application configuration file for WPF single file self contained exe.

**Comment by scalablecory** [comment] 2019-09-09 14:47
What are you trying to change and how is it not working?

**Comment by ganeshmj** [comment] 2019-09-09 14:59
Steps to Repro below:

1. Create WPF desktop application.
2. Add App.Config to application with some keys.
3. Publish the application using publish command with /p:PublishSingleFile=true and--self-contained
4. When single file exe is created at specified location, one cannot find corresponding app.config file which need to be changed if needed.

**Comment by ganeshmj** [comment] 2019-09-10 08:38
@scalablecory Please let me know if any other details are needed here.

**Comment by scalablecory** [comment] 2019-09-19 18:13
@livarcocc is this in your area?

**Comment by scalablecory** [comment] 2019-09-19 18:13
I'm not really sure if we even use app.config for WPF anymore.

**Comment by livarcocc** [comment] 2019-09-19 19:01
@jeffschwMSFT @nguerrera

**Comment by jeffschwMSFT** [comment] 2019-09-19 19:41
@ganeshmj how are you reading the config file?  In single file you would need to point to the extracted location in order to read from it.  Adding @swaroop-sridhar who can provide recommended way of finding the config file on disk.

**Comment by swaroop-sridhar** [comment] 2019-09-19 19:52
@ganeshmj In a single-file publish, all output files are bundled into the single file. So, in your case, the `app.config` file is also bundled into the app.

In this case, looks like you need to keep the `app.config` file separate and bundle everything else into a single-file (so that the configurations can be modified later). So, the file needs to be marked `<ExcludeFromSingleFile>true</ExcludeFromSingleFile>` as explained [here](https://github.com/dotnet/designs/blob/master/accepted/single-file/design.md#build-system-interface).

Duplicate of https://github.com/dotnet/core-setup/issues/7738

**Comment by scalablecory** [comment] 2019-09-26 18:33
Closing out as it seems we found a solution -- feel free to re-open if this doesn't solve your need.

**Closed by scalablecory** 2019-09-26 18:33 UTC

**Comment by selimdissem** [comment] 2020-08-28 23:54
I don't agree that this is a solution. 
To me, the whole idea of having a single file deployment with a config file would be to allow the deployment person/team to edit that config file for the environment it's deployed to. 
If the config file is saved into the exe and gets extracted as built, then the deployment person has to run the exe to extract to the temp directory and go edit the config file in the temp directory with the new environment values. Next update to the exe will overwrite those changes.
If the config file is excluded from the packaging of the exe and just sits next to the exe, editing it is pointless as it's not where the extracted code is going to try and read it (at least the way things work now).
Given that to get a self contained exe you need to specify the target, wouldn't it be possible to have an exe similar to a "classic" exe with all libraries static-linked into it?
