### ISSUE TITLE
Cannot download packages on Debian 9

### ISSUE THREAD

**Issue by dooferorg** [dotnet/core#3603] opened 2019-10-11 13:54 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/sdk-current
Operating System: Linux Debian 9 - x64

Got this:

```
Get:4 https://packages.microsoft.com/debian/9/prod stretch InRelease [4,023 B]
Err:4 https://packages.microsoft.com/debian/9/prod stretch InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
```

**Comment by dooferorg** [comment] 2019-10-11 13:57
Same as https://github.com/dotnet/core/issues/3598

**Comment by rynnova** [comment] 2019-10-11 14:16
Had the same issue with Windows Subsystem for Linux using Debian to install .NET Core on it.

I'll wait for 15 minutes and see if it resolves itself as per [this comment](https://github.com/Microsoft/mssql-docker/issues/409#issuecomment-452746606).

**Comment by rynnova** [comment] 2019-10-11 14:17
Had the same issue with Windows Subsystem for Linux using Debian to install .NET Core on it.

I'll wait for 15 minutes and see if it resolves itself as per [this comment](https://github.com/Microsoft/mssql-docker/issues/409#issuecomment-452746606) on https://github.com/Microsoft/mssql-docker/issues/409.

**Comment by dagood** [comment] 2019-10-11 18:24
Duplicate of https://github.com/dotnet/core/issues/3598

**Closed by dagood** 2019-10-11 18:24 UTC
