### ISSUE TITLE
Build Error VS2019 for Mac Preview 3 'The "ResolvePackageAssets" task failed unexpectedly.'

### ISSUE THREAD

**Issue by aaronmbos** [dotnet/core#2461] opened 2019-03-15 03:23 UTC
# Issue Build Error VS2019 for Mac Preview 3 'The "ResolvePackageAssets" task failed unexpectedly.'

# General
.NET Core SDK Version: 3.0.100-preview3-010431
IDE: Visual Studio 2019 for Mac (Preview 3)

After installing .NET Core 3.0 sdk I am no longer able to build my WebAPI project through Visual Studio.  It seems to build fine using "dotnet build" with CLI.  Prior to installing and updating the WebAPI project to ASP.NET Core 3.0 (Preview 3), I didn't have any issues building through Visual Studio.  If I can provide anymore helpful information, please just let me know. Below is the description of the error I am receiving.

/usr/local/share/dotnet/sdk/3.0.100-preview3-010431/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(5,5): Error MSB4018: The "ResolvePackageAssets" task failed unexpectedly.
System.TypeLoadException: Could not resolve type with token 0100003f from typeref (expected class 'NuGet.Packaging.Core.PackageDependency' in assembly 'NuGet.Packaging, Version=5.0.0.4, Culture=neutral, PublicKeyToken=31bf3856ad364e35')
  at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheWriter.GetPlatformPackageExclusions () [0x000d7] in <9524e6fbf1724027a475d15b01fab866>:0 
  at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheWriter..ctor (Microsoft.NET.Build.Tasks.ResolvePackageAssets task, System.IO.Stream stream) [0x0009b] in <9524e6fbf1724027a475d15b01fab866>:0 
  at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheReader.CreateReaderFromDisk (Microsoft.NET.Build.Tasks.ResolvePackageAssets task, System.Byte[] settingsHash) [0x0003a] in <9524e6fbf1724027a475d15b01fab866>:0 
  at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheReader..ctor (Microsoft.NET.Build.Tasks.ResolvePackageAssets task) [0x00015] in <9524e6fbf1724027a475d15b01fab866>:0 
  at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups () [0x00000] in <9524e6fbf1724027a475d15b01fab866>:0 
  at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore () [0x00018] in <9524e6fbf1724027a475d15b01fab866>:0 
  at Microsoft.NET.Build.Tasks.TaskBase.Execute () [0x00000] in <9524e6fbf1724027a475d15b01fab866>:0 
  at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:573 
  at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x00212] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:784

**Comment by leecow** [comment] 2019-03-15 17:56
Possibly related to https://github.com/dotnet/core/issues/2460?

**Comment by sergiotapia** [comment] 2019-03-17 01:00
Same

**Comment by ovicrisan** [comment] 2019-03-17 14:33
Same thing here, but also for VS 2017 targeting ASP.NET Core 2.2, not only for 3.0 preview. My previous projects don't work anymore in VS after installing .NET Core 3.0 preview. Very annoying.

**Comment by leecow** [comment] 2019-03-18 17:47
@ovicrisan - you need to use the VS 2019 Previews in order to work with .NET Core 3.0 Previews. 3.0 will not be supported from VS 2017.

**Comment by ovicrisan** [comment] 2019-03-19 03:02
I wasn't explicit enough: beside VS 2019 not working after installing .NET Core 3.0 preview 3, also my previous (side-by-side) VS 2017 targeting .NET Core 2.2 doesn't work any more.
Building and running it from CLI works fine, but not from VS. This is from VS 2017 w/ .NET Core 2.2 project:

![Screen Shot 2019-03-18 at 11 00 45 PM](https://user-images.githubusercontent.com/41134790/54577361-ddd18880-49d1-11e9-9a7f-84e1ae637bda.png)

**Comment by ovicrisan** [comment] 2019-03-22 04:22
I've just uninstalled .NET 3.0 preview3 as described here https://docs.microsoft.com/en-us/dotnet/core/versions/remove-runtime-sdk-versions?tabs=macos and everything works fine now:

$ dotnet --list-sdks
[...]
3.0.100-preview3-010431 /usr/local/share/dotnet/sdk
$ sudo rm -rf /usr/local/share/dotnet/sdk/3.0.100-preview3-010431

$ dotnet --list-runtimes
[...]
Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 /usr/local/share/dotnet/shared/Microsoft.AspNetCore.App
Microsoft.NETCore.App 3.0.0-preview3-27503-5 /usr/local/share/dotnet/shared/Microsoft.NETCore.App

$ sudo rm -rf /usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 
$ sudo rm -rf /usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/Microsoft.NETCore.App 3.0.0-preview3-27503-5

**Comment by karelz** [comment] 2019-03-30 18:41
Is there still a problem to resolve in VS 2019 for Mac? Or does the last reply mean there is a way to resolve it?
cc @mhutch

**Comment by JordanPritt** [comment] 2019-03-30 19:14
I'm experiencing the same issue. Unless you completely remove the core 3.0 preview SDK, all .NET core projects stop building on either version of VS for Mac.

**Comment by aaronmbos** [comment] 2019-03-31 00:01
I'm no longer receiving the same error that I started this issue with.  I'm now seeing the error below when I try to build.
Error: The version of the .NET Core SDK currently installed (/usr/local/share/dotnet/sdk/3.0.100-preview3-010431/Sdks) is not supported and continuing to use it may result in a broken tooling experience.

**Comment by karelz** [comment] 2019-03-31 00:05
@JordanPritt any idea why is your experience different from @aaronmbos ?

**Comment by mhutch** [comment] 2019-03-31 23:01
See https://github.com/dotnet/core/issues/2460#issuecomment-476713465

**Comment by JordanPritt** [comment] 2019-03-31 23:11
@karelz I’m not certain what you’re asking. Could you elaborate please? Thanks

**Comment by karelz** [comment] 2019-04-01 01:02
@JordanPritt it is unclear if there is anything left to address and if everyone is seeing the same problems.

**Comment by karelz** [comment] 2019-04-01 01:04
Duplicate of #2460

**Closed by karelz** 2019-04-01 01:04 UTC
