### ISSUE TITLE
Folder structure can prevent project from loading files

### ISSUE THREAD

**Issue by thrane** [dotnet/core#6992] opened 2021-12-01 20:43 UTC
### Description

If you create a project in a folder, that contains %20, and this folder is under a folder with a space file the project cannot compile.
Folder structure:
"Simple folder"
      | 
      |_Console%20App3 <- sln and project file lives here
                  

This works: "Simple folder\ConsoleApp3"
This also works: "SimpleFolder\Console%20App3
This does not work: "Simple folder\Console%20App3"

### Configuration

This is run on dotnet: 6.0.100
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000
running on x64

### Other information

This is the error message I get from the compiler:
`
C:\Program Files\dotnet\sdk\6.0.100\NuGet.targets(289,5): error MSB3202: The project file "C:\TempProjects\Simple folder\Console App3\ConsoleApp3.csproj" was not found. [C:\TempProjects\Simple folder\Console%20App3\ConsoleApp3.sln]

Build FAILED.

C:\Program Files\dotnet\sdk\6.0.100\NuGet.targets(289,5): error MSB3202: The project file "C:\TempProjects\Simple folder\Console App3\ConsoleApp3.csproj" was not found. [C:\TempProjects\Simple folder\Console%20App3\ConsoleApp3.sln]
    0 Warning(s)
    1 Error(s)
`

**Comment by thrane** [comment] 2021-12-01 20:44
I am not sure if this issue goes here, or if this is a Roslyn issue. Hope you can help me find the right place for this

**Comment by omajid** [comment] 2021-12-01 22:37
Sounds like a duplicate of https://github.com/dotnet/msbuild/issues/2178 ?

**Comment by scalablecory** [comment] 2021-12-02 00:15
Closing as duplicate of https://github.com/dotnet/msbuild/issues/2178

**Closed by scalablecory** 2021-12-02 00:15 UTC

**Comment by thrane** [comment] 2021-12-02 09:03
I agree this is a duplicate. 
I do not know if its just on my machine, but some times it actually works with %20 in the folder names.
