### ISSUE TITLE
"Portable" target runtime isn't portable

### ISSUE THREAD

**Issue by pieterphilippaerts** [dotnet/core#3554] opened 2019-10-05 19:14 UTC
I'm bulding a WPF application on .NET Core 3. When I publish the program to a folder, I can choose the target runtime (portable, win-x86, win-x64, linux-x64, ...). I assume that "portable" means I can run the binary on any architecture.

When I deploy the application as "portable", I cannot run it on x86, however. When I try to run the application, Windows tells me "This app can't run on your PC. To find a version for your PC, check with the software publisher.". If I explicitly change the target runtime to win-x86, the application does start correctly.

**Comment by vivmishra** [comment] 2019-10-07 18:28
@dsplaisted  @vatsan-madhavan

**Comment by dsplaisted** [comment] 2019-10-07 18:35
The .exe is a native shim for the app and is not portable.  You should be able to run the app portably with `dotnet MyApp.dll`.  However, I'm not sure that works entirely with WPF apps, as the app wouldn't be marked as a Windows app.

So I'm not sure the portable deploy option is supported for WPF apps.

@KathleenDollard @nguerrera Do you know if we have docs on this?

**Comment by KathleenDollard** [comment] 2019-10-09 00:53
x86 will run on both x86 and x64, so you can use that to run on all Windows platforms, and that will work well for most WPF and WinForms applications. 

When we added creation of executables we muddied the waters on what is portable. It is unfortunate/wrong that you have an option of "portable" that isn't really portable. Only the DLL can be portable, since execuatables are different on different platforms.

**Comment by vatsan-madhavan** [comment] 2019-10-09 02:03
As long as this is about wow64, this seems ok to me - modulo our desire to emphasize x64 on .NET Core (and deemphasize x86). We really want the ecosystem to move to x64 since it solves a lot of problems esp ones caused by limited address space in x86. 

/cc @richlander

<hr/>

I don’t think this is what is being proposed...but I’ll put this out anyway since I’m not quite sure. I can’t say without additional experimentation as to how the WPF x64 C++/CLI DLL’s will behave if they are attempted to be loaded in an x86 process. We didn’t intend for them to be used that way. We definitely didn’t intend for pure C++ x64 assemblies to be loaded on an x86 process.

**Comment by richlander** [comment] 2019-10-09 05:16
Only `win-x64` and `win-x86` should be offered. There is no portable model and certainly no `linux-x64`. Can you get that fixed, CLI team?

As Vatsan suggests, we recommend X64 as your first option.

**Comment by nguerrera** [comment] 2019-10-09 14:07
@vijayrkn’s team owns the dialog. I’m not sure if we have a way to limit the options without a coordinated change on their side...

**Comment by nguerrera** [comment] 2019-10-09 14:12
> I don’t think this is what is being proposed...

It’s not but maybe I’m misunderstanding. When you make your app x86, it will run on the x86 shared frameworks and runtime. You are either framework dependent and require the x86 runtime and shared frameworks to be installed, or self contained and carry the x86 runtimes and shared frameworks with you. Ditto for s/x86/x64/g. It’s fully one arch or the other. There’s no way to cross streams.

**Comment by nguerrera** [comment] 2019-10-09 14:15
For console/web apps, using dotnet.exe (getting to pick x86 or x64 dotnet) portableapp.dll is viable. For Windows apps, this might partially work, but it’s a dead end as you will get a console window and not get your own win32 manifest applied.

**Comment by richlander** [comment] 2019-10-09 17:56
Agree with @nguerrera.

This sounds like we need some doc updates and a blog post explaining all these bitness-related choices. They way things work is actually simple but not necessarily intuitive.

I think the guidance from @KathleenDollard on "x86 will run on both x86 and x64" is a good frame for self-contained, but more complicated for framework-dependent apps.

This is obviously coming back to the proposal that Nick and I worked on that we need to publish for public feedback for 5.0.

**Comment by vatsan-madhavan** [comment] 2019-10-09 17:58
> There’s no way to cross streams.

That's my understanding as well.

**Comment by carlossanlop** [comment] 2019-10-31 00:09
> _This sounds like we need some doc updates and a blog post explaining all these bitness-related choices._
@KathleenDollard  @richlander will one of you take care of this task, or who can take over it?
CC @mairaw

**Comment by carlossanlop** [comment] 2019-12-12 20:25
Ping @KathleenDollard @richlander who should take care of publishing doc/blog updates?

**Comment by scalablecory** [comment] 2020-09-09 22:26
@KathleenDollard have we made any docs updates for this? Can this be closed?

**Comment by mairaw** [comment] 2020-09-09 23:43
Pinging @tdykstra too

**Comment by tdykstra** [comment] 2020-09-10 17:58
I created an issue in the docs repo for the doc update.

**Comment by mairaw** [comment] 2021-08-11 23:20
Given we have a tracking doc work item, I'll close this issue. Please let me know if I missed anything else.

**Closed by mairaw** 2021-08-11 23:20 UTC
