### ISSUE TITLE
Cannot install dotnet no matter what I try.

### ISSUE THREAD

**Issue by sazar97** [dotnet/core#2836] opened 2019-06-05 19:49 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 19.04 - x64

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.5) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.5) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by sazar97** [comment] 2019-06-05 19:52
Note: I'm running Mint 19.1, and have tried all of the ubuntu packages, as well as Debian just to be sure. All ended up with this same error.

**Comment by dagood** [comment] 2019-06-07 20:43
Ubuntu 18.04's package seems like the one that will work for Mint 19.1. 18.04 has `libicu60`, which matches Mint 19.1's `libicu60`. Ubuntu 19.04 went on to `libicu63`.

(I used the `linuxmintd/mint19-amd64` Docker image to check what Mint has, not completely sure if that's correct.)

The install error you're getting unfortunately doesn't give enough info to do anything about this, you have to follow the package dependency chain down manually to see what the root cause is. Can you run these for more info?

```
# This install command will show exactly which dependency can't be met.
sudo apt-get install dotnet-runtime-deps-2.2
# Shows the repositories you have configured. Source: https://askubuntu.com/a/741948
grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
```

**Comment by sazar97** [comment] 2019-06-08 05:26
Hey thanks for your reply! Fortunately I was able to [fix it]https://stackoverflow.com/questions/54065894/cannot-install-net-core-2-2-on-ubuntu-18-04l) with this stack over flow answer and get  it installed! Thanks again!

**Comment by karelz** [comment] 2019-06-14 18:37
Seems to be addressed, closing.

**Closed by karelz** 2019-06-14 18:37 UTC
Labels: needs more info
