### ISSUE TITLE
Could not found packages-microsoft-prod.deb file.

### ISSUE THREAD

**Issue by jackie82422** [dotnet/core#6383] opened 2021-06-17 06:06 UTC
Problem encountered on https://docs.microsoft.com/zh-tw/dotnet/core/install/linux-ubuntu
Operating System: ubuntu 18.04

When I wget "https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb" get 404 not found.

and use apt-get install -y dotnet-sdk-3.1 get 404 not found too.

**Comment by jljordaan** [comment] 2021-06-17 06:41
I am experiencing the same issue for Ubuntu 16.04.

**Comment by maxoptimate** [comment] 2021-06-17 06:59
Same for [https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb]

**Comment by zpqrtbnk** [comment] 2021-06-17 07:18
Same, even though https://packages.microsoft.com/config/ubuntu/20.04/ does list the packages-microsoft-prod.deb file, one cannot retrieve it (404)

**Comment by tdesmet** [comment] 2021-06-17 07:37
same for https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb

**Comment by Mikhail1234** [comment] 2021-06-17 08:37
The same thing here
https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb

**Comment by Youssef1313** [comment] 2021-06-17 08:50
This is being reported in dotnet/docs as well:

https://github.com/dotnet/docs/issues/24718
https://github.com/dotnet/docs/issues/24717
https://github.com/dotnet/docs/issues/24716
https://github.com/dotnet/docs/issues/24713
https://github.com/dotnet/docs/issues/24711

**Comment by dazfuller** [comment] 2021-06-17 09:31
Having the same issues outside of dotnet. Trying to install the SQL ODBC driver on a Databricks cluster (running Ubuntu 18.04)

https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/m/msodbcsql17/msodbcsql17_17.7.2.1-1_amd64.deb

**Comment by lastseenjustnow** [comment] 2021-06-17 09:34
Same:

Step 20/25 : RUN ACCEPT_EULA=Y apt-get -y install msodbcsql17 --fix-missing
 ---> Running in ea24424f2562
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libodbc1 multiarch-support odbcinst odbcinst1debian2 unixodbc unixodbc-dev
Suggested packages:
  unixodbc-bin
The following NEW packages will be installed:
  msodbcsql17 multiarch-support unixodbc
The following packages will be upgraded:
  libodbc1 odbcinst odbcinst1debian2 unixodbc-dev
4 upgraded, 3 newly installed, 0 to remove and 37 not upgraded.
Need to get 1,721 kB of archives.
After this operation, 253 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 multiarch-support amd64 2.28-10 [215 kB]
Err:2 https://packages.microsoft.com/debian/10/prod buster/main amd64 odbcinst amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]
Err:3 https://packages.microsoft.com/debian/10/prod buster/main amd64 unixodbc-dev amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]
Err:4 https://packages.microsoft.com/debian/10/prod buster/main amd64 odbcinst1debian2 amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]
Err:5 https://packages.microsoft.com/debian/10/prod buster/main amd64 libodbc1 amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]
Err:6 https://packages.microsoft.com/debian/10/prod buster/main amd64 unixodbc amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]
Err:7 https://packages.microsoft.com/debian/10/prod buster/main amd64 msodbcsql17 amd64 17.7.2.1-1
  404  Not Found [IP: 104.214.230.139 443]

**Comment by daguito81** [comment] 2021-06-17 09:37
Same problem here. If you look at the link (for ubuntu in my case but I think it's the same) It's looking at distro/version/prod/pool...
but going to their repository https://packages.microsoft.com/ubuntu/18.04/prod/
There is no "pool" directory anymore. This happens in all ubuntu versions, debian as well.

**Comment by LennyBEL** [comment] 2021-06-17 09:38
You can temporarily use Snap to install dotnet, it seems to still work:
https://docs.microsoft.com/en-us/dotnet/core/install/linux-snap

**Comment by zpqrtbnk** [comment] 2021-06-17 09:40
The funny thing is, https://packages.microsoft.com/config/ubuntu/20.04/ *does* list the file, along other files which you *can* retrieve - only the `.deb` file cannot. Has someone messed with the configuration and the `.deb` extension is not recognized anymore?

**Comment by daguito81** [comment] 2021-06-17 10:00
Yes, when you update the repo it does include msodbcsql17 for exampe. The error  doesn't show "can't find a package by that name" but it actually tries to download it and get a 404 error. 
![image](https://user-images.githubusercontent.com/14969458/122373925-318cfc80-cf62-11eb-9804-bd2fada74c6d.png)

It's like someone simply deleted the folder but kept the index the same

**Comment by daguito81** [comment] 2021-06-17 10:03
Different package but same repository
![image](https://user-images.githubusercontent.com/14969458/122375935-f8ee2280-cf63-11eb-96e2-b6c0487e9790.png)
Seems like in some parts of the world the repository is back to how it was. Europe still seems to be affected

**Comment by dazfuller** [comment] 2021-06-17 10:07
I just connected over VPN to an endpoint in India and this is what I'm seeing now for the packages I'm looking for

![image](https://user-images.githubusercontent.com/204848/122376568-2c2cb380-cf5c-11eb-91df-27f95c17440c.png)

**Comment by svick** [comment] 2021-06-17 11:34
This is a duplicate of https://github.com/dotnet/core/issues/6381, which contains more information about the current status.

**Comment by zpqrtbnk** [comment] 2021-06-17 11:34
this is tracked in #6381 - this issue is now a duplicate

**Comment by zpqrtbnk** [comment] 2021-06-17 11:34
sorry @svick we collided

**Comment by Youssef1313** [comment] 2021-06-17 14:21
This should have been fixed now per https://github.com/dotnet/core/issues/6381#issuecomment-863274298

**Comment by michaelgsharp** [comment] 2021-06-17 17:19
This issue is being tracked with #6381. It should be fixed now (as Youssef1313 said), but some are still seeing slowdowns since everyone is trying to download it. Closing this issue.

**Closed by michaelgsharp** 2021-06-17 17:19 UTC

**Comment by pyhoff** [comment] 2024-09-04 21:15
Still this issue with debian 12? come on

**Comment by krwq** [comment] 2024-09-05 08:16
@pyhoff if you're seeing this issue please create a new issue
