### ISSUE TITLE
privacy error

### ISSUE THREAD

**Issue by martha-sulamo** [dotnet/core#8898] opened 2023-11-11 18:57 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/install.
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

"Your connection isn't private"

**Comment by mairaw** [comment] 2023-11-11 20:21
Duplicate of #8897

**Closed by mairaw** 2023-11-11 20:21 UTC
