### ISSUE TITLE
Exited with error code 1

### ISSUE THREAD

**Issue by Elson-KaiDong** [dotnet/core#6107] opened 2021-03-31 01:23 UTC
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/run
Operating System: windows
watch : Exited with error code 1
watch : waiting for a file to change before restarting dotnet . . .

**Comment by Jozkee** [comment] 2021-04-05 21:34
Thanks for reporting, can you provide more details about what you are specifically doing that triggers this error? Do you hit it consistently?

cc @wli3 @dsplaisted

**Comment by mairaw** [comment] 2021-04-05 21:37
Tagging @danroth27  as well

**Comment by danroth27** [comment] 2021-04-05 21:44
> watch : Exited with error code 1

Adding @pranavkm as well.

**Comment by mairaw** [comment] 2021-04-06 21:00
Just closed #6124 as a duplicate of this one, even though that was on a Linux machine.

**Closed** 2021-06-10 20:24 UTC
Labels: area-tutorials, needs-more-info
