### ISSUE TITLE
This site can’t provide a secure connection

### ISSUE THREAD

**Issue by rajsharma-dev** [dotnet/core#4690] opened 2020-05-17 05:31 UTC
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Getting this error when running myWebApp at https://localhost:5000/
This site can’t provide a secure connection
localhost sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

**Comment by mairaw** [comment] 2020-07-08 02:22
The tutorial indicates that you have to navigate to http://localhost:5000 without an s since we haven't enabled https when we created the site.

Duplicate of https://github.com/dotnet/aspnetcore/issues/20404

**Closed by mairaw** 2020-07-08 02:22 UTC
