### ISSUE TITLE
my terminal is not recognixing dotnet command after installation of .net sdk

### ISSUE THREAD

**Issue by kumarsh8483** [dotnet/core#3936] opened 2019-11-30 20:25 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by dagood** [comment] 2019-12-02 15:31
This is probably a duplicate of https://github.com/dotnet/core/issues/3831. See https://github.com/dotnet/core-setup/issues/6521 for more info. I'm closing this one as a duplicate, but let me know if that doesn't work for you and we can reopen (or you can start a new issue with more info).

**Comment by dagood** [comment] 2019-12-02 15:31
Duplicate of https://github.com/dotnet/core/issues/3831

**Closed by dagood** 2019-12-02 15:31 UTC
