### ISSUE TITLE
BUG view Edit 

### ISSUE THREAD

**Issue by renatoprogramer** [dotnet/core#1736] opened 2018-06-28 14:07 UTC
When I edit my view of an error this started with an automatic update already upgraded to the 2.1.1 Ai of the error of Pomelo, the incredible that started out of nowhere this is pitiful a minimal upgrade screwing with everything this way is better to program in PHP even.

![image](https://user-images.githubusercontent.com/15394508/42039315-78ad8a36-7ac3-11e8-9d01-3ff7464491e2.png)

**Comment by svick** [comment] 2018-06-28 14:12
This seems to be a duplicate of https://github.com/aspnet/Mvc/issues/7969.

**Comment by Petermarcu** [comment] 2018-07-09 21:12
This was addressed here: https://github.com/aspnet/Mvc/issues/7969

**Closed by Petermarcu** 2018-07-09 21:12 UTC
