### ISSUE TITLE
can't run dotnet command

### ISSUE THREAD

**Issue by EngKhaled91** [dotnet/core#1963] opened 2018-09-26 11:19 UTC
Hello Everybody:
I've installed dotnet core sdk 2.1 but when I try to run (dotnet --version) I get a dialog box says
"The procedure entry point-p-wargv could not be located in the dynamic link  library c:\Program Files\dotnet\dotnet.exe"
would any one help me with this 
thanks alot

**Comment by karelz** [comment] 2018-10-02 22:44
@EngKhaled91 how did you install .NET Core SDK? (which installer did you run?)
Which OS do you use?
Did you try the same steps on another machine (e.g. a VM)?

**Comment by EngKhaled91** [comment] 2018-10-03 03:50
windows 8.1 and version of SDK is 2.1

**Comment by karelz** [comment] 2018-10-13 16:55
@EngKhaled91 can you please answer also the remaining questions?
*  how did you install .NET Core SDK? (which installer did you run?)
* Did you try the same steps on another machine (e.g. a VM)?

The issue is currently not actionable.

**Comment by EngKhaled91** [comment] 2018-10-13 17:09
I got the installer from this link:
https://www.microsoft.com/net/download
on another VM or Machine it works 
but I want to know about the reason for this error

**Comment by karelz** [comment] 2018-10-22 17:19
@EngKhaled91 this looks like OS loader error. Unless you can reproduce it on another (Win8.1) machine, I think it is likely caused by bad installation (either OS or .NET Core itself).
You can either reinstall/repair .NET Core SDK and OS, or you can try to debug the problem in debugger on your machine to see what goes wrong (start with getting call stack for the error). Note that debugging OS loader failures is usually fairly involved low-level debugging.

Given that this is the only report (search of the error does not reveal any other hits), I will close it as external until there are either more hits, or something actionable for .NET Core. Thanks!

**Closed by karelz** 2018-10-22 17:19 UTC
Labels: needs more info
