### ISSUE TITLE
Unable to locate package aspnetcore-runtime-3.0

### ISSUE THREAD

**Issue by Jebarson** [dotnet/core#3609] opened 2019-10-12 21:21 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian10/runtime-current
Operating System: Linux Debian 10 - x64

Running Raspian on Rp4 and unable to install aspnet-core or dotnet core

**Comment by scalablecory** [comment] 2019-10-14 17:17
I'm not sure if we distribute arm packages; @krwq can you give some help here?

**Comment by dagood** [comment] 2019-10-14 17:24
We don't, @Jebarson, you need to follow this link on the download page:

> Not running x64? You'll need to [download the .NET Core binaries](https://dotnet.microsoft.com/download/dotnet-core/3.0#runtime-3.0.0) instead.

**Comment by dagood** [comment] 2019-10-14 17:26
Duplicate of https://github.com/dotnet/core/issues/2422

**Closed by dagood** 2019-10-14 17:26 UTC
