### ISSUE TITLE
.NET Core SDK for Windows Installation Path Problem

### ISSUE THREAD

**Issue by myhlivecom** [dotnet/core#192] opened 2016-07-01 01:02 UTC
The .NET Core SDK for Windows installer
[https://go.microsoft.com/fwlink/?LinkID=809122](url)
has an option to set installation path other than C:\Program Files\dotnet.
Unfortunately, the installer always installs it to C:\Program Files\dotnet even if you change the installation path option.
Please fix it if it is a bug.

**Comment by Petermarcu** [comment] 2016-07-01 06:06
@piotrpMSFT , Can you take a look at this and get this issue files in the repo where the bug exists? core-setup or cli?

**Comment by piotrpMSFT** [comment] 2016-07-01 21:32
This is a known UI issue. The installer should not be exposing this option. The installation path for the installers on Windows is fixed, like on other OSs.

**Comment by piotrpMSFT** [comment] 2016-07-01 21:34
Duplicate of https://github.com/dotnet/cli/issues/3568

**Closed by piotrpMSFT** 2016-07-01 21:34 UTC
