### ISSUE TITLE
„dotnet-sdk-3.1.100-osx-x64.pkg“ kann nicht geöffnet werden, da Apple darin nicht nach Schadsoftware suchen kann.

### ISSUE THREAD

**Issue by tnerger2020** [dotnet/core#4054] opened 2019-12-28 10:10 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by carlossanlop** [comment] 2020-09-09 22:38
Translation:
> cannot be opened because Apple cannot search for malware in it

Dupe of: https://github.com/dotnet/core/issues/3943

**Closed by carlossanlop** 2020-09-09 22:38 UTC
