### ISSUE TITLE
access denied in windows 

### ISSUE THREAD

**Issue by Lynne30** [dotnet/core#8524] opened 2023-06-05 15:44 UTC
Problem encountered on https://dotnet.microsoft.com/en-us/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by steveharter** [comment] 2023-06-05 16:11
Closing as duplicate of https://github.com/dotnet/core/issues/8525 wheich was also opened by @Lynne30

**Closed by steveharter** 2023-06-05 16:11 UTC
Labels: area-setup, untriaged
