### ISSUE TITLE
Failed to fetch https://packages.microsoft.com/repos/edge/dists/stable/main/binary-amd64/Packages.gz  File has unexpected size

### ISSUE THREAD

**Issue by Titas-OpenTrack** [dotnet/core#9284] opened 2024-04-25 09:07 UTC
**Description**

Just like in https://github.com/dotnet/core/issues/9276 and https://github.com/orgs/community/discussions/121059, we have been experiencing this issue randomly since yesterday (24 April, 2024).

> E: Failed to fetch https://packages.microsoft.com/repos/edge/dists/stable/main/binary-amd64/Packages.gz  File has unexpected size (8078 != 8155). Mirror sync in progress? [IP: 13.107.246.69 443]
>    Hashes of expected file:
>     - Filesize:8155 [weak]
>     - SHA512:c2a3e7edbc44eac190f8df014238d836992b1300d52ac5eed89dc9cc571c1e35623a281e9544649418ec167a854f707a407f3c252076282fe3ba61049f835cd3
>     - SHA256:41e205cfa4dc4dce04cc0ed0cae41245955ba6f49fcd331d55a712e97c4a8bf8
>    Release file created at: Thu, 18 Apr 2024 18:02:47 +0000
> E: Some index files failed to download. They have been ignored, or old ones used instead.

**Regression?**

Seems like faulty Mirror links.

**Comment by ManickaP** [comment] 2024-04-29 07:10
This seems like dupe of https://github.com/microsoft/linux-package-repositories/issues/130
It should be resolved now, I'll close this. 
If you still experience the issue, feel free to let us know.

**Closed by ManickaP** 2024-04-29 07:10 UTC

**Comment by Titas-OpenTrack** [comment] 2024-05-24 08:54
@ManickaP It has been working fine for a while, but the error has returned in the past few days:

> W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Error reading from server - read (104: Connection reset by peer) [IP: 151.101.50.xxx xx]
> --
> 75 | E: Failed to fetch http://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages  Connection timed out [IP: 151.101.50.xxx xx]

**Comment by ManickaP** [comment] 2024-05-24 16:00
That's Debian server, not Microsoft though.
