### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by muminfarooq190** [dotnet/core#6581] opened 2021-08-14 06:36 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment] 2021-08-14 19:32
Duplicate of #6582

**Closed by mairaw** 2021-08-14 19:32 UTC
