### ISSUE TITLE
ASP.NET Core 2.2: Framework-dependent executable (FDE) refuses to work on Linux

### ISSUE THREAD

**Issue by GTANAdam** [dotnet/core#2182] opened 2018-12-23 22:39 UTC
# ASP.NET Core 2.2: Framework-dependent executable (FDE) issue on Linux Ubuntu 18.04

Deployed [FDE](https://docs.microsoft.com/en-us/dotnet/core/deploying/) builds simply refuse to work on Linux, even with all the dependencies being installed. 

the feature itself is a pretty good mix of SCD and FDD, gaining performance thanks to platform-specific build crossgen-ing as well as reduced package size footprint which is great when combined with docker.

This, afaik, mainly affects Linux (Ubuntu 18.04) since it works perfectly fine on Windows with the dotnet-hosting 2.2.0 installed.

### Exception thrown

> $ ./myapp
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.2.0' was not found.
>  - Check application dependencies and target a framework version installed at:
      (../myapp)/bin/Release/netcoreapp2.2/publish/
>  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
>  - The .NET Core framework and SDK can be installed from:

### dotnet --info

>.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7
>
>Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
> OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.101/
>
>Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed
>
>.NET Core SDKs installed:
  2.2.101 [/usr/share/dotnet/sdk]
>
>.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
>  Microsoft.NETCore.App 2.2.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**!! Notice the installed runtimes.**

### Steps to reproduce
1. Make sure to have **aspnetcore-runtime-2.2** installed along with the rest of the required .NET Core 2.2 dependencies.

2. Publish any **ASP.NET Core 2.2** project, targeting **linux-x64** with the Deployment mode set to **Framework-dependent**. (https://i.imgur.com/e9EFtBl.png)

3. Launch the published executable without the "dotnet" utility.

**Comment by karelz** [comment] 2019-01-08 04:30
@Eilon is it something you / your team knows about? Or is it more general?

**Comment by natemcmaster** [comment] 2019-01-08 17:38
This looks like https://github.com/dotnet/sdk/issues/2722 which the SDK team closed as 'wontfix'.

**Comment by karelz** [comment] 2019-01-08 21:24
Duplicate of https://github.com/dotnet/sdk/issues/2722

**Closed by karelz** 2019-01-08 21:24 UTC
Labels: area-aspnet
