### ISSUE TITLE
dotnet installation need more documentation 

### ISSUE THREAD

**Issue by CsBigDataHub** [dotnet/core#3580] opened 2019-10-09 12:36 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

I have installed dotnet in macos with the installer. dotnet installed fine but I got "**'dotnet' is not recognized as an internal or external command**" error even after opening a new terminal instance. This is because I needed to add `DOTNET_HOME=/usr/local/share/dotnet` in my path variable in my .zshrc or .bashrc or .profile file. 

fix-
It would be great if that information is provided in the installation page if the people see the error above.

**Comment by dagood** [comment] 2019-10-09 17:51
`'dotnet' is not recognized as an internal or external command` sounds like a `PATH` issue, I'm not sure how `DOTNET_HOME` would be involved. Do you know why setting `DOTNET_HOME` helped your shell find `dotnet`?

I'm wondering if you actually ran into this other known issue, where if your profile sets `PATH` (rather than appending/prepending to it) then the macOS utility `path_helper` stops working: https://github.com/dotnet/core-setup/issues/6521.

**Comment by scalablecory** [comment] 2019-10-14 17:49
Closing as duplicate of https://github.com/dotnet/core-setup/issues/6521.

Please feel free to re-open if you're still having this problem and have more detail.

**Closed by scalablecory** 2019-10-14 17:49 UTC
Labels: area-setup, needs more info
