### ISSUE TITLE
Unable to locate the package dotnet-sdk-2.2

### ISSUE THREAD

**Issue by chaos1908** [dotnet/core#2896] opened 2019-06-18 07:04 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Debian 9 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by dagood** [comment] 2019-06-20 14:20
Duplicate of #2897

**Closed by dagood** 2019-06-20 14:20 UTC
