### ISSUE TITLE
Unable to debug

### ISSUE THREAD

**Issue by Eilon** [dotnet/core#2058] opened 2018-11-14 18:25 UTC
_From @h0730303779 on Tuesday, 13 November 2018 03:03:24_

### Describe the bug
Unable Debug ConsoleApp    String exceeds 20W  on  dotnetcore  !!!

### To Reproduce
1. Net Core 2.1 
2. Run this code 
            var  s = '**'; //Please enter the 20W string
            Console.WriteLine(s.Length);
            Console.ReadLine();
3. 
4. See images
5.No problem for Same code  on framework  

why?

### Expected behavior
debug

### Screenshots
on netcore 2.1
![image](https://user-images.githubusercontent.com/16299810/48388375-1582a800-e734-11e8-94fb-e829cce27563.png)

on  framework  4.5
![image](https://user-images.githubusercontent.com/16299810/48388249-a1e09b00-e733-11e8-8aa4-601d1b0a50a9.png)

### Additional context

_Copied from original issue: aspnet/AspNetCore#4010_

**Comment by karelz** [comment] 2018-11-14 18:30
@h0730303779 what is "20W" string? Can you please post full compilable repro?
What does it mean it is unable to debug? (I don't understand the non-English text in your screenshot)

**Comment by Eilon** [comment] 2018-11-14 22:37
Here's what I got:

> 0 references 10 authors, o items change 10 exceptions static void Main(string [] args)e::strings "organize\\: 7a579db2-f4e3-489c-aed9-d39cf? Console. WriteLine (s. Length); currently not The executable code of the target code type of the debugger that has no associated debuggers may include: conditional compilation, compiler optimization, or the current debugger code type does not support the target architecture of this line ConsoleAppl.Program.Main 0 references 10 authors, o items change 10 exceptions, static void Main(string [] args)

Though I don't know what 20W is either.

**Comment by h0730303779** [comment] 2018-11-15 02:03
> @h0730303779 what is "20W" string? Can you please post full compilable repro?
> What does it mean it is unable to debug? (I don't understand the non-English text in your screenshot)

sorry   .  200,000 string length

**Comment by h0730303779** [comment] 2018-11-15 02:15
> 这是我得到的：
> 
> > 0个引用10个作者，o个项更改10个异常static void Main（string [] args）e :: strings“organize \：7a579db2-f4e3-489c-aed9-d39cf？Console.WriteLine（s。Length）;当前不是可执行文件没有关联调试器的调试器的目标代码类型的代码可能包括：条件编译，编译器优化或当前调试器代码类型不支持此行的目标体系结构ConsoleAppl.Program.Main 0引用10个作者，o项更改10个异常，static void Main（string [] args）
> 
> 虽然我不知道20W是什么。

hello   variable  's'  Arbitrary length string 200,000 Above

**Comment by h0730303779** [comment] 2018-11-15 02:15
> Here's what I got:
> 
> > 0 references 10 authors, o items change 10 exceptions static void Main(string [] args)e::strings "organize\: 7a579db2-f4e3-489c-aed9-d39cf? Console. WriteLine (s. Length); currently not The executable code of the target code type of the debugger that has no associated debuggers may include: conditional compilation, compiler optimization, or the current debugger code type does not support the target architecture of this line ConsoleAppl.Program.Main 0 references 10 authors, o items change 10 exceptions, static void Main(string [] args)
> 


hello   variable  's'  Arbitrary length string 200,000 Above

**Comment by h0730303779** [comment] 2018-11-15 02:39
> @h0730303779 what is "20W" string? Can you please post full compilable repro?
> What does it mean it is unable to debug? (I don't understand the non-English text in your screenshot)

![image](https://user-images.githubusercontent.com/16299810/48526448-a6878980-e8c2-11e8-84b3-992482c6ee03.png)

sorry , My English is poor

**Comment by 0xd4d** [comment] 2018-11-15 12:03
This is a known Roslyn bug: https://github.com/dotnet/roslyn/issues/20118

A workaround is to split the string into many smaller strings, eg.:

```C#
string s = "abc................." +
"def.................." +
...etc...
"zzz.............";
```

**Comment by h0730303779** [comment] 2018-11-15 12:13
> This is a known Roslyn bug: [dotnet/roslyn#20118](https://github.com/dotnet/roslyn/issues/20118)
> 
> A workaround is to split the string into many smaller strings, eg.:
> 
> ```cs
> string s = "abc................." +
> "def.................." +
> ...etc...
> "zzz.............";
> ```


thank you for your reply
I will put it in the database in the production environment.

**Comment by karelz** [comment] 2018-11-16 19:59
Duplicate of https://github.com/dotnet/roslyn/issues/20118

**Closed by karelz** 2018-11-16 19:59 UTC
