### ISSUE TITLE
Generating DLLs in different folders breaks VS Enterprise Architecture

### ISSUE THREAD

**Issue by gabrielcs** [dotnet/core#186] opened 2016-06-30 04:16 UTC
It appears the layer diagram feature under the Architecture menu on Visual Studio Enterprise expects all DLLs to be available under the `bin/` folder of each project after compilation. However, with .NET Core they seem to be generated under other folders, for example `bin/Debug/netcoreapp1.0/` or `bin/Debug/netstandard1.6/`. See [screenshot]
(https://www.dropbox.com/s/f14kcz8ty3nax3m/dll-error.png?dl=0).

As a side note, the layer diagram feature also seems to break when setting a different `buildOptions.outputName` in `project.json`.

I am using Visual Studio 2015 update 3.

**Comment by blackdwarf** [comment] 2016-07-21 03:57
@gabrielcs the behavior is by design for the .net core tooling. However, seems like there are some problems here. Can you please move this issue to https://github.com/aspnet/tooling/issues and we will triage it appropriately from there? I will close this one. Thanks!

**Closed by blackdwarf** 2016-07-21 03:57 UTC
