### ISSUE TITLE
999

### ISSUE THREAD

**Issue by qnetvova** [dotnet/core#6364] opened 2021-06-13 22:50 UTC
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment] 2021-06-14 20:15
Duplicate of #6365

**Closed by mairaw** 2021-06-14 20:15 UTC
