### ISSUE TITLE
Enexpected AccessViolationException when reading from array.

### ISSUE THREAD

**Issue by ddobric** [dotnet/core#2322] opened 2019-02-16 18:35 UTC
I have an array of size 4096, 250000 = 1024000000 = 0x3d090000.
Unfortunately accessing of row with index 2147 fails with  **AccessViolationException**.

 ```csharp
           var x = new int[4096, 250000];
            for (int i = 0; i < 4096; i++)
            {
                var y = x.GetRow(i);
            }
```

```csharp
        public static T[] GetRow<T>(this T[,] array, int row)
        {
            if (array == null)
                throw new ArgumentNullException("array");

            int cols = array.GetUpperBound(1) + 1;
            T[] result = new T[cols];

            for (int i = 0; i < cols; i++)
            {
                result[i] = array[row, i];       // <<< = ERROR
            }
            return result;
        }
```

When executing the code above , following exception is thrown:
> An unhandled exception of type 'System.AccessViolationException' occurred in NeoCortexApi.dll
> Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

![image](https://user-images.githubusercontent.com/1756871/52903619-6f59a900-3220-11e9-841e-3bb74f3ac95d.png)

![image](https://user-images.githubusercontent.com/1756871/52903701-b8f6c380-3221-11e9-9893-f8f73c30e06b.png)

**Comment by karelz** [comment] 2019-02-17 08:57
Duplicate of #2094

**Closed by karelz** 2019-02-17 08:57 UTC
