### ISSUE TITLE
Create Docker image

### ISSUE THREAD

**Issue by alinedev** [dotnet/core#7592] opened 2022-07-11 21:11 UTC
I tried to create a docker image  after building the Dockerfile and run this coomand: docker build -t mymicroservice .
this is the message that I got and I have no idea how to fix it. If someone could help that would be great.
Thank you
error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=mymicroservice&target=&ulimits=null&version=1": open //./pipe/docker_engine: The system cannot find the file specanything else that is relevant.

**Comment by akoken** [comment] 2022-07-12 21:26
Duplicate of #7570

**Comment by ViktorHofer** [comment] 2022-07-20 07:55
Closing as dup of https://github.com/dotnet/core/issues/7570

**Closed by ViktorHofer** 2022-07-20 07:55 UTC
