### ISSUE TITLE
Updating 3.0.0 to 3.0.1 on CentOS removes AspnetCore Runtime

### ISSUE THREAD

**Issue by thepaleone** [dotnet/core#3913] opened 2019-11-26 16:34 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/runtime-aspnetcore-3.0.1
Operating System: Linux - CentOS 7 - x64

Recently tried to update from 3.0.0 to 3.0.1. After doing so aspnet apps fail to start and it appears that the update removes the aspnetcore runtime files.

Pre update
```
~ # dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
Update process
```
yum update -y
--> Running transaction check
---> Package aspnetcore-runtime-3.0.x86_64 0:3.0.0-1 will be updated
---> Package aspnetcore-runtime-3.0.x86_64 0:3.0.1-1 will be an update
---> Package aspnetcore-targeting-pack-3.0.x86_64 0:3.0.0-1 will be updated
---> Package aspnetcore-targeting-pack-3.0.x86_64 0:3.0.1-1 will be an update
---> Package dotnet-apphost-pack-3.0.x86_64 0:3.0.0-1 will be updated
---> Package dotnet-apphost-pack-3.0.x86_64 0:3.0.1-1 will be an update
---> Package dotnet-host.x86_64 0:3.0.0-1 will be updated
---> Package dotnet-host.x86_64 0:3.0.1-1 will be an update
---> Package dotnet-hostfxr-3.0.x86_64 0:3.0.0-1 will be updated
---> Package dotnet-hostfxr-3.0.x86_64 0:3.0.1-1 will be an update
---> Package dotnet-runtime-3.0.x86_64 0:3.0.0-1 will be updated
---> Package dotnet-runtime-3.0.x86_64 0:3.0.1-1 will be an update
---> Package dotnet-runtime-deps-3.0.x86_64 0:3.0.0-1 will be updated
---> Package dotnet-runtime-deps-3.0.x86_64 0:3.0.1-1 will be an update
---> Package dotnet-sdk-3.0.x86_64 0:3.0.100-1 will be updated
---> Package dotnet-sdk-3.0.x86_64 0:3.0.101-1 will be an update
---> Package dotnet-targeting-pack-3.0.x86_64 0:3.0.0-1 will be updated
---> Package dotnet-targeting-pack-3.0.x86_64 0:3.0.1-1 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

======================================================================================================================================================================================================================================
 Package                                                            Arch                                        Version                                        Repository                                                        Size
======================================================================================================================================================================================================================================
Updating:
 aspnetcore-runtime-3.0                                             x86_64                                      3.0.1-1                                        packages-microsoft-com-prod                                      7.5 M
 aspnetcore-targeting-pack-3.0                                      x86_64                                      3.0.1-1                                        packages-microsoft-com-prod                                      1.4 M
 dotnet-apphost-pack-3.0                                            x86_64                                      3.0.1-1                                        packages-microsoft-com-prod                                       66 k
 dotnet-host                                                        x86_64                                      3.0.1-1                                        packages-microsoft-com-prod                                       39 k
 dotnet-hostfxr-3.0                                                 x86_64                                      3.0.1-1                                        packages-microsoft-com-prod                                      147 k
 dotnet-runtime-3.0                                                 x86_64                                      3.0.1-1                                        packages-microsoft-com-prod                                       29 M
 dotnet-runtime-deps-3.0                                            x86_64                                      3.0.1-1                                        packages-microsoft-com-prod                                      2.8 k
 dotnet-sdk-3.0                                                     x86_64                                      3.0.101-1                                      packages-microsoft-com-prod                                       64 M
 dotnet-targeting-pack-3.0                                          x86_64                                      3.0.1-1                                        packages-microsoft-com-prod                                      3.4 M

Transaction Summary
======================================================================================================================================================================================================================================
Upgrade  9 Packages

Total download size: 105 M
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
(1/9): aspnetcore-targeting-pack-3.0.1.rpm                                                                                                                                                                     | 1.4 MB  00:00:00
(2/9): dotnet-apphost-pack-3.0.1-x64.rpm                                                                                                                                                                       |  66 kB  00:00:00
(3/9): dotnet-host-3.0.1-x64.rpm                                                                                                                                                                               |  39 kB  00:00:00
(4/9): dotnet-hostfxr-3.0.1-x64.rpm                                                                                                                                                                            | 147 kB  00:00:00
(5/9): aspnetcore-runtime-3.0.1-rh.rhel.7-x64.rpm                                                                                                                                                              | 7.5 MB  00:00:01
(6/9): dotnet-runtime-deps-3.0.1-rhel.7-x64.rpm                                                                                                                                                                | 2.8 kB  00:00:00
(7/9): dotnet-runtime-3.0.1-x64.rpm                                                                                                                                                                            |  29 MB  00:00:11
(8/9): dotnet-targeting-pack-3.0.1-x64.rpm                                                                                                                                                                     | 3.4 MB  00:00:00
(9/9): dotnet-sdk-3.0.101-x64.rpm                                                                                                                                                                              |  64 MB  00:00:14
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                                 6.3 MB/s | 105 MB  00:00:16
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : dotnet-targeting-pack-3.0-3.0.1-1.x86_64                                                                                                                                                                          1/18
  Updating   : aspnetcore-targeting-pack-3.0-3.0.1-1.x86_64                                                                                                                                                                      2/18
  Updating   : dotnet-apphost-pack-3.0-3.0.1-1.x86_64                                                                                                                                                                            3/18
  Updating   : dotnet-runtime-deps-3.0-3.0.1-1.x86_64                                                                                                                                                                            4/18
  Updating   : dotnet-host-3.0.1-1.x86_64                                                                                                                                                                                        5/18
  Updating   : dotnet-hostfxr-3.0-3.0.1-1.x86_64                                                                                                                                                                                 6/18
  Updating   : dotnet-runtime-3.0-3.0.1-1.x86_64                                                                                                                                                                                 7/18
  Updating   : aspnetcore-runtime-3.0-3.0.1-1.x86_64                                                                                                                                                                             8/18
  Updating   : dotnet-sdk-3.0-3.0.101-1.x86_64
....
Updated:
  aspnetcore-runtime-3.0.x86_64 0:3.0.1-1     aspnetcore-targeting-pack-3.0.x86_64 0:3.0.1-1     dotnet-apphost-pack-3.0.x86_64 0:3.0.1-1     dotnet-host.x86_64 0:3.0.1-1                   dotnet-hostfxr-3.0.x86_64 0:3.0.1-1
  dotnet-runtime-3.0.x86_64 0:3.0.1-1         dotnet-runtime-deps-3.0.x86_64 0:3.0.1-1           dotnet-sdk-3.0.x86_64 0:3.0.101-1            dotnet-targeting-pack-3.0.x86_64 0:3.0.1-1

Complete!
```
After update
```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.101
 Commit:    bc5f8df0f5

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.101/

Host (useful for support):
  Version: 3.0.1
  Commit:  19942e7199

.NET Core SDKs installed:
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Notice that MicrosoftAspNetCore.App.3.0.1 is missing. I can run CLI programs using 3.0.1, just not AspNet applications.

**Comment by dagood** [comment] 2019-11-26 16:38
Duplicate of https://github.com/dotnet/core/issues/3886

**Comment by dagood** [comment] 2019-11-26 16:39
This is a known issue, basically there was a "normal" RPM and RHEL-style RPM published to the same place, and the RHEL-style one won out. It installs the ASP.NET Core runtime to a place that `dotnet` can't find it. There's a workaround at https://github.com/dotnet/core/issues/3886#issuecomment-557312983 to grab the normal one.

**Closed by dagood** 2019-11-26 16:39 UTC
