### ISSUE TITLE
MediaPlayerElement from Microsoft.Toolkit.Wpf.UI.Controls not working properly

### ISSUE THREAD

**Issue by yashwinder1411** [dotnet/core#3328] opened 2019-09-07 06:13 UTC
# Issue Title

MediaPlayerElement from Microsoft.Toolkit.Wpf.UI.Controls not working properly in in .net core 3.0.0-preview9.19423.6.
# General

.NET Core Version: 3.0-preview9.19423.6
Windows version: 1903
Does the bug reproduce also in WPF for .NET Framework 4.8?: Not supported in .Net Framework
Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)?No
Tried implementing UWP MediaPlayerElement in .net core 3.0.0-preview9.19423.6 WPF application but Video is not playing sometime

Actual behaviour:
[TestVide.zip](https://github.com/dotnet/core/files/3586302/TestVide.zip)

Video is getting played some time and sometimes not. No runtime exceptions. Video just hangs on the first frame.

Expected behaviour: Video should play as and when the project is loaded as Autorun property of the MediaPlayerElement is set to true.

**Comment by scalablecory** [comment] 2019-09-09 20:48
@grubioe is this something you can help with?

**Comment by grubioe** [comment] 2019-09-09 20:55
@scalablecory you can close as a dupe of WPF #[1807](https://github.com/dotnet/wpf/issues/1807).  Thanks

**Closed** 2019-09-09 21:29 UTC
Labels: area-wpf
