### ISSUE TITLE
COM event with recursion .net 6 problem

### ISSUE THREAD

**Issue by maciejpieprzyk** [dotnet/core#7680] opened 2022-08-09 14:22 UTC
---
id: 5fgfrbsef88gej7ei7o5684
title: Issue
desc: 'COM event with recursion .net 6 problem'
updated: 1660054184192
created: 1660053414611
---
### Description

We are using a system that exposes UI interface using COM objects. It is an external application so I cannot send a minimal reproduction source code of a problem.  I will try to explain the whole workflow.

#### Background information

There is an application interface (COM) that exposes event.

Event declaration in the App interface:

```c#
event _IApplicationEvents_StatusBarEventEventHandler StatusBarEvent;
```

Delegate definition:

```c#
public delegate void _IApplicationEvents_StatusBarEventEventHandler([In][MarshalAs(UnmanagedType.BStr)] string Text, [In] BoStatusBarMessageType messageType);
```

There is also a StatusBarControl that allows us to set up the ProgressBarMessage:

```c#
application.StatusBar.SetText(“some text”);
```

When we set the text to the status bar Event is fired.

#### Reproduction

UseCase: When the StatusBarEvent fires with text equal to “crush” we want to change this to "****" on the status bar

EventHandler implementation:

```c#
public override void OnStatusBarDisplayed(string text, BoStatusBarMessageType messageType)
{
    if (text.Equals("crush",StringComparison.CurrentCultureIgnoreCase))
    {
        application.StatusBar.SetText("*****");
    }
}
```

I will provide some screenshots of the debugging session:

1. Set "crush" to the status bar. ![image](https://user-images.githubusercontent.com/11562129/183669932-142a27de-d396-46d6-af17-028fabef3b5c.png)
2. We get the Event notification and call the setText("****").
3. System freezes. We can see that the event handler thread freezes on the set text method. ![image](https://user-images.githubusercontent.com/11562129/183670295-a1fd1989-ec16-44db-88b8-9276995fca18.png)
4. We can see that in the separate thread invoking a method the foreach loop of _delegateWrapper. ![image](https://user-images.githubusercontent.com/11562129/183670408-a912b540-42d3-401b-abe8-633cb8b21d7d.png)

#### Expected result

What should happen: this thread @29816 should invoke this method and Call the OnStatusBarDisplayed event again. This is working correctly when running in the .net framework.

Below is the same call stack of the .net framework debugging session. ![image](https://user-images.githubusercontent.com/11562129/183670717-228d0842-c11f-49f4-ae78-182c29f6afe6.png)

Calling SetText in another thread is not an option for us.

### Regression

This is working correctly when running in the .net framework.

**Comment by buyaa-n** [comment] 2022-08-14 19:50
Not sure if it WinForms issue CC @RussKie  or WPF issue CC @gomathip02 @vatsan-madhavan

**Comment by lukaszch** [comment] 2022-08-14 21:01
This issue is not directly related to WinForms or WPF. It happens in the described scenario on .NET Core (6/7), while it works correctly on .NET Framework. That blocks the migration of our codebase from .NET Framework to .NET Core.

**Comment by RussKie** [comment] 2022-08-15 03:51
This doesn't look like Windows Forms/WPF code, so it could be something in either .NET runtime or in SAP implementations.
AFAIK UI must be affinitised with STA, which isn't obvious from the screenshots whether it is the case. An attempt to access a UI control from a wrong thread could lead to multiple issues, including freezes and crashes. Perhaps this is something to investigate and verify.
Without a repro app it's hard to provide any concrete ideas.

Looping in @AaronRobinsonMSFT who may have other thoughts.

**Comment by MichalWeczorek** [comment] 2022-08-23 11:02
This issue was moved to dotnet/runtime repo.
direct link : [https://github.com/dotnet/runtime/issues/73754]

**Comment by AaronRobinsonMSFT** [comment] 2022-08-23 14:10
Closing this as duplicate of https://github.com/dotnet/runtime/issues/73754

**Closed by AaronRobinsonMSFT** 2022-08-23 14:10 UTC
