### ISSUE TITLE
Instructions for ubuntu18.10 don't work on 19.04 ... please update

### ISSUE THREAD

**Issue by duartemolha** [dotnet/core#2644] opened 2019-04-26 16:10 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Ubuntu 18.10 - x64
udo apt-get install dotnet-sdk-2.2
[sudo] password for user: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.4) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by dagood** [comment] 2019-04-26 19:45
Duplicate of #2526

**Closed by dagood** 2019-04-26 19:45 UTC
