### ISSUE TITLE
Currency format fails in .NET 5.0

### ISSUE THREAD

**Issue by redymc** [dotnet/core#5587] opened 2020-11-12 13:31 UTC
# Currency format fails in .NET 5.0

I am using currency format in my Blazor Server-Side application and I have faced an issue, after migrated to .NET 5.0.

The '¤' symbol appears, instead of the current culture's currency symbol (currently I am using german culture). In .NET Core 3.1 there was no problem.

**.NET Core 3.1 result:**
![result3 1](https://user-images.githubusercontent.com/55623342/98945895-709e2f80-24f3-11eb-9014-8a78a1bd4fe0.PNG)

**.NET 5.0 result:**
![result5 0](https://user-images.githubusercontent.com/55623342/98945982-91ff1b80-24f3-11eb-9e2c-f0f552f19af0.png)

**_ConfigureServices (Startup):_**

            services.Configure<RequestLocalizationOptions>(options =>
            {
                var supportedCultures = new List<CultureInfo>()
                {
                    new CultureInfo("de")
                };
                options.DefaultRequestCulture = new RequestCulture("de");
                options.SupportedCultures = supportedCultures;
                options.SupportedUICultures = supportedCultures;
            });

**_Configure (Startup):_**

            app.UseRequestLocalization(app.ApplicationServices.GetService<IOptions<RequestLocalizationOptions>>().Value);

**_Index.razor:_**

            <p>Value: @(Value?.ToString("C0"))</p>

            @code
            {
                  public int? Value { get; set; } = 500;
            }

I attached a repro project for your convenience: [CurrencyFormatIssue_NET5.0.zip](https://github.com/dotnet/core/files/5530790/CurrencyFormatIssue_NET5.0.zip)

Thanks in advance!

**Comment by GrabYourPitchforks** [comment] 2020-11-12 18:41
Duplicate of https://github.com/dotnet/runtime/issues/38308. Please see that issue for resolution (use "de-DE" instead of "de").

**Closed by GrabYourPitchforks** 2020-11-12 18:41 UTC
