### ISSUE TITLE
dot net core path in VS Code

### ISSUE THREAD

**Issue by mammadkoma** [dotnet/core#2196] opened 2019-01-01 09:16 UTC
My VS Code can not find dot net core cli because I can not install any program (for network policies reason) and I can not copy dotnet folder to _C:\Program Files_ because I have not the admin user pass.
I only downloaded _dotnet-sdk-2.2.101-win-x64.zip_ and VSCode portable file and extract dotnet to _C:\dotnet_.
I can create a mvc project and run it by command line but VS Code can not start debugging.
how can I set a setting for VS Code to define dotnet core path to _C:\dotnet_?

**Comment by MarcoRossignoli** [comment] 2019-01-01 15:52
Better to ask here https://github.com/Microsoft/vscode/issues

**Comment by mammadkoma** [comment] 2019-01-01 20:33
https://github.com/Microsoft/vscode/issues/65818

**Comment by MarcoRossignoli** [comment] 2019-01-01 20:44
@mammadkoma actually c# vs code extension is provided by Omnisharp you could try to ask also here https://github.com/OmniSharp/omnisharp-vscode/issues
--

**Comment by mammadkoma** [comment] 2019-01-02 06:56
https://github.com/OmniSharp/omnisharp-vscode/issues/2772

**Comment by karelz** [comment] 2019-01-08 04:37
Duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/2772

**Closed by karelz** 2019-01-08 04:37 UTC
