### ISSUE TITLE
dotnet run error

### ISSUE THREAD

**Issue by LeMinhNam** [dotnet/core#6759] opened 2021-10-02 07:17 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

When I take command line: dotnet --version
Then receive the error:  "Unhandled exception. System.DllNotFoundException: Unable to load shared library 'System.Native' or one of its dependencies.". Can you help me, please?

**Comment by mairaw** [comment] 2021-10-05 01:50
Duplicate of #6630

**Closed by mairaw** 2021-10-05 01:50 UTC
