### ISSUE TITLE
netstandard-targeting-pack-2.1 FAILED

### ISSUE THREAD

**Issue by siddharthashw** [dotnet/core#3862] opened 2019-11-20 14:35 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/sdk-3.0.101
Operating System:  Centos 7

**This is what happening, When I am trying install sdk-3.0 on my centos server**

Install  1 Package (+4 Dependent packages)

Total size: 71 M
Total download size: 2.1 M
Installed size: 71 M
Is this ok [y/d/N]: y
Downloading packages:
netstandard-targeting-pack-2.1 FAILED
https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod/netstandard-targeting-pack-2.1.0-x64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=packages-microsoft-com-prod clean metadata
Trying other mirror.

Error downloading packages:
  netstandard-targeting-pack-2.1-2.1.0-1.x86_64: [Errno 256] No more mirrors to try.

**Comment by craigjbass** [comment] 2019-11-20 16:26
Dupe of #3853

**Closed** 2019-11-20 16:29 UTC
