### ISSUE TITLE
Linux package names are inconsistent

### ISSUE THREAD

**Issue by mxplusb** [dotnet/core#502] opened 2017-02-15 21:10 UTC
I'm writing an automated script to install the latest SDK 1.0.0 Preview for Debian/Ubuntu, and I noticed this when performing an `apt-cache search apt-cache search dotnet-dev-1.0.0-preview2` search:

```shell
# apt-cache search dotnet-dev-1.0.0-preview2
dotnet-dev-1.0.0-preview2-003121 - Microsoft .NET Core 1.0.0 - SDK Preview 2
dotnet-dev-1.0.0-preview2-003131 - Microsoft .NET Core 1.0.1 - SDK 1.0.0 Preview 2-003131
dotnet-dev-1.0.0-preview2-003156 - Microsoft .NET Core 1.0.3 - SDK 1.0.0 Preview 2-003156
dotnet-dev-1.0.0-preview2-1-003177 - Microsoft .NET Core 1.1.0 - SDK 1.0.0 Preview 2.1-003177
dotnet-dev-1.0.0-preview2.1-003155 - Microsoft .NET Core 1.1.0 Preview1 - SDK 1.0.0 Preview 2.1-003155
```

Looking at builds `003155` and `003177`, the package name formats are slightly different:

```
# preview2.1 with a period
dotnet-dev-1.0.0-preview2.1-003155
# preview2-1 with a slash.
dotnet-dev-1.0.0-preview2-1-003177
```

I know it seems minute, it was something I noticed when I called `sort` in Bash.

Here was the workaround for it in Bash:
```bash
dotnet=(); for i in $(apt-cache search dotnet-dev-1.0.0-preview2 | awk '{print $1}'); do dotnet+=(`echo $i| rev`); done; IFS=$'\n' sorted=($(sort <<<"${dotnet[*]}")); echo ${sorted[@]} | rev
```

**Comment by Petermarcu** [comment] 2017-02-16 07:30
Yeah, I remember what happened. the 2.1 version was used everywhere in the buildsystem and the "." in there broke some of the version parsers. It was quickly changed to 2-1. As soon as these things aren't in preview (very soon), these packages should all become obsolete. 

Thanks for posting the workaround. I think the problem is already addresses moving forward so I'm going to close this. Let me know if there was an additional action you think should be taken.

**Closed** 2017-02-16 07:30 UTC
