### ISSUE TITLE
sudo apt-get upgrade fails

### ISSUE THREAD

**Issue by stevenaharrison** [dotnet/core#3598] opened 2019-10-11 00:52 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/runtime-current
Operating System: Linux Debian 9 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Error Recieved: Failed to fetch https://packages.microsoft.com/debian/9/prod/dists/stretch/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)

googling this seems to indicate a proxy issue, but I am not going through a proxy server.  I can wget the same file no problem.

Thanks!

**Comment by nathanruiz** [comment] 2019-10-11 04:23
Getting the same error here, also running Debian 9:

```
Hit:1 http://security.debian.org stretch/updates InRelease
Get:2 https://download.docker.com/linux/debian stretch InRelease [44.8 kB]
Ign:3 http://http.us.debian.org/debian stretch InRelease
Hit:4 http://http.us.debian.org/debian stretch-updates InRelease
Hit:5 http://http.us.debian.org/debian stretch Release
Get:7 https://packages.microsoft.com/debian/9/prod stretch InRelease [4,023 B]
Err:7 https://packages.microsoft.com/debian/9/prod stretch InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Hit:8 http://apt.postgresql.org/pub/repos/apt stretch-pgdg InRelease
Fetched 48.9 kB in 1s (34.3 kB/s)
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/debian/9/prod/dists/stretch/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by noppGithub** [comment] 2019-10-11 05:32
Same issue, it's seems that there is some change on the repository yesterday.
![image](https://user-images.githubusercontent.com/21082770/66626586-fda4f400-ec22-11e9-8c28-b43f0e9851b5.png)

I use the [guide provided by Microsoft](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017) for a long time.
But now it's not working because of this error.

**Comment by Dennis-Petrov** [comment] 2019-10-11 06:28
The same problem detected today when building docker images:

```
Hit:1 http://security-cdn.debian.org/debian-security stretch/updates InRelease
Get:2 https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch InRelease [4023 B]
Err:2 https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Hit:4 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease
Hit:5 http://cdn-fastly.deb.debian.org/debian stretch Release
Fetched 4023 B in 0s (4176 B/s)
Reading package lists...
[91mE: Failed to fetch https://packages.microsoft.com/repos/microsoft-debian-stretch-prod/dists/stretch/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
There were no any changes on our side.

**Comment by ghclo** [comment] 2019-10-11 07:57
This issue can be easily reproduced by running following commands in Debian:
```
curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list
sudo apt-get update
```

**Comment by Tob0t** [comment] 2019-10-11 08:08
Same issue, cannot deploy anymore due to this bug :/
```E: Failed to fetch https://packages.microsoft.com/debian/9/prod/dists/stretch/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)```
Any chances that this will be fixed in the next hours?

**Comment by pkisztelinski** [comment] 2019-10-11 08:18
you can change version of debian from 9 to 10 :

```
curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list
sudo apt-get update
```
works fine in my situation

**Comment by bakgat** [comment] 2019-10-11 10:01
I'm trying this to use this to install msodbcsql17.
WIth debian 9 it worked till yesterday.
With debian 10 I get:
`Package 'msodbcsql17' has no installation candidate`

Any ideas where I can find 'msodbcsql17' for debian 10?

**Comment by axa-dfd** [comment] 2019-10-11 10:07
We changed to debian 8 which let us install  msodbcsql17 until we get debian 9 to work again.

**Comment by kitsuyui** [comment] 2019-10-11 11:49
I think it relates this issue. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884922

Cleartext signed InRelease files with CRLF line ending is invalid in older versions of apt.

apt version of Debian 9 stretch is 1.4.9.
InRelease file seems to be broken for this version.

```sh
$ curl -s https://packages.microsoft.com/debian/8/prod/dists/jessie/InRelease | file -
/dev/stdin: ASCII text

$ curl -s https://packages.microsoft.com/debian/9/prod/dists/stretch/InRelease | file -
/dev/stdin: ASCII text, with CRLF, LF line terminators

$ curl -s https://packages.microsoft.com/debian/10/prod/dists/buster/InRelease | file -
/dev/stdin: ASCII text
```

**Comment by mthidell** [comment] 2019-10-11 12:04
I experience the same issue even with newer apt version which contains the fix. 
I my case, on the Ubuntu "InRelease" 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884922

```
$ curl -s https://packages.microsoft.com/ubuntu/18.04/prod/dist/bionic/InRelease | file -
/dev/stdin: HTML document, ASCII text, with CRLF line terminators

$ apt --version
apt 1.6.12 (amd64)

$ apt changelog apt
....
apt (1.6~alpha6) unstable; urgency=medium
  * Support cleartext signed InRelease files with CRLF line endings.
      Thanks to Lukas Wunner for detailed report & initial patch! (Closes: 884922)
```

**Comment by erik-wramner** [comment] 2019-10-11 12:16
Is there any workaround for this? I'm trying to build a docker image based on an image that in turn was based on stretch. I can't change the base image and I need to install msodbcsql17 and mssql-tools. I can live with bypassing security temporarily if necessary or I could add some steps that download and fix the files, but I don't know how. Any pointers?

**Comment by Himura2la** [comment] 2019-10-11 12:40
This issue affects many products, I faced it when our docker image failed to build because of issues with PowerShell installation (we used this ugly script https://github.com/PowerShell/PowerShell/blob/a96b4c0/tools/install-powershell.sh on debian)

I temporary solved the problem as follows:

```
curl -LsSo pwsh.deb https://github.com/PowerShell/PowerShell/releases/download/v6.2.3/powershell_6.2.3-1.debian.9_amd64.deb && dpkg -i pwsh.deb && apt-get install -f && rm pwsh.deb
```

**Comment by heinrich-ulbricht** [comment] 2019-10-11 13:27
I'm also affected on Debian 9. Started searching for a solution some hours ago and now this ticket explodes. Good :)

**Comment by dooferorg** [comment] 2019-10-11 13:57
Yea.. just came here to report this as well!

I was just trying to set up a new dotnet box today too. Sources were working the other day

**Comment by rynnova** [comment] 2019-10-11 14:15
Had the same issue with Windows Subsystem for Linux using Debian to install .NET Core on it.

I'll wait for 15 minutes and see if it resolves itself.

**Comment by lochuynh** [comment] 2019-10-11 14:35
I got the same issue, and It locked  my release on next Monday, I cannot build a docker image on Azure  pipeline anymore.
E: Failed to fetch https://packages.microsoft.com/debian/9/prod/dists/stretch/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by lochuynh** [comment] 2019-10-11 15:06
Any workaround to build a docker image? I have a urgent release, please help.

**Comment by Himura2la** [comment] 2019-10-11 15:24
@lochuynh Try this https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script

**Comment by amamounelsayed** [comment] 2019-10-11 17:54
It is working for me now! Thank you!

**Comment by dagood** [comment] 2019-10-11 17:55
I've sent a high-importance mail to the Microsoft Linux repository admins, will report back here as I have more info. Thanks everyone for reporting this. /cc @leecow

**Comment by dagood** [comment] 2019-10-11 18:24
They confirmed this should be fixed now.

Do let us know if there are any problems with specific packages: the repository itself is fixed, but individual packages may still be broken. The repo admins are now working on identifying and fixing any cases where that's happened.

There was a change in the backend's signing infra that seems to have caused the initial issue when a team pushed a new package to the repo.

**Closed by dagood** 2019-10-11 18:24 UTC

**Comment by heinrich-ulbricht** [comment] 2019-10-11 19:51
Working for me now. Thanks!

**Comment by lochuynh** [comment] 2019-10-11 22:40
Thanks @Himura2la.
It is working now, I am back on my schedule. Thanks

**Comment by ffloimair** [comment] 2019-12-13 08:54
> They confirmed this should be fixed now.
> 
> Do let us know if there are any problems with specific packages: the repository itself is fixed, but individual packages may still be broken. The repo admins are now working on identifying and fixing any cases where that's happened.
> 
> There was a change in the backend's signing infra that seems to have caused the initial issue when a team pushed a new package to the repo.

Happens again today. 

`Err:13 https://packages.microsoft.com/debian/9/prod stretch/main amd64 Contents (deb)

Fetched 72.6 kB in 0s (82.1 kB/s)
Reading package lists... Done
W: Conflicting distribution: https://packages.microsoft.com/debian/9/prod stretch InRelease (expected stretch but got stable)
E: Failed to fetch https://packages.microsoft.com/debian/9/prod/dists/stretch/main/binary-amd64/Packages.bz2  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:156065 [weak]
    - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
    - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
    - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
    - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
   Hashes of received file:
    - SHA512:a18b4df496d00477e52cf62e01c9f6c9534926ad0e3bf17f94fc28fc9bd91d5ee5e906b460477e2c1b280a5757a067937c9b2724bd6c72066e982a19306f28b8
    - SHA256:94e637dd6df186bbed5a19f2e7bdc2dcc8f7bb0feb2f1eaf93f05b45dd322cc4
    - SHA1:fb9e80e17952a577030e9266737b23269c8d878b [weak]
    - MD5Sum:4360374f4ec05159ef14908c0dbf4116 [weak]
    - Filesize:68668 [weak]
   Last modification reported: Fri, 13 Dec 2019 01:35:23 +0000
   Release file created at: Thu, 12 Dec 2019 19:59:19 +0000
E: Failed to fetch https://packages.microsoft.com/debian/9/prod/dists/stretch/main/Contents-amd64.gz`

**Comment by jontro** [comment] 2019-12-13 10:29
Can confirm, our CI systems cannot build artifacts depending on this repo.

**Comment by raubreywhite** [comment] 2019-12-13 11:00
Same problem as @ffloimair

**Comment by raubreywhite** [comment] 2019-12-13 11:06
This no longer works: 

https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#microsoft-odbc-driver-17-for-sql-server

**Comment by pkisztelinski** [comment] 2019-12-13 11:08
version 9 and 10 doesnt work, 8 works fine in my situation

**Comment by Evoluti0n** [comment] 2019-12-13 12:26
i have the same problem, in Debian 10

**Comment by rsnathan** [comment] 2019-12-13 13:27
Does anyone know where this issue is being tracked

**Comment by dagood** [comment] 2019-12-13 15:37
The current outage is being tracked at https://github.com/dotnet/core/issues/3988.

I'm going to lock this thread as resolved: I encourage everyone seeing this in the future to file new issues rather than add comments to this one. Because the issue is closed, new comments might not be seen by the right people in the future. A new issue is more likely to get noticed. There's nothing wrong with posting relevant comments to old issues, but I want to make sure outages are seen as soon as possible. Thanks!
