### ISSUE TITLE
Missing packages for Fedora 29/30

### ISSUE THREAD

**Issue by ggobbe** [dotnet/core#2634] opened 2019-04-24 12:09 UTC
# Missing packages for Fedora 29/30

If one wants to install `dotnet-sdk` or `dotnet-runtime` on Fedora, the most recent version of Fedora supported is *28*, although it uses the Fedora *27* repo. cf. https://dotnet.microsoft.com/download/linux-package-manager/fedora28/sdk-current

By browsing https://packages.microsoft.com it appears that the repos for Fedora *29* and *30* are there, but both are empty: 
- https://packages.microsoft.com/fedora/29/prod/
- https://packages.microsoft.com/fedora/30/prod/

As said, the most recent version of Fedora having a repo with packages available is 27:
- https://packages.microsoft.com/fedora/27/prod/

Would it be possible to publish packages for every version of Fedora that is supported? For .NET Core 3, that is Fedora 28, 29 and 30. cf. https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md

Thanks

**Comment by dagood** [comment] 2019-04-24 16:15
openSUSE is in a similar situation, at https://github.com/dotnet/core/issues/2576. I agree the current way this is set up is confusing.

The packages in the 27 repository are intended to work with any supported Fedora release. It is *possible* to publish packages for every supported release, but our release process doesn't make that particularly easy so we've been using the earliest that it works on.

If there's an issue using the 27 repository's packages on a supported release, definitely want to hear about it!

I'm closing because I expect whatever we arrive at in https://github.com/dotnet/core/issues/2576 will fix this as well. Let me know if there's a particular problem or a short-term fix that I'm missing here.

**Comment by dagood** [comment] 2019-04-24 16:15
Duplicate of #2576

**Closed by dagood** 2019-04-24 16:15 UTC

**Comment by ggobbe** [comment] 2019-04-24 16:28
Thanks for details, it makes more sense. 
I'll be waiting for a proper solution then.

**Comment by jeffguorg** [comment] 2019-06-12 07:40
I found there is a [dotnet Special Interest Group](https://copr.fedorainfracloud.org/groups/g/dotnet-sig/coprs/) for fedora. is this official or not? 

I think I'm gonna use it for a while

**Comment by omajid** [comment] 2019-06-12 22:01
> I found there is a dotnet Special Interest Group for fedora. is this official or not?

It's not official in the sense of being officially backed by Microsoft or by the .NET Foundation. It was started by some of us who are involved with Fedora as well as .NET Core here on github.  

> I think I'm gonna use it for a while

Please do! If you run into any issues, please let us know at https://pagure.io/dotnet-sig/packaging-issues/issues
