### ISSUE TITLE
.NET Core December Update -  2.2.101 and 2.1.502 SDK

### ISSUE THREAD

**Issue by vivmishra** [dotnet/core#2134] opened 2018-12-11 20:07 UTC
* .NET Core SDK 2.1.502
  [Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.502-SDK/2.1.502.md)
  [Download 2.1.502](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.502-SDK/2.1.502-download.md)

* .NET Core SDK 2.2.101
  [Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2.101-SDK/2.2.101.md)
  [Download 2.2.101](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2.101-SDK/2.2.101-download.md)

Please report any issues you find with 2.1.502/2.2.101, either responding to this issue, creating a new issue or creating a new issue in one of the following repos:

* [aspnet/Home](https://github.com/aspnet/Home/issues) - for ASP.NET Core questions
* [aspnet/EntityFrameworkCore](https://github.com/aspnet/EntityFrameworkCore/issues) - for Entity Framework Core questions
* [dotnet/cli](https://github.com/dotnet/cli/issues) - for CLI tools and questions
* [dotnet/corefx](https://github.com/dotnet/corefx/issues) - for API issues and questions
* [dotnet/coreclr](https://github.com/dotnet/coreclr/issues) - for runtime issues
* [dotnet/core-setup](https://github.com/dotnet/core-setup/issues) - for installer issues
* [nuget/home](https://github.com/nuget/home/issues) - for NuGet questions and issues

**Comment by Nothing-Works** [comment] 2018-12-11 21:16
@vivmishra Hi I just updated to Visual Studio 2017 version 15.9.4 and I just got .NET Core SDK 2.1.502 no .NET Core SDK 2.2.101 is this the expected version?

According to this [Release Notes](https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2.101-SDK/2.2.101.md) I should have .NET Core SDK 2.2.101 as well right?

**Comment by vivmishra** [comment] 2018-12-11 22:54
@Nothing-Works, thanks for pointing out the mistake -- rel note is updated. 
2.2.101 is not yet included in any released VS version.

**Comment by mrsquish** [comment] 2018-12-12 03:36
Here I was thinking this was just me!

Mind you, even after installing SDK 2.1.502 I can't seem to update the Nuget packages to 2.1.5? Or am I completely barking up the wrong tree.

**Comment by UweKeim** [comment] 2018-12-12 06:56
Did **IIS in-process hosting** make it into 2.2 [as stated here](https://github.com/aspnet/AspNetCore/issues/3794#issuecomment-435473758)?

**Comment by Rutix** [comment] 2018-12-12 07:41
@UweKeim yes it did. See also https://blogs.msdn.microsoft.com/webdev/2018/12/04/asp-net-core-2-2-available-today/

**Comment by tristanbarcelon** [comment] 2018-12-12 14:49
Could this 2.1.502 update of the SDK introduced an inconsistent pattern with the 2.1 releases.json file? I posted the [issue](https://github.com/dotnet/core/issues/2139) here. Having analyzed the releases.json files for prior releases, this 2.1.502 sdk entry would have previously ended up in the sdk field of the 2.1.6 release instead of having its own release entry. Can we get some clarification please?

**Comment by tristanbarcelon** [comment] 2018-12-13 10:42
@leecow I looked over the shape of 2.0's releases.json and it's missing latest-runtime and latest-sdk fields. Granted its maintenance status is EOL, would it hurt to show these two fields across all releases so we don't have to code for missing fields/exceptions when parsing the json file?

**Comment by tristanbarcelon** [comment] 2018-12-14 01:38
Thanks @leecow for your consideration.

**Comment by leecow** [comment] 2018-12-14 04:45
@tristanbarcelon - most of the changes have been implemented and you can see them from https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json. We'll be using this azure storage rather than github to host the 'production' json files. Something will be added to the github files to make it clear they should not be used as the production endpoint for the data.

**Comment by leecow** [comment] 2018-12-14 16:07
@tristanbarcelon 

- added runtime-version to 2.1.100 so should be good there now. 
- looks like I switched to sha512 last November. 

2.0.3 was released with the 2.0.3 SDK in November then again with the 2.1.2 SDK in December. The minor version bump was lIkely due to updated toolset features for VS but would have to dig a little to know for sure. At any rate, toolset changes would not result in changes to the hosting bundle which is why that's the same as well.

Now that we're tracking runtime and sdk versions in all the right places, the release-version field is really starting to bother me ;-)

**Comment by tristanbarcelon** [comment] 2018-12-14 18:50
@leecow did something just change in https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json? The 'releases.json' parameter now points back to github instead of the azure blob.

**Comment by leecow** [comment] 2018-12-14 19:07
@tristanbarcelon ... sorry about that - fixed up.

**Comment by kevindqc** [comment] 2018-12-19 16:56
The changes are here: https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2.101-SDK/2.2.101-commits.md

**Comment by CumpsD** [comment] 2018-12-19 19:08
Thanks!

**Comment by TristanApc** [comment] 2018-12-20 14:35
In 2.2.101 I'm receiving a `System.ObjectDisposedException: 'The CancellationTokenSource has been disposed.'` exception from `System.Private.CoreLib`, resulting in a hard crash. The issue is intermittent. Full exception detail below:

```
System.ObjectDisposedException
  HResult=0x80131622
  Message=The CancellationTokenSource has been disposed.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.IO.FileStream.FileStreamCompletionSource.CompleteCallback(UInt64 packedResult)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

**Comment by karelz** [comment] 2018-12-20 19:15
@TristanApc it is not clear from the callstack if it is a bug in your code, some 3rd party library or in .NET Core itself. You will likely need to root-cause it first or at least do deeper investigation, then file a bug.

**Comment by sepehr1014** [comment] 2018-12-21 07:18
@TristanApc @karelz It might be related to https://github.com/aspnet/AspNetCore/issues/4422 which should be fixed in the next minor release https://github.com/dotnet/coreclr/pull/21417

**Comment by TristanApc** [comment] 2018-12-21 13:33
@sepehr1014 thanks! That definitively seems related since CoreLib directly throws the exception that I'm getting. The application is indeed ASP MVC using kestrel.

**Comment by johnkwaters** [comment] 2018-12-28 17:43
Still no ANCM for Azure App Services?

**Comment by karelz** [comment] 2019-01-08 04:32
@johnkwaters what is ANCM? In general, we recommend to watch Azure App Services announcement repo: https://github.com/Azure/app-service-announcements

**Comment by johnkwaters** [comment] 2019-01-08 16:17
Thanks @karelz - it is the new AspNetCoreModule. I had asked previously, and was also told to monitor for announcements,. but there have been none, and it was supposed to roll out in December. However I was told in another thread that it is out there now, and sure enough, it is - so maybe you should announce it?

**Comment by karelz** [comment] 2019-01-08 16:21
@johnkwaters good idea to raise it to App Service team ...

**Comment by leecow** [comment] 2019-01-10 17:45
@shirhatti for ideas on ANCM announcement channels.

**Comment by tristanbarcelon** [comment] 2019-01-19 01:00
Hi @vivmishra @leecow, did anything change in the [dotnetcore release index](https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json) yesterday or today? My script which was working just fine yesterday now gets an error when used today.

**Comment by leecow** [comment] 2019-01-19 01:50
@tristanbarcelon - there was a refresh of the sdk yesterday. Looks like an errant comma slipped into the file. Fixed.

**Comment by tristanbarcelon** [comment] 2019-01-19 03:51
Thank you @leecow

**Comment by leecow** [comment] 2019-02-12 21:48
Closing this release discussion issue in favor of https://github.com/dotnet/core/issues/2304.

**Closed by leecow** 2019-02-12 21:48 UTC
Labels: Announcement
