### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by webtop** [dotnet/core#3142] opened 2019-08-02 18:58 UTC
Trying to install dependencies on CentOS 7 x64, yielded the following:

Retrieving https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
curl: (22) The requested URL returned error: 404 Not Found
error: skipping https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm - transfer failed

**Comment by webtop** [comment] 2019-08-02 19:01
Looking at the site for that URL, this is available:
https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm

Did the RPM change and the docs just not updated?

The doc I was doing this from is: https://dotnet.microsoft.com/download/linux-package-manager/centos/runtime-current

**Comment by webtop** [comment] 2019-08-02 19:03
Here: https://packages.microsoft.com/config/rhel/7/ it shows, but clicking on it goes to a 404.

**Comment by webtop** [comment] 2019-08-02 19:04
Interestingly, going up one more level to https://packages.microsoft.com/config/rhel/7.4/ shows that there is the package and it does download.

**Comment by jceddy** [comment] 2019-08-02 19:08
I came here to report the same issue.

**Comment by webtop** [comment] 2019-08-02 19:13
Unfortunately the 7.4 repo has no aspnetcore packages, but changes to the 7.3 folder does.
I think installing this RPM will yield the expected results: https://packages.microsoft.com/rhel/7.3/prod/packages-microsoft-prod-1.0-1.el7.noarch.rpm

**Comment by dagood** [comment] 2019-08-02 19:14
In https://github.com/dotnet/core/issues/3141 it's pointed out there's a CentOS one that might be better for these instructions to use: https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm

**Comment by dagood** [comment] 2019-08-02 19:14
Duplicate of https://github.com/dotnet/core/issues/3141

**Closed by dagood** 2019-08-02 19:14 UTC
