### ISSUE TITLE
Breakpoints are not hit when a source file contains a line of > 65536 columns.

### ISSUE THREAD

**Issue by Bodmoor** [dotnet/core#2071] opened 2018-11-20 13:16 UTC
# Breakpoints are not hit when a source file contains a line of > 65536 columns.

# General information

version: .NET core 2.1.500
OS: windows 10 pro
Visual studio 2017 Community 15.9.0

I have created a project where the test input parameter was very long. > 800k characters. When testing, the breakpoints in my project were not hit anymore.

## Issue

When I gradually reduced the number of characters, the breakpoints started working again at 65534 (so including the newline, that would be 65536)

Also when I extended the string but split it into two lines using a string concat ( + ), the breakpoints started working again.

This is not a 'normal' scenario, but there is no warning of any sort or error as to why a basic/core feature suddenly is not behaving as expected.

## Expected behaviour

I would expect a warning that one of my source files contains an insanely long string, and that it may prevent visual studio from behaving normally.

**Comment by 0xd4d** [comment] 2018-11-20 14:55
https://github.com/dotnet/roslyn/issues/20118

https://github.com/dotnet/core/issues/2058

**Comment by karelz** [comment] 2018-11-26 04:59
Duplicate of https://github.com/dotnet/roslyn/issues/20118

Thanks @0xd4d for finding the dupe!

**Comment by karelz** [comment] 2018-11-26 05:00
Thanks @0xd4d for finding the dupe!

**Closed by karelz** 2018-11-26 04:59 UTC
