### ISSUE TITLE
Debian 9 Hash Sum Mismatch

### ISSUE THREAD

**Issue by Remorc** [dotnet/core#3994] opened 2019-12-13 16:20 UTC
# Debian 9 Hash Sum Mismatch

# General

I am actively attempting to install dotnet core 3.0 on Debian 9. I am getting a Hash Sum Mismatch when running `sudo apt-get update`. I am following the instructions here: https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-debian9

It's worth mentioning that I started seeing this issue on 2019-12-13. Everything worked fine on 2019-12-12

Here's the output:
```
    $ sudo apt-get update
    Ign:1 <http://deb.debian.org/debian> stretch InRelease
    Hit:2 <http://repos.rcn-ee.com/debian> stretch InRelease
    Hit:3 <http://deb.debian.org/debian> stretch-updates InRelease
    Hit:4 <http://deb.debian.org/debian-security> stretch/updates InRelease
    Hit:5 <http://deb.debian.org/debian> stretch Release
    Get:11 <https://packages.microsoft.com/debian/9/prod> stretch/main amd64 Packages [156 kB]
    Err:11 <https://packages.microsoft.com/debian/9/prod> stretch/main amd64 Packages
      Hash Sum mismatch
      Hashes of expected file:
       - Filesize:156065 [weak]
       - SHA512:12e6dffcd247d1ff067acfa61a3c4eb6078c326c2858feb4f6f141a1d809e22292a78282414a5c103038ea80bb63cd734c7516782c9809c341335083d4e7611b
       - SHA256:c850f35f1979831ac75641978c397e51519fa22313598ec12bde5f52277044c0
       - SHA1:1f65f4a7388c22bcf7b7f30fb7bc337c60d94b2e [weak]
       - MD5Sum:4153a12e4a5629bfb14ed98f4c8ac234 [weak]
      Hashes of received file:
       - SHA512:a18b4df496d00477e52cf62e01c9f6c9534926ad0e3bf17f94fc28fc9bd91d5ee5e906b460477e2c1b280a5757a067937c9b2724bd6c72066e982a19306f28b8
       - SHA256:94e637dd6df186bbed5a19f2e7bdc2dcc8f7bb0feb2f1eaf93f05b45dd322cc4
       - SHA1:fb9e80e17952a577030e9266737b23269c8d878b [weak]
       - MD5Sum:4360374f4ec05159ef14908c0dbf4116 [weak]
       - Filesize:68668 [weak]
      Last modification reported: Fri, 13 Dec 2019 01:35:23 +0000
      Release file created at: Thu, 12 Dec 2019 19:59:19 +0000
    Fetched 68.7 kB in 14s (4,612 B/s)
```

**Comment by dagood** [comment] 2019-12-13 16:26
Yeah, there's an outage right now, tracked at https://github.com/dotnet/core/issues/3988.

**Comment by dagood** [comment] 2019-12-13 16:26
Duplicate of https://github.com/dotnet/core/issues/3988

**Closed by dagood** 2019-12-13 16:26 UTC
