### ISSUE TITLE
Inconsistent behavior in treating paths in Evolve.Evolve() on Windows and Linux

### ISSUE THREAD

**Issue by master0luc** [dotnet/core#7293] opened 2022-03-18 07:05 UTC
### Description
Passing roots in this way :
```cs
                        evolve.Locations = new[] {
                            Path.Combine("db", "migrations")
                        };
```
On  Windows works as if it was "./db"
but on Linux just as it is, e.g. "db" 

### Configuration
Net 5.0.15 on Windows
mcr.microsoft.com/dotnet/aspnet:5.0 on Linux

**Comment by rzikm** [comment] 2022-03-18 07:54
Hi, I am not entirely sure what the issue is about, can you please share a full minimal reproducible code example which triggers the error?

**Comment by master0luc** [comment] 2022-03-18 13:03
migration scripts are diposed in  **"{ProjectFolder}\db\migrations\*.sq;"**
  This task is invoked on statrup:
  ```
   public abstract class DbMigrationTask : IStartupTask
    {
        protected readonly string _connectionString;
        private readonly string _databaseSchema;
        private readonly ILogger<DbMigrationTask> _logger;

        protected DbMigrationTask(string connectionString, ILogger<DbMigrationTask> logger)
        {
            _connectionString = connectionString;
            _logger = logger;
        }

        protected DbMigrationTask(string connectionString, ILogger<DbMigrationTask> logger, string databaseSchema)
        {
            _connectionString = connectionString;
            _databaseSchema = databaseSchema;
            _logger = logger;
		}

		public virtual Task ExecuteAsync()
        {
            try {
                using (var connection = new NpgsqlConnection(_connectionString)) {
                    var evolve = new Evolve.Evolve(connection, msg => _logger.LogInformation(msg)) {
                        IsEraseDisabled = true,
                        CommandTimeout = 600
                    };
                  //HERE ADD FOLDERS
                    evolve.Locations = new[] {
                          Path.Combine("db", "migrations")
                    };
                   //SO,  PATH IS "db/migrations/"
                   //ON LINUX SQL SCRIPTS  ARE NOT FOUND  => and it is correct behavior
                   //BUT  ON WINDOWS SQL SCRIPTS ARE PERFECTLY FOUND
                    evolve.Migrate();
                }
            }
            catch (Exception e)
            {
					switch (e) {
						case NpgsqlException npgsqlException
							when npgsqlException.Message.StartsWith("The connection pool has been exhausted") ||
									npgsqlException.Message.StartsWith("Exception while reading from stream"):
						case PostgresException postgresException
							when postgresException.SqlState == "57P03":
							_logger.LogCritical("Database migration failed.", e);
							throw;
						default:
							break;
					}
            }

            return Task.CompletedTask;
        }
    }
```

**Comment by rzikm** [comment] 2022-03-21 08:14
@ajcvickers Can you please take a look?

**Comment by ajcvickers** [comment] 2022-03-21 08:37
@rzikm What is `Evolve`? What is it supposed to do in this case?

**Comment by rzikm** [comment] 2022-03-21 08:51
Sorry, my bad, I thought it was something from EF. It actually looks like it is a 3rd party library https://github.com/lecaillon/Evolve.

@master0luc Can you confirm? If that is the case than you need to file an issue in the library's repository.

**Comment by master0luc** [comment] 2022-03-21 11:08
O my, You are right.
My fault,  Sorry for my carelessness about this issue

**Comment by rzikm** [comment] 2022-03-21 12:19
no problem, I will close this issue. If you have any other questions, feel free to reopen it or file a new one.

**Closed by rzikm** 2022-03-21 12:19 UTC
