### ISSUE TITLE
Unable to locate the package dotnet-sdk-2.2

### ISSUE THREAD

**Issue by chaos1908** [dotnet/core#2897] opened 2019-06-18 07:04 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: Linux Debian 9 - x64

Unable to locate package dotnet-sdk-2.2

**Comment by dagood** [comment] 2019-06-20 14:22
I'm tentatively closing this as a duplicate of https://github.com/dotnet/core/issues/2874, because it seems to be the same error and the other issue has slightly more detail.

**Comment by dagood** [comment] 2019-06-20 14:23
Duplicate of #2874

**Closed by dagood** 2019-06-20 14:22 UTC
