### ISSUE TITLE
i need solution

### ISSUE THREAD

**Issue by Nelsonh123** [dotnet/core#3991] opened 2019-12-13 10:25 UTC
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
'dotnet' is not recognized as an internal or external command error
64bit operationg system

**Comment by scalablecory** [comment] 2019-12-19 10:10
Did you restart your console window after installing?

**Comment by Nelsonh123** [comment] 2019-12-19 10:33
No, I didn't.

**Comment by carlossanlop** [comment] 2020-02-21 21:22
This is a common question and the root cause is usually the same: the cmd window must be opened after installing dotnet.
Closing as resolved.

**Closed by carlossanlop** 2020-02-21 21:22 UTC
