### ISSUE TITLE
Ubuntu 18.04 having trouble getting packages.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/core#4180] opened 2020-01-24 23:58 UTC
Our CI/CD machine routinely fails when new .net core packages are pushed with:

```
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages  Writing more data than expected (490390 > 488334)
```

This brings CI to a complete standstill due to this mismatch.  This can happen for several hours at a time, during prime working hours.

**Comment by dagood** [comment] 2020-01-25 00:30
We're tracking the current active issue with Ubuntu 18.04 at https://github.com/dotnet/core/issues/4179, and the ongoing troubles (it looks like this issue is about that) with https://github.com/dotnet/core/issues/4167.

I'm curious if you happen to have some extra data (e.g. downtime windows) you've seen, especially if it's not reported in this repo. Our team has no impression at all that the current uptime is acceptable, but more info is always better.

**Comment by CyrusNajmabadi** [comment] 2020-01-25 01:22
> I'm curious if you happen to have some extra data (e.g. downtime windows) you've seen

What data do you need?  We've def run into this multiple times in the past, and the impact has been on the order of hours.  As this impacts CI/CD, we effectively are completely blocked in terms of being able to test/deploy anything.

**Comment by CyrusNajmabadi** [comment] 2020-01-25 01:22
It's also really unpleasant that this is done on a friday as this may mean nothing can get done until monday.

**Comment by dagood** [comment] 2020-01-25 03:52
I was wondering if this might be underreported. However, the problem right now isn't that someone thinks we don't have enough justification--we have more fundamental problems working with the team providing the service. I can't think of any specific data that will help right now.

About timing... yeah, this is nasty. Even worse because the responsible team has no public presence--someone on .NET Core has to see reports in this repo and forward them on. The linux repo problems can happen any time any team pushes any new Deb/RPM package, so it's very unpredictable.

**Comment by dagood** [comment] 2020-01-29 16:25
Closing as a duplicate of the resolved point-in-time issue, https://github.com/dotnet/core/issues/4179, and the active issue tracking the ongoing effort, https://github.com/dotnet/core/issues/4167. (Lee just posted a quick update there.)

**Closed by dagood** 2020-01-29 16:25 UTC
