### ISSUE TITLE
DateOnly and TimeOnly not working with SQLServer.

### ISSUE THREAD

**Issue by musictopia2** [dotnet/core#6956] opened 2021-11-22 17:53 UTC
There is a major problem with the new DateOnly and TimeOnly types.   If I try to use them with SQL Server, it gives an error.  The error says "Failed to convert parameter value from a DateOnly to a DateTime.
 ---> System.InvalidCastException: Object must implement IConvertible."

Would be really disappointing if the new types only work if you are not storing them in a database.  I was not even using entity framework core.  I was using from dapper.  There was dapper bugs.  However, I made a copy of their source code and made their changes.  After that, the error shows up in the underlying sql server stuff.

**Comment by scalablecory** [comment] 2021-11-22 18:35
Can you provide the code your using to access SQL Server?

CC @dotnet/sqlclientadmins @dotnet/sqlclientdevteam

**Comment by musictopia2** [comment] 2021-11-22 18:39
I transferred the dapper code.  then i made the changes on the dapper side.  after that, then the problem happened with the sql server's provider.

**Comment by DavoudEshtehari** [comment] 2021-11-22 19:57
We already don't support these two new types in [Microsoft.Data.SqlClient](https://github.com/dotnet/SqlClient). You can join in the discussion at [issue #1009](https://github.com/dotnet/SqlClient/issues/1009) for further updates.

**Comment by scalablecory** [comment] 2021-11-22 20:17
Thanks Davoud! Closing as duplicate of https://github.com/dotnet/SqlClient/issues/1009

**Closed by scalablecory** 2021-11-22 20:17 UTC
