### ISSUE TITLE
Can't install PowerShell on Ubuntu 20.04

### ISSUE THREAD

**Issue by superbonaci** [dotnet/core#4664] opened 2020-05-10 13:29 UTC
PowerShell depends on this project to work on Ubuntu 20.04:
Issue: https://github.com/PowerShell/PowerShell/issues/12594

**Comment by svick** [comment] 2020-05-10 13:36
This is a duplicate of https://github.com/dotnet/core/issues/4360. The official packages for Ubuntu 20.04 should be released on 12 May.

**Comment by superbonaci** [comment] 2020-05-10 16:16
Thanks

**Comment by mairaw** [comment] 2020-05-14 01:09
Duplicate of #4360

**Comment by mairaw** [comment] 2020-05-14 01:10
Docs updates are in progress. You can see a draft at https://github.com/dotnet/docs/pull/18160/files

**Closed by mairaw** 2020-05-14 01:09 UTC
Labels: duplicate
