### ISSUE TITLE
why asp.net core .cshtml's file encoding format  is not uft-8 encoded ，but ansi encoded？

### ISSUE THREAD

**Issue by weiwangda2014** [dotnet/core#607] opened 2017-04-29 18:21 UTC
in visual studio 2017，why asp.net core .cshtml's  file encoding format  is not uft-8 encoded ，but ansi encoded？

How to solve this problem。

**Comment by ojoadeolagabriel** [comment] 2017-04-30 06:25
Who cares about. Net core? Waste of space

**Comment by Petermarcu** [comment] 2017-05-15 18:54
@barrytang , can you take a look?

**Comment by barrytang** [comment] 2017-05-17 02:07
/cc @mlorbetske and @phenning 

Hi @weiwangda2014, do you mean when adding a file to the project via VS Add New Item dialog?

**Comment by weiwangda2014** [comment] 2017-06-02 08:44
@barrytang yes.

**Comment by WeihanLi** [comment] 2017-06-02 09:20
I also met this problem,when I add a view via visual studio 2017,the file's encoding is not utf-8 as before

**Comment by barrytang** [comment] 2017-06-02 23:53
@mlorbetske?

**Comment by mlorbetske** [comment] 2017-06-04 08:11
I've just tried this out by adding all the different things (via add new item from the project context menu) that produce cshtml files in VS2017.3's upcoming preview and am seeing that they're producing files encoded as UTF-8 with BOM. @weiwangda2014, could you post the exact steps you're using when you're seeing this to make sure that I've verified that the case you're hitting is working correctly in that release please? /cc @phenning 

@WeihanLi for the add view flow, this should have been fixed with https://github.com/aspnet/Scaffolding/pull/293. /cc @prafullbhosale 

Are either of your projects using an `.editorconfig` file that indicates that file encoding should be UTF-8 without BOM?

**Comment by WeihanLi** [comment] 2017-06-04 12:53
I do not have an `.editorconfig` file with my project

**Comment by taadis** [comment] 2017-06-05 07:15
我也遇到了这个问题,在 Visual Studio 2017 中[右键菜单] -> 直接添加的`.cshtml & controller.cs & class.cs `文件都会出现一样问题.

但是在[右键菜单] -> [新建项] -> [添加文件]就是正常的.我目前是都到*新建项*中添加需要的文件.

**Comment by weiwangda2014** [comment] 2017-06-24 12:14
@WeihanLi we are same problem.i have no time that i am busy.  you can show detail problem to them.

**Comment by richlander** [comment] 2017-07-03 21:33
Can one of you provide specific instructions? I read that the team is stuck moving forward without them.

@weiwangda2014  @taadis  @WeihanLi

**Comment by WeihanLi** [comment] 2017-07-04 01:56
Sorry for not replying in time @richlander . The problem is as follows: 
There's a option named `[add] --> [add view]`  in ` views`  folder's context menu,I added a view this way and typed in some Chinese characters, and when I reopen the view just created,there's a encoding problem. 
Just as follows:
![encoding_problem](https://user-images.githubusercontent.com/7604648/27812084-c04a4734-609e-11e7-9b31-a79204475855.png)

**Comment by mlorbetske** [comment] 2017-07-04 03:27
Based on the information from @WeihanLi, I'll move this to the scaffolding repo.

**Comment by mlorbetske** [comment] 2017-07-04 03:27
This issue was moved to aspnet/Scaffolding#539

**Closed by mlorbetske** 2017-07-04 03:27 UTC

**Comment by richlander** [comment] 2017-07-04 03:30
Thanks @mlorbetske!
