### ISSUE TITLE
dotnet core web api exception handling - unhandled exceptions

### ISSUE THREAD

**Issue by gitfortee** [dotnet/core#1338] opened 2018-03-12 19:44 UTC
The Main method in Program.cs in my dotnet core web api project has the following code.

```
public static void Main(string[] args)
{
    var logger = LogManager.LoadConfiguration("nlog.config").GetCurrentClassLogger();
    try
    {
        BuildWebHost(args).Run();
    }
    catch (Exception ex)
    {
        //NLog: catch setup errors
        logger.Error(ex, "An exception occurred during application start.");
        throw;
    }
}  
```
I also setup an exception handling middleware like this:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseResponseCompression();
    app.UseMiddleware(typeof(HandleExceptionMiddleware));
    app.UseMvc();
}
```
Should i also add a `AppDomain.CurrentDomain.UnhandledException` ? to the `Main` method - since dotnet core web api is a console application?. Do I loose/gain any chances of trapping exceptions without this?

**Comment by Tratcher** [comment] 2018-03-12 21:36
Duplicate of https://github.com/aspnet/Home/issues/2950.

**Closed** 2018-03-12 23:14 UTC
