### ISSUE TITLE
.net my app not recognized 

### ISSUE THREAD

**Issue by kushalsharma1818** [dotnet/core#4432] opened 2020-03-21 13:48 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by GrabYourPitchforks** [comment] 2020-03-21 20:26
Duplicate of https://github.com/dotnet/core/issues/4431.

**Closed by GrabYourPitchforks** 2020-03-21 20:26 UTC
