### ISSUE TITLE
[.NET Tutorial]: Any installed dotnet tool crashes

### ISSUE THREAD

**Issue by vadi2** [dotnet/core#7776] opened 2022-09-05 09:28 UTC
### URL

https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools

### Operating system

Linux

### More information about your system

Running Linux on my Intel Chromebook:

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
```

### Description

Running _any_ installed dotnet tool crashes:

```
vadi@penguin:/tmp$ dotnet tool install -g dotnetsay
You can invoke the tool using the following command: dotnetsay
Tool 'dotnetsay' (version '2.1.7') was successfully installed.
vadi@penguin:/tmp$ dotnetsay 
Segmentation fault (core dumped)
```

### dotnet --info

```
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /snap/dotnet-sdk/177/sdk/6.0.400/

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.400 [/snap/dotnet-sdk/177/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/snap/dotnet-sdk/177/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [/snap/dotnet-sdk/177/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by rzikm** [comment] 2022-09-05 10:46
It may have something to do with snap, would you mind trying again with the official debian package? See installation steps here https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian#debian-11-

**Comment by vadi2** [comment] 2022-09-05 11:07
That was it! Looks like the snap setup is broken.

**Comment by rzikm** [comment] 2022-09-07 12:41
The snap packages have been always broken with global tools. Closing as duplicate of https://github.com/dotnet/runtime/issues/60441

**Closed by rzikm** 2022-09-07 12:41 UTC
Labels: area-setup

**Comment by omajid** [comment] 2022-09-07 13:28
Should we document that at https://docs.microsoft.com/en-us/dotnet/core/install/linux-snap ? It says "Snaps are a great alternative to the package manager built into your Linux distribution" and there's no warning there about dotnet global tools not working.

**Comment by rzikm** [comment] 2022-09-07 13:53
I added a mention in https://github.com/dotnet/docs/pull/31045

**Comment by leecow** [comment] 2023-06-09 22:17
Resolved by https://github.com/dotnet/installer/pull/16641 though an additional step is needed as `dotnetsay` (and possible other global tools) don't find the snap install of dotnet. Once I symlinked the snap dotnet-sdk directroy to where the tool expected, this worked fine on a test Fedora 38 install with .NET 7. 

`sudo ln -s /var/lib/snapd/snap/dotnet-sdk/current dotnet`
