### ISSUE TITLE
C:\Program Files\dotnet\sdk\2.2.104\NuGet.targets(499,5): error : Unable to obtain lock file access on 'C:\Windows\TEMP\NuGetScratch\lock'

### ISSUE THREAD

**Issue by dineshpandiyan** [dotnet/core#2417] opened 2019-03-10 07:03 UTC
C:\Program Files\dotnet\sdk\2.2.104\NuGet.targets(499,5): error : Unable to obtain lock file access on 'C:\Windows\TEMP\NuGetScratch\lock'
for operations on 'C:\Users\Home\AppData\Roaming\NuGet\NuGet.Config'. This may mean that a different user or administator is holding this lock and that this process does not have permission to access it. If no other process is currently performing an operation on this file it may mean that an earlier NuGet process crashed and left an inaccessible lock file, in this case removing the file 'C:\Windows\TEMP\NuGetScratch\lock' will allow NuGet to continue. [C:\Users\Home\Desktop\muruga\myApp\myApp.csproj]

Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'

**Comment by dineshpandiyan** [comment] 2019-03-10 07:04
Kindly help me on this pls...

**Comment by karelz** [comment] 2019-03-19 01:25
Did you try to delete the file manually? Looks like some weird OS hiccup?
Are you able to reproduce it on another machine/VM?

**Comment by karelz** [comment] 2019-03-30 18:09
No additional info, not actionable, closing. Feel free to reopen if there is more info.

**Closed by karelz** 2019-03-30 18:09 UTC
Labels: needs more info
