### ISSUE TITLE
Cannot find compilation library location for package 'Microsoft.NETCore.App'

### ISSUE THREAD

**Issue by nefcanto** [dotnet/core#1725] opened 2018-06-25 11:11 UTC
I've upgraded from .NET Core 2.0 to 2.1.1.

I built my project and now I'm getting this error:

> Cannot find compilation library location for package 'Microsoft.NETCore.App'

I don't know what other information should I provide. Please guide me in providing more info on this issue.

It's such a frustrating experience. Upgrading backward compatible version in [Semantic Versioning ](https://semver.org/)shouldn't break things. I wish you had versioned this release as .NET Core 3.0, so that we wouldn't upgrade. Any help?

**Comment by leecow** [comment] 2018-06-25 17:15
@nefcanto , can you include output from `dotnet --info` so we can see a bit of your environment?

@dsplaisted

**Comment by nefcanto** [comment] 2018-06-25 17:28
Yeah, sure.

![capture2](https://user-images.githubusercontent.com/12782347/41865620-e4657ef8-78c2-11e8-9e5a-d0bca1c3c2e0.PNG)

**Comment by dsplaisted** [comment] 2018-06-25 19:01
@nefcanto It looks like there may be something wrong with your .NET Core SDK installation.  Instead of the error message at the beginning of the output of `dotnet --info`, you should be seeing something like this:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.301\
```

Do you have this file on your machine? `C:\Program Files\dotnet\sdk\2.1.301\runtimes\win\lib\netcoreapp2.0\System.Text.Encoding.CodePages.dll`

Can you try repairing (or uninstalling and then reinstalling) the 2.1.301 .NET Core SDK?

Thanks

**Comment by nefcanto** [comment] 2018-06-26 09:09
I uninstalled all runtimes and SDKs installed on my machine from previous versions and including the current version. And then reinstalled the SDK. Here is a screenshot of the SDK:

![capture2](https://user-images.githubusercontent.com/12782347/41901454-2e091a64-7946-11e8-9b2b-8762c75e8c15.PNG)

But the problem is that now I can't build my applications. It complains that:

> MSB4236	The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.

**Comment by nefcanto** [comment] 2018-06-26 09:22
Well I restarted my PC, and now project is built. But again back to the original problem, I see:

> Cannot find compilation library location for package 'Microsoft.NETCore.App'

**Comment by dsplaisted** [comment] 2018-06-26 17:48
OK, sorry this is still not working for you.

Do you get the failure if you create a new project from a template?

Can you enable more detailed output to provide more details about the failure?

Can you share a binary log of your build?  You can create a binary log by building with the `-bl` parameter, it will then create a file called msbuild.binlog.  That file is very useful for debugging build issues, however note that it includes very detailed information about your build (including the contents of your project files, your environment variables, and the inputs and outputs of all the targets and tasks that were run), so depending on your project you may not be able to share all that information.  You can download a viewer for the .binlog files at http://msbuildlog.com/ if you would like to look at what's in them yourself.

**Comment by joshfree** [comment] 2018-07-24 16:46
Thanks for posting your solution @nefcanto.

@dsplaisted @leecow do we need to update any docs / FAQs for this?  Is this issue safe to close now?

**Comment by dsplaisted** [comment] 2018-07-24 18:43
Unfortunately it's still no clear what the root cause was here.  So I wouldn't update docs unless we understand what's going on.  But since @nefcanto was able to get things working, I think we can close the issue.

**Closed by dsplaisted** 2018-07-24 18:43 UTC

**Comment by kaansengul** [comment] 2018-07-27 14:02
I also encountered the same problem when I first migrated from 2.0 to 2.1.

Be sure you checked the "Publish > Settings > File Publish Options > Remove additional files at destination" option (if you publishing manually). I think some files is breaking the whole application.

Now same problem happens when I publish a single *.cshtml file even I've tried the csproj editions.

**Comment by kubaizi** [comment] 2018-09-06 10:29
@kaansengul you are right, Remove additional files at destination will fix the problem but you will lose WebJobs

**Comment by vankampenp** [comment] 2018-10-15 23:01
You do not need to change the publish options, just once removing all dll's, service references, and runtimes manually is enough. You can keep configuration files, wwwroot, etc. Then publish again. Apparently there is an old 2.0 dll which needs to be manually removed.

**Comment by mjharper84** [comment] 2018-11-23 14:19
I got this issue when publishing a single razor file (layout) I won't make that mistake again! Remove additional files at destination fixed it for me

**Comment by chillfire** [comment] 2018-11-26 11:11
Hi, I am having the same issue.

dotnet --info shows me:

```
.NET Core SDKs installed: 2.1.4 to 2.1.500
.NET Core runtimes installed: 
 Microsoft.AspNetCore.All: 2.1.2 to 2.1.6
 Microsoft.AspNetCore.App 2.1.2 to 2.1.6
 Microsoft.NETCore.App 2.0.5 to 2.1.6
```

In csproj:
```
    <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
    <MvcRazorPrecompile >true</MvcRazorPrecompile>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <RuntimeFrameworkVersion>2.1.6</RuntimeFrameworkVersion>
```

I can run the project perfectly from vstudio, however when I use dotnet publish (locally) and then run it from the "publish" folder I get:

 _The view 'Index' was not found. Searched locations: /Views/Home/Index.cshtml, /Views/Shared/Index.cshtml, /Pages/Shared/Index.cshtml_

There is a xxxxx.PrecompiledViews.dll file in the publish folder and when I JustDecompile the views dll:
![image](https://user-images.githubusercontent.com/892155/49006606-5d0c2980-f161-11e8-96d5-a4b76f6f6659.png)

And the main dll I see:
![image](https://user-images.githubusercontent.com/892155/49006884-02bf9880-f162-11e8-99d2-55b992cc1fc8.png)

So as far as I can work out all of the files are embedded correctly and they work when running from IISExpress, jut not when run as a published app. I have published to azure and get the same error in the azure logging console so I have missed something somewhere along the way.

**Comment by vankampenp** [comment] 2018-11-26 15:52
@chillfire that looks like a different type of issue.

**Comment by jjxtra** [comment] 2019-06-10 21:53
I'm getting this error from self contained Windows application on machines without .NET core installed. Any ideas?

**Comment by DMW007** [comment] 2019-10-03 19:50
I had this issue on an ASP.NET Core MVC 2.1 application when publishing and deploying to Docker using the default 2.1 tag (Debian based). Problem was fixed by adding the following to my csproj file: 

    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>

However, it's not really clear to me yet why this issue occurs. Similar other MVC 2.1 projects doesn't require this directive, even they run in the same Docker environment.

**Comment by valdisiljuconoks** [comment] 2020-09-10 18:58
> I had this issue on an ASP.NET Core MVC 2.1 application when publishing and deploying to Docker using the default 2.1 tag (Debian based). Problem was fixed by adding the following to my csproj file:
> 
> ```
> <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
> ```
> 
> However, it's not really clear to me yet why this issue occurs. Similar other MVC 2.1 projects doesn't require this directive, even they run in the same Docker environment.

yeah! this solved problem in our case! thx

**Comment by xantari** [comment] 2021-11-16 00:24
None of the resolutions here solved this issue for me when upgrading from .NET Core 5 web app to .NET Core 6. Only happens if you run the app in IIS mode, and works just fine in Kestrel mode. No idea what the fix is... May be a .NET Core 6 issue, but not sure.

**Comment by onlinemxu** [comment] 2021-11-19 23:37
Same here after upgrade from NET 5 to 6 running IIS Host mode

**Comment by xantari** [comment] 2021-11-20 00:15
@onlinemxu Can you see if all your packages got upgrade to the .NET 6 equivalents? The one that didn't upgrade automatically (still not sure why the nuget upgrade didn't work) was Microsoft.VisualStudio.Web.CodeGeneration.Design, Try remove that package completely from your project (you may need to edit the .csproj manually) and see if that fixes it.
