### ISSUE TITLE
Apt-Update and packages.microsoft.com, Clearsigned

### ISSUE THREAD

**Issue by indraneeldey1** [dotnet/core#3607] opened 2019-10-11 17:28 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/debian9/runtime-current
Operating System: Linux Debian 9 - x64

When doing an apt-update found the following issue

E: Failed to fetch https://packages.microsoft.com/repos/microsoft-debian-stretch-prod/dists/stretch/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: Some index files failed to download. They have been ignored, or old ones used instead.

This is occurring with any apt get function from packages.microsoft.com

**Comment by dagood** [comment] 2019-10-11 18:26
Duplicate of https://github.com/dotnet/core/issues/3598

**Closed by dagood** 2019-10-11 18:26 UTC
