### ISSUE TITLE
Dependency Injection UnitOfWork Pattern In Asp.Net Core

### ISSUE THREAD

**Issue by MurtuzaTravadi** [dotnet/core#660] opened 2017-05-17 10:06 UTC
I have created code Repository + unitofwork way pattern In .NetCore & i am getting this exception 

> InvalidOperationException: Unable to resolve service for type 'AirlineManagement.Repository.UnitOfWork' while attempting to activate 'AirlineManagement.Controllers.StudentsController'.

In Startup.cs File I have write this code

```
 public void ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddApplicationInsightsTelemetry(Configuration);
            services.AddDbContext<AirlineContext>(options =>
                        options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
            services.AddEntityFramework(Configuration.GetConnectionString("DefaultConnection"));
            services.AddTransient<IAirlineRepository, AirlineRepository>();
            services.AddTransient<IUnitOfWork, UnitOfWork>();
            services.AddMvc();
           }
```

After tha in my UnitOfWork.cs File I have write this code

```
 public partial class UnitOfWork : IUnitOfWork
    {
        // public IAirlineRepository AirlineRepository => new AirlineRepository();
        private AirlineContext context;
        private AirlineRepository _airlineRepository;
        private AirportRepository _airportRepository;

        public UnitOfWork(AirlineContext context)
        {
            this.context = context ?? throw new ArgumentNullException("Context was not supplied");
        }

        public IAirlineRepository AirlineRepository
        {
            get
            {
                if (_airlineRepository == null)
                {
                    _airlineRepository = new AirlineRepository(context);
                }

                return _airlineRepository;
            }
        }
}
```

In IUnitOfWork.cs

```
public interface IUnitOfWork : IDisposable
    {
        IAirlineRepository AirlineRepository { get; }
        IAirportRepository AirportRepository { get; }

        int SaveChanges();
    }
```

In my RepositoryFile I have created baserepository 
```

 public class AirportRepository : BaseRepository<Airport>, IAirportRepository
    {
        public AirportRepository(AirlineContext context)
        {
            this.context = context;
        }
}
```

And In my StudentController.cs 

 ```
public class StudentsController : Controller
    {
        private IUnitOfWork _unitofWork;
        public StudentsController(UnitOfWork unitOfWork)
        {
            _unitofWork = unitOfWork;
        }

        // GET: Students
        public ActionResult Index()
        {
            var abc = _unitofWork.AirlineRepository.GetAll();
            return View(abc);
        }
}
```

You can Follow this link to refer CodeExample

https://github.com/MurtuzaTravadi/DotNetCoreRepositoryPattern

and I have just Implemented UnitOfWork Concept in above code And I am getting That Exception

Please Help me out

--Note--
all nuget package is updated

**Comment by MurtuzaTravadi** [comment] 2017-05-17 13:25
Any Please Help me out

@shanselman @AArnott @anurse @AustinWise @devhawk

**Comment by anurse** [comment] 2017-05-17 13:52
The problem is that you're registering a services associated with `IUnitOfWork` here:

```csharp
            services.AddTransient<IUnitOfWork, UnitOfWork>();
```

But then in your controller you're requesting a `UnitOfWork` here:

```csharp
       public StudentsController(UnitOfWork unitOfWork)
       {
           _unitofWork = unitOfWork;
       }
```

If you change `StudentsController` to accept `IUnitOfWork` your error should go away.

Closing, since this isn't a bug in .NET Core and the answer should resolve the problem. If you have further questions or issues about ASP.NET Core or Dependency Injection, I suggest posting issues in http://github.com/aspnet/Home or on [StackOverflow](https://stackoverflow.com/), as you're more likely to find people familiar with ASP.NET Core in those forums.

Hope that helps!

**Closed by anurse** 2017-05-17 13:52 UTC

**Comment by MurtuzaTravadi** [comment] 2017-05-17 13:58
Thank for quick replay @anurse  but i cant change `StudentsController` to `IUnitOfWork` 
how can i change my controller ctor to Class name 
can you please Follow this link (https://github.com/MurtuzaTravadi/DotNetCoreRepositoryPattern)  and guide me to how can i add UnitOfWork concept 

Thank you

**Comment by MurtuzaTravadi** [comment] 2017-05-29 07:01
Its simple solution thanks to @glennc i just replace this part 

```
 private IUnitOfWork _unitofWork;


        public StudentsController(IUnitOfWork unitOfWork)
        {
            _unitofWork = unitOfWork;
        }
```
