### ISSUE TITLE
exited with error code 1 watch : Waiting for a file to change...

### ISSUE THREAD

**Issue by paskes718** [dotnet/core#6655] opened 2021-09-03 18:27 UTC
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by mairaw** [comment] 2021-09-03 19:05
Duplicate of #6656

**Closed by mairaw** 2021-09-03 19:05 UTC
Labels: duplicate
