### ISSUE TITLE
Latest ILLink.Task is failing for osx-x64 Runtime Identifier

### ISSUE THREAD

**Issue by sidravi** [dotnet/core#2112] opened 2018-12-05 23:27 UTC
When I do `dotnet publish -c release -r osx-x64` after adding ILLink.Tasks nuget package version 0.1.5-preview-1841731, it fails with the following error: 
`C:\Program Files\dotnet\sdk\2.1.500\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(72,5): error NETSDK1016: Unable to find resolved path for '...\.nuget\packages\runtime.osx-x64.microsoft.netcore.app\2.1.6\runtimes\osx-x64\native\..\..\..\tools\crossgen.exe'. [....csproj]`

Looks like its searching for `crossgen.exe` for Mac version, instead of `crossgen`.

I tried using older versions (0.14 preview) and it failed with error `The "GetRuntimeLibraries" task failed unexpectedly.` I believe this is the same issue discussed in #308  which I think is resolved in later versions.

**Comment by karelz** [comment] 2018-12-18 21:49
@sbomer @jeffschwMSFT can you please help route the issue?

**Comment by GTANAdam** [comment] 2018-12-23 21:41
Duplicate of https://github.com/mono/linker/issues/405#issue-384591824
Additionally, this affects linux and windows as well as mentioned here: https://github.com/mono/linker/issues/405#issuecomment-449644906

**Closed as completed** 2018-12-26 03:23 UTC

**Comment by sidravi** [comment] 2019-01-17 00:35
Sorry for the dup.

Any update on when this will get resolved?

Also, are there any plan on releasing an official version of ILLink.Tasks nuget package? The current nuget package is a preview version only.

**Comment by karelz** [comment] 2019-01-17 01:52
@sidravi the other repo would be a good place to ask these questions ;)
