### ISSUE TITLE
issue when installing the SDK

### ISSUE THREAD

**Issue by abuarqowa** [dotnet/core#6951] opened 2021-11-21 17:12 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install
Operating System: macos

when run the code $dotnet i ot the message "zsh: command not found: dotnet" in the terminal even though i opened  new terminal
<img width="504" alt="Screen Shot 2021-11-21 at 8 10 24 PM" src="https://user-images.githubusercontent.com/94798394/142772021-1b1c7caf-9b0b-44f5-a2e6-f7265e5fb9e2.png">
.

**Comment by eiriktsarpalis** [comment] 2021-11-22 15:46
Seems like a dupe of #6953. Please consider contributing to the conversation there.

**Closed by eiriktsarpalis** 2021-11-22 15:46 UTC
