### ISSUE TITLE
Update RHEL8 install guide noting 3.0 will be available starting in 8.1

### ISSUE THREAD

**Issue by jatin-cbs** [dotnet/core#3585] opened 2019-10-09 18:21 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/rhel8/sdk-current
Operating System: Linux RHEL 8 - x64

The instructions are wrong as there is no dotnet 3.0 in the repository of RHEL 8 there is dotnet-sdk-2.1.x86_64 and dotnet-sdk-2.1.5xx.x86_64  only these two versions in RHEL 8 repository please check..

**Comment by RheaAyase** [comment] 2019-10-10 19:27
Duplicate of #3491

**Comment by RheaAyase** [comment] 2019-10-10 19:28
If anything the documentation on the download page needs clarifying?

**Comment by carlossanlop** [comment] 2019-10-30 23:59
@leecow is this your area of expertise?

**Comment by leecow** [comment] 2019-10-31 19:27
Will get the site fixed up.

**Comment by mairaw** [comment] 2020-05-14 01:31
Can this be closed @leecow?

**Comment by RheaAyase** [comment] 2020-05-14 08:19
This topic in regards to .NET 5 should be discussed...

**Comment by mairaw** [comment] 2021-08-05 22:53
Is this still an issue for .NET 5 or can this be closed? /cc @adegeo

**Comment by adegeo** [comment] 2021-08-06 15:06
I think this can be closed.

**Closed by adegeo** 2021-08-06 15:06 UTC
Labels: needs-more-info, area-tutorials
