### ISSUE TITLE
404-Not Found when downloading  .NET SDK

### ISSUE THREAD

**Issue by sat1591** [dotnet/core#6502] opened 2021-07-25 07:12 UTC
Problem encountered on https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/install
Operating System: windows

I am not able to download .NET SDK file from URL path. Error was 404-Not Found
![image](https://user-images.githubusercontent.com/64651715/126890900-e0be6ea2-34ff-4941-88ad-c39cc28a078d.png)
![image](https://user-images.githubusercontent.com/64651715/126890918-8234929c-e307-4495-90fe-4361ffaabdf6.png)

**Comment by mairaw** [comment] 2021-07-25 07:25
Hi @sat1591, our apologies for the incovenience. I'll close this as a duplicate of #6496. There's a team of engineers investigating the issue.

**Closed by mairaw** 2021-07-25 07:25 UTC
Labels: duplicate
