### ISSUE TITLE
Fail for install dotnet-sdk-2.2 on Linux Mint 19.1

### ISSUE THREAD

**Issue by gilsao** [dotnet/core#2885] opened 2019-06-16 03:04 UTC
Problem encountered on https://dotnet.microsoft.com/download/linux-package-manager/ubuntu19-04/sdk-current
Operating System: Linux Ubuntu 19.04 - x64

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Problem below:

sudo apt-get install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.2 : Depends: aspnetcore-runtime-2.2 (>= 2.2.5) but it is not going to be installed
                  Depends: dotnet-runtime-2.2 (>= 2.2.5) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Help me please.

**Comment by dagood** [comment] 2019-06-20 14:29
You're using the Ubuntu 19.04 instructions, but actually the Ubuntu 18.04 instructions are more likely to work on Linux Mint 19.1. We don't have dropdown entries for some distros and there's no easy way to figure this out on your own, sorry about that. Someone else hit this problem earlier at https://github.com/dotnet/core/issues/2836.

(https://github.com/dotnet/core/issues/2576 is tracking making this clearer somehow.)

**Comment by dagood** [comment] 2019-06-20 14:29
Duplicate of https://github.com/dotnet/core/issues/2836

**Closed by dagood** 2019-06-20 14:29 UTC
