### ISSUE TITLE
Feature Request - Porting Microsoft SQL Server Type dll to .net core

### ISSUE THREAD

**Issue by nishant-newton** [dotnet/core#2273] opened 2019-01-31 05:51 UTC
Want to check whether MS has any plan to port Microsoft.SQLServer.Types library to .net core.

I could not see any plan for this library to be made available for .net core.

With the inbuilt support for Geo processing this is a very useful library but unfortunately can not be used in .net core / standard?

**Comment by karelz** [comment] 2019-01-31 07:17
@divega can you please comment or route?

**Comment by divega** [comment] 2019-01-31 21:54
@nishant-newton Microsoft.SqlServer.Types is part of the SQL Server product. We have talked to SQL Server team about adding support for .NET Core but there isn't a concrete plan we can share at the moment. 

In the meantime, for spatial data, we have implemented compatibility with other types that exist in .NET Core, called NetTopologySuite. In the comment at https://github.com/dotnet/corefx/issues/12034#issuecomment-436732668 explains how we are using that library in EF Core 2.2, but the types and the ability to serialize and deserialize geography and geometry columns from SQL Server is available at the ADO.NET layer using [NetTopologySuite.IO.SqlServerBytes](https://github.com/NetTopologySuite/NetTopologySuite.IO.SqlServerBytes). 

Also @dotmorten has created a version of Microsoft.SqlServer.Types. the library for .NET Core, but my understanding is that it does not implement spatial calculations. 

There are also a few challenges to make Microsoft.SQLServer.Types available to .NET Core:

- Microsoft.SqlServer.Types.dll is SQL Server version-specific
- At least part of the code is written in C++

@karelz This issue can be considered a duplicate of https://github.com/dotnet/corefx/issues/31775. However it is not directly actionable by the .NET team, but by an internal partner. What do you think would be the best place to keep this open as a feature request?

**Comment by karelz** [comment] 2019-01-31 22:01
Duplicate of https://github.com/dotnet/corefx/issues/31775

**Comment by karelz** [comment] 2019-01-31 22:01
Closed as dupe. If the CoreFX issue is in wrong place, let's move it to the right place, or at least mark it as "external".

**Closed by karelz** 2019-01-31 22:01 UTC
