### ISSUE TITLE
.NET download links in releases.json files are broken

### ISSUE THREAD

**Issue by bishal-pdMSFT** [dotnet/core#6508] opened 2021-07-26 18:37 UTC
### Description
.NET SDK and runtime download links mentioned in [releases.json](https://github.com/dotnet/core/blob/main/release-notes/releases-index.json) are not working. For example: https://github.com/dotnet/core/blob/main/release-notes/releases-index.json fails with 404 error.
This is causing azure pipelines tasks to fail as it takes dependency on this file.

cc @leecow 

### Regression?

Yes

**Comment by bishal-pdMSFT** [comment] 2021-07-26 18:39
The **http** url seems to work fine: http://download.visualstudio.microsoft.com/download/pr/c7afc344-acf0-4a6c-8e53-4455f2bcfc85/321418f6300e475f6c5d52849efa2e2e/dotnet-sdk-3.1.411-linux-x64.tar.gz works

**Comment by mairaw** [comment] 2021-07-26 18:41
We're investigating some 404 issues. I think it depends where the pipeline is configured. Some folks are also having trouble the link directly. This seems like a duplicate of #6496.

**Comment by bishal-pdMSFT** [comment] 2021-07-26 18:50
I was wrong about http working fine. Even https works fine intermittently. So indeed looks like an issue with CDN servers.

@mairaw is there an ETA on this issue? This may potentially start impacting azure pipelines for large number of customers.

**Comment by adrianwyatt** [comment] 2021-07-26 20:39
Dupe: https://github.com/microsoft/azure-pipelines-tasks/issues/15086

**Comment by mairaw** [comment] 2021-07-26 21:07
I'll close this one then since we have at least two issues covering the same problem and the team is aware of this. Didn't get an ETA from this yet.

**Closed by mairaw** 2021-07-26 21:07 UTC
Labels: duplicate
