### ISSUE TITLE
Issues Creating an app .NET Core

### ISSUE THREAD

**Issue by ZephyrDogma** [dotnet/core#6020] opened 2021-03-04 18:24 UTC
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![image](https://user-images.githubusercontent.com/77338971/110010744-8b9ce580-7d16-11eb-91ba-93af513d894f.png)
And when i create a new project in Visual Studio Community 2019 i get this issue:
![image](https://user-images.githubusercontent.com/77338971/110010850-a5d6c380-7d16-11eb-9b69-d7573338db7b.png)
As u can see i cant get it to recognize i have projects on
Heres another image:
![image](https://user-images.githubusercontent.com/77338971/110011038-e0406080-7d16-11eb-98e4-f6cdf0ff911c.png)
Why arent my SDK's installed??? I installed them already?? why arent they recognized???

Please as a Student i need help with this or I'll be left behind the others

**Comment by mairaw** [comment] 2021-03-04 19:31
Duplicate of #6019

**Closed by mairaw** 2021-03-04 19:31 UTC
