### ISSUE TITLE
Cannot resolve type/namespace conflict

### ISSUE THREAD

**Issue by ivaylo5ev** [dotnet/core#2033] opened 2018-10-31 10:56 UTC
# Cannot resolve type/namespace conflict

I have a C# class library project that uses the dotnet sdk and targets netstandard2.0
The project references two libraries : `Foo.dll` and `Foo.Bar.dll` , both targeting netstandard2.0 among other framework versions in their respective nuget packages.

- `Foo.dll` defines a public class `Bar` under the `Foo` namespace, thus we have `Foo.Bar, Foo` as the assembly-qualified name.
- `Foo.Bar.dll` defines an attribute type `BazAttribute` under the `Foo.Bar` namespace, with assembly-qualified name `Foo.Bar.BazAttribute, Foo.Bar`

In my class library project, I attempt to use the attribute:

```c#
namespace MyConsumerCode
{
    using Foo;
    using Foo.Bar;

    [BazAttribute]
    public class MyClass
    {
    }
}
```
The compiler does not recognize the `BazAttribute`, as the `Foo.Bar` namespace from the `Foo.Bar` dll is being shadowed by the `Foo.Bar` class from the `Foo.dll`

Below is a sample error message produced by the compiler when executing `dotnet build`:

> error CS0434: The namespace 'Foo.Bar' in 'Foo.Bar, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' conflicts with the type 'Bar' in 'Foo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' 
> error CS0616: 'Bar.BazAttribute' is not an attribute class

## Attempted Workarounds

I have unsuccessfully attempted workarounds such as aliasing:

```c#
namespace MyConsumerCode
{
    using Foo;
    using BazAttribute = Foo.Bar.BazAttribute;

    [BazAttribute]
    public class MyClass
}
```

Using `global::Foo.Bar.BazAttribute` does not help either.

In former .NET project types, it was possible to alias the entire reference for `Foo.Bar.dll` as `bar`, and then use it like:

`bar::Foo.Bar.BazAttribute`

I do not know if this type of aliasing is possible in the new SDK, if so, this could hopefilly fix my problem.

## Additional Information

The `Foo.dll` is written in C#. The `Foo.Bar.dll` is written in F#. 
I use paket for managing my nuget dependencies, although I do not feel that would be the problem. Maybe I am wrong?

## A Working Solition

Rewriting the code in F# does not exhibit the problem. Could it be the issue is with the C# compiler?

```f#
namespace MyConsumerCode
open Foo
open Foo.Bar

[<BazAttribute>]
type [<Sealed>] MyClass= class end
```

# General

OS: Windows 7 Professional 
IDE: Visual Studio 2017 Community, v15.8.4
Dotnet:
> $ dotnet --info
>.NET Core SDK (reflecting any global.json):
> Version:   2.1.402
> Commit:    3599f217f4
>
>
>
> Runtime Environment:
>   OS Name:     Windows
>   OS Version:  6.1.7601
>   OS Platform: Windows
>   RID:         win7-x64
>   Base Path:   C:\Program Files\dotnet\sdk\2.1.402\
> 
> Host (useful for support):
>   Version: 2.1.4
>   Commit:  85255dde3e
> 
> .NET Core SDKs installed:
>   1.0.4 [C:\Program Files\dotnet\sdk]
>   1.1.0 [C:\Program Files\dotnet\sdk]
>   1.1.7 [C:\Program Files\dotnet\sdk]
>   1.1.9 [C:\Program Files\dotnet\sdk]
>   1.1.10 [C:\Program Files\dotnet\sdk]
>   2.1.4 [C:\Program Files\dotnet\sdk]
>   2.1.201 [C:\Program Files\dotnet\sdk]
>   2.1.202 [C:\Program Files\dotnet\sdk]
>   2.1.400 [C:\Program Files\dotnet\sdk]
>   2.1.402 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by KathleenDollard** [comment] 2018-10-31 15:41
This is an error from the C# compiler. I believe it is expected behavior. 

Did you try this (no using)

```c#
[Foo.Bar.BazAttribute]
public class MyClass
```

**Comment by karelz** [comment] 2018-10-31 15:50
Argh, I mixed up namespace aliasing with assembly aliasing which happens over command line arguments to C#, sorry.

**Comment by karelz** [comment] 2018-10-31 15:51
Assuming this is purely C# compiler thing, I would expect the same result to be on .NET Framework and on .NET Core.
If you target netstandard20 or something else should not matter as soon as you have the same C# compiler version (which may be tricky).
Can you please confirm that @ivaylo5ev

**Comment by ivaylo5ev** [comment] 2018-10-31 16:06
@KathleenDollard -  yes, I tried using the fully-quallified name of the attribute type as well without success.

@karelz - I receive the error from building from visual studio as well, which may be using the .NET framework compiler. I have a question -- if I invoke the msbuild.exe process (from VS developer tools console, will it use the framework compiler even when the target framework is set to `netstandard2.0`? If yes, I could certainly do so and report the results here.

Also, I have used some dummy code samples in my issue report not to reveal details for my acutal project. I could create a git repo with a few demo projects where we could experiment with the problem, as the problematic case is trivial enough.

**Comment by karelz** [comment] 2018-10-31 16:34
Definitely create minimal repro. Create .NET Framework console app and try it there. Without .NET Standard. The less specialization, the better.
If it repros everywhere, then it is not .NET Core specific, but rather question for "How to do this in C#" and we can route it.

**Comment by ivaylo5ev** [comment] 2018-10-31 16:41
@karelz Thanks for the feedback. I will link to the repo project soon.

**Comment by ivaylo5ev** [comment] 2018-10-31 17:23
[Here](https://github.com/ivaylo5ev/csharp-namespace-resolution-issue) it is. The solution contains 3 projects - the two libraries with overlapping naming, that targetting `netsdandard2.0` and a console application targeting `netcoreapp2.1`.

**Comment by karelz** [comment] 2018-10-31 19:04
@ivaylo5ev are you able to reproduce it when targeting .NET Framework? (not .NET Core or .NET Standard involved)

**Comment by nguerrera** [comment] 2018-10-31 20:08
This would reproduce in a traditional project as well. It is behaving by design.

> In former .NET project types, it was possible to alias the entire reference for Foo.Bar.dll as bar, and then use it like:

You can do this in SDK-style projects as well. You need to set Aliases metadata on the ProjectReference. 

Here is a change to your repro that shows how to do that: https://github.com/nguerrera/csharp-namespace-resolution-issue/commit/571ae9db3d43b28e9d7b619a78eaf57076062a62

**Comment by karelz** [comment] 2018-10-31 21:41
Thanks @nguerrera a lot!
Given the info above, I think this is resolved, so closing. Let me know if I missed anything.

**Closed by karelz** 2018-10-31 21:41 UTC

**Comment by ivaylo5ev** [comment] 2018-11-01 08:13
@karelz , @nguerrera Thanks! I did not know how to do that aliasing with the new SDK. Could you also tell me whether I can alias package references (the MSBuild ones) in the same manner? In my real use case I am referencing the libraries as nuget packages.

On a separate note, as I am using paket for managing my dependencies. It does seem to support library aliasing per documentation, but it does not have any effect on a dotnet sdk project. I am currently working on resolving that matter with the paket guys, but maybe it is useful to have a note on that here.
